### ISSUE TITLE
Deployment options

### ISSUE THREAD

**Issue by arvislacis** [DEVSENSE/phptools-docs#10]
Hello,

Are there any plans to implement some kind of deployment options (upload/sync/pull/deploy/diff to FTP/SFTP) for PHP Tools for Visual Studio Code? Thanks for information.

**Comment by jakubmisek** [comment]
Hi,

Currently there are no plans as it relies on user's command line tools and 3rd party VSCode extensions like this one https://marketplace.visualstudio.com/items?itemName=mkloubert.vs-deploy. 

In future PHP Tools will support the `Remote Workspace` feature that allows you to open projects on a remote server.

**Comment by Mordef** [comment]
There is a new Version: https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded
It really good

**Comment by jakubmisek** [comment]
@arvislacis does `mkloubert.vscode-deploy-reloaded` work fine for you?

**Comment by arvislacis** [comment]
@jakubmisek Yes, it works fine for me, thanks. I was just asking this question because it would be nice to have also deployment features integrated in PHP Tools for Visual Studio Code - one powerful extension for almost all PHP developer needs. But probably yes, it's much better to rely development on other extensions or tools.

**Comment by jakubmisek** [comment]
Good. You are right! In this case it is just reasonable to rely on the existing extension until it works fine : )
