### ISSUE TITLE
Seems like it doesn't support laravel properly. 10k+ warnings in my project.

### ISSUE THREAD

**Issue by aasutossh** [DEVSENSE/phptools-docs#100]
`Model::where()` warning. Call to Unknown method.
Use of Unknown class `Auth`, and so on. If I am doing something wrong, or something need setting up for Laravel projects then please enlighten me.

**Comment by jakubmisek** [comment]
You are right. I have found the following possible issues:

- `@mixin` PHPDoc tag is not supported, so the editor does not see methods like `where()` or `with()` etc. This is used e.g. in vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php. We should implement this.
- barryvdh\laravel-ide-helper composer package should be installed to generate IDE helper metadata:
  `php artisan ide-helper:meta`
  This should be done in your project.

We'll implement the support for the `@mixin` PHPDoc tag, and we'll try to improve this continuously.

**Comment by jakubmisek** [comment]
the next update will reduce the number of warnings, we'll keep improving it. Since there are incomplete or incorrect type annotations in the majority of the code, as a workaround you can ignore specific warnings in `settings.json` file (https://docs.devsense.com/en/vscode/problems#phpproblemsexclude)

e.g. to ignore `PHP0418`:
```json
"php.problems.exclude" : {
    "/" : [0418],
}
```

**Comment by aasutossh** [comment]
Glad to hear about the upcoming improvement. Till then, not gonna worry bout this.

**Comment by jakubmisek** [comment]
The just released update `1.2.5783` reduces the number of problems reported to about 2k; we'll get rid of most of them in future updates.

**Comment by aasutossh** [comment]
Great to hear that.

**Comment by jakubmisek** [comment]
The updated version does not report the vendor by default, even tho there might be typos in PHPDoc etc. Read more at https://docs.devsense.com/en/vscode/problems#phpproblemsscope
