### ISSUE TITLE
Possibility to add more "code style" options

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#101]
I see that currently there are only 2 options for code style in the settings (and I assume these come from dev sense)
![image](https://user-images.githubusercontent.com/3308769/103276134-a4f37f80-49bd-11eb-91d1-e9a3a29eb07f.png)

How can we add more?

**Comment by jakubmisek** [comment]
Those are pre-set, but based on users' feedback we can provide more options.

What would you like to set as formatting options?

**Comment by addshore** [comment]
Personally I would love MediaWiki one :)
But I'd need to understand what sorts of things are included in this code style functionality to see if it even makes sense at all.
Or if for mediawiki projects it should just be disabled and codesniffer relied upon.

**Comment by jakubmisek** [comment]
In case the user has another code-formatting extension that formats statements after pressing a semi-colon or a closing bracket, the phptools formatting can be turned off.

Although; we define code styles based on the following parameters:
- whether to use tabs or spaces for indentation (vscode setting `editor.insertSpaces`)
- indentation size (`editor.tabSize`)
- code blocks on new line (no setting yet)
- functions body on new line (no setting yet)
- whether to keep single-line blocks on a single line
- how to indent multi-lines expressions

This covers the PSR conventions; we can provide predefined code styles for popular frameworks like MediaWiki, WordPress, etc., or allow to customize the formatting by the user.

The `PHP Tools` code style matches the default C#-like formatting actually, we'll rename it probably in the next update.

**Comment by addshore** [comment]
Regarding `editor.insertSpaces` and `editor.tabSize` I split a concern out into another issue that I noticed in the past days https://github.com/DEVSENSE/phptools-docs/issues/103

> This covers the PSR conventions; we can provide predefined code styles for popular frameworks like MediaWiki, WordPress, etc., or allow to customize the formatting by the user.

If I only need to provide the 6 things above to get a MediaWiki code style added that sounds great!

**Comment by jakubmisek** [comment]
@addshore do you have a link on MediaWiki code style guidelines?

**Comment by addshore** [comment]
A written version can be found at https://www.mediawiki.org/wiki/Manual:Coding_conventions/PHP

**Comment by Zerotask** [comment]
> A written version can be found at https://www.mediawiki.org/wiki/Manual:Coding_conventions/PHP

PSR-12 is supported now which is the recommended code style - in case you didn't know it

**Comment by markeissler** [comment]
Just started trialing DevSense on a new project I've picked up. I'd like to see more flexibility with regard to formatting.

I think what I want is to be able to set a specific formatter (PSR-2, PSR-12, etc.) as a base (starting point) and then apply additional formatters (configurable) which I think is the way that [kokororin.vscode-phpfmt](https://github.com/kokororin/vscode-phpfmt) is supposed to work.

At a high level, I'd like to have support for transformations as listed in [Supported Transformations](https://github.com/kokororin/vscode-phpfmt#supported-transformations).

If this type for auto-formatting is already supported please point me to the directions of where they can be set.

What brings me to the DevSense plugin is that the `kokororin` plugin appears to be broken right now (fails trying to run a syntax check) and `intelephense` can't seem to resolve inherited attributes and/or methods all of the time unless you add something like the [Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper).

**Comment by Miloslav** [comment]
Hi Mark,

Thank you for your comment!

I agree, we will need to add more customization options for the formatting and use predefined code styles as a base.

Please let us know which particular options you would like to see. There is so much to configure here, that we will need to prioritize.

Thank you!

**Comment by markeissler** [comment]
@Miloslav I think the options provided by [kokororin.vscode-phpfmt](https://github.com/kokororin/vscode-phpfmt) are good set. I know that's a lot! In particular, I'm looking for things like:

- AutoPreIncrement
- AutoSemicolon
- ClassToSelf
- ClassToStatic
- DoubleToSingleQuote
- EchoToPrint
- NewLineBeforeReturn
- OrderAndRemoveUseClauses
- ReindentSwitchBlocks
- RemoveSemicolonAfterCurly
- ReplaceBooleanAndOr
- ReplaceIsNull
- SortUseNameSpace
- SpaceAroundControlStructures
- SpaceAfterExclamationMark
- SpaceAroundExclamationMark
- SpaceAroundParentheses
- SpaceBetweenMethods
- StripExtraCommaInArray
- StripNewlineAfterClassOpen
- StripNewlineAfterCurlyOpen
- StripSpaces
- StripSpaceWithinControlStructures
- TightConcat
- TrimSpaceBeforeSemicolon
- WordWrap.... (this should be configurable for any column number)

I hope this helps. It's a long long list. I'm trying to clean up some very very messy code I just inherited and the lack of consistency between developers is just driving me crazy!

**Comment by Miloslav** [comment]
Hi Mark,

Thank you for the list. I guess for some of those there should be (or already is - like sorting namespaces) a quick action/refactoring than formatting settings - or maybe not, we will have to think about it. So far we wanted to limit the formatter so it doesn't change the actual tokens.

But I'm happy to announce that we're releasing a configurable formatter in the upcoming version. We're starting with around `30` formatting rules and more will be coming - we will prioritize based on the feedback.

Here is what will be supported right now https://docs.devsense.com/en/vscode/editor/customize-formatting

Anyway, I think I can close this one, and requests for particular formatting rules can be submitted separately. 

Thank you
