### ISSUE TITLE
Special case for PHPUnit mock object returns? PHP0410

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#102]
I end up with a lot of warnings around the use of the PHPUnit MockObject class in tests.

![image](https://user-images.githubusercontent.com/3308769/103277901-fd2c8080-49c1-11eb-812f-19c8aee93b68.png)

I wonder what the general advice is from phptools folks to deal with this?
Is it expected that we should correctly typehint the possibility of MockObject in all of these places?
Should / could we add some sort of magic special case for such magicish mock objects?

**Comment by jakubmisek** [comment]
Soon we'll be releasing an update that improves support for `.phpstorm.meta.php` file which is used for those kinds of workarounds.

In general, we should not report `PHP0410` or at least we should not be strict about it. User can add the meta file mentioned above (I think it is already a part of most of the libraries)

**Comment by jakubmisek** [comment]
Seems phpunit has included .phpstorm.meta.php file with undocumented syntaxes. Working on it.

**Comment by jakubmisek** [comment]
closing the issue - fix available in the upcoming update!
