### ISSUE TITLE
Faster suggestions for importing / using classes.

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#104]
One of the things that I miss from jetbrains / intelij / phpstorm is the much faster suggestions for classes to import and use.

I can type `WikibaseRepo::` in phptools and not get any suggestions for imports.

![image](https://user-images.githubusercontent.com/3308769/103537045-8c86d780-4e8b-11eb-8f45-2af621eae0ea.png)

I can also do `WikibaseRepo::class`

![image](https://user-images.githubusercontent.com/3308769/103537111-b17b4a80-4e8b-11eb-97de-a4c019681320.png)

Only if I start trying to write some other method do I get the suggestions currently, such as `WikibaseRepo::get`

![image](https://user-images.githubusercontent.com/3308769/103537141-c48e1a80-4e8b-11eb-8c34-1247649d5b1c.png)

**Comment by jakubmisek** [comment]
I see; there are "No code actions available" because the code could not be parsed yet.

- we should fix it and suggest the code actions
- would it be more comfortable to automatically add `"use ..."` statement?

**Comment by addshore** [comment]
For me personally, automatically adding the use statement sounds fine.

In terms of parsing, the second example using ::class should surely be parsable?
I don't see why there should be a different in behaviour between the `::get` and `::class`.

**Comment by jakubmisek** [comment]
the behavior should be the same, it's just not handled on our side properly

**Comment by addshore** [comment]
This `::class` one is still quite annoying :(

**Comment by storm1er** [comment]
As a workaround, I'm using another extension for this purpose: `mehedidracula.php-namespace-resolver` 

Would be great to see this directly implemented here.

**Comment by jakubmisek** [comment]
@storm1er Thank you. Just noting, PHP Tools do have namespace resolver and other features for sorting and cleaning up `use`s

The issue is, it just won't show the corresponding code action immediately, but after a while.

**Comment by addshore** [comment]
> As a workaround, I'm using another extension for this purpose: mehedidracula.php-namespace-resolver

I might have to give this a go

> The issue is, it just won't show the corresponding code action immediately, but after a while.

It would be great to be able to speed this up somehow.
I remember using InteliJ for example and I'd be able to type `Foo::class` for example and immediately be able to add the `use` statement or expand the namespace.
phptools certainly seems much slower in this regard and it makes general development a little hard, as you end up circling back to do these things later, where it would be nice to do them as you go.

**Comment by jakubmisek** [comment]
yes, you are right., Currently, phptools simply postpone the code analysis which results in the corresponding code actions to be shown with a delay; just looking into it

**Comment by jakubmisek** [comment]
So just to clarify this; in PHP Storm, whenever I choose the class name from code completion, it automatically adds the corresponding `use`, however it won't offer me a code action if I already have the class name typed and I miss the `use`.

**Comment by jakubmisek** [comment]
Auto-import with an option to add either alias or fully qualified name has been implemented. Will be available within the next update. Thanks!

![vsc-autoimport](https://user-images.githubusercontent.com/842150/122774419-74740a80-d2a9-11eb-8ce6-0c15b98c24e6.gif)

**Comment by jakubmisek** [comment]
sidenote - the next update will improve the auto-import feature. The code completion will list all the available types so it will be possible to choose which namespace will be imported.
