### ISSUE TITLE
No error when non existent class / object property is used.

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#105]
getSiteLinkList returns a SiteLinkList object.
SiteLinkList has a count() method, but no count property, thus I would expect this code to highlight some sort of warning.

![image](https://user-images.githubusercontent.com/3308769/103544911-b09ce580-4e98-11eb-8c09-fc4ceb6415b1.png)

The correct code would be `$entity->getSiteLinkList()->count()`

This happens to me frequently as phptools does not add `()` automatically when autocompleting methods.

I guess a minimal reporduction is:
```
class A {}
$a = new A();
var_dump( $a->count );
```

**Comment by jakubmisek** [comment]
You're right. We are adding those kinds of warnings continuously. Right now, we started reporting unknown methods and getting rid of false warnings. Once we polish that, unknown properties will follow.

For a ref. we have this feature request already at https://community.devsense.com/d/269-missing-property-or-method-warning

**Comment by jakubmisek** [comment]
this feature has been implemented in v1.14, thank you for the feedback!
