### ISSUE TITLE
@todo in comment block not marked in vscode todo colour

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#107]
I wanted to move this TODO from in code to in the doc block

![image](https://user-images.githubusercontent.com/3308769/103663936-93841780-4f69-11eb-83c1-a718384b601e.png)

Doing so made it really hard to spot as it followed doc block colourings instead of TODO colourings
![image](https://user-images.githubusercontent.com/3308769/103663989-a565ba80-4f69-11eb-924c-9e059b765890.png)

Removing the @ returns the colour

![image](https://user-images.githubusercontent.com/3308769/103664029-b44c6d00-4f69-11eb-8990-30b34a6f2612.png)

But I personally believe this should also be orange with @todo

**Comment by jakubmisek** [comment]
That's a good idea as an optional feature. I'm not sure it is some kind of convention across IDEs to highlight TODO.

Do you have an extension for highlighting `// TODO` in the first place?

**Comment by addshore** [comment]
I don't think so, I believe this is just a vscode default.

Comparable desired behaviour in InteliJ

![image](https://user-images.githubusercontent.com/3308769/103801373-8dfbff80-5045-11eb-9d73-ce57e073584a.png)

**Comment by jakubmisek** [comment]
I don't have it orange tho:

![image](https://user-images.githubusercontent.com/842150/119505867-ac049b00-bd6d-11eb-928a-6003557d155f.png)

Isn't it another 3rd party extension?

**Comment by addshore** [comment]
Interesting, do you have any dev tips that might help me figure this out or should I just enable and disable things until I see it appear / disappear.
Naturally i was assuming this was devsense, as it is a todo in PHP code!

**Comment by jakubmisek** [comment]
The colorization in general is built-in VSCode. Additionally, extensions can re-colorize portions of your code as they want.

I know of https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight but it looks different.

You may post here the list of extensions, maybe we'll find the one.

**Comment by addshore** [comment]
It seems it is this one!

```
Name: Better Comments
Id: aaron-bond.better-comments
Description: Improve your code commenting by annotating with alert, informational, TODOs, and more!
Version: 2.1.0
Publisher: Aaron Bond
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments
```

https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments
https://github.com/aaron-bond/better-comments

I guess I can go and file a task over there? :)

**Comment by jakubmisek** [comment]
@addshore great you found it! yes filling a feature request in there is the best approach, although if it's dead we can create a similar functionality (since we already do that in the full Visual Studio)

**Comment by jakubmisek** [comment]
@addshore we have added to-do highlighter!

so I'm closing the issue now, and please start a new one related to the current state.

thank you!
