### ISSUE TITLE
Show visibility (and other info) in the outline

### ISSUE THREAD

**Issue by markkirchner** [DEVSENSE/phptools-docs#109]
**Problem:**
Currently (as far as I can tell) it's not possible to distinguish between "public/protected/private" methods and properties in the outline (and code completion dialogs).
The same seems to be the case for "static/non-static" or "abstract" or "final".

**Proposal:**
It would be great to have the outline/code completion show different colors/icons/... for the different "types" of methods and properties.

**Additional context:**
If I understand microsoft/vscode#49995 correctly, VS Code already provides support for this and "most work left is [...] on extensions to populate the fields accordingly".

**Comment by jakubmisek** [comment]
good feature, we already do that in Visual Studio. In VS code we didn't found a way of showing other icons than listed in https://github.com/microsoft/vscode/blob/bcaa2be1b51441fd11685e599b2704908f25a6f2/src/vs/vscode.d.ts#L2506 ; although, we'll look further into that

**Comment by markkirchner** [comment]
I see. Looking more closely at the file you linked and the comment in microsoft/vscode#49995 it seems that the `SymbolTag` mechanism is intended to provide the VS Code-side support for this.
But so far, there is only a "Deprecated" `SymbolTag` (at [vscode.d.ts#L2539](https://github.com/microsoft/vscode/blob/bcaa2be1b51441fd11685e599b2704908f25a6f2/src/vs/vscode.d.ts#L2539)).

So does this mean VS Code has to convinced to provide more of those tags (for public/protected/...) first?

**Comment by jakubmisek** [comment]
That's what I found as well - seems there is only "deprecated" tag, and neither additional modifiers, more SymbolTags, nor SymbolKinds are provided.

I was checking other languages like C# and they don't have those icons either.

This is the issue that should "solve" it - https://github.com/microsoft/vscode/issues/23927 - but it was closed even it's actually still not resolved

**Comment by jakubmisek** [comment]
This is what we need https://github.com/microsoft/vscode/issues/113845

**Comment by markkirchner** [comment]
Are there maybe any news about this?

In my opinion, it's still sorely missing functionality, especially when trying to get an overview of an unfamiliar codebase / library.

**Comment by jakubmisek** [comment]
Thank you for reminding me.

The icons are still not extensible - only `deprecated` tag in `SymbolTags`.

We can add what C++ extension does - a small label with the symbol visibility - https://github.com/microsoft/vscode/issues/113845#issuecomment-844604183

**Comment by markkirchner** [comment]
Sounds good to me as a workaround.

Apart from that: As far as I understood, you are waiting for something to happen upstream, so that you (as an extension vendor) can provide this functionality, correct?
So wouldn't is make sense to create an upstream issue for that (which specifies what you need exactly)? Because the existing one that you mentioned (https://github.com/microsoft/vscode/issues/23927) probably won't get any progress anymore.

**Comment by jakubmisek** [comment]
Thanks, I've added the document outline with methods visibility and enum/interface/trait flags (similarly to the C++ extension)

The feature will be available in the next release (1.38) and in upcoming pre-releases.
