### ISSUE TITLE
VSC Extension warning

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#11]
Please disable Warning for https://github.com/chinchiheather/vscode-margin-colours or is there an option in PHP-Tools that support rgb colors display in JavaScript files?

> Following extensions should be disabled since their features may interfere with PHP Tools: chinchiheather.vscode-margin-colours

**Comment by jakubmisek** [comment]
thank you, done.

**Comment by Mordef** [comment]
Warning is still active.
Have update from 26.11.18

**Comment by jakubmisek** [comment]
our bad, typo. Thanks for noticing.
