### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Malek-fadel** [DEVSENSE/phptools-docs#110]
- Issue Type: `Bug`
- Extension Name: `phptools-vscode`
- Extension Version: `1.2.6021`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakubmisek** [comment]
Thank you for the issue. May I ask you for more details? Any log or details on what happened.
