### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Reuben89Breda** [DEVSENSE/phptools-docs#112]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.2.6305`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.55.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MYPC~1\AppData\Local\Temp\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
thank you for reporting the issue. Although I have to close it since the cpuprofile.txt file is missing.

> **:warning: Make sure to **attach** this file from your *home*-directory:**
> **:warning:`c:\Users\MYPC~1\AppData\Local\Temp\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`**
