### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by messias1976** [DEVSENSE/phptools-docs#113]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.2.6305`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MESSIA~1\AppData\Local\Temp\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
Make sure to attach this file from your home-directory:
⚠️c:\Users\MESSIA~1\AppData\Local\Temp\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt

**Comment by jakubmisek** [comment]
I'd ask to **attach** the file together with the issue report, as suggested in the error message.
