### ISSUE TITLE
select between start and end if 

### ISSUE THREAD

**Issue by parsibox** [DEVSENSE/phptools-docs#114]
hi
how can i select content between  start and end if tag?
for example
```
<?
$a=1;
if(  $a == 1 ){
       print 'ok';
}else{
       print 'no';
}
?>
```
i want get once print 'ok'; and once again print 'no';
please help me

**Comment by jakubmisek** [comment]
hello,

Is this a general question about programming? The code you've posted seems fine tho.

Or you are suggesting a feature request to VSCode for a shortcut to select the text between if and endif?

thank you

**Comment by parsibox** [comment]
hi
this question is about VSCOde not programing

**Comment by jakubmisek** [comment]
To select everything between braces, you can use the shortcut (by default `shift+alt+right`). See https://stackoverflow.com/questions/37835012/is-there-in-vscode-an-option-to-select-everything-between-matching-brackets
