### ISSUE TITLE
No hint to add full class name in @var annotation when class is not know

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#115]
No hint to add full class name in @var annotation when class is not know

![image](https://user-images.githubusercontent.com/3308769/117892008-d1929e80-b2af-11eb-92f0-65041afa3626.png)

If I manually enter the full class name the IDE then enjoys itself

![image](https://user-images.githubusercontent.com/3308769/117892089-fa1a9880-b2af-11eb-812a-bcb1495af6e3.png)

**Comment by addshore** [comment]
Instead of this being an auto fixable thing highlighted with some underline, I need to:
 - Find the class using find class and string "RevisionStore"
 - Open the file
 - Copy the namespace from the top
 - Enter the namespace into the comment

This should just be an autofix

**Comment by jakubmisek** [comment]
It seems it's not getting code fixes, because the type name is correct as it is? If it is not underlined, it is not considered missing.

Do you see anything if you mouse hover over the `"RevisionStore"` ?

**Comment by jakubmisek** [comment]
We still cannot replicate the issue? Maybe the quick fix appears after a second or so?

**Comment by addshore** [comment]
So, I tried this again today and it seemed to work just fine.
I have no idea if this was thus just a one off issue or something else, if I see it again I'll report back.
Are there any sort of verbose / debug logs or commands i should run in cases like this to be able to provide a better picture of what state my IDE is in?

**Comment by jakubmisek** [comment]
Thank you @addshore ; we'll keep an eye on that.

An additional verbose is a good idea. Maybe we'll add something in the future.
