### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kenjesan** [DEVSENSE/phptools-docs#119]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.4.6842`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\a\AppData\Local\Temp\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\a\AppData\Local\Temp\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`
