### ISSUE TITLE
VSCode Xdebug Documentation

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#12]
Got Problems to start Debugging on VS Code (Windows 10) with remote VM (Linux)

Problem was: Firewall. 
Firewall didn't ask to allow listen on Ports for VS Code.
After enable VS Code incoming Ports all works fine.

Maybe u can extend the Configuration-Page https://docs.devsense.com/en/vs/debugging/configuring-xdebug ( https://docs.devsense.com/en/vscode/debug/xdebug is still empty )
So other people don't run in that problem.

**Comment by jakubmisek** [comment]
Thank you, we will do.

For other people reading this post; there is also proxy setting in VSCode https://code.visualstudio.com/docs/setup/network in out-coming connection fails.

**Comment by jakubmisek** [comment]
We have updated the debug documentation and added links to additional Proxy settings.

https://docs.devsense.com/en/vscode/debug

Thank you for pointing this out!
