### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by alistart** [DEVSENSE/phptools-docs#122]
- Issue Type: `Bug`
- Extension Name: `phptools-vscode`
- Extension Version: `1.4.6842`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakubmisek** [comment]
⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

---

sorry, we're closing the issue. Please paste the data next time, we'll try to fix it asap. Thank you.
