### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Hkchill** [DEVSENSE/phptools-docs#123]
- Issue Type: `Bug`
- Extension Name: `phptools-vscode`
- Extension Version: `1.4.6982`
- OS Version: `Windows_NT x64 10.0.16299`
- VS Code version: `1.58.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakubmisek** [comment]
⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

--

sorry, we're closing the issue. Please paste the data next time, we'll fix it asap.
