### ISSUE TITLE
EMFILE: Too many open file using WSL

### ISSUE THREAD

**Issue by storm1er** [DEVSENSE/phptools-docs#124]
Hi,

You will find more information about this problem here:
- Related to https://github.com/microsoft/vscode-remote-release/issues/5452
- Related to #45

(and possibly all related issues which goes quite far)

### Problem:

When opening a big project containing 50k+ PHP files, the EMFILE error is triggered.
It makes the extension failing to start, most of the time blocking more extension.
The only option is to disable this extension.

### Solution:

It would be great to have some options as a workaround:
- An option "Defer startup analyze" that would wait for a little before eager loading/analyzing the workspace
- An option "Analyzer chunk size" that would give us the possibility to eager load by chunk instead of the whole workspace in one shot
- I don't have any other ideas right now, but I may add if more appears in the comment.

**Comment by jakubmisek** [comment]
thank you for the issue;

this might happen only when scanning for test files (which is already deferred). The `.php` files themselves are scanned outside of the VSCode process.

We'll try that although seems more like an issue in VSCode itself (?)

Do you have a stack trace of the exception? This might be available in VSCode Help / Toggle Developer Tools.

**Comment by jakubmisek** [comment]
we have reduced pen files handles to minimum; afaik the issue not happening anymore
