### ISSUE TITLE
Suggestion stop working

### ISSUE THREAD

**Issue by Kcko** [DEVSENSE/phptools-docs#125]
PHPDoc comments not working -> bit.ly/2XifsPx
Getters / Setters auto generating not working -> https://bit.ly/2Xk44Cs

Thx for feedback; i have last version of PHPtools & VSC.

**Comment by jakubmisek** [comment]
Thanks for creating the issue and for the video!

Additional details might be found in Help / Toggle Developer Tools -> Console tab. Is there any error or exception?

**Comment by jakubmisek** [comment]
found and fixed the issue - we have been sending corrupted json requests from language server
