### ISSUE TITLE
XDEBUG ignore file pattern

### ISSUE THREAD

**Issue by snandos** [DEVSENSE/phptools-docs#128]
Hi,

am I correct, that Devsense PHP debugging in vscode does not have a "ignore path" option as it is supported by the "official" PHP Debug plugin (xdebug.php-debug)?
If so, is there any chance that this option will be added in near future?
I need this option because some vendor files are throwing exceptions which cannot be mapped to my local workspace folder.

Thanks!

**Comment by jakubmisek** [comment]
Hello,

Thank you for the suggestion! 

That makes sense. `"IgnorePath"` will be added.

We're also thinking about adding something like `"JustMyCode" setting; which would ignore exceptions in the /vendor folder as well, and .phar files etc.

**Comment by jakubmisek** [comment]
@snandos 

there is already `"exclude"` setting, with this functionality:

```json
{
    {
            "type": "php",
            "request": "launch",
            "port": 9003,
            "exclude": [
                "**/vendor/**"
            ]
        }
}
```

It accepts array of path patterns using wildcards (`*` and `**` works).

We'll add the corresponding documentation

**Comment by jakubmisek** [comment]
Thank you for your suggestion! Please let us know if there would be anything else we should add support for.
