### ISSUE TITLE
specify phpunit path

### ISSUE THREAD

**Issue by louismariegaborit** [DEVSENSE/phptools-docs#129]
How to specify the path of phpunit binary ?

The binary which is execute is `/workspace/vendor/bin/.phpunit/phpunit` but I want `/workspace/bin/phpunit`

**Comment by jakubmisek** [comment]
We'll release an update within a day.

The setting `"phpunit.phpunit"` will allow you to specify the PHPUnit binary. Also _phptools_ will now correctly detect the `/bin/phpunit` binary if it's there, so the settings won't be necessary in most cases.
