### ISSUE TITLE
PHPUnit autocomplete

### ISSUE THREAD

**Issue by hagishi** [DEVSENSE/phptools-docs#13]
hi,
PHPUnit autocomplete doesn't in vsc work?

**Comment by jakubmisek** [comment]
Hi, you are right - `phpunit.phar` is not yet processed so its content is not included in the autocomplete. Will be added.

**Comment by jakubmisek** [comment]
just released the update - `1.0.3936`

It introduces completion and navigation through `.phar` files which should resolve this issue.

If you have a phpunit .phar file in your workspace, you should see code completion, type analysis and be able to go to definition of PHPUnit classes and functions right into the decoded .phar file.

Please confirm :)

**Comment by jakubmisek** [comment]
Marking this as closed, PHPUnit completion works with the new Phar integration. 

To make it working you need a phpunit .phar file inside your workspace
