### ISSUE TITLE
PHP Tool Can't Load PHP_ZIP.DLL

### ISSUE THREAD

**Issue by AlexanderAdelAU** [DEVSENSE/phptools-docs#130]
The only way I can get PHP programmes to load the php_zip.dll is to disable PHP Tools from VS Code.   The error appears to come from PHP_Tools mangling the path to the DLL.   For example  `php_php_zip.dll.dll`.  XAMPP will load the php_zip.dll so it is not an issue with the dll.  Here is the error message that VS Code produces:

**PHP Warning:  PHP Startup: Unable to load dynamic library 'php_zip.dll' (tried: C:\xampp-7.4.11\php\ext\php_zip.dll (%1 is not a valid Win32 application.), C:\xampp-7.4.11\php\ext\php_php_zip.dll.dll (The specified module could not be found.)) in Unknown on line 0**

**Comment by jakubmisek** [comment]
Hello @AlexanderAdelAU 

Thank you for reporting the issue.

Is it related to Visual Studio or Visual Studio Code? I don't think PHP Tools are installing "php_zip" extension, but we'll check that!

**Comment by jakubmisek** [comment]
It seems the warning is caused by PHP - it tries the extension `{name}` specified in your `php.ini` as it is, and if it's not there, it tries "php_`{name}`.dll". May I ask if "php_zip" is your `php.ini` correctly?

**Comment by AlexanderAdelAU** [comment]
Yes,  here is my php.ini entry:
 `extension=php_rar.dll
 extension=php_zip.dll `

I think PHP is loading it correctly as I can start and stop XAMPP and it I have the wrong php_zip.dll in the php ext directory it will throw and error.   So php.ini appears to be okay.  

Now I have PHP Debug and PHP Tools extensions loaded in VS Code.   I removed PHP Debug and the problem remained so it sort of points to PHP Tools.

**Comment by jakubmisek** [comment]
PHP Tools for VS Code do not modify `php.ini`. It only quickly checks that your PHP is fine by running

`php --version`

and showing you the warnings from PHP itself.

It is an automatic checker, that the `php` is configured properly.

According to the warning, there is `php_zip.dll` set in your `php.ini` but you don't have `php_zip.dll` in your `C:\xampp-7.4.11\php\ext` directory. Maybe the installation of your xampp is not complete? https://stackoverflow.com/questions/23564138/how-to-enable-zip-dll-in-xampp

**Comment by AlexanderAdelAU** [comment]
Okay, thanks.   I can work around it as it is not a huge problem in my testing environment, but I will see if I can get to the bottom of it though.  My XAMPP is working very well and the php_zip.dll is loading, I just get that error.!
