### ISSUE TITLE
PHP Tools Reports PHP 'MYSQLI_ASSOC' as undefined

### ISSUE THREAD

**Issue by AlexanderAdelAU** [DEVSENSE/phptools-docs#131]
PHP Tools is reporting `MYSQLI_ASSOC` constant as undefined , for example

`	$row = mysqli_fetch_array($result, MYSQLI_ASSOC);`  gets reported as

`Use of undefined constant 'MYSQLI_ASSOC'PHP(PHP0415`

This is likely a PHP Documents issue, but I thought that I would report it anyway.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue,

The `MYSQLI_***` constants will be added to the documentation in the next update

**Comment by jakubmisek** [comment]
there is a pre-release available, which fixes MYSQLI_ constants and functions

thanks!
