### ISSUE TITLE
Extension causes unselected areas to be affected 

### ISSUE THREAD

**Issue by niketpathak** [DEVSENSE/phptools-docs#132]
Hello, 

Thank you for this incredible extension. 
A found a rather irritating bug. It is just not possible to rename a single instance of a variable. For example, if I have `$res` that appears 3 times in the code and wish to change a single instance of the same, I cannot do that. Changing any one of the 3 instance of $res causes all of them to change. Had to disable the extension until the problem gets resolved.

Here's a video that shows this behaviour -

https://user-images.githubusercontent.com/10226768/158437902-ce682e4f-2006-469b-b3dd-b2a545867683.mp4

**Comment by jakubmisek** [comment]
Hello,

Thank you very much for your feedback!

This is a feature of VSCode called "linked editing". You can turn it off in your settings:
```json
"editor.linkedEditing": false
```

More at https://code.visualstudio.com/docs/getstarted/settings . 

This can be eventually turned off just for `php` files using the following settings (your `.vscode/settings.json`)

```json
{
  "[php]": {
    "editor.linkedEditing": false
  }
}
```

I hope it helps! Please let us know if you'd have any other feedback for us. Thank you!

**Comment by jakubmisek** [comment]
thank you again for the issue; we're closing it since it is a feature that you can turn off (it is off by default)

**Comment by jakubmisek** [comment]
Yes - linked editing is a feature provided by extensions like phptools. Most of the features are provided by extensions. Maybe you can read the list of features, that PHP Tools provide to you: https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode

You can disable the feature using the setting `"editor.linkedEditing": false` to turn it off.
