### ISSUE TITLE
Can not recognize the readonly keyword in  __construct function

### ISSUE THREAD

**Issue by zengbo** [DEVSENSE/phptools-docs#133]
<img width="1625" alt="CleanShot 2022-03-18 at 09 42 14@2x" src="https://user-images.githubusercontent.com/1001621/158921383-c3c4cd4d-d985-42f3-8cb3-3b26d5ae4cc2.png">

**Comment by jakubmisek** [comment]
Thank you @zengbo ! you're right. We'll try to fix that as soon as possible.

**Comment by jakubmisek** [comment]
we're updating pre-release - version `1.8.8904` fixes the issue

thanks!
