### ISSUE TITLE
darwin-arm64 runs error

### ISSUE THREAD

**Issue by zengbo** [DEVSENSE/phptools-docs#134]
<img width="680" alt="CleanShot 2022-03-21 at 09 29 06@2x" src="https://user-images.githubusercontent.com/1001621/159195165-f206eb72-9df4-493a-a02d-f1fca365d9e7.png">

**Comment by jakubmisek** [comment]
thank you for the issue!

We're testing the new runtime on osx-arm64 on our pre-release, and it seems it's not working.

We'll revert back to x86 executable depending on Apple's Rosetta x86->arm64 translation, and we'll do more testing.

**Comment by jakubmisek** [comment]
ref https://github.com/dotnet/runtime/issues/49091#issuecomment-900006813

**Comment by jakubmisek** [comment]
does the pre-release `1.8.8950` fix the issue for you? thanks for any info

**Comment by zengbo** [comment]
It's a x86 binary, use Rosetta is OK.
<img width="753" alt="CleanShot 2022-03-22 at 09 43 57@2x" src="https://user-images.githubusercontent.com/1001621/159390704-0e328959-51e7-4b34-a73c-868a04d385ca.png">

**Comment by jakubmisek** [comment]
thank you, and does it work for you now?

**Comment by zengbo** [comment]
Yes, it works well

**Comment by jakubmisek** [comment]
thank you @zengbo
