### ISSUE TITLE
how to disable the format option completely ?

### ISSUE THREAD

**Issue by ctf0** [DEVSENSE/phptools-docs#135]
i have `"php.format.codeStyle": "Off",` but everytime i save a file it seems that it have to go through the extension first b4 it save.

i can say that the extension does nothing to the file but not sure why it have to hook into the save process even if the config for formating is off.

the reason am asking is also because for problem reporting i have to use both 
```
"php.problems.scope": "none",
"php.problems.exclude": {
        "**/*": true
    },
```

to disable this feature completly other wise the scanning will take place regardless of the reporting config.

**Comment by jakubmisek** [comment]
Thank you for reporting an issue.

I'm not sure I understand.

`"php.format.codeStyle": "Off"` turns off document and selection formatting when editing a PHP file.

`"php.problems.scope": "none"` disables analysing and reporting problems in VS Code Problems window.

However, PHP Tools will always read and scan your local files, because it needs to know you functions/class/etc.

**Comment by ctf0** [comment]
yeah i know,  u r correct it needs to read the project files in order to provide all of its functionality but for the errors reporting i found that unsing both of the configs reduce the editor lagging however for the saving issue i dont know how to make phptools stop watching the file or rebuilding its index on each save.

**Comment by jakubmisek** [comment]
I see;

We can fix "php.problems.scope", so when set to "none", it reduces the CPU usage.

It should not re-build the index on saving, it should just read that single file. We'll check that.

**Comment by ctf0** [comment]
here is the popup i get on every file save
![Untitled](https://user-images.githubusercontent.com/7388088/161072063-fa3058b0-490c-4cf6-9329-20f46a49f76c.jpg)

**Comment by jakubmisek** [comment]
mm, it doesn't seem like anything PHP Tools popping. More like a side effect of another extension.


I have found a few related posts on that:

https://stackoverflow.com/questions/65487080/vscode-saving-getting-code-actions-from
https://github.com/microsoft/vscode-go/issues/3179

Does any of it help?

**Comment by ctf0** [comment]
sadly not but all i can tell u is if phptools is disabled, i dont get the popup anymore.

**Comment by jakubmisek** [comment]
It's more like there is an extension that tries to apply "code fixes" upon saving.

PHP Tools extension provides the "code actions" (and code fixes) but it's managed by VSCode itself. Also, PHP Tools are reading files in a separate process, and lazily, so it can't even affect the VSCode main window.

**Comment by ctf0** [comment]
if there is a way i could help u with the debugging plz tell me.

**Comment by ctf0** [comment]
i tried 
```
"[php]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": false,
        },
    },
```
but no difference.

**Comment by jakubmisek** [comment]
May I ask, what is your settings, and what extensions do you have enabled?

**Comment by ctf0** [comment]
> what is your settings

can u be more specific ?, the settings file is quite large

> what extensions do you have enabled

quite a number but for php at least here is what i have atm
![demo](https://user-images.githubusercontent.com/7388088/161099764-784d203c-7720-481d-857d-8396da5f645b.png)

**Comment by jakubmisek** [comment]
Thanks.

First, there are many extensions, that do the same as PHP Tools. This may cause some weird behavior and unnecessary CPU usage.

I'm actually not sure what settings might be the problem. But there is something causing "code fixes" to be applied upon saving the file.

**Comment by ctf0** [comment]
the issue with the `code fixes` is there is no way to find the extension settings that affect this part.

for example this is all i can found so far
```json
"source.autoFix": true,
"source.fixAll.tslint": true,
"source.fixAll.stylelint": true,
"source.fixAll.eslint": false,
"source.organizeImports": false
```
