### ISSUE TITLE
how to use "php.executables" with docker

### ISSUE THREAD

**Issue by ctf0** [DEVSENSE/phptools-docs#136]
atm am trying something like 
```jsonc
"php.executables": {
        "laravel_test": "/usr/local/bin/docker exec laravel_test php",
        // ... other projects
    }
```

to get around not being able to use `"php.executablePath": ""` per project, however  this doesn't work and it always uses the machine local setup instead
```log
PHP Tools extension started.

Couldn't resolve requested PHP version 'laravel_test' ... Using default 'php'.
Found PHP, version: 8.1.4, Xdebug: not loaded.
PHP Language Server Started.
```

is there a special config for the docker based setup that i've missed or is it not supported ?

**Comment by jakubmisek** [comment]
hi,

`"php.executables"` setting is for specifying local path to `php` (https://docs.devsense.com/en/vscode/php-version#custom-php-paths)

If you're hosting your PHP on docker, you don't have to specify this setting.

Run docker by yourself or within VSCode's `launch.json`, and configure the Xdebug port as it would be a remote connection (https://docs.devsense.com/en/vscode/debug/launch-json#listen-for-xdebug-locally-or-remote-debug)

**Comment by jakubmisek** [comment]
I'm glad I could help! Please et us know if there would be anything else
