### ISSUE TITLE
LDAP constants flagged as 'undefined' in Problems window

### ISSUE THREAD

**Issue by gwythan** [DEVSENSE/phptools-docs#137]
It seems that PHP Tools does not recognise the following valid LDAP_* constants in PHP 7.4, 8.0 and 8.1. There may be others from the LDAP extension that I have not tested:

LDAP_ESCAPE_FILTER
LDAP_ESCAPE_DN
LDAP_OPT_X_TLS_NEVER,
LDAP_OPT_X_TLS_TRY,
LDAP_OPT_X_TLS_DEMAND,
LDAP_OPT_X_TLS_HARD,
LDAP_OPT_X_TLS_ALLOW,
LDAP_OPT_X_TLS_NEVER

**Comment by jakubmisek** [comment]
thank you for reporting that; you are right, LDAP stubs are not included. Will be fixed.

**Comment by jakubmisek** [comment]
Seems those constants are undocumented. So we'll add them, but without any documentary comment.

**Comment by jakubmisek** [comment]
preparing a pre-release within an hour (`v1.8.9260`) (docs on how to install it at https://docs.devsense.com/en/vscode/installation#pre-release-installation)

the full release will be available within a day or two.

thank you!
