### ISSUE TITLE
LDAP functions incorrectly reporting Argument '1' type error on PHP7.4

### ISSUE THREAD

**Issue by gwythan** [DEVSENSE/phptools-docs#138]
PHP Tools reports the following error for **all** LDAP functions:

**Argument '1' passed to ldap_search() is expected to be of type LDAP\Connection|array, resource given**\

Sample code:

```
$ldapConn = ldap_connect($myURL, $myPort);
$sr = ldap_search($ldapConn, $myBase, '(objectClass=group)', ['member']);

```
I have PHP 7.4 set for this workspace:

```
"php.executables": {
        "v7.4": "/Applications/MAMP/bin/php/php7.4.27/bin/php",
        "v8.0": "/Applications/MAMP/bin/php/php8.0.14/bin/php",
        "v8.1": "/Applications/MAMP/bin/php/php8.1.1/bin/php"
 },
"php.version": "v7.4",
"php.validate.executablePath": "/Applications/MAMP/bin/php/php7.4.27/bin/php",
```

In this case, the resource type for Argument 1 is correct. It was not until PHP 8.1 that the type for Argument 1 was changed to LDAP\Connection. See: https://www.php.net/manual/en/function.ldap-search

Note, I am getting this error for all PHP ldap_xxxx() functions that expect a resource type in Argument 1

**Comment by jakubmisek** [comment]
Hi @gwythan 
Thank you for reporting the issue.

You are right, they have changed it in PHP 8.x . We'll fix this in the integrated manual. I'll keep you informed in this thread.

**Comment by gwythan** [comment]
Thank you. Can I also add that I get the following error for ldap_sort(), which is also not valid when using PHP7.4 ldap_sort() was depreciated only with PHP8.0.

**Function 'ldap_sort' has been removed and is available up to PHP 7**

**Comment by jakubmisek** [comment]
thanks @gwythan ; according to the documentation, the function is deprecated in PHP 7
https://www.php.net/manual/en/function.ldap-sort.php
We'll check that

**Comment by gwythan** [comment]
Thank you. I agree, that it has been depreciated, but the error message says "Function 'ldap_sort' has been **removed**". This is not correct for PHP 7.x
Kind regards.

**Comment by jakubmisek** [comment]
Hi @gwythan ; thank you again for reporting the issue.

We have checked the deprecation messages and those should be alright, but there may be a bug in the **PHP version setting**.

May I ask you if you have the expected version `PHP 7.4` in your status bar?

![image](https://user-images.githubusercontent.com/842150/169025868-5353b03c-806b-4004-a4e6-fa11d4901af2.png)

Also after changing the PHP version, the editor may need to be reopened in some cases.

**Comment by gwythan** [comment]
Just want to report a further issue on how LDAP functions are defined in PHP 7+ and PHP 8+, which PHPTool is flagging as an error in PHP7:

For the code snippet:

`$ldapConn = ldap_connect('my-ldap-server.net', 389);`

I get the error:

```
[{
	"resource": "/Users/kevinash/Sites/policymanager/support_files/test-ldap.php",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "PHP0443",
	"severity": 4,
	"message": "Too many arguments to function ldap_connect(). 2 provided, but 1 accepted.",
	"source": "PHP",
	"startLineNumber": 116,
	"startColumn": 42,
	"endLineNumber": 116,
	"endColumn": 51
}]
```

The documentation for ldap_connect() defines the function as:

`ldap_connect(?string $uri = null): LDAP\Connection|false`

However, the following signature for this function, which is now depreciated, is still correct for PHP7:

`ldap_connect(?string $uri = null, int $port = 389): LDAP\Connection|false`

I draw your attention again to the original issue in this ticket. The PHP documentation reads:

`PHP 8.1.0:  Returns an LDAP\Connection instance now; previously, a resource was returned.`

I have many PHPTools errors reported in my code for LDAP functions using PHP7.4 (and PHP8!) where I am still using a 'resource' type for a variable instead of LDAP\Connection. For example:

`Argument '1' passed to ldap_close() is expected to be of type LDAP\\Connection, resource given`

As always, I have version PHP 7.4 in my VSC status bar, which is configured for a PHP7.4 executable.

**Comment by jakubmisek** [comment]
thank you for reporting that! LDAP has some ambiguities in the documentation - we'll try to fix that

**Comment by jakubmisek** [comment]
LDAP fixed; both Connnection and resource are accepted types now
