### ISSUE TITLE
How to set the directory to ignore scan? Such as the runtime dir.

### ISSUE THREAD

**Issue by lvguozhong** [DEVSENSE/phptools-docs#139]

**Comment by jakubmisek** [comment]
Hello,

To ignore directories from Code Analysis (Problems), you can use `php.problems.exclude` setting (https://docs.devsense.com/en/vscode/problems#phpproblemsexclude)

To completely exclude files from parsing and from workspace, use `files.exclude` setting (https://code.visualstudio.com/docs/getstarted/settings)

I hope it helps!
