### ISSUE TITLE
How to implement the instantiation of class parameters to prompt and complement, there is a solution, or how to comment, like @mixin?

### ISSUE THREAD

**Issue by jcleng** [DEVSENSE/phptools-docs#140]
```php
class Demo
{
    public function f_name()
    {
        return 'demo->name';
    }
}

function meke($parama_class_name)
{
    return new $parama_class_name();
}

// tips f_name()
meke('Demo')->f_name();
```

```text
code: meke('Demo')->
completion: f_name()
```

hints and complements for classes instantiated with parameters

**Comment by jakubmisek** [comment]
Hello,

Thank you for the question.

This is possible using a special `.phpstorm.meta.php` file. Create a file `.phpstorm.meta.php` anywhere in your workspace, and put the following code inside:

```php
<?php

namespace PHPSTORM_META {
    override(\meke(), type(0));
}
```

![image](https://user-images.githubusercontent.com/842150/170978750-905d3ce2-be23-4b24-9bba-4c18e6fd9369.png)


---

> In the future, this will also work with `@template` PHPDoc annotation, but it's not fully supported **yet**.

**Comment by jakubmisek** [comment]
We have implemented support for the combination of `@template T`,  `class-string<T>`, and `@return T`. This will be available in the future update:

```php
/**
 * @template T
 * @param class-string<T> $classname
 * @return T
 */
function make($classname) {
    return new $classname();
}
```

**Comment by jcleng** [comment]
> We have implemented support for the combination of `@template T`, `class-string<T>`, and `@return T`. This will be available in the future update:
> 
> ```
> /**
>  * @template T
>  * @param class-string<T> $classname
>  * @return T
>  */
> function make($classname) {
>     return new $classname();
> }
> ```

and a small doubt, when use ::class no tips
```php
meke(Demo::class)->
```
