### ISSUE TITLE
How to set a directory that prohibits analysis?

### ISSUE THREAD

**Issue by imajinyun** [DEVSENSE/phptools-docs#141]
If my dependency is not the `vendor` directory of modern PHP, but other directories generated by historical projects. If it is the `acme` directory, how can I prohibit or jump to analyze this directory?

**Comment by jakubmisek** [comment]
Hello,

phptools scan the entire workspace (it doesn't matter if there is `vendor` or something else). The directory needs to be included in your workspaces.

To exclude the directory form showing `PROBLEMS`, you can use `php.problems.exclude` setting. For more information please see https://docs.devsense.com/en/vscode/problems#phpproblemsexclude

**Comment by imajinyun** [comment]
Thank <sup>you</sup> 👍👍👍 @jakubmisek

**Comment by imajinyun** [comment]
Thank <sup>you</sup> 🙏

**Comment by jakubmisek** [comment]
I'm glad I could help!
