### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by carlospureza** [DEVSENSE/phptools-docs#142]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.9.9585`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ADMINI~1/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory: ⚠️`file:///c%3A/Users/ADMINI~1/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

I have to close this issue, since the profiling file is missing. Please post a new issue with the cpuprofile.txt. Thank you
