### ISSUE TITLE
only tests starting with 'test_' are detected

### ISSUE THREAD

**Issue by tyler36** [DEVSENSE/phptools-docs#143]
I have a project with 1000+ tests.
These run fine from CLI with `phpunit`.

I use annotations to mark tests, however PHP Tools only seems to detect tests that start with `test_`

`test_staff_can_log_in_via_staff_page` is detected but `it_creates_a_half_admin_account` is not.

```php
    /** @test */
    public function test_staff_can_log_in_via_staff_page()
    {
   ...
    }

    /** @test */
    public function it_creates_a_half_admin_account()
    {
    ...
    }
```

I can run `phpunit --filter it_creates_a_half_admin_account` and it passes. The issue does not appear to be related to PHPunit.

VSCode: 1.68.1
PHP Tools: 1.9.9585
OS: Win10

UPDATE:
I did some testing with older versions on a fresh copy of VSCode.

The following versions display all tests and run them correctly:
- 1.7.8766
- 1.8.8970
- 1.9.9277

The following versions have problem.
- 1.9.9425 (start of problem?)
- 1.9.9585 (current)

**Comment by jakubmisek** [comment]
Thank you for the issue; we'll take a look at that.

PhpTools should definitely list the test methods annotated with `/** @test */` documentary comment.

**Comment by tyler36** [comment]
## Test

- Currently working with `1.9.9277` (shows multiple tests in tree view)
- Click extension button
- Click "Install another version" in the panel
- Select version, and wait for completion
- Restart Vscode

Following versions were checked:
- ✅ 1.9.9277
- ❌ 1.9.9585
- ❌ 1.9.9627
- ❌ 1.10.9687
- ✅ 1.9.9277

- Reverting back to `1.9.9277` displays all tests again

VSCode: 1.63.2

**Comment by jakubmisek** [comment]
thanks!

**Comment by jakubmisek** [comment]
Pre-Release on the way. Thanks @tyler36 !

**Comment by jakubmisek** [comment]
fixed in the release `v1.10`

thanks!

**Comment by tyler36** [comment]
Confirmed.

VSCode updated the extension to `1.10.9721` this morning.
All tests appear in panel and run as expected. 

Thank you for the update!

**Comment by jakubmisek** [comment]
awesome! thanks for the feedback. If there would be anything else, please let us know.
