### ISSUE TITLE
Do not show errors in Wordpress hooks

### ISSUE THREAD

**Issue by beckymarques** [DEVSENSE/phptools-docs#144]
Currently the tool do not recognize Wordpress hooks and displays it as errors on output.

**Comment by jakubmisek** [comment]
Hi @beckymarques 

PhpTools should display and recognize all the functions defined anywhere in the Workspace.
Also, it is not supposed to display errors on Output, but rather in "Problems" window.

May I ask for a screenshot, or a few more details? I'm sure we can figure it out.

Thanks!

**Comment by kanlukasz** [comment]
I test it with the latest version and can confirm that everything is working fine.
Every hook is recognized and I don't see any errors

E.g.:
![image](https://user-images.githubusercontent.com/30685349/196043364-d3ef77d8-c200-4e7a-8bde-9f6f9d396635.png)
![image](https://user-images.githubusercontent.com/30685349/196043369-2f605a16-7c0a-4fed-be32-d917cae9aa08.png)

**Comment by jakubmisek** [comment]
thank you @kanlukasz for the confirmation!
