### ISSUE TITLE
Runing phpunit within a docker container

### ISSUE THREAD

**Issue by gdelazzer** [DEVSENSE/phptools-docs#146]
Hi,

On VSCode, is it possible to run the tests within a docker container? If yes, how to configure it to do so? I unfortunately haven't been able to find this information in the doc :)

Thank you in advance for your help!

**Comment by jakubmisek** [comment]
Hi,

Thanks for the question.

Currently, it is not supported directly by the Test Explorer (https://community.devsense.com/d/596-running-phpunit-in-docker/5).

**Comment by gdelazzer** [comment]
Thanks for the quick answer @jakubmisek , and sorry for the cross post, i wasn't sure which place was the best to post this question ^^

Hopefully this can be done "easily" white researching I quickly saw some discussion on how they implemented this for Mochat test runner if you ever needed some inspiration ^^

Thanks again for the quick answer, it is really appreciated!

**Comment by jakubmisek** [comment]
We'll take a look, and hopefully it will be simple for the remote workspaces in general:)

**Comment by jakubmisek** [comment]
There are some resources on how to do it now:

- https://docs.devsense.com/en/vscode/remote
- https://blog.devsense.com/2022/develop-php-in-docker

I hope it helps! closing :)
