### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Pablo-hub44** [DEVSENSE/phptools-docs#148]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.10.9721`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/PABLOJ~1/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory: ⚠️`file:///c%3A/Users/PABLOJ~1/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

thank you for reporting the issue. We have to close it since the required file was not attached. Please feel free to open a new issue with the details.
