### ISSUE TITLE
Configure phpunit.xml path

### ISSUE THREAD

**Issue by gayanhewa** [DEVSENSE/phptools-docs#15]
For some projects, phpunit.xml is not located in the project root. It would be a good option to make the path configurable like many other phpunit extensions.

**Comment by jakubmisek** [comment]
@gayanhewa it is a good idea.

Currently if there is no `phpunit.xml` or `phpunit.xml.dist` at the workspace root, we find all phpunit.xml configurations and show all of them in the test explorer.

**Comment by gayanhewa** [comment]
Ok, but that doesn't seem to work. I have my phpunit.xml in a directory named build. One level down from root.

**Comment by gayanhewa** [comment]
I just noticed that I get on the dev console

```
notificationsAlerts.ts:40 Error while loading tests: Error: EACCES: permission denied, scandir
```

**Comment by jakubmisek** [comment]
@gayanhewa oh, seems like the issue here. Is there a stack trace or any more info?

We'll take a look on that.

**Comment by gayanhewa** [comment]
```

  | t.onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | e.fire | @ | event.ts:228
  | t.notify | @ | notifications.ts:113
  | t.notify | @ | notificationService.ts:52
  | e._showMessage | @ | mainThreadMessageService.ts:83
  | e._showMessage | @ | mainThreadMessageService.ts:44
  | e.$showMessage | @ | mainThreadMessageService.ts:38
  | t._doInvokeHandler | @ | rpcProtocol.ts:461
  | t._invokeHandler | @ | rpcProtocol.ts:446
  | t._receiveRequest | @ | rpcProtocol.ts:366
  | t._receiveOneMessage | @ | rpcProtocol.ts:296
  | (anonymous) | @ | rpcProtocol.ts:171
  | e.fire | @ | event.ts:228
  | a | @ | ipc.net.ts:103
  | n._socketDataListener | @ | ipc.net.ts:132
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js:263
  | readableAddChunk | @ | _stream_readable.js:250
  | Readable.push | @ | _stream_readable.js:208
  | onread | @ | net.js:594


```

**Comment by jakubmisek** [comment]
thank you @gayanhewa : ) let me see what we can do

**Comment by jakubmisek** [comment]
meanwhile - obviously there seems to be a missing permission to some directory/file within the workspace.

@gayanhewa I guess you are running linux/mac? There might be few hints on https://stackoverflow.com/questions/38980338/eacces-permission-denied-in-vs-code-mac if you want to try.

**Comment by gayanhewa** [comment]
👍 will take a look.

**Comment by jakubmisek** [comment]
currently PHPTools find `phpunit.xml` or `phpunit.xml.dist` within the workspace and let user to choose what tests to run

setting is not necessary yet
