### ISSUE TITLE
Testing panel appears broken after update

### ISSUE THREAD

**Issue by tyler36** [DEVSENSE/phptools-docs#150]
I'm having an issue after the recent update to  `1.12.9985`

- `1.11.97.62` version 
![image](https://user-images.githubusercontent.com/7234392/180121563-454b74ba-f56e-4ed2-ab9d-af02bfc51589.png)

- `1.12.9985` version
![image](https://user-images.githubusercontent.com/7234392/180121886-cbc7f767-c1d6-42fe-82af-064801399546.png)

- There are 2 test explorer panels
  -  The native test explorer panel appears at the top.
  - The "PHP Tools" test explorer panel appears at the bottom
- "PHP Tools" test explorer does not detect any tests

If I downgrade, and restart, things appear to work as expects.
Upgrading back to the latest breaks things again.

PHP Tools: `1.12.9985`
VSCcode:  `1.69.2`
OS: Ubuntu 2020.04 via WSL2 on Win10

**Comment by jakubmisek** [comment]
thank you @tyler36 for pointing this out.

The second (empty) Test Explorer panel is a leftover from two deprecated extensions, which you can uninstall.

  - `ms-vscode.test-adapter-converter` **(can be uninstalled)**
  - `hbenl.vscode-test-explorer` **(can be uninstalled)**

The panel will disappear.

We'll add some notifications, which will tell users they should uninstall those old extensions.

**Comment by jakubmisek** [comment]
![image](https://user-images.githubusercontent.com/842150/180244564-2260152c-9417-46f7-884e-10080b0cd9ca.png)

**Comment by tyler36** [comment]
Thank you for the update.

I uninstalled both extensions..
When I run PHP tools with a failing test, it opens a new tab pointing to `/home/user13/code/playground/debug-php-tools/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:186
 /home/user13/code/playground/debug-php-tools/tests/Feature/ExampleTest.php:19
 phpvfscomposer:///home/user13/code/playground/debug-php-tools/vendor/phpunit/phpunit/phpunit`

It displays the following message: "The editor could not be opened because the file was not found."

![image](https://user-images.githubusercontent.com/7234392/180334581-7c344872-c8f0-4b64-9da7-668e92dfab0e.png)

The test appears to be marked as failed as shown in the following screenshot, however the new feature outlined in #149 are not present.

![image](https://user-images.githubusercontent.com/7234392/180334847-aeeb79ec-9d39-4810-bdef-9db816aca9b2.png)

**Comment by bigbearzhu** [comment]
> Thank you for the update.
> 
> I uninstalled both extensions.. When I run PHP tools with a failing test, it opens a new tab pointing to `/home/user13/code/playground/debug-php-tools/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:186 /home/user13/code/playground/debug-php-tools/tests/Feature/ExampleTest.php:19 phpvfscomposer:///home/user13/code/playground/debug-php-tools/vendor/phpunit/phpunit/phpunit`
> 
> It displays the following message: "The editor could not be opened because the file was not found."
> 
> ![image](https://user-images.githubusercontent.com/7234392/180334581-7c344872-c8f0-4b64-9da7-668e92dfab0e.png)
> 
> The test appears to be marked as failed as shown in the following screenshot, however the new feature outlined in #149 are not present.
> 
> ![image](https://user-images.githubusercontent.com/7234392/180334847-aeeb79ec-9d39-4810-bdef-9db816aca9b2.png)

I'm having same issue when a test fails. Although it works fine if I debug the failed test. Seems there is something wrong parsing the file paths.

**Comment by jakubmisek** [comment]
May I ask what's in your Output window, `"PHP (PHPUnit)"` tab?
![image](https://user-images.githubusercontent.com/842150/182603238-3dc74695-ecba-4b05-892e-15da60964cab.png)
And then in your `Help/Toggle Developer Tools` -> `Console`?
![image](https://user-images.githubusercontent.com/842150/182603464-fd51204d-ec7b-4b07-ac61-38437f011401.png)


Thank you!

**Comment by tyler36** [comment]
Output window, `PHP (PHPUnit)` displays the following

```
Running tests ...
> /usr/bin/php7.2 -d display_errors=on /home/user13/code/laravel/iq-community/vendor/bin/phpunit --teamcity --filter ^(Tests\\Unit\\Livewire\\InvoiceIndexTest::only_authorized_users_can_approve_all_invoices(\s.*)?)$
PHPUnit 8.5.15 by Sebastian Bergmann and contributors.
Time: 1.37 seconds, Memory: 56.25 MB
FAILURES!
Tests: 1, Assertions: 16, Failures: 1.
```

Developer tools shows the following:

```js
[Extension Host] phpunit: looking for phpunit bin ...
console.ts:137 [Extension Host] phpunit: found 2 phpunit file(s).
instantiationService.ts:99 [createInstance] First service dependency of Fe at position 6 conflicts with 4 static arguments
_createInstance @ instantiationService.ts:99
createInstance @ instantiationService.ts:76
_fillBody @ testingOutputPeek.ts:699
_fillContainer @ peekView.ts:175
create @ zoneWidget.ts:237
show @ testingOutputPeek.ts:495
showPeekFromUri @ testingOutputPeek.ts:229
await in showPeekFromUri (async)
tryPeekFirstError @ testingOutputPeek.ts:174
openPeekOnFailure @ testingOutputPeek.ts:275
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
(anonymous) @ testResult.ts:497
fireUpdateAndRefresh @ testResult.ts:496
updateState @ testResult.ts:390
(anonymous) @ mainThreadTesting.ts:141
withLiveRun @ mainThreadTesting.ts:260
$updateTestStateInRun @ mainThreadTesting.ts:141
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
_fileReader.onload @ browserSocketFactory.ts:91
Show 12 more frames
log.ts:313   ERR Error: File not found
    at g.handleSetInputError (textFileEditor.ts:180:53)
    at async g.setInput (textFileEditor.ts:143:4)
    at async l.doSetInput (editorPanes.ts:353:4)
    at async l.doOpenEditor (editorPanes.ts:222:34)
    at async l.openEditor (editorPanes.ts:126:11)
    at async editorGroupView.ts:1089:49
    at async ue.showPeekFromUri (testingOutputPeek.ts:218:16)
```

**Comment by jakubmisek** [comment]
found it, fixing!

**Comment by jakubmisek** [comment]
Thank you all for letting us know. We're releasing an update `1.12.10139` which fixes the test failure location.

**Comment by tyler36** [comment]
Confirmed; working as expected on `1.12.10140`

Thank you for the update!

**Comment by jakubmisek** [comment]
thank you @tyler36 for the confirmation!
