### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by junakmlakonja** [DEVSENSE/phptools-docs#151]
- Issue Type: `Bug`
- Extension Name: `phptools-vscode`
- Extension Version: `1.12.9985`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 99,
		"activateCallTime": 60,
		"activateResolvedTime": 26081,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "DEVSENSE.phptools-vscode",
				"_lower": "devsense.phptools-vscode"
			},
			"activationEvent": "onLanguage:php"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by jakubmisek** [comment]
thank you for posting the issue @junakmlakonja 

May I ask if, or how many, PHP binaries you have installed?

*phptools* are resolving available `php`s at startup, and it may be the issue.

**Comment by junakmlakonja** [comment]
Just one PHP binary I'm afraid.

**Comment by jakubmisek** [comment]
thanks, we'll review what we do during the startup;

**Comment by jakubmisek** [comment]
@junakmlakonja it seems you're using a pretty old version - 1.12 - the current version is 1.16.

Please update, the issue should be resolved already.

Thanks!
