### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AlexandraBrRo** [DEVSENSE/phptools-docs#152]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.12.9985`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Ronn/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory: ⚠️`file:///c%3A/Users/Ronn/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

thank you for reporting the issue - I'm closing it now, but please send the `.cpuprofile.txt` file next time so we can try to fix it. Thank you :)
