### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by legumii** [DEVSENSE/phptools-docs#153]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.12.9985`
- OS Version: `Linux x64 5.18.0-kali5-amd64`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory: ⚠️`file:///tmp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Thank you for reporting the issue. **Please attach the file as noted above.**
