### ISSUE TITLE
Post Test Task

### ISSUE THREAD

**Issue by L3v3L** [DEVSENSE/phptools-docs#154]
I would love to be able to set a post vscode task to run after Testing has been completed, if not a vscode task maybe a command line to trigger.

**Comment by jakubmisek** [comment]
that's a good idea. I was looking if it can be configured directly in `phpunit.xml` and it seems it only allows to specify a bootstrap (before test run) ...

We have basically a few options how to add this feature:
- either extend `phpunit.xml` with our custom configuration (e.g. `cleanup=...`), something like:
  ```xml
  <phpunit bootstrap="./bootstrap.php" cleanup="./afterrun.php">
  ```
- or provide vscode task for test run with before/after commands
- or the same but as a vscode setting like `"phpunit.afterRunScript"="${workspaceFolder}/afterrun.php"`

Task would be the nicest option I guess.

**Comment by L3v3L** [comment]
well my vote would be a mixture of the last two.

vscode settings:
```json
    "phpTools.phpunit.preTask": "vscode-task-1",
    "phpTools.phpunit.postTask": "vscode-task-2",
```

not sure if this blows the scope of this feature, 
but passing the value used in the **--filter** as an argument to the task would be great!!

**Comment by jakubmisek** [comment]
> ... passing the value used in the **--filter** as an argument to the task would be great!!

Where to put the value? We can add a property "filter" or "testsuite" to the task being executed.

**Comment by jakubmisek** [comment]
@L3v3L we have pre-released version `1.13.10392` with `"phpunit.preTask"` and `"phpunit.postTask"` settings. It allows specifying a task name or array of task names.

It also adds an attribute "filter" or "testsuite" to the executed task, but I'm not sure how this works in practice.

**Comment by L3v3L** [comment]
I've just tested the "phpunit.preTask" and "phpunit.postTask", super!
some notes:

1. I'm not sure if using the phpunit prefix as the root for your settings is standard. 
I always thought that each extension would always prefix their settings with something that defines that these settings belong to a specific extension:
**phpTools**.phpunit.postTask vs **phpunit**.postTask

2. regarding the attributes, the ideia was so that the task could pass along what filter was used, this means, it could then be piped into another program. 
(if you still don't understand the pratical use, here's an example: I sometimes test individual tests, and sometimes I do a full run of all tests, and I only want something to post happen when I'm running the full run)

I thought maybe something like this would then work, 
`
{
    "label": "postmsg",
    "detail": "something",
    "type": "shell",
    "command": "echo ${filter}",
}
`

**Comment by jakubmisek** [comment]
awesome, thanks for the quick test!

1. you're right. We're actually planning to make this feature as a separate extension (which will be bundled with `phptools`)
2. I get it, I just don't know how to pass the `${filter}` value into the task using the vscode API. But we'll figure it out.

**Comment by jakubmisek** [comment]
> 2. I get it, I just don't know how to pass the `${filter}` value into the task using the vscode API. But we'll figure it out.

We have found the way; the variable is `${command:phpunit.filter}` or `${command:phpunit.testsuite}`. Implemented since `1.13.10393` (pre-release).

The task would look like this:

```json
{
  "label": "postmsg",
  "type": "shell",
  "command": "echo ${command:phpunit.filter}",
}
```

the setting:
```json
{
  "phpunit.postTask": "postmsg",
}
```

Let us know if there would be any other variables needed.

**Comment by jakubmisek** [comment]
I'll close the issue, but we can continue discussing the variables and other details here. Thanks!

**Comment by L3v3L** [comment]
tested and works, 

but small issue,
(just guessing) i think you need to set the variable to empty string when not given as this wont work:

```json
        {
            "label": "postmsg",
            "type": "shell",
            "command": [
                "echo '${command:phpunit.filter}'",
                "\n",
                "echo '${command:phpunit.testsuite}'"
            ],
        }
```

you have to use one or the other for it to work (refering to filter or testsuite), 
which defeats the purpose of the feature as, only the filter is set when running individual tests, and only the testsuite is set when running a suite of tests.

**Comment by jakubmisek** [comment]
you're right, we've just fixed that! preparing pre-release ...
