### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MkVerma643** [DEVSENSE/phptools-docs#155]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.12.10140`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.70.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/smb/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory: ⚠️`file:///c%3A/Users/smb/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

thank you, but we have to close the issue because the file was not attached
