### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pardmeister** [DEVSENSE/phptools-docs#158]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.13.10378`
- OS Version: `Darwin x64 21.6.0`
- VS Code version: `1.70.2`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt](https://github.com/DEVSENSE/phptools-docs/files/9468158/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt)

**Comment by jakubmisek** [comment]
thank you for reporting the issue; 

We've been working hard to fix the performance issues. It's not happening anymore, as far as I know.
