### ISSUE TITLE
Improve how function signatures are displayed in tooltips

### ISSUE THREAD

**Issue by ZebulanStanphill** [DEVSENSE/phptools-docs#159]
The current tooltips showing function signatures tend to look pretty messy when optional parameters are involved.

![image](https://user-images.githubusercontent.com/19592990/189271002-e3bf66a2-7645-4324-8490-7f54919ccfe4.png)

I think the square bracket syntax is too noisy, is unnecessary for params with default arguments, and doesn't even make much sense anymore since in PHP 8 you can include optional params like these in any order you please.

Maybe just have a little badge next to the optional params (without a default param) saying `optional`?

Additionally, I think it would help if functions with lots of parameters had each param on a separate line.

I think the [Intelephense](https://github.com/bmewburn/vscode-intelephense) extension handles this fairly well:

![image](https://user-images.githubusercontent.com/19592990/189271567-d1c997b9-ba16-4e31-966a-4356c643c39b.png)

**Comment by jakubmisek** [comment]
@ZebulanStanphill Thank you for the feedback!

You are right, this tooltip syntax we have is dated back from PHP 5.

I agree, that the square brackets are unnecessary, and for more than 3 parameters, we should split them into more lines.

We'll do it.

**Comment by jakubmisek** [comment]
We have prepared pre-release `1.14.10495` with the updates. The tooltips and generated code will look like the following now:

![image](https://user-images.githubusercontent.com/842150/189379025-0f1874ac-4b9f-4c9f-b654-2214d26d307e.png)

Thank you again for the suggestion!

**Comment by ZebulanStanphill** [comment]
@jakubmisek Wow, that was remarkably quick! Thank you so much!

**Comment by jakubmisek** [comment]
@ZebulanStanphill I'm glad if it helps! please let us know if there would be anything else
