### ISSUE TITLE
Reindexing when switching branches

### ISSUE THREAD

**Issue by gayanhewa** [DEVSENSE/phptools-docs#16]
This isn't a bug report. But when I am switching branches (which happens quite frequently) the editor gets stalled because of a full on reindexing. This is a bit disruptive. You should be able to replicate the behaviour on a fresh PHP framework project like Laravel or similar. Ideally, I would prefer if we can index in a lazy mode. Or less disruptively. Unsure if the language server is causing this behaviour in the way it kicks off parsing the files. 

Let me know if I can provide more information.

**Comment by jakubmisek** [comment]
Thank you. We should be doing the indexing on background already, but we'll definitely check and optimize the behavior if possible.

**Comment by jakubmisek** [comment]
recent updates improves the performance and additionally allows to disable background workspace analysis (https://github.com/DEVSENSE/phptools-docs/issues/29). 

closing

please add a new issue in case the problem remains.
