### ISSUE TITLE
Variadic parameters are incorrectly display as a comment in function signature tooltips

### ISSUE THREAD

**Issue by ZebulanStanphill** [DEVSENSE/phptools-docs#161]
The function signature tooltips currently display all variadic parameters as comments. I assume this bug has something to do with the `...` being misinterpreted.

![image](https://user-images.githubusercontent.com/19592990/191878158-ec987c75-2694-48d7-bbdd-8b256ee42361.png)

**Comment by jakubmisek** [comment]
Thank you for reporting the issue! you are right. This was designed a long time ago for PHP 5.4 ...

We'll fix it soon.

**Comment by jakubmisek** [comment]
we're releasing a pre-release (1.16.10631) with the fix

thank you for your feedback!
