### ISSUE TITLE
Code formatting named arguments

### ISSUE THREAD

**Issue by goevexx** [DEVSENSE/phptools-docs#163]
Since named arguments are supoorted in PHP I'm looking for a nice formatting solution for those cases. Generally arguments in a function could be expansed to multiple lines, if an ending `,` is given after the last argument, like flutter does.

**Comment by goevexx** [comment]
For example here is some dart code
```dart
formatMe(text1: '', text2: '', text3: '', text4: '');
```
which after adding `.` formats to 
```dart
formatMe(
    text1: '',
    text2: '',
    text3: '',
    text4: '',
  );
```
Likewise in PHP it could look the same.

**Comment by jakubmisek** [comment]
thank you @goevexx for reporting the issue!

**Comment by Miloslav** [comment]
Hi Nicolas,

Thanks again for reporting this. The next pre-release will fix the formatting of the named arguments.

As for wrapping the arguments command/settings, we will think about that one.

Cheers!
