### ISSUE TITLE
PHP1409 -- Should not be an error type, can be a warning

### ISSUE THREAD

**Issue by AShujiao** [DEVSENSE/phptools-docs#164]
Using "void' as a return value from a function redirect()

It's just that the comments are not standardized and should not be emphasized as error types. When the project has too many such prompts, it will be impossible to quickly find the real fatal error.

**Comment by jakubmisek** [comment]
Thank you for the feedback! You are right, usually, this can even be used intentionally.

We'll change the severity to "Warning" within the next update.

Meanwhile, you can configure the diagnostic in your workspace as described at https://docs.devsense.com/en/vscode/problems#editorconfig

**Comment by AShujiao** [comment]
Ok, it has been solved after configuration

**Comment by AShujiao** [comment]
> 感谢您的反馈！你是对的，通常，这甚至可以故意使用。
> 
> 我们将在下次更新中将严重性更改为“警告”。
> 
> 同时，可以在工作区中配置诊断，如 https://docs.devsense.com/en/vscode/problems#editorconfig 中所述

Just found that there are similar "PHP1408" -- Assigning "void" from a function name

**Comment by jakubmisek** [comment]
> Just found that there are similar "PHP1408" -- Assigning "void" from a function name

This will be updated as well. Thank you.
