### ISSUE TITLE
Composer Updates Require Restart

### ISSUE THREAD

**Issue by jimbo2150** [DEVSENSE/phptools-docs#165]
Whenever I run `composer update` in a terminal and a package that is used in my code updates to a newer version, that package is no longer available in intellisense. Files that use the updated packages appear in the Problems tab stating the class/function is not found. I have to restart VSCode in order for it to see the updated code.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue!

We can see it's happening, and we'll try to fix this asap.

**Comment by jakubmisek** [comment]
@jimbo2150 just a quick question - do you have the latest version?

**Comment by jimbo2150** [comment]
I have version 1.18.10692 (latest stable, not prerelease).

**Comment by jakubmisek** [comment]
thank you @jimbo2150

**Comment by jakubmisek** [comment]
There is a pre-release `1.18.10824` which fixes the issue (in most cases)

We'll be releasing the full release within a few days.

Thank you!

**Comment by jimbo2150** [comment]
After updating to 1.19.10893, restarting, and updating composer packages, this problem is still occurring.

**Comment by jimbo2150** [comment]
This appears to be fixed in 1.28.12222.

**Comment by jakubmisek** [comment]
@jimbo2150 thank you for the update!
