### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ManuelVR461** [DEVSENSE/phptools-docs#166]
- Issue Type: `Bug`
- Extension Name: `phptools-vscode`
- Extension Version: `1.18.10692`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakubmisek** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

@ManuelVR461 thank you for reporting the issue, but we have to close it. There is insufficient information.
