### ISSUE TITLE
Heredoc formatting doesn't work

### ISSUE THREAD

**Issue by goevexx** [DEVSENSE/phptools-docs#168]
Formatting a file containing Heredoc syntax formats badly.
Given
```php
$test = <<<TEST
It's
    a
        test.
TEST;
```
formats to 
```php
$test = <<<TEST
It's
    a
        test.TEST;
```
which breaks susequent code.

VSCode extension: DEVSENSE.phptools-vscode@1.18.10692

**Comment by Miloslav** [comment]
Hello,

Thanks for the bug report! This is actually fixed in the latest pre-release version.

Thank you!
