### ISSUE TITLE
Using a formatter removes the code

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#170]
## Code before formatting:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

<section <?php echo $class; ?> >
    <div>
        <div>
            <h1></h1>
        </div>
    </div>
</section>

</body>

</html>


```
## Code after formatting:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <section <?phpl?> >
        <div>
            <div>
                <h1></h1>
            </div>
        </div>
    </section>

</body>

</html>
```
## Problematic code section after formatting:
![image](https://user-images.githubusercontent.com/30685349/195986231-849df994-d9cb-47f8-9a87-3dac9b448bb1.png)

## Environment for tests:
- VsCode Version: 1.72.2
- PHP Tools v1.18.10878 Pre-Release
- OS Name:                   Microsoft Windows 11 Pro
- OS Version:                10.0.22621 N/A Build 22621

## VSCode settings:
```
{
    "workbench.colorTheme": "Darcula",
    "php.suggest.basic": false,
    "php.validate.enable": false,
    "emmet.excludeLanguages": [
        "markdown",
        "php"
    ],
    "php.problems.exclude": {
        "wp-admin/": true,
        "wp-includes/": true,
        "wp-content/plugins/": true,
        "vendor/": true,
    },
    "php.codeLens.enabled": false
}
```

**Comment by Miloslav** [comment]
Hello Łukasz,

Thank you for the issue!

This one should be fixed in the latest pre-release version. Please try it out and let me know.

Thank you!

**Comment by kanlukasz** [comment]
Hello,
My tests are performed on the pre-release version `1.18.10878 Pre-Release` 
![image](https://user-images.githubusercontent.com/30685349/195986793-51718f28-4561-4ea8-ae15-79eadaef5e01.png)


Is there a newer version?

**Comment by Miloslav** [comment]
You're right! This is broken in the pre-release, the release version is fine! 

Thank you - will be fixed

**Comment by Miloslav** [comment]
It should be fixed in the latest pre-release.

**Comment by kanlukasz** [comment]
I confirm. Works fine now. Thank you
