### ISSUE TITLE
No matching tag highlighted if we use php inside the tag

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#172]
## Video gif example:

![Animation2](https://user-images.githubusercontent.com/30685349/195987213-3f301bd0-e998-48a2-a276-914e660af0a8.gif)

## Note:
As you can see at the beginning of the video, all tags are properly matched / highlighted
But after using php inside a tag, the `</section>` tag does not highlight a match

## Environment for tests:
- VsCode Version: 1.72.2
- PHP Tools v1.18.10878 Pre-Release
- OS Name:                   Microsoft Windows 11 Pro
- OS Version:                10.0.22621 N/A Build 22621

## VSCode settings:
```json
{
    "workbench.colorTheme": "Darcula",
    "php.suggest.basic": false,
    "php.validate.enable": false,
    "emmet.excludeLanguages": [
        "markdown",
        "php"
    ],
    "php.problems.exclude": {
        "wp-admin/": true,
        "wp-includes/": true,
        "wp-content/plugins/": true,
        "vendor/": true,
    },
    "php.codeLens.enabled": false
}
```

**Comment by jakubmisek** [comment]
Thank you. We'll take a look at that, although it seems this is a bug in VSC HTML editor itself.

**Comment by kanlukasz** [comment]
> although it seems this is a bug in VSC HTML editor itself.

But if I disable your addon it works fine.

**Comment by Miloslav** [comment]
This is fixed in the upcoming pre-release.
