### ISSUE TITLE
No error when placing a properties inside interface

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#174]
## Describe the bug
No error when placing a properties inside interface

## To Reproduce
```
<?php

declare(strict_types=1);

namespace Test;

interface UsersInterface
{
    public array $users = [];
}

class Users implements UsersInterface
{
}

new Users;

```

## Screenshot:
![image](https://user-images.githubusercontent.com/30685349/195996672-65d27c4e-b56c-4310-8f38-9744119c9f70.png)

## Environment for tests:
- VsCode Version: 1.72.2
- PHP Tools v1.18.10878 Pre-Release
- OS Name:                   Microsoft Windows 11 Pro
- OS Version:                10.0.22621 N/A Build 22621

## VSCode settings:
```
{
    "workbench.colorTheme": "Darcula",
    "php.suggest.basic": false,
    "php.validate.enable": false,
    "emmet.excludeLanguages": [
        "markdown",
        "php"
    ],
    "php.problems.exclude": {
        "wp-admin/": true,
        "wp-includes/": true,
        "wp-content/plugins/": true,
        "vendor/": true,
    },
    "php.codeLens.enabled": false
}
```

**Comment by jakubmisek** [comment]
thank you! implemented in the upcoming `v1.22` (and the latest pre-release coming today)
