### ISSUE TITLE
One space after type casting operators

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#175]
_( I'm not sure but can be related with https://github.com/DEVSENSE/phptools-docs/issues/162 )_

Currently, after using the formatter, there is no space between the type cast operator and the variable value:
![image](https://user-images.githubusercontent.com/30685349/195998911-d1231c35-0778-4aa4-893b-c58218a96f52.png)

It would be much more legible if there was a space.
From what I see, this is how they write code in Symfony fw.
E.g.:
![image](https://user-images.githubusercontent.com/30685349/195998985-2631c679-b78b-4a09-966b-f36cdb514685.png)

**Comment by Miloslav** [comment]
This will be the default behavior in the next pre-release.

Thanks!

**Comment by jakubmisek** [comment]
preparing pre-release `1.19.10920` with the changes

thank you again for the feedback!

**Comment by Miloslav** [comment]
Fixed in the latest version.
