### ISSUE TITLE
Smart Select needs improvement

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#177]
**Describe the bug**
Smart Select sometimes have wrong selecting. Details below:

---

**Code snippets for test**
```
<ul>
  <li>Text: <?php echo $note['created'] ?></li>
</ul>
```
```
echo 'this is simple string';
```

---

**Expected behavior**
It should select more precisely step by step

---

**My suggestion of what the selection extending steps should look like**
**(more or less)**
![obraz](https://user-images.githubusercontent.com/30685349/93664680-06c45500-fa71-11ea-8c84-40b0b3dd8b6c.png)

**Another example:**
![image](https://user-images.githubusercontent.com/30685349/196043947-3246b2df-7eaa-4b29-a1f9-a62b0dddaa53.png)
![image](https://user-images.githubusercontent.com/30685349/196043953-60a10fca-ae96-4849-907a-8a818677e2e6.png)

**Comment by jakubmisek** [comment]
Thank you for the suggestion!

Actually, we don't provide "Smart Select" functionality at all, but it's on our to-do list.

**Comment by jakubmisek** [comment]
we're adding selection ranges into the next update;

For now, it will select statements (larger syntactic elements), but it'll be still in progress. Also we'll be adding smart select of HTML elements into the future release as well.

**Comment by jakubmisek** [comment]
The latest update ads smart select for doc comments and HTML elements. It also improves smart select for PHP syntax tree.
