### ISSUE TITLE
[Feature request] Highlighting of matching control structures

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#178]
This functionality always helps a lot. Especially when there is more code in between

I will show examples of how this works in the PHP Intelephense plugin.

![44](https://user-images.githubusercontent.com/30685349/196044553-bf1a6946-ecc9-4144-9d97-973110fc067c.gif)

What do you think?

**Comment by jakubmisek** [comment]
good suggestion! We already do that in the full Visual Studio - we'll enable this feature on VSCode as well.

**Comment by jakubmisek** [comment]
We're preparing pre-release `1.19.10906` which implements highlighting of loop-control-structures (for,while,foreach,do with corresponding `break` and `continue`), and highlighting occurrences of `return` , and `switch` with `break` and separately its `case`s

TO-DO: try-catch-finally, and if-else-elseif.

**Comment by kanlukasz** [comment]
It's great! Thank you
Ps. Would be nice to see an alternative syntax (e.g. `foreach` / `endforeach` ) highlighting as well, eg.:
![eeee](https://user-images.githubusercontent.com/30685349/196231856-796e5413-a2d6-496f-b4da-8a4556d9c0a7.gif)

**Comment by jakubmisek** [comment]
tracking:

- [ ] loop structures (for, foreach, do, while)
- [ ] switch
- [ ] end*** tokens
- [ ] try/catch/finally
- [ ] if/elseif/else/endif

**Comment by kanlukasz** [comment]
Great, thank you.
I test and found two little issues:

#### 1 - while/endwhile - (`while` is not highlighted)
![while1](https://user-images.githubusercontent.com/30685349/196479778-6b767f2d-c797-4097-9e4f-4f186da38c71.gif)

#### 2 - do/while- (`while` is not highlighted)
![do1](https://user-images.githubusercontent.com/30685349/196480006-fe7f9727-52a6-4f54-8047-3153cca6d14d.gif)
