### ISSUE TITLE
[IMPROVEMENT] Static analysis shows issue PHP0443 also for method/functions that do not depend on a fixed # of args (i.e. using "func_get_args()"/"func_num_args()" instead)

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#179]
Version:  1.19

`Too many arguments to function` issues (-> PHP0443) are shown also for methods/functions that do not depend on a fixed number of arguments by using the functions `func_get_args()` and `func_num_args()` instead., like for instance ...

```php
  public function methodWithNoFixedNumOfArgs(string $method): mixed
  {
      if (func_num_args() > 1) {
          return callMethod($method, func_get_args());
      }
      
      return callMethod($method);
  }
```

**Comment by jakubmisek** [comment]
you are right;

we were assuming there is always `vararg` notation, i.e.

```php
function methodWithNoFixedNumOfArgs(string $method, ... $args) {
```

**Comment by jakubmisek** [comment]
We're preparing pre-release `1.19.10906` which fixes the issue!

The full release might be ready in about week-or-two

**Comment by menturion** [comment]
Many thanks. 
Just tested with `1.19.10907`. 
It works.

**Comment by jakubmisek** [comment]
awesome, thank you for the confirmation
