### ISSUE TITLE
Problem with autoformating

### ISSUE THREAD

**Issue by deartify** [DEVSENSE/phptools-docs#18]
I have noticed many problems with autoformating.  For example jumping code on each format code command (doesn't metter Phptools style or PSR-2).

Sometimes it mess all the code. For example for missing ; deletes line of code before.
I will try to post here more examples.
[sample.txt](https://github.com/DEVSENSE/phptools-docs/files/2872946/sample.txt)

**Comment by jakubmisek** [comment]
Thank you for the issue! It seems when the code is syntactically incorrect, code formatter removes the invalid parts (!!), this will be fixed asap.

The jumping will be fixed as well. For now as I know, the formatting is not automatic (it has to be called via a command). Automatic formatting (On Paste, after typing `;` or `}`) will be introduced in a future update.

**Comment by jakubmisek** [comment]
@deartify The format is now not allowed for syntactically wrong code. The next update will target the jumping cursor. Thanks for the issue!

**Comment by jakubmisek** [comment]
the issue should be solved now, please reopen or comment if still fails
