### ISSUE TITLE
Ability to show `Problems` only for open files in the workspace

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#180]
Now, after indexing the entire workspace, the `Problems` pane shows all notifications - even for files that are not open.
Is it possible to setting display "Problems" only for open files in the workspace?

**Comment by jakubmisek** [comment]
That's actually intended behavior, that _phptools_ do perform full workspace diagnostics continuously.

However, you are right, that we don't have an option to analyze _only_ opened documents.

We're working on it!

**Comment by jakubmisek** [comment]
we're adding "php.problems.scope": "opened" setting in the next pre-release (version `1.19.10907`)
