### ISSUE TITLE
PSR-2 has been marked as deprecated

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#181]
## First of all:
Sorry for many tickets over the two days. It's not spam.
I understand that software takes time to develop. 
However, I test your extension very thoroughly and try to show you what can be fixed.

## Issue description:
As we know PSR-2 has been marked as deprecated. [PSR-12](https://www.php-fig.org/psr/psr-12/) is now recommended as an alternative.
Are you planning to replace it with PSR-12?

## Related:
https://github.com/DEVSENSE/phptools-docs/issues/162

**Comment by Miloslav** [comment]
Hi  Łukasz, we really appreciate you've taken the time to test and report all the things we can improve/fix!

PSR-12 is on the priority list, I will keep you posted on the progress.

**Comment by jakubmisek** [comment]
this is also tracked in https://github.com/DEVSENSE/phptools-docs/issues/162

**Comment by Miloslav** [comment]
The upcoming version adds the PSR-12 code style and makes it a default.
