### ISSUE TITLE
Missing "highlighting of matching control structures" for `while` in two cases

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#184]
Hi,

I test implementation from https://github.com/DEVSENSE/phptools-docs/issues/178 and found two little issues:

#### 1 - while/endwhile - (`endwhile` works fine but `while` is not highlighted)
![while1](https://user-images.githubusercontent.com/30685349/196479778-6b767f2d-c797-4097-9e4f-4f186da38c71.gif)

#### 2 - do/while- (`do` works fine but `while` is not highlighted)
![do1](https://user-images.githubusercontent.com/30685349/196480006-fe7f9727-52a6-4f54-8047-3153cca6d14d.gif)

**Comment by jakubmisek** [comment]
thanks @kanlukasz !

**Comment by jakubmisek** [comment]
will be fixed in the next pre-release/release!

thank you
