### ISSUE TITLE
Improvement of quick action to create getter and setter

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#187]
Let's assume I have the following class
```php
<?php

class User {
    private ?string $id;
}
```

If I right-click on `$id` I get the option to create a getter, setter or both ("Add getId and setId").
The latter will create the following:
```php
<?php

class User {
    private ?string $id;
    /**
    * @return ?string
    */
    function getId(): ?string {
    	return $this->id;
    }

    /**
    * @param ?string $id
    * @return User
    */
    function setId(?string $id): self {
    	$this->id = $id;
    	return $this;
    }
}

```

Suggestions:
1. add a new line after the property
2. change `@return ?string` to `@return null|string`
3. change the specific class name, e. g. `@return User` to `@return self`
4. add public by default for getter and setter (nowadays you always use visibility, even our linters enforce it)

See https://docs.phpdoc.org/3.0/guide/references/phpdoc/types.html regarding phpDocblocks.

**Comment by jakubmisek** [comment]
thank you! we're on it

**Comment by jakubmisek** [comment]
preparing pre-release `1.22.11127` with the changes! (~1 hour ETA)

thank you

**Comment by Zerotask** [comment]
Something I've noticed from another issue:
the generated code doesn't apply the configured code formatting (PSR12 in my case).

Also (and this might be subjective) for bool properties, people often expect the getter's name to be `ìsXXX` instead of `getXXX`.
Example:
```php
<?php

class User
{
    private bool $developer;
	/**
	 * @return bool
	 */
	function getDeveloper(): bool {
		return $this->developer;
	}
}
```

Could be:
```php
<?php

class User
{
    private bool $developer;
	/**
	 * @return bool
	 */
	function isDeveloper(): bool {
		return $this->developer;
	}
}
```

I think this is also the default behavior for PhpStorm.

The property's name could also be `$isDeveloper` and the generated getter then is `getIsDeveloper()`. Also for this case `isDeveloper()` would make more sense. 
Maybe there could be an extension config to decide which behaviour you want.


(indentation is correctly in vscode, just GH displays it wrong)
