### ISSUE TITLE
Improvements of docblock generation for class properties & constants

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#188]
## properties

Example:
```php
<?php

class User
{
    public ?string $id;
}
```

If I create a docblock, by writing `/**` before, it creates the following:
```php
<?php

class User
{
    /**
     * Summary of id
     * @var mixed
     */
    public ?string $id;
}
```

I would assume, that it creates `@var null|string`

It does work for methods, but not for properties.

## constants

example:
```php
<?php

class User
{
    public const NAME = 'test';
}
```

the generated dockblock then is:
```php
<?php

class User
{
    /**
     * Summary of NAME
     */
    public const NAME = 'test';
}
```

Regarding https://stackoverflow.com/questions/6706051/what-is-the-correct-way-to-write-phpdocs-for-constants etc. the recommened way is to use `@var` too.
Therefore I'd assume the following:
```php
<?php

class User
{
    /**
     * Summary of NAME
     * @var string
     */
    public const NAME = 'test';
}
```

Since you can't add a data type for const, you have to use Reflection for example to get type of the content.

Also, would it be possible to add a quick fix for the docblock generation (for all class members)?

**Comment by jakubmisek** [comment]
thanks, 
- [x] we've added the `@var` for constants and fixed type names for properties

**Comment by jakubmisek** [comment]
created new issue at https://github.com/DEVSENSE/phptools-docs/issues/226

this one is closed, thank you :)
