### ISSUE TITLE
x references hint shows wrong numbers

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#189]
I noticed multiple times, that those numbers are too high. For example it shows method calls with the same method name inside the vendor directory. The correct number in this case would be 6.

![image](https://user-images.githubusercontent.com/20150243/199591359-e49e80f8-cb18-40eb-9554-0d692c1de55a.png)

![image](https://user-images.githubusercontent.com/20150243/199591439-aada2030-0cec-4fce-a6a6-8cbf8198ada1.png)

My code does use classes and methods from vendor, but not vice versa, so I don't care about vendor here.

"Find all references" shows a similar number, at least with grayed out vendor files
![image](https://user-images.githubusercontent.com/20150243/199591901-5301f78e-720d-4ad2-a1db-80d42563d8a4.png)

**Comment by jakubmisek** [comment]
thank your for letting us know; it makes perfect sense.

We're showing all the references count, and we're also counting cases, where we don't know because of lack of type information in PHP ... we'll take a look what we can do. Ignoring references in 'vendor' folder is a good idea.

**Comment by jakubmisek** [comment]
we have updated the [references] count so it only shows the real references, ignoring the once that are not strongly typed, and hence not 100% sure about.
