### ISSUE TITLE
Laravel project starts with 2k errors

### ISSUE THREAD

**Issue by deartify** [DEVSENSE/phptools-docs#19]
When Im opening laravel project it starts with 2k+ problems :). After editing any php file and saving it, everything backs to normal. It's not a big problem to open and save random file but will be great when Im opening project and see only my mistakes :)

**Comment by Mordef** [comment]
Maybe this will help: https://github.com/DEVSENSE/phptools-docs/issues/5

**Comment by jakubmisek** [comment]
this issue should be fixed, also as mentioned this might help https://docs.devsense.com/en/vscode/problems#configuration :)
