### ISSUE TITLE
Docblock generation for `never`

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#193]
PHP 8.1 introduced the `never` type (https://php.watch/versions/8.1/never-return-type).
If I create a docblock for the following code, it should add `@return never` and not `@return void`
```php
<?php

class User
{
    public function getName()
    {
        exit();
    }
}
```

Not really important for me, I just noticed it while I was playing around.

**Comment by jakubmisek** [comment]
Definitely nice to have. We'll try to do it.

**Comment by jakubmisek** [comment]
added to the next pre-release!
thanks
