### ISSUE TITLE
Support `enum`

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#194]
I tried the example code from https://www.php.net/manual/en/language.types.enumerations.php and it can't be formatted
![image](https://user-images.githubusercontent.com/20150243/200040579-e9ca3d2a-bff4-4c13-9683-a238a849fbe6.png)

Also I can't hover enums (doesn't show anything), don't have auto-completion etc.

```php
<?php

enum Suit
{
    case Hearts;
    case Diamonds;
    case Clubs;
    case Spades;
}

function do_stuff(Suit $s)
{
    // ...
}

do_stuff(Suit::Spades);
```

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

The code above works for us correctly. Don't you have something else in here? It seems the editor "thinks" there are syntax errors?

**Comment by jremerich** [comment]
I'm having an issue with enum to, look:
![image](https://user-images.githubusercontent.com/7144038/204688861-d03ef13c-e10a-45bf-be46-1debf5d22937.png)

This is the only problem. All others features like hover and auto-completion are fine.

**Comment by jakubmisek** [comment]
> I'm having an issue with enum to

Hi @jremerich - this looks like the editor language version is set to something <= 8.0
![image](https://user-images.githubusercontent.com/842150/204924895-86692341-795a-4475-b746-ced55c698422.png)

Click on the version number and select PHP >= 8.1. More at https://docs.devsense.com/en/vscode/php-version

**Comment by jremerich** [comment]
Hi @jakubmisek !!!

Oooo, I see that option, but I have my environment in docker containers... So I need to use Dev Containers or something like that, right?

**Comment by jakubmisek** [comment]
I believe the editor itself should work just fine. Or isn't the _PHP Version Picker_ showing you your PHP in there like that?
![image](https://user-images.githubusercontent.com/842150/205488608-d9e71b72-8f0f-4398-a2ac-6df82d5df9ba.png)

---

For debugging and running in a docker container, we have the following tutorials if you'd be interested:
- https://blog.devsense.com/2022/develop-php-in-docker
- https://blog.devsense.com/2022/laravel-on-docker
