### ISSUE TITLE
LDAP_OPT_X_* constants incorrectly defined as strings (should be int)

### ISSUE THREAD

**Issue by gwythan** [DEVSENSE/phptools-docs#195]
Hello,

In PHP 8.1

The following code:

<img width="872" alt="Screenshot 2022-11-04 at 17 49 40" src="https://user-images.githubusercontent.com/59928681/200042525-59336739-daa4-44a2-8462-42ad9c24c0b9.png">

Gives the following error:

[{
	"resource": "/Users/kevinash/Sites/devsense/ldap_set_option.php",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": "PHP0406",
	"severity": 4,
	**"message": "Argument '2' passed to ldap_set_option() is expected to be of type int, string given",**
	"source": "PHP",
	"startLineNumber": 5,
	"startColumn": 23,
	"endLineNumber": 5,
	"endColumn": 47
}]

It turns out that the type hint for ALL of the LDAP_OPT_X_* constants are defined as "@var string" in the generated definition:

<img width="536" alt="Screenshot 2022-11-04 at 17 47 40" src="https://user-images.githubusercontent.com/59928681/200042185-e6de2784-9b60-4a2a-8492-e3e41022f416.png">

I don't know if it is PHPSENSE that generates this code, but they should be defined as "@var int"

Thank you.

**Comment by jakubmisek** [comment]
thank you for letting us know! Yes, the type hint is incorrect. Will be fixed

**Comment by jakubmisek** [comment]
it seems it is incorrectly specified in PHP documentation - https://www.php.net/manual/en/function.ldap-get-option.php

we'll fix it in the PHP Editor integrated manual for now

**Comment by jakubmisek** [comment]
fixed in the next pre-release, thank you
