### ISSUE TITLE
`false` not recgonized as an argument/return type.

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#196]
When use the [false pseudo-type](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.composite.union.false) in a union type PHP Tools doesn't properly recognize it and incorrectly reports an error like `Use of unknown class: 'Foo\Bar\false' PHP(PHP0413)`

**Comment by jakubmisek** [comment]
thank you for reporting the issue!

You are right, the `false` pseudo-type is not handled in union types. Will be fixed!

**Comment by jakubmisek** [comment]
fixed in the next pre-release! thank you
