### ISSUE TITLE
PHP DocBlocker Support

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#20]
Please disable warnings for PHP DocBlocker or implement same funktions.
Warning comes with last Update.

**Comment by Kcko** [comment]
I confirm this, its in a conflict, previous version works fine together .

**Comment by jakubmisek** [comment]
With the update PHP Tools extension support PHPDoc features described at https://docs.devsense.com/en/vscode/editor/phpdoc . The setting `editor.formatOnType` has to be enabled.

It conflicts with features of DocBlocker.

**Comment by jakubmisek** [comment]
Doc blocks will be inserted as snippets (with placeholders) in the upcoming update.

**Comment by jakubmisek** [comment]
Version 1.0.3213 (https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode) should work very similarly. Don't forget to enable `editor.formatOnType` setting.

If there would be anything else we can improve in PHPDoc generator and PHPDoc completion, please start a new issue, we'll be happy to make improve this feature as possible.
