### ISSUE TITLE
Enhancement: Add auto imported classes in alphabetical order.

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#200]
Currently auto imported classes (`use` statements) are always added at the end of the list. It would be nice if the new imports were added in alphabetical order.

The [PHP Namespace Resolver](https://github.com/MehediDracula/PHP-Namespace-Resolver#settings) extension has the option for doing so.

**Comment by jakubmisek** [comment]
thank you! We're doing it in the quick fix already. So we should probably do the same in code completion when auto-import.

**Comment by jakubmisek** [comment]
![vsc-autoimport-sorted](https://user-images.githubusercontent.com/842150/204293760-ff634b03-e10d-4f70-af33-a078cea7d60f.gif)

We should be sorting the auto-imported names already. Does it work for you like that?

Thnak you

**Comment by ADmad** [comment]
> Does it work for you like that?

Nope, new imports always get added below the existing imports for me.

**Comment by ADmad** [comment]
Umm no, it's `v1.6.8448`. But VS Code doesn't show me any available update. It reinstalled and still get the same version.

I see that https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode is showing the `1.23.11386`.

Any ideas why the latest version isn't being installed?

**Comment by ADmad** [comment]
My apologies, I had an older version of VS Code itself which was incompatible with the latest version of the extension. Alphabetical sorting seems to work fine with v1.23 of the extension.

**Comment by jakubmisek** [comment]
Good! I'm glad it works for you now
