### ISSUE TITLE
Incorrect error for PCRE pattern syntax.

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#201]
```
PCRE pattern syntax error: Not enough )'s.PHP(PHP0439)
``` 
is shown for this valid pattern 
```
/^[0-2]?[0-9]:[0-5][0-9](?::[0-5][0-9](?:\.[0-9]{1,6})?)?$/
```

**Comment by jakubmisek** [comment]
thank you for reporting the issue!

**Comment by jakubmisek** [comment]
it's not happening in our test code:
![image](https://user-images.githubusercontent.com/842150/200575820-344d641d-f252-4f43-8c55-305305db0a33.png)

```php
<?php

preg_match('/^[0-2]?[0-9]:[0-5][0-9](?::[0-5][0-9](?:\.[0-9]{1,6})?)?$/', $s);
```

May I ask you to share your piece of code?

**Comment by ADmad** [comment]
https://github.com/cakephp/chronos/blob/a21b7b633f483c4cf525d200219d200f551ee38b/src/Traits/RelativeKeywordTrait.php#L39

**Comment by ADmad** [comment]
![Screenshot from 2022-11-08 19-38-49](https://user-images.githubusercontent.com/142658/200586509-280d991b-4595-4d67-8330-da4ae479157b.png)

**Comment by jakubmisek** [comment]
@ADmad thank you! we'll try that

**Comment by ADmad** [comment]
I no longer see this error with v1.23.

**Comment by jakubmisek** [comment]
thank you for the update!
