### ISSUE TITLE
Incorrect error regarding return value code paths for method with exceptions

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#202]
```
'rowCountAndClose': not all code paths return a value PHP(PHP0405)
```

https://github.com/cakephp/cakephp/blob/4b1f17c669634a8789ccdfbf06c07366b1cc7815/src/Database/Query.php#L282-L290

**Comment by jakubmisek** [comment]
It seems it is fixed in the latest pre-release (`v1.22.11181`):

![image](https://user-images.githubusercontent.com/842150/200864693-dd1eb9ef-384d-40b6-9467-8fb523f6f578.png)
