### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by babakfp** [DEVSENSE/phptools-docs#203]
![Screenshot 2022-11-08 194324](https://user-images.githubusercontent.com/44144724/200733207-3800afc6-9cae-468a-83ac-ab63c6cd00db.png)

**Comment by Miloslav** [comment]
Hi Babak,

Thank you for reporting the issue. We've fixed this one. It will be available in the pre-release within a few hours.

**Comment by Miloslav** [comment]
This is fixed in the pre-release version.

Thank you again for reporting!
