### ISSUE TITLE
PHPUnit Test indicator does not reset when 'Run Tests' is cancelled

### ISSUE THREAD

**Issue by gwythan** [DEVSENSE/phptools-docs#204]
Hi,

A UI issue.

When you click the 'Run Tests' button at the top of the testing panel...

<img width="299" alt="Screenshot 2022-11-09 at 09 38 54" src="https://user-images.githubusercontent.com/59928681/200795312-64e4af5c-c32d-44f3-a4e5-7f72f599d626.png">

...then click the 'Cancel Test Run' button...

<img width="288" alt="Screenshot 2022-11-09 at 09 35 12" src="https://user-images.githubusercontent.com/59928681/200795482-d100f1e1-5047-4f91-bf32-6cbe96671bd6.png">

The test *do* stop running but the 'Run Tests' button does not reappear, and the test indicator at the bottom of the window does not reset (it just stays like this):

<img width="368" alt="Screenshot 2022-11-09 at 09 34 59" src="https://user-images.githubusercontent.com/59928681/200796047-e9694353-c25c-4e1a-9136-dc4e66e42929.png">

I'm not sure if this is a PHPSENSE issue or a problem with the VSC testing framework, but I thought I'd raise it here.

The only way I know to reset the Test controls is to quit and restart VSC.

Thank you!
Kevin

**Comment by jakubmisek** [comment]
Thank you for reporting the issue! We'll try to fix that in the next release )

**Comment by jakubmisek** [comment]
tracking issues

- [ ] handle cancelling test run, and do not run more processes
- [ ] in case of error, properly end the run session (reset the run/stop button)
- [ ] when test run is cancelled, stop the pending `php` process

**Comment by jakubmisek** [comment]
the test run should be handled correctly now.

Canceling tests will kill the pending `php` since the next update (v1.26)
