### ISSUE TITLE
Trailing comma not supported in Closure `use` clause

### ISSUE THREAD

**Issue by ZebulanStanphill** [DEVSENSE/phptools-docs#207]
Trailing commas should be supported in the Closure `use` clauses, but they're not, and they cause the extension to fail parsing code that use them.

![image](https://user-images.githubusercontent.com/19592990/204196666-217e8eec-1546-46ff-872a-5cb5024d54a6.png)

![image](https://user-images.githubusercontent.com/19592990/204196805-6c3e8b66-1399-4549-ab4a-6c6cbc8fa8f8.png)

**Comment by jakubmisek** [comment]
thank you for reporting the issue, will be fixed!

**Comment by jakubmisek** [comment]
preparing pre-release with the fixes

**Comment by jakubmisek** [comment]
pre-release `1.23.11385` fixes that, 

thank you!
