### ISSUE TITLE
Extension fails to start PHP server on latest

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#211]
Issue happening when updated to v1.23.11386, **not happening on v1.23.11367 tho, so rolling back fixes the problems**

<img width="483" alt="image" src="https://user-images.githubusercontent.com/2331052/204522401-27365451-feb2-4d19-9f7e-cea34c70f21c.png">

### Output logs

https://gist.github.com/d8vjork/877787900de6892a8961302504cce826

### Environment

**Operating System:** Mac OS X 12.6.1
**VS Code:** 1.73.1
**Extension:** v1.23.11386

**Comment by jakubmisek** [comment]
thank you for reporting that ,will be fixed!

**Comment by Miloslav** [comment]
Fixed in the upcoming pre-release. Thanks!
