### ISSUE TITLE
Ctrl + Click or Cmd+Click (Mac OS) doesn't go to definition (as expected by any language tool in VSCode)

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#214]
### Expected behaviour

Cmd+Click / Ctrl+Click just goes to my class/method/function definition

### What it does

Nothing...

**Extension version:** v1.24.11486

**Comment by jakubmisek** [comment]
thank you for noticing!

We've introduced a bug in the latest pre-release. Fixed now, and preparing an update.
