### ISSUE TITLE
8.2 Random Classes Not Recognized

### ISSUE THREAD

**Issue by jimbo2150** [DEVSENSE/phptools-docs#215]
The PHP 8.2 `Random` namespace (`Randomizer` & engines) classes are not being recognized.

![vscode-phptools-8 2-new-classes-unknown](https://user-images.githubusercontent.com/25777094/206917800-736c4021-bf0b-4ca9-ad65-a298a9f1fc84.png)

Linux x64
PHPTools v1.25.11537

**Comment by jakubmisek** [comment]
@jimbo2150 thank you for letting us know! We'll update the integrated manual with the new PHP 8.2 Random core extension.

**Comment by jakubmisek** [comment]
New class definitions were added in the pre-release `1.25.11540`.

Thank you!
