### ISSUE TITLE
Wrongly marked as issue (unrecognised type through arrow function binding)

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#217]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/2331052/207380863-6c2f6bc1-297d-4169-aa15-24c15a856c3f.png">

### Expected behaviour

Not report any error as is enforced to be typed as string

**Comment by jakubmisek** [comment]
That's interesting, thank you for reporting that.

**Comment by jakubmisek** [comment]
fixed, thank you. Will be available in the next pre-release
