### ISSUE TITLE
[Feature request] Number of calls

### ISSUE THREAD

**Issue by helloguille** [DEVSENSE/phptools-docs#218]
I'm using the profiler. Great add-on! It'll be very popular since it is such a big problems being solved.

I'd like to see the number of calls to a function along its performance cost.

Guillermo

**Comment by jakubmisek** [comment]
Thank you, Guillermo!

I believe there is a number of calls already (https://docs.devsense.com/en/vscode/profiling#inspecting-call-times).

Did you mean to put the number somewhere else? We'll be happy to improve!

**Comment by helloguille** [comment]
Thanks!

**Comment by jakubmisek** [comment]
if it was what you meant, I;m closing the issue :-) thank you

**Comment by helloguille** [comment]
Yes, thanks. I actually was looking to have the number of call in the source code, but I think it would look too cluttered.
