### ISSUE TITLE
[Feature request] Mask path

### ISSUE THREAD

**Issue by helloguille** [DEVSENSE/phptools-docs#219]
I work locally with a mounted veloume on a Container, which means that, the files have a different execution path:

I must run this in order to get the hot paths working:

sed -i '' 's/\/var\/www\/html/\/Users\/helloguille\/webapps\/pms/g' xdebug.out.*

It would be cool to automise this.

**Comment by jakubmisek** [comment]
May I ask for more details?

- what you are trying to do (debugging, profiling, or just opening xdebug profile output?)
- is there any error in VS Code console?

Thank you

**Comment by jakubmisek** [comment]
Thank you, so quick summary (for me); it's about the profiling and hot path feature; the paths in the xdebug.out file do not match the files URI in the VSCode workspace.

**Comment by jakubmisek** [comment]
I've added relative path resolving; which works in most cases including this one.

Released in the next update (v1.31 or pre-releases since today), please let me know if it helps)

**Comment by helloguille** [comment]
Hi! Thank you so much for making progress.

It didnt work form me but I could help you. Could you point at the source file that resolves the path?

**Comment by jakubmisek** [comment]
@helloguille thank you for the update;

Are you profiling by yourself, and then opening the cachegrind file in VSCode I guess?

> It didnt work form me but I could help you
Thank you! More details would help - are you on Windows or Linux/mac?

> Could you point at the source file that resolves the path?
There is no source file available actually.
