### ISSUE TITLE
Enhance detection of undefined variables

### ISSUE THREAD

**Issue by AShujiao** [DEVSENSE/phptools-docs#22]
![image](https://user-images.githubusercontent.com/14969576/54897492-97b18300-4f03-11e9-9785-dc4b89363d50.png)

：Unused variable detection
$abc  And  $weher (Deliberately wrong)
Only ‘abc’ will warn

![image](https://user-images.githubusercontent.com/14969576/54897583-01ca2800-4f04-11e9-8047-4ec999df9005.png)
This is ‘PHP Intelephense’ The detection of the plugin is normal

**Comment by jakubmisek** [comment]
Hello, thank you for the issue.

Technically `$weher['b'] = 1` is correct and defines a new variable. However; I see in this case it is a typo.

We'll take a look whether we'll report it is a warning, and keep you informed in this thread.

**Comment by jakubmisek** [comment]
Thanks again for suggesting the feature. It will be available within the next update of VSCode and VS extension.
