### ISSUE TITLE
Don't auto import `parent`.

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#224]
Currently when trying to autocomple `parent` (for a call to the parent class' method) it gets auto imported too (`use parent`) at the top of the file, which is invalid. `parent` shouldn't be listed for auto importing since it's not a function or class.

![Screenshot from 2022-12-19 23-07-29](https://user-images.githubusercontent.com/142658/208487645-787f2b39-8252-42cd-afb4-7a9f552aa324.png)

**Comment by jakubmisek** [comment]
@ADmad thank you! that's totally wrong

**Comment by jakubmisek** [comment]
preparing release `1.25.11633` with the fix
