### ISSUE TITLE
Laravel's container injection function `app()` gets confused

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#228]
I think this is a regression or something as it was perfectly working fine before.

### Actual behaviour

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/2331052/209540003-aac01ed0-d4ca-485b-99dd-6e934081c1bc.png">

### Expected behaviour

Should take second suggestion rather than the first...

1. First is coming from Laravel's Application facade which is what is being used by that `app()` but wrapping all container injections to that `DuplicateRevisionWithContent` class
2. `DuplicateRevisionWithContent` class has a handle function with a single array argument, not Request or anything

I know this is some magic from Laravel, anyway every framework uses it (at least Symfony does)

**Comment by jakubmisek** [comment]
thank you! We have to find out, where it's getting the first `handle()` function :)

**Comment by d8vjork** [comment]
@jakubmisek This is the one that I see in all `app(MyClass::class)`: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Application.php#L987

**Comment by jakubmisek** [comment]
I see. It finds both `handle()` functions on `Application` class (which implements the `Application` interface returned by `app()`, and `handle()` on `DuplicateRevisionWithContent` class.

So, in case there is `phpstorm.meta` file overriding the `app()` return type, we should ignore the `Application` interface specified on `app()` doc comment.

**Comment by jakubmisek** [comment]
will be in the next pre-release, thanks!
