### ISSUE TITLE
array_map using arrow function gets problem (PHP0421) while normally shouldn't

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#230]
### Actual behaviour

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/2331052/209962050-44288322-5854-4ce7-a790-d825fb0548a3.png">

This only happens when using arrow functions on `array_map`, the following example is fine (which is the comparative to the arrow function one):

```php
$myFunc = fn () => array_map(function ($item) {
    return $item[0];
}, ['hello' => ['foo'], 'world' => ['bar']]);
```

### Expected behaviour

To not report this **PHP0421** problem when done as an arrow function like this:

```php
$myFunc = fn () => array_map(fn ($item) => $item[0], ['hello' => ['foo'], 'world' => ['bar']]);
```

**Comment by jakubmisek** [comment]
thank you @d8vjork , fixed!
