### ISSUE TITLE
Add problems to non imported but used PHP 8 attributes

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#231]
When typing an attribute class and not importing anything PHPTools doesn't complaint about any problem, but PHP will at runtime (sometimes, just in case the attribute is required somehow somewhere else at the reflection thingy).

So taking the following example:

```php
<?php

namespace App;

#[HookAttribute('foobar')]
class MyClass
{
// the rest of the class
```

HookAttribute being undefined doesn't get marked as a problem, I think it should at least appears as a warning (the yellow one), or maybe the red one to add some visibility to the problem...

**Comment by jakubmisek** [comment]
we will check that, although just a note, PHP allows writing anything as an attribute, e.g.

```php
#[literally_anything]
```

and reflection will work fine. Only instantiation of the attribute class will fail.

**Comment by jakubmisek** [comment]
implemented in the next pre-release!
