### ISSUE TITLE
when navigating the class name，how to navigate to class file

### ISSUE THREAD

**Issue by augushong** [DEVSENSE/phptools-docs#233]
I want when instantiating a class, when navigating the class name, it navigates to the class file instead of the constructor of its parent class, how to do?

Like the screenshot below, when tracking jumps, I want to jump to the file of the class.
This class doesn't define a constructor, so it traces back to the constructor of its parent class.
But I want this case to jump to the class file.

![图片](https://user-images.githubusercontent.com/31880431/210473234-f55c604e-8fd0-4f97-b1e3-c9dcfb2f4ab7.png)
![图片](https://user-images.githubusercontent.com/31880431/210473251-9bce12f2-838b-4983-9a3e-63aeef93eeba.png)
![图片](https://user-images.githubusercontent.com/31880431/210473268-509c8163-22ba-4b6c-9142-3cd8a6972c8e.png)

**Comment by jakubmisek** [comment]
@augushong Thank you for the issue.

It makes sense. We should jump to the class, not its parent. We'll do something about it in the future update.

**Comment by jakubmisek** [comment]
We're going to Go To the Definition of both - the class and the constructor, so the user can choose.

Will be available in the next pre-release.
