### ISSUE TITLE
Feature Request: Add support for `list` type.

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#235]
[phpstan](https://phpstan.org/writing-php-code/phpdoc-types#lists) and [psalm](https://psalm.dev/docs/annotating_code/type_syntax/array_types/#lists) support the `list` type.

But phptools doesn't recognize/support it and gives an error like `Use of unknown class: 'Foo\Bar\list'PHP(PHP0413)`.

**Comment by jakubmisek** [comment]
thank you @ADmad - adding `list`, `list<types, ...>`, and we've seen `list{ ... }` as well

**Comment by jakubmisek** [comment]
also adding `non-empty-list<Type>`

**Comment by jakubmisek** [comment]
release in pre-release `1.26.11908`

the full release will be ready within a week!
