### ISSUE TITLE
Laravel Model Constructor Warnings

### ISSUE THREAD

**Issue by ev3nst** [DEVSENSE/phptools-docs#236]
I tried vs studio code extension today and i must say this has one of the best features freely available. thank you for your great efforts.

I mainly working with laravel framework and i noticed some incorrect warnings.

````php
$user = new User([
  'name' => 'Test User',
]);

````

outputs -->
`Class 'App\Models\User' does not have any constructor and shall be called without argumentsPHP(PHP0441)`

Im also using "barryvdh/laravel-ide-helper". Is this package redundant or does it still have some benefits ? Because im also getting false warnings on "_ide_helper_models.php" file. My models implements interface and necessary methods are present on the model but im getting error as "... does not implement abstract methods:"

**Comment by ev3nst** [comment]
After i removed "_ide_helper_models.php". problems are gone. i presume "barryvdh/laravel-ide-helper" is redundant when using this extension ?

**Comment by jakubmisek** [comment]
@ev3nst thank you for trying our extension!

We're working on improving the warnings; so any feedback is appreciated.

`barryvdh/laravel-ide-helper` may cause some issues, but the goal is to be compatible since `barryvdh/laravel-ide-helper` provides important and useful metadata for Laravel; i.e. by running
> php artisan ide-helper:generate
> php artisan ide-helper:meta

If you're having some false warnings, we'll be happy to try to fix them. Some screenshots (for example a mouse tooltip of the `User` class) may help to diagnose the cause.

**Comment by ev3nst** [comment]
Sure. Here is the screenshots of aforementioned warnings.

![models_warn_1](https://user-images.githubusercontent.com/16917285/211202284-ccc1e968-3e67-4405-967f-dd0476e8517a.png)
![models_warn_2](https://user-images.githubusercontent.com/16917285/211202286-df9ddb14-e162-4cc1-9205-a74c6e69961b.png)

Like i said if i dont use the "_ide_helper_models.php" these warnings disappear.

App\Models\User.php
````php

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

use App\Models\IModels\Searchable;

class User extends Authenticatable implements Searchable {
    use HasApiTokens, HasFactory;
  // code ....
````

**Comment by jakubmisek** [comment]
Ok, it seams ide-helper has a few bugs, and the generated code is not valid, indeed.

Removing ide-helper should fix most of the issues; since we do support Laravel+Facades+Services out of the box.

Recommending to install latest pre-release.
