### ISSUE TITLE
Follow syntax colouring on fully qualified classes (docblocks)

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#238]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/2331052/211580126-74b151f0-237e-45d7-a96f-69f1d69ba1b8.png">

I think this should follow the colouring that VSCode uses on the PHP imports (at the top), like these:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/2331052/211580357-2b215e7e-923c-4d92-8f76-b7a7ee41dec4.png">

Leaving last part after last "\" character with different color will help alleviate eye stress and focus on the class names (the most important).

Otherwise, found this last thing quite the addon, good job!

**Comment by jakubmisek** [comment]
Thank you @d8vjork !

Yes, we needed to colorize Doc Block types correctly, since VSCode doesn't understand all the quirks of phpstan and psalm, and you're right about the namespace names ...

We had to break the following since the VSCode API does not provide all the semantic tokens needed

- [ ] color of primitive types (they are colored as keywords now)
- [ ] color of namespaces

We'll try to workaround/fix that, namespace should be colored as you say.

**Comment by jakubmisek** [comment]
---
BTW; this update provides different semantic types for generic types, enums, interfaces, and classes, so (at least in PHPDoc), **they can be colorized differently**

If this is not provided by the theme you're using, colors/styles can be set in settings.json:

```json
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "enum": "#FF0000",
            "interface": {
                "foreground": "#00FF00",
                "fontStyle": "italic"
            }
        }
    }
```

**Comment by d8vjork** [comment]
I understand, VSCode doesn't really provide anything easier so you do all yourself

Awesome, will be cool to know how compatible this could be with some templates or if they can be adapted to these new tokens (I guess its what you guys made from the extension, which is great)

**Comment by jakubmisek** [comment]
with the upcoming pre-release, we'll leave the namespace part untouched:

![image](https://user-images.githubusercontent.com/842150/211591097-966bb6a8-5cb9-44b1-8df9-964e26e41980.png)

**Comment by d8vjork** [comment]
Awesome! Looking great
