### ISSUE TITLE
Extension causes high memory load

### ISSUE THREAD

**Issue by dev24athis** [DEVSENSE/phptools-docs#239]
**- Issue Type**: Performance
**- Extension Name:** DEVSENSE.phptools-vscode
**- Extension Version:** 1.27.12036
**- OS Version:** Windows 10 x64
**- VSCode version:** 1.74.2

[Attachment](https://anonymfile.com/ad2qY/capture.png)

**Comment by dalpat** [comment]
[Solution] Uninstalled. Use PhpIntelephense by Ben Mewburn instead.

**Comment by jakubmisek** [comment]
@dev24athis May I ask for more details? I cannot view the attachment. It would help us to know your project size, what you do, how much memory is "high", how fast does it happen?
