### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DevelopOne11** [DEVSENSE/phptools-docs#24]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.0.3428`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/xcodeserver/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
Thank you for the issue - may I ask you to attach the file?

**Comment by jakubmisek** [comment]
update: latest update (`1.0.3645`) decreases times for the workspace opening. For circa 18000 PHP files (biggest project we worked with), 4 yrs old Core i7 6th gen, 2-core, SSD, it takes:
- 4-6 seconds to read content of files from disk
- ~4 seconds to parse the files
- during typing and activity, the extension does not perform any additional background tasks
- ~22 seconds workspace-wide code analysis **once** during inactivity. There is a feature request to disable workspace-wide analysis (https://github.com/DEVSENSE/phptools-docs/issues/29).

**Comment by jakubmisek** [comment]
Recent update (`1.0.3686`) introduces set of performance improvements as described above -> closing

Please create a new issue with more details if the problems persists :)
