### ISSUE TITLE
rector internal stubs conflicting with PHPTools internal types

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#241]
Add rector to any project that contains enums: `composer require --dev rector/rector`

### Actual behaviour

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2331052/212678943-586a7ac9-4327-45a3-bf13-84e382cae0d0.png">

Looking to the definition of that `\BackedEnum` seems like PHP Tools is taking it before its own implementation of `\BackedEnum`

### Expected behaviour

While I think this is a good thing to have (I even think Symfony have some packages like `php-${extOrPHPVersion}-polyfill` for the purpose of adding stuff to IDEs)

I worry anything PHP related can be modified by adding a simple dependency that does stuff like this and breaks the functionality of this extension and its autocompletion

Hope there's an alternative solution for these types to either be friendly with the stuff mentioned before (Symfony polyfills) and internals of this extension

**Comment by d8vjork** [comment]
Related and breaking feature #229 (might have other internal stuff broken as well)

**Comment by jakubmisek** [comment]
I agree; the rector's `BackedEnum` is defined conditionally - in such case, we should definitely prefer our annotated definition.

**Comment by jakubmisek** [comment]
preparing pre-release which hides most of the polyfill declarations from the IntelliSense
