### ISSUE TITLE
Cancel insertion of docblock "snippet" when pressing more keys after expand

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#243]
Always when I start typing a docblock with `/**` and type anything else this takes time sometimes which is fine, but some other times when I want custom stuff I just start typing immediate and seems like own VSCode + PHPTools snippets colides:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/2331052/212901217-61e70e15-5692-47f2-b171-9277734ad9fb.png">

Creating that faulty docblock, so I wonder if there's an easy way to fix this by cancelling after user type any other key and/or don't wait the snippet "expansion" process

**Comment by jakubmisek** [comment]
@d8vjork Good point. I was investigating a little already (reported on https://community.devsense.com/d/732-phpdoc-issue-with-bad-type-and-syntax-error)

We handle `/**` in VSCode's "formatOnType" and then we change the piece of code to a snippet with placeholders; this may be causing the problem - so as you said, if user is typing, we should cancel the expansion process.

**Comment by jakubmisek** [comment]
@d8vjork we did some related fixes in the latest pre-release (1.27.12161), should be fixed now

**Comment by d8vjork** [comment]
@jakubmisek Yes it is, closing this issue, great job!

**Comment by jakubmisek** [comment]
thank you @d8vjork !
