### ISSUE TITLE
constant created inside function highlighted as undefined

### ISSUE THREAD

**Issue by frkinta** [DEVSENSE/phptools-docs#244]
![image](https://user-images.githubusercontent.com/20577647/213254049-d1e1bc1d-d233-4a74-86c4-b68f8b943a22.png)

**Comment by jakubmisek** [comment]
@frkinta thank you for reporting the issue - we'll take a look what's happening in there

**Comment by jakubmisek** [comment]
it seems `define()` is unhandled in lambda functions ... will be fixed
