### ISSUE TITLE
Unreachable code detectedPHP(PHP0419)

### ISSUE THREAD

**Issue by ImNotTiara** [DEVSENSE/phptools-docs#245]
I'm having the exact same issue as in https://github.com/DEVSENSE/phptools-docs/issues/221.
After digging through the previous versions, it started happening after the v1.22.11089 update (v1.23.11234).
Please look into this **now** as I'm getting extremely annoyed by having to downgrade to v1.22.11089 every single time you guys push out an update.

**Comment by jakubmisek** [comment]
Thank you for the details!

Sorry for the trouble, we'll be fixing this issue in the upcoming release.

**Comment by Timbuktu1982** [comment]
thx

**Comment by jakubmisek** [comment]
Thank you again for reminding this;

https://github.com/DEVSENSE/phptools-docs/issues/221 has been fixed. Please wait for the upcoming pre-release/release version `1.28.12223` or higher.

If you would have any other test case, where the code analysis fails, please feel free to start a new issue.
