### ISSUE TITLE
Syntax error: unexpected token 'function'PHP(PHP2014)

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#246]
I'm getting about 700 false issues shown due to wrong handling with static definitions since `1.28.12192 (January 20, 2023)`.

For instance, a syntax error "unexpected token 'function'PHP(PHP2014)" is shown in case of static methods, see below...

```
public static `function` myMethod()
{

}
```

**Comment by jakubmisek** [comment]
Thank you for reporting the issue, and sorry for the trouble.

We have released an update that fixes that.

Please update to the latest version `1.28.12200`
