### ISSUE TITLE
unexpected token / unknown class errors with newest update

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#247]
I just updated to the latest version and now I have a lot of classes which aren't recognized anymore.

> Use of unknown class: 'XX\XXX\Service\Utils\StringHelper'PHP(PHP0413)

![image](https://user-images.githubusercontent.com/20150243/213865151-b7eb7ac0-fb40-415c-8c06-6413b5c53e03.png)

> Syntax error: unexpected token 'function'PHP(PHP2014)

![image](https://user-images.githubusercontent.com/20150243/213865061-edd0adad-77a6-4db8-9b37-749faef02394.png)

> Syntax error: unexpected token 'array'PHP(PHP2014)

![image](https://user-images.githubusercontent.com/20150243/213865092-9f3eccf7-0331-422b-b790-2bf18d7e5498.png)

It's not generally broken, only for some token and classes. It worked before the update.

I'm using PHP 8.0 inside WSL (Ubuntu)

**Comment by jakubmisek** [comment]
thank you for reporting the issue!

We have released an update, which fixes the issue with `static` and `global` keywords. Unknown classes are resolved as well.

**Comment by jakubmisek** [comment]
Fixed in `1.28.12200`
