### ISSUE TITLE
Formatter Issue: Yield From

### ISSUE THREAD

**Issue by jimbo2150** [DEVSENSE/phptools-docs#248]
Formatting a php document causes an issue with `yield from` statements. `yield` works fine but when `yield from` is used, the space after "from" is removed causing syntax errors:

```php
class MyClass {
    function generator() {
        yield from AnotherClass::action();
    }
}
```

Becomes

```php
class MyClass {
    function generator() {
        yield fromAnotherClass::action();
    }
}
```

PHP now looks for `fromAnotherClass` as a class name which doesn't exist.

**Comment by Miloslav** [comment]
Fixed in pre-release. Thank you!
