### ISSUE TITLE
php.problems.scope.XXX not found

### ISSUE THREAD

**Issue by Timbuktu1982** [DEVSENSE/phptools-docs#249]
Hi there,
after last update today i see following failures in the dev console of vs code.

![grafik](https://user-images.githubusercontent.com/47846931/213989285-b46645d8-e034-4ea1-ba7f-cacbaef47247.png)

**Comment by Timbuktu1982** [comment]
It gives more problems with this option. The default selected option is not "user", but "opened". And this option not working (not for opened and reopened files). When i change manual to user, code lense is working (but code lense not renewal after changes, like described in https://github.com/DEVSENSE/phptools-docs/issues/182).

**Comment by jakubmisek** [comment]
thank you; "php.problems.scope.none" was happening on non-en localizations - fixed.

This option only affects the analysis of code problems; we'll check what may be causing issues there.

**Comment by jakubmisek** [comment]
We have fixed some "delays" happening in the code editor; it should fix this issue as well.

**Comment by Timbuktu1982** [comment]
Hi Jakub. Thank you for your help.
