### ISSUE TITLE
Feature: Enter 'use' followed by completion to automatically populate the full namespace.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#25]

**Comment by jakubmisek** [comment]
thank you @tiansin 

Actually we already list all classes and namespaces after `use` keyword. It is just not automatic (you have to press `Ctrl+Space`).

![image](https://user-images.githubusercontent.com/842150/60767408-f61bff00-a0b7-11e9-9ec3-d079ff42e0c0.png)

Also we do list all `trait` declarations within a class context:

![image](https://user-images.githubusercontent.com/842150/60767422-46935c80-a0b8-11e9-8a7d-4afc066f7f39.png)

---

We'll take a look if the completion can be opened automatically (like it is in full Visual Studio) and we might improve the completion to list full namespace names.

**Comment by tiansin** [comment]
Sorry, maybe I have a problem with expression. I want to use ‘use’ and then type the full namespace of the class into the editor when I hit Enter.

like:
![Screen Shot 2019-07-07 at 19 43 38](https://user-images.githubusercontent.com/4232281/60767814-a48f6680-a0ef-11e9-9948-30c3093f968e.png)
When I press Enter, I want to get the full namespace of 'use Jenssegers\Mongodb\Collection' instead of 'use Collection'.

**Comment by tiansin** [comment]
@jakubmisek If you have a different idea, you can use the configuration to switch it. Thank you.

**Comment by jakubmisek** [comment]
Ok, that makes sense, agree.

**Comment by jakubmisek** [comment]
Thanks again for the suggestion. This feature will be available within the next update. Here is a preview on how it looks in full Visual Studio 2019

![image](https://user-images.githubusercontent.com/842150/60812558-16b88780-a192-11e9-9379-a46e3f0f7161.png)

**Comment by tiansin** [comment]
@jakubmisek Thank you for your previous improvements, but I found that many times 'use' is hard to find the class name I need.

![1](https://user-images.githubusercontent.com/4232281/61927897-2b29bc00-afa9-11e9-9c17-cdc79d737fa7.gif)

I hope that the following prompt will appear after I typed 'Collect', but when I press Enter, I put the 'Jenssegers\Mongodb\Collection' namespace into the editor.
![2](https://user-images.githubusercontent.com/4232281/61928230-65478d80-afaa-11e9-8cb3-b7e7c741ddf8.png)

Currently: 
![Screen Shot 2019-07-26 at 13 42 21](https://user-images.githubusercontent.com/4232281/61928525-4990b700-afab-11e9-9a0d-31a549e50df3.png)
Matching too many namespaces I don't want, the actual namespace I want needs to be paged.

**Comment by jakubmisek** [comment]
That's a good suggestion :) we'll show just the type names and the namespace will be completed.

**Comment by tiansin** [comment]
> That's a good suggestion :) we'll show just the type names and the namespace will be completed.
> 
> EDIT: Also we can display the entire name and filter just by the class name.

@jakubmisek  Haha. It would be better if the configuration could be chosen by the user.

**Comment by jakubmisek** [comment]
sometimes you also might use namespaces
