### ISSUE TITLE
Unreachable code raised in a simple switch

### ISSUE THREAD

**Issue by mattiamerlini** [DEVSENSE/phptools-docs#251]
### Behaviour
Before the whole block there is a `die()`. The question is: why are only the second and third switch cases marked as unreachable ?
![Immagine 2023-01-24 104847](https://user-images.githubusercontent.com/14093339/214267317-c2d05b58-942d-485b-9878-6dfb68693a4d.jpg)
![Immagine 2023-01-24 104819](https://user-images.githubusercontent.com/14093339/214267373-5341fcdc-0ea0-4fd6-8df3-d4cff10166d2.jpg)
### Expected behaviour
No warnings or all warnings

**Comment by jakubmisek** [comment]
oh, thank you for reporting that!

**Comment by jakubmisek** [comment]
May I ask for the whole method, or something reproducible?

I can't repro the issue with just the code in the screenshot above.

Thank you

**Comment by mattiamerlini** [comment]
I'm updating the code with more info.

**Comment by jakubmisek** [comment]
> I'm updating the code with more info.
thank you!

**Comment by jakubmisek** [comment]
@mattiamerlini isn't it in `try`/`catch` ? I'll try to repro the issue with `die()` before that

**Comment by jakubmisek** [comment]
yep, I'm having similar results with `die()` like this:

![image](https://user-images.githubusercontent.com/842150/214321824-d7e58778-721d-45d9-b60d-bed1523c9ef1.png)

It should be definitely fixed.

**Comment by mattiamerlini** [comment]
> @mattiamerlini isn't it in `try`/`catch` ? I'll try to repro the issue with `die()` before that

Yes Jakub, the code is a `try/catch` and the behaviour is the same you posted in your screenshot. Thank you

**Comment by jakubmisek** [comment]
something like this?

![image](https://user-images.githubusercontent.com/842150/214323034-a3487ab4-070e-4d1f-96ec-bc8a3f40d76c.png)

**Comment by jakubmisek** [comment]
@mattiamerlini thanks for the info - I'm on it.

**Comment by jakubmisek** [comment]
We have released pre-release version, which fixes the issue!

We'll be improving unreachable code diagnostics in the future (so the entire "switch" will be dimmed, and not underlined, as it should be).

Thank you @mattiamerlini !
