### ISSUE TITLE
Property Docblock generation for already imported classes

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#253]
I have the following property
```php
protected EntityRepository $categoryRepository;
```

and now I start typing `/**` above to create the docblock for it.
The class EntityRepository  is already imported.

The generated docblock looks like:
```php
/**
 * Summary of categoryRepository
 * @var Shopware\Core\Framework\DataAbstractionLayer\EntityRepository
 */
```

Since the class is already imported, there's no need for the fully qualified namespace.
Therefore it should look like:

```php
/**
 * Summary of categoryRepository
 * @var EntityRepository
 */
```

**Comment by d8vjork** [comment]
Weird, have the complete opposite, I want full qualified namespaces everywhere where I've a docblock

I think there should be an option to let everyone choose wether use full or not full qualified names in the first place and then let the extension/LSP do its own thing resolving the class path

**Comment by d8vjork** [comment]
I disagree, as a Laravel/Symfony developer, they have strict guidelines when contributing on their open source (same as every org in Github).

In their cases, they use full qualified names on docblocks even if the classes are imported, not from a functional perspective but more for a mental one, a developer could think a method could return a class named `Workspace` but in reality there are multiple classes called `Workspace`, which leads to create polymorphism or type errors on their apps

Therefore I still agree on the config, as there are users that still wants class names over full ones

**Comment by Zerotask** [comment]
I just checked a few Symfony classes and the their coding standards and can't agree with that. In Laravel I noticed that they're doing that.
Besides that, I am open to a new configuration as it meets my needs. This way I'm not "forced" to follow the Laravel way.

> a developer may think a method could return a class named Workspace

That's the problem of the developer. It's natural for bigger projects, that class names can occur multiple times inside the project. That's why you work with namespaces/scopes.
In other programming languages it's normal and often the only way to import a class.

**Comment by jakubmisek** [comment]
thank you for all the feedback; both seem correct!

- [ ] First; I noticed there was actually a bug - the fully qualified name must be prefixed with `\`
- [ ] I would suggest that generating doc block should respect the `"php.completion.autoimport-docblock"` setting?

**Comment by d8vjork** [comment]
@jakubmisek Maybe add to another point there, a VSCode code action (the floating bulb thingy) to refresh docblocks taking in mind the user settings, useful when reviewing PR's code from others on the team

**Comment by jakubmisek** [comment]
We have fixed generating PHPDoc above properties in the latest update.

We'll keep working on the additional settings.
