### ISSUE TITLE
ZipArchive incomplete `OPSYS_*` constants

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#256]
These are the currently available (only `OPSYS_DOS`):

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/2331052/215735896-e11ba27f-eaf9-4f67-9e24-102ada498113.png">

While in [PHP.net there are these](https://www.php.net/manual/en/zip.constants.php):

<img width="625" alt="image" src="https://user-images.githubusercontent.com/2331052/215736093-1bc676dd-9f6c-4dfa-94a1-d4883d743acb.png">

**Comment by jakubmisek** [comment]
fixed, will be in the next pre-release!
