### ISSUE TITLE
formatting adds a space in string: "?><\/"

### ISSUE THREAD

**Issue by weterynarzfred** [DEVSENSE/phptools-docs#259]
File containing one line: `<?php $a = "?><\/";` gets formatted as `<?php $a = "?><\ /";` (additional space between slashes).

I'm assuming its because of the "?>" in the string. Can this be resolved somehow? The only workaround I found is writing it as: `<?php $a = "?" . "><\/";`

**Comment by Miloslav** [comment]
This appears to work.

![html](https://user-images.githubusercontent.com/842147/216089633-373df2f3-383a-45c0-a97b-0e328dbef76d.gif)

What PHP Tools version do you have? And do you have other extensions installed?

Thanks

**Comment by weterynarzfred** [comment]
I found the issue. It was in another extension: Format HTML in PHP, I was testing it before switching to phptools and forgot to disable it, now it works as it should. My fault, sorry and thanks for your help.

**Comment by jakubmisek** [comment]
@weterynarzfred thank you for the update, please let us know if there would be anything else.
