### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#26]
[crash.zip](https://github.com/DEVSENSE/phptools-docs/files/3365385/crash.zip)

**Comment by jakubmisek** [comment]
thank you @tiansin , there seems to be a nullref exception, we'll try to fix it asap.

**Comment by tiansin** [comment]
[dotnet_2019-07-08-181216_MacPro.zip](https://github.com/DEVSENSE/phptools-docs/files/3367881/dotnet_2019-07-08-181216_MacPro.zip)

**Comment by jakubmisek** [comment]
thank you, still cannot find out why it happens, we'd need more testing

**Comment by jakubmisek** [comment]
We still the didn't find the casuse of the error. May I ask to check the error console in VSCode next time?
![image](https://user-images.githubusercontent.com/842150/61402040-89341080-a8d2-11e9-94c1-887d09fdfe63.png)
Thank you, meantime we'll keep trying to fix this.

**Comment by tiansin** [comment]
Thank you, I am very happy.

**Comment by jakubmisek** [comment]
closing, please if you;d have any stack traces, open a new issue :) thank you-
