### ISSUE TITLE
setting "Problems: Exclude Git Ignore" not working as expected

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#260]
I have checked the option to ignore files from my .gitignore file.
For example in my .gitignore is `var/` which excludes local stuff like lint caches from git. I would expect that this setting would behave the same and don't report problems from this folder.
Although I noticed a lot of problems from files inside var/
![image](https://user-images.githubusercontent.com/20150243/216570010-fcafce19-5cd7-43e0-84c0-10bf14e9a54f.png)

**Comment by jakubmisek** [comment]
thank you for reporting that;

we have handled only up to 8 `.gitignore` files within the workspace - fixed
