### ISSUE TITLE
Enum issue

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#262]
![image](https://user-images.githubusercontent.com/39626142/216770432-62032c67-5244-495c-835d-32ae1f5bdbb8.png)

**Comment by jakubmisek** [comment]
Probably running PHP <= 8.0;

Please pick PHP language level > 8.0 (https://docs.devsense.com/en/vscode/php-version#choosing-php-version)

**Comment by jakubmisek** [comment]
![image](https://user-images.githubusercontent.com/842150/216772532-529a205f-17f7-4507-9a2f-e6dbdcfe85a2.png)

![image](https://user-images.githubusercontent.com/842150/216772538-8232c0a8-ce06-4e4c-a12e-afe5a56eec7a.png)

**Comment by ProtocolLive** [comment]
Thanks
