### ISSUE TITLE
Global var hint

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#264]
![image](https://user-images.githubusercontent.com/39626142/216789168-3c72414a-2ec8-4c86-9d90-46239bb36002.png)

Expected:
![image](https://user-images.githubusercontent.com/39626142/216789221-732014b0-ecaa-4e92-8e87-97755e552bf0.png)

**Comment by jakubmisek** [comment]
thank you for reporting the issue; will be fixed!

**Comment by jakubmisek** [comment]
fixed in the next pre-release, thanks!
