### ISSUE TITLE
Installing this extension breaks switch statements. 

### ISSUE THREAD

**Issue by SudoTronic** [DEVSENSE/phptools-docs#266]
Syntax error goes as follows : 
Syntax error: unexpected token 'switch'PHP(PHP2014)

Basically, you cant use switches. You have to use if else.

**Comment by jakubmisek** [comment]
May I ask for the code sample?

The parser should report syntax errors only if it can't be parsed for some reason.

**Comment by jakubmisek** [comment]
I'm going to close this one - you can use `switch` - but if there would be any code sample, I'm sure we'll figure it out :-)

Thank you!
