### ISSUE TITLE
Handle cancellation on VSCode commands

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#267]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/2331052/217215345-aee90306-5f73-4d3f-86f1-d7b6852c9d0d.png">

This happens when `Ctrl+P` (`Cmd+P` in Mac OS) and `PHP: Background process` then Enter and press Escape.

Not a lifesaver but a small issue anyway

**Comment by jakubmisek** [comment]
Thanks! it's not happening on our tests, but we'll add a bunch of checks for sure.

Meantime this can be set using setting `"php.problems.scope"`

**Comment by jakubmisek** [comment]
Ok it's happening

**Comment by jakubmisek** [comment]
fixed, thank you
