### ISSUE TITLE
Use namespace

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#268]
When I click on some class name, hit ctrl + space and accept the suggestion, it writes the namespace. The previous intelisense I used, created the "use" at the beginning of the document

**Comment by jakubmisek** [comment]
There is a setting `"php.completion.autoimport"` which may affect this. For more details please see https://docs.devsense.com/en/vscode/editor/auto-import#setting.

PHP Editor still adds `use`, it depends on the context, settings, and whether it is safe to add the `use`. 

Also by default, it adds namespace to class names in Doc Comments, this can also be changed in the settings (`"php.format.autoimport-docblock"`).
