### ISSUE TITLE
Laravel-goto-view extension conflict

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#27]
Following extensions should be disabled since their features may interfere with PHP Tools: codingyu.laravel-goto-view

https://marketplace.visualstudio.com/items?itemName=codingyu.laravel-goto-view

**Comment by jakubmisek** [comment]
thank you, will be fixed in the next update :)

**Comment by jakubmisek** [comment]
@tiansin question:
what would help you with Laravel development? We can improve go to definition, type analysis, and problems analysis. Thanks

**Comment by tiansin** [comment]
@jakubmisek It would be great if you could achieve it.
https://github.com/bmewburn/vscode-intelephense/issues/246

**Comment by jakubmisek** [comment]
@tiansin thank you, `.phpstorm.meta.php`, IoC, Blade and launching/debugging artisan upon `F5` are the next milestone for Laravel development.
