### ISSUE TITLE
Unwanted space in type declaration

### ISSUE THREAD

**Issue by Avokadomos** [DEVSENSE/phptools-docs#271]
When using the `array` keyword in type declarations, it is always followed by an unwanted space before the next type. This is how it formats when you have multiple type declarations. Notice the space after `array`.

```php
public function execute(): array |bool
```

If you put array last, it looks better.

```php
public function execute(): bool|array
```

**Comment by Miloslav** [comment]
Hi Kentaro,

Thank you very much for reporting the issue. This will be fixed in the upcoming pre-release.

Have a great day!
