### ISSUE TITLE
Implode

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#272]
![image](https://user-images.githubusercontent.com/39626142/217909299-df2bd568-0402-4489-a58b-ce73292c788d.png)
I dont found that in the docs....
https://www.php.net/manual/en/function.implode.php

**Comment by menturion** [comment]
Same here.

**Comment by jakubmisek** [comment]
@ProtocolLive thank you, and sorry for that.

Closing and releasing update.

Ref https://github.com/DEVSENSE/phptools-docs/issues/273

**Comment by ProtocolLive** [comment]
I just want to say how satisfying it is to work with an extension that has such thoughtful support ^^

**Comment by jakubmisek** [comment]
Thank you @ProtocolLive! I really appreciate all the feedback so we can quickly fix and improve :-)
