### ISSUE TITLE
Call to unknown function: 'ob_start' (PHP0417)

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#274]
`Call to unknown function: 'ob_start' (PHP0417)`

See https://www.php.net/manual/en/function.ob-start.php.

**Comment by jakubmisek** [comment]
thank you for letting me know @menturion - we've fixed that and added internal tests so it won't happen again!

**Comment by menturion** [comment]
@jakubmisek 
Many thanks, I updated to the latest v1.30.12484 (February 10, 2023). These issues are fixed.


Should `phptools` be aware of the below methods resp. classes?

APC: https://www.php.net/manual/en/book.apcu.php
Use of unknown class: 'APCUIterator'
Call to unknown function: 'apcu_cache_info'
Call to unknown function: 'apcu_add'
Call to unknown function: 'apcu_delete'
Call to unknown function: 'apcu_fetch'
Call to unknown function: 'apcu_clear_cache'
Call to unknown function: 'apcu_sma_info'


opcache: https://www.php.net/manual/en/book.opcache.php
Call to unknown function: 'opcache_get_configuration'
Call to unknown function: 'opcache_get_status'
Call to unknown function: 'opcache_reset'


Imagick: https://www.php.net/manual/en/class.imagick.php
Use of unknown class: 'Imagick'

**Comment by jakubmisek** [comment]
@menturion yep, they are a part of non-standard PHP extension, so we don't include them in IntelliSense by default.

You can add those non-standard extensions into `"php.stubs"` setting, or using quick action:

![image](https://user-images.githubusercontent.com/842150/218259050-66e5cde0-e2fc-49c2-a855-0e14b1ce944d.png)

> It is possible, we have missed some standard extension and did not include it in IntelliSense by default; Also in the future, we'll probably take this information right from your actual `php` configuration.

**Comment by menturion** [comment]
Great, many thanks! Added it instantly :)

**Comment by jakubmisek** [comment]
@menturion thanks for the confirmation :)

If you think, there is something we should include by default, please let me know!
