### ISSUE TITLE
Call to unknown function: 'class_exists' (PHP0417)

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#277]
`Call to unknown function: 'class_exists' (PHP0417)`

See https://www.php.net/manual/en/function.class-exists.php.

**Comment by menturion** [comment]
I add similar issues below: 

- Call to unknown function: 'func_get_args'
- Call to unknown function: 'func_num_args'
- Call to unknown function: 'method_exists'
- Call to unknown function: 'ob_get_contents'
- Call to unknown function: 'ob_clean'
- Call to unknown function: 'register_shutdown_function'
- Call to unknown function: 'flush'
- Call to unknown function: 'call_user_func'

**Comment by menturion** [comment]
In total > 430 issues.
I will check further issues after the next release.
Is this ok for you?

**Comment by jakubmisek** [comment]
thank you for the quick issue report, I've released a fixed already, sorry for the inconvenience.
