### ISSUE TITLE
Test unit functionality is not available.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#28]
When my test code contains functions such as 'exit' 'die', the test unit will not be able to enumerate any functions. In many cases, we only need to test the individual functions, and we will add the exit function to the test function, which will result in The test unit function cannot be used.

Recommendation: Is it possible to add a configuration to disable the test unit functionality in 'phptools'.

Or implement parsing like https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit .

**Comment by jakubmisek** [comment]
Good idea, we do it this way in the full Visual Studio, and we are about to implement it the same way in VSCode together with PHAR file parser.

**Comment by jakubmisek** [comment]
related to https://github.com/DEVSENSE/phptools-docs/issues/13

**Comment by jakubmisek** [comment]
test explorer functionality has been reimplemented, it now discovers the tests without running the code, and allows to efficiently run single tests or selection of tests, or debug selected tests only.
