### ISSUE TITLE
Does PHP Tools support Codeigniter 4

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#286]
Hi I tried looking in all documentation. Does PHP Tools v1.30.12484 support Codeigniter 4?

**Comment by d8vjork** [comment]
This should be a generic PHP extension, I don't see why this should not support anything that is based on latest and actively supported PHP versions

**Comment by murugappanrm** [comment]
@d8vjork you must be mistaken. Yes, in one way it PHP but there are many things in the autocomplete for Codeigniter syntax that is not supported in the php extensions.
