### ISSUE TITLE
Move references and implementations helper to peek

### ISSUE THREAD

**Issue by oojacoboo** [DEVSENSE/phptools-docs#289]
The following is above every class and method/function.  There is already enough going on with docblocks and attributes these days.  This is distracting and I don't see the need to have this information so visible when it can easily be displayed on hover/peek.

![image](https://user-images.githubusercontent.com/764664/219533777-5cc1d392-c3a1-47e4-b1c6-bee6c927824f.png)

**Comment by jakubmisek** [comment]
Thank you for the question.

The feature is called "Code Lens".

You can enable or disable it in VS Code Settings (https://code.visualstudio.com/docs/getstarted/settings):
`"editor.codelens": false`

Or just for the PHP code:
`"php.codeLens.enabled": false`

More details on https://docs.devsense.com/en/vscode/editor/code-lens

I'm not sure this information supposes to be in a hover tool-tip tho

**Comment by oojacoboo** [comment]
I see, so this is a default implementation of the editor?  I thought it was something custom for this plugin...

Assuming it's the editor default, I guess there isn't anything more to add.  It's unfortunate though.  The information is valuable.  But it's not something that needs to be seen in the actual code.  That's a design mistake IMO.

**Comment by jakubmisek** [comment]
It's a Visual Studio thing, although you can turn it off.

Our PHP extension provides support for it; so it's up to the user whether they want to see it or not)

I agree it may look disruptive at first. Personally, I have it turned off, but there are people who like it. Maybe it's just a manner of getting used to it.

---

Anyways; I'm noting the idea about having that information in a tooltip - might not be a bad feature; maybe within an adornment on the side ... I haven't seen it anywhere else tho.
