### ISSUE TITLE
Feature: The problem only shows the open document.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#29]
It is recommended to add configuration, the problem is only to retrieve the open document, not all project files, when the document is closed, the problem of closing the document.
I think it can also improve the performance of the extension.

**Comment by tiansin** [comment]
I am a full member of you, but as of today, my use of extensions is very limited, because the extended experience is not particularly good, although it has improved a lot now, but the test unit is not perfect and the cpu is loading and running. Still exist, my cpu fan will spin at high speed every few minutes.

I hope I can optimize it better so that I don't have to return to 'PHP Intelephense'.

**Comment by jakubmisek** [comment]
Thank you @tiansin ! and sorry for the inconvenience. We're still working on the CPU usage.

Problems are always analyzed so there is no reason to not show them. You can however disable showing of problems in certain folders or disable certain problems by their ID (useful for `/vendors` folder) (https://docs.devsense.com/en/vscode/problems#configuration)

**Comment by jakubmisek** [comment]
related to #24

**Comment by tiansin** [comment]
In my opinion, a good extension should provide more configuration for the user to set the plugin function according to their own preferences, instead of forcibly using the extended built-in configuration. Just some suggestions, thank you. @jakubmisek

**Comment by jakubmisek** [comment]
Agree :) currently we are refactoring the code, because the analysis itself performs 100 times faster in the "laboratory environment" :) so there is something wrong causing the high CPU usage in VSCode .. working on it.

**Comment by jakubmisek** [comment]
update:
next update will have `php.problems.workspaceAnalysis` setting allowing you to disable analysis of the entire workspace. If set to `false`, only opened documents will be analysed and additionally simple errors (like syntax errors) in the rest of the workspace will be reported.

**Comment by jakubmisek** [comment]
The recent update '1.0.3686' introduces `php.problems.workspaceAnalysis` setting which you can use to disable full-workspace analysis.  It might be useful for large workspaces (10000+ php files).

Note there is still an initial load time needed to process the source files. This has been optimized as well.

Closing.

In case there would be any other feedback or suggestion, please feel free to add a new issue :) thank you!
