### ISSUE TITLE
Missing namespace in autocomplete tooltip

### ISSUE THREAD

**Issue by oojacoboo** [DEVSENSE/phptools-docs#290]
See the following image.  How am I to know which one to select?

![image](https://user-images.githubusercontent.com/764664/220035163-839de28d-af75-47c9-9305-7af4fbc91e5c.png)

**Comment by oojacoboo** [comment]
Nevermind this.  It looks like those are the ones in the global namespace that are deprecated.  Intelliphense used to sort these based on last use I believe.  So, I'm accustomed to seeing namespaces by default and not the deprecated ones in the global namespace.d

**Comment by oojacoboo** [comment]
It's also worth mentioning that the lookup on autocomplete is significantly slower than Intelliphense right now.  And sometimes doesn't even show up, especially in conjunction with Github's AutoPilot

**Comment by jakubmisek** [comment]
@oojacoboo thank you for the feedback!

We're sorting the completion list based on the context, local symbols, then imported symbols, then symbols from other namespaces.

We're open to suggestions, on what would make the filtering better.

Ad to speed - isn't there something else running in the background? Autocomplete is one of the things we should have instantaneous.

**Comment by oojacoboo** [comment]
>We're sorting the completion list based on the context, local symbols, then imported symbols, then symbols from other namespaces.

I don't think it's working then.  Because those deprecated classes you see in that lookup list aren't in the file and are rarely used, or not used at all in the project.  They've been deprecated for year and on their way out.  So, the logic is flawed.
