### ISSUE TITLE
Highlight unused imports

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#292]
I think this has worked in the past, but since a few weeks I noticed that unused imports are not highlighted (grayed out) anymore.

**Comment by jakubmisek** [comment]
We have it working on test machines:

![image](https://user-images.githubusercontent.com/842150/220136725-c0b9b0b6-dff6-4206-b999-c60a0098243a.png)

Any error in the developer console (Help/Toggle Developer Tools/Console) or on the Output window?

**Comment by Zerotask** [comment]
Output Window:
> 2023-02-20 14:53:43.218 [error] Error processing the request: document 'git:/var/projects/shopware6.4-abas-connector/src/Storefront/Controller/AbasCartLineItemController.php?%7B%22path%22%3A%22%2Fvar%2Fprojects%2Fshopware6.4-abas-connector%2Fsrc%2FStorefront%2FController%2FAbasCartLineItemController.php%22%2C%22ref%22%3A%22~%22%7D' not found: Error: Error processing the request: document 'git:/var/projects/shopware6.4-abas-connector/src/Storefront/Controller/AbasCartLineItemController.php?%7B%22path%22%3A%22%2Fvar%2Fprojects%2Fshopware6.4-abas-connector%2Fsrc%2FStorefront%2FController%2FAbasCartLineItemController.php%22%2C%22ref%22%3A%22~%22%7D' not found
    at Lt (/home/phintermayer/.vscode-server/extensions/devsense.phptools-vscode-1.30.12484-linux-x64/out/src/extension.js:62:223)
    at We (/home/phintermayer/.vscode-server/extensions/devsense.phptools-vscode-1.30.12484-linux-x64/out/src/extension.js:61:11258)
    at Immediate.<anonymous> (/home/phintermayer/.vscode-server/extensions/devsense.phptools-vscode-1.30.12484-linux-x64/out/src/extension.js:61:11108)
    at processImmediate (node:internal/timers:466:21)

**Comment by jakubmisek** [comment]
Currently, we're ignoring PHP documents in Git/Diff window. So this functionality might be limited there.

I make a note to implement it.

**Comment by Zerotask** [comment]
This error/behavior is from a regular PHP document and not from a diff view.
I don't see unused imports at all

**Comment by jakubmisek** [comment]
we have found, the unused use is not highlighted, if `"php.problems.scope"` setting is set to `"none"`. Fixing.

**Comment by jakubmisek** [comment]
@Zerotask please try the latest pre-release `1.31.12861`

**Comment by Zerotask** [comment]
> we have found, the unused use is not highlighted, if "php.problems.scope" setting is set to "none". Fixing.

My "php.problems.scope" is on "user".

Although I noticed that recently I don't see any problems in the console bar. Therefore I assume specific settings and/or extensions are causing my problem.
Thank you for investigating it.

**Comment by jakubmisek** [comment]
Thank you for the update.

Yep, unused 'use' **was** connected to the analysis of the problems. So without problems in the given file, unused `use` was not reported.

If you don't have any problems reported, please open a new issue.
