### ISSUE TITLE
ParaTest results not displayed

### ISSUE THREAD

**Issue by DellanX** [DEVSENSE/phptools-docs#299]
Unsure if this is a Bug, or if it'd need a new feature to support ParaTest.

I am unable to view the test results in VSCode when using ParaTest to run my tests in parallel
Everything runs fine when using the original phpunit executable, just not when using paratest

For example, after switching to the paratest executable, I added an assertion that false is true (which fails)

<img width="675" alt="image" src="https://user-images.githubusercontent.com/31318348/222482391-2eb11c8d-ab0b-44e9-8ee7-4e595f571eee.png">

VSCode; however, still shows that the test passed.

**Comment by jakubmisek** [comment]
We have not tested or verified support for "ParaTest".

May I ask for a sample workspace? (a zip file or a GitHub repo) we'll test it and make it work if possible.

Thank you!

**Comment by jakubmisek** [comment]
I've found out, we need to support _custom PHPUnit command_ to run ParaTests - i.e. not running `vendor/bin/phpunit` but `vendor/bin/paratest` instead.

Working on it.

**Comment by jakubmisek** [comment]
@DellanX as far as I understand, you need the following setting in your workspace:

``json
{
  "phpunit.phpunit": "vendor/bin/paratest"
}
```

**Comment by DellanX** [comment]
> @DellanX as far as I understand, you need the following setting in your workspace:
> 
> ```json
> {
>   "phpunit.phpunit": "vendor/bin/paratest"
> }
> ```

To clarify, this does get the first part working, in xdebug I can see the tests running fine.

The reason I created this issue, it's that the test results don't appear.
I had to revert from paratest to phpunit to get test results, after which the extension works as expected.

**Comment by jakubmisek** [comment]
@DellanX probably the `--teamcity` argument is not working in paratest. We'll try that.

**Comment by jakubmisek** [comment]
@DellanX I've found ParaTest returns test results in a little bit different format. We'll fix that.

**Comment by jakubmisek** [comment]
@DellanX it was a little bit more work )

Anyways; the next pre-release/release (`1.32.12920` and newer) will support ParaTest. 

Settings:
```json
{
  "phpunit.phpunit": "vendor/bin/paratest"
}
```

Note, debugging paratest tests is not working (yet)
