### ISSUE TITLE
VSC FR folding brackets

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#3]
When u collapse an array/if/foreach, last bracket is not shown, so u cant's see if there is a comma.
It looks like:
'array' => [ ...

Need:
'array' => [ ... ]
or
'array' => [ ... ], if comma is set
or
'array' => [ ... 
], bracket in new line

Same for if, foreach etc. with { }
it shoes only { ... at the end.

Default in VSC is:
if (true) { ...
} <-- bracket in new line

**Comment by jakubmisek** [comment]
You are right. We did folding according to the full VS's behavior where it collapses outer bounds of the brackets. VSC collapses the inner bounds.

**Comment by jakubmisek** [comment]
Thank you @Mordef , this has been fixed and will be available in the next update.
