### ISSUE TITLE
PhpStorm Meta Container

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#30]
@jakubmisek  I tried the following kinds of intellisense, it seems that only the first way is successful.

1.  app('events')->     **success.**
2. \App::make('events')->  **failed.**

/** @var \Illuminate\Foundation\Application $app */
3. $app->make('events')-> **failed.**

[phpstorm.meta.zip](https://github.com/DEVSENSE/phptools-docs/files/3394255/phpstorm.meta.zip)

**Comment by jakubmisek** [comment]
thank you for testing this, we'll take a look

**Comment by jakubmisek** [comment]
2. works for me, but we'll doublecheck
3. seems that we have to resolve base classes as well, will be done.

**Comment by jakubmisek** [comment]
thanks @tiansin , will be fixed in the upcoming update

**Comment by tiansin** [comment]
@jakubmisek  The third program seems to be still unable to work here, thank you.

![1](https://user-images.githubusercontent.com/4232281/61344310-662e4000-a883-11e9-85ba-d09788be14c2.gif)

**Comment by jakubmisek** [comment]
@tiansin  I see, it is also possible to specify interfaces within the phpstorm metadata "override" :) we'll make it right, thanks!

**Comment by jakubmisek** [comment]
implemented in latest release `1.0.3703`

please reopen or comment if it still lacks something :) thank you
