### ISSUE TITLE
Destructured array assignments give false positive reports PHP1412 and PHP0407 - 'Use of unassigned variable' and 'Trying to get property of non-object of type void'

### ISSUE THREAD

**Issue by marinaglancy** [DEVSENSE/phptools-docs#300]
Devsense gives so many errors on our unittests that it's actually impossible to use it. I do not want to disable these error types because they can be very useful. Here is the example, there is absolutely nothing wrong with this code:

```
<?php

class A {
  public function create_test_data($count) {
    $users = [];
    for ($i = 0; $i < $count; $i++) {
      $users[] = (object)['id' => $i];
    }
    return [(object)[], $users];
  }
  public function B() {
    [$tenant, [$user11, $user12, $user13]] = $this->create_test_data(3);
    $this->do_something(0, [$user11->id, $user12->id, $user13->id]);
  }

  public function do_something($programid, $userids) {
    //...
  }
}
```
![devsense_example](https://user-images.githubusercontent.com/836986/222772042-88c57a52-b021-454e-a13b-c251ff0996c3.png)

**Comment by jakubmisek** [comment]
Thank you, @marinaglancy, for reporting the issue and for the detailed test case.

We'll try to fix this asap!

**Comment by jakubmisek** [comment]
Fixed and we have released the update yesterday.

Please let me know if there would be anything else we can dog for you.

Thank you!

**Comment by marinaglancy** [comment]
you guys are on fire! Thanks, it works like a charm!

If I find something else I'll let you know :)

**Comment by jakubmisek** [comment]
Thank you Marina!
