### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AzpoulMasr** [DEVSENSE/phptools-docs#301]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.2.5843`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\azqoul\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
@AzpoulMasr thank you for reporting the issue, please:

> :warning: Make sure to **attach** this file from your *home*-directory:
