### ISSUE TITLE
Support `truthy-string`/`non-falsy-string` pseudo-type

### ISSUE THREAD

**Issue by ZebulanStanphill** [DEVSENSE/phptools-docs#302]
[PHPStan](https://phpstan.org/writing-php-code/phpdoc-types#other-advanced-string-types) and [Psalm](https://github.com/vimeo/psalm/blob/3af9ccde91d5eaf65741f8da0ed9cad20e5f542c/src/Psalm/Type/Atomic.php#L277) both support a pseudo-type called `truthy-string` (with alias `non-falsy-string`), which represents a `string` that is not `''` and not `'0'`... in other words, a string that will always be `true` when cast to `bool`. (Another way it can be thought of is as a subset of `non-empty-string` that excludes `0`.)

The PHP Tools extension does not currently support this pseudo-type, and treats it like a class.
![image](https://user-images.githubusercontent.com/19592990/222984497-f951cb88-a331-4d0b-8b96-d236775321fb.png)

**Comment by jakubmisek** [comment]
Thank you @ZebulanStanphill ,

We'll fix the warning, so those special keywords will be recognized.

Evcntually, in the future update, we'll be checking the string is actually not falsy/not empty.

**Comment by jakubmisek** [comment]
keywords recognized in the latest update, thank you!

closing
