### ISSUE TITLE
$GLOBALS in function leaves variable unassigned

### ISSUE THREAD

**Issue by bookworm109** [DEVSENSE/phptools-docs#303]
I'm trying to set up a debugging function using $GLOBALS, and phptools is saying the variable I assign a value with is unassigned. The variable works fine, and I had to trick phptools into preventing it from giving me an error.

This shows the variable $xValue as unassigned.
![unassigned](https://user-images.githubusercontent.com/42516263/223214878-f147e709-eea0-481e-8859-eb8faf4f8b42.png)

I trick phptools with an assignment that never happens.

![tricked](https://user-images.githubusercontent.com/42516263/223215199-f8b1f994-006f-428c-a4f7-2fb939c99390.png)

**Comment by jakubmisek** [comment]
Thank you @bookworm109 for reporting the issue!

We'll fix that.

FYI I would suggest another quick workaround for now:
```php
/** @var string $xValue */
$sType = gettype($xValue);
...
```

**Comment by jakubmisek** [comment]
Fixed in the next pre-release, thank you!

---

_Hint: to improve the editor type inferring, you can take advantage of PHPDoc:_

```
/** @var string $xValue */
```
