### ISSUE TITLE
phpdoc @property from @mixin not recognized

### ISSUE THREAD

**Issue by raiza2309** [DEVSENSE/phptools-docs#304]
My eloquent model class have `@mixin` to IdeHelperClass (package by [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) Code completion is right, but when I hover it's not recognized. I'm running on Visual Studio Code. Any suggestion?
![Issue-code-completion-is-right](https://user-images.githubusercontent.com/54885057/223470569-82644098-d759-4397-8e0e-87560405a285.png)

> This is when code completion

![Issue-code-completion-on-hover-is-wrong](https://user-images.githubusercontent.com/54885057/223470892-408a8d89-a6c1-44ac-bbab-a64bb43d375f.png)

> This is when I hover or I want to access property is giving function instead of object

**Comment by jakubmisek** [comment]
Thank you for reporting the issue, we'll take a look on it!

**Comment by jakubmisek** [comment]
implemented; we'll be updating pre-release within a day or two.

thank you!
