### ISSUE TITLE
Return type brackets are not in the same line

### ISSUE THREAD

**Issue by amoschristian** [DEVSENSE/phptools-docs#305]
With PSR 12, if there is multiline params inside a function and return type are declared as per this explanation
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-12-extended-coding-style-guide.md

> When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.

![image](https://user-images.githubusercontent.com/46567795/223662040-21945497-7391-4f1a-ad87-e3967c86f219.png)

but on my end it does look like this

```php
<?php

namespace Vendor\Package;

class ReturnTypeVariations
{
    public function functionName(int $arg1, $arg2): string
    {
        return 'foo';
    }

    public function anotherFunction(
        string $foo,
        string $bar,
        int $baz
    ): string
    {
        return 'foo';
    }
}
```

But for a function with one line params, it has no issue

Is there any settings that i miss? or is this a bug?
Thank you

**Comment by Miloslav** [comment]
Hi Christian,

Thank you for opening the issue.

That's a bug. We will fix that asap.

Thanks!

**Comment by amoschristian** [comment]
@Miloslav sweet, Thank you looking forward for the fix :smile:

**Comment by Miloslav** [comment]
Thanks Christian!

We've fixed this one, it will be available in the next pre-release.

Have a great day
