### ISSUE TITLE
Weird PHP function formatting

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#306]
In many functions when passing a closure, the formatter is separating the braces and parentheses in the end.

![image](https://user-images.githubusercontent.com/441455/223885808-ef50503b-76b2-4d0f-8c19-5048453af44b.png)

Is there a way to make the formatter stop doing that?

PS: Using VSCode

**Comment by Miloslav** [comment]
Hello Tiago,

We've fixed it. The next pre-release will behave correctly.

Thanks again!
