### ISSUE TITLE
Support for `.phpstorm.meta.php` : `expectedArguments()`

### ISSUE THREAD

**Issue by dxkrs** [DEVSENSE/phptools-docs#308]
I just do the testing for ".phpstorm.metadata supporting" in this project:
`/t1.php` :
```
<?php

namespace hello;

class t1
{
    public function abcd(int $a, string $b)
    {
        return $a + intval($b);
    }
}
```
`/t2.php` :
```
<?php

namespace hello;

class t2
{
    public function test()
    {
        $a = new t1();
        $a = $a->abcd(1,'444');
    }
}
```
`/.phpstorm.meta.php` : 
```
<?php
namespace PHPSTORM_META {
    expectedArguments(
        \hello\t1::abcd(),
        1,
        '123',
        '456'
    );
}
```

I put the Ctrl+Space after type the `$a = $a->abcd(1,'` in `\t2.php` file ,it show a list ,but haven't '123' or '456' in the select list.
It means the `.phpstorm.meta.php` not working? Or other somethings wrong?

**Comment by jakubmisek** [comment]
Thank you @dxkrs for reporting the issue;

The PHP extension supports a wide range of `.phpstorm.met.php` features, although `expectedArguments()` is not yet handled.

We have it on our to-do list.

I'll keep you informed in this thread.

**Comment by dxkrs** [comment]
Okay, I'm really looking forward to it！
However, I see the extension introduction show the "PHPStorm metadata notation is automatically processed", can talk about that in detail in extension document?

**Comment by jakubmisek** [comment]
Partially supported in the latest `1.32`!

**Comment by jakubmisek** [comment]
Implememted the rest of `expectedArguments` features! Thank you.
