### ISSUE TITLE
Last Update

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#31]
Looks bad, nothing works, must disable it.
![grafik](https://user-images.githubusercontent.com/22061464/61378783-7acfff80-a8a6-11e9-9f45-31a47d1b5ad5.png)
Thats all, "loading..." , simple nothing.
No other PHP-Extenison is activated.

When i use jump to definition, loadining indicator is showning under the file-tabs and other extensions will no work, like TypeScript.
Need to reload VS-Code.

can't use the extension anymore, please fix fast or rollback!

**Comment by jakubmisek** [comment]
thank you for the issue @Mordef 

May I ask to check the version you have? There was a release with this issue but has been fixed in past few hours. Current version is `1.0.3696`

**Comment by Mordef** [comment]
got an update, but still same error
Im on 1.0.3702 now

**Comment by jakubmisek** [comment]
oh I see, will be fixed (accidental infinite recursion in case of certain `php.problems.exclude` combination

**Comment by jakubmisek** [comment]
thanks @Mordef and sorry for the inconvenience, please update to `1.0.3703` (I don't know how the previous release passed tests, but we'll do something about it so it won't happen again in the future)
