### ISSUE TITLE
Navigating to definition and renaming functions referenced in @uses and @see in docblocks

### ISSUE THREAD

**Issue by marinaglancy** [DEVSENSE/phptools-docs#310]
While migrating from PHPStorm to vscode with DEVSense extension I noticed one difference that is affecting the way we do development. In Moodle there are some magic ways to call functions and we often rely on @see and @uses directives in the docblocks. 

I made a couple of screencasts to demonstrate the difference. In PHPStorm I can navigate from @uses to the function definition and it also shows up in the function usage references, even when it is not called directly. I can also rename the function and all links to it are also renamed. 

Here is the code:

```
<?php

class myclass {
  public static function usefulfunction($a, $b) {
      return $a + $b;
  }
}

// ----- Correct behaviors: ------

// With this notation you can "go to definition" and it is shown in function references.
echo myclass::usefulfunction(1, 2);

// With this notation you can "go to definition" but it does not show in function references
// It also is not changed when you refactor (in phpstorm it is).
/** @see myclass::usefulfunction() */

// ----- Incorrect behavior: ------

// You can not "go to definition" and it is not shown in function references.
// In PHPStorm the directive @uses is treated as if we called the method directly.
/** @uses myclass::usefulfunction() */

```

PHPStorm:

https://user-images.githubusercontent.com/836986/226645240-271bdc59-c048-4124-9f22-1cdc46e19a3e.mp4

VSCode:

https://user-images.githubusercontent.com/836986/226645337-353c2dab-18c1-46af-a807-20acce0314a5.mp4

**Comment by jakubmisek** [comment]
@marinaglancy thank you for the detailed feature request! 

`@see` and `@uses` are totally ignored by our extension now - we'll implement that!

**Comment by jakubmisek** [comment]
Implemented in `1.32`!

Although we'll keep working on it since there are a lot of other different forms of this notation.

**Comment by marinaglancy** [comment]
thank you very much!

**Comment by str** [comment]
@jakubmisek thank you for this!  

I know I'm being too picky, but, could you please change the colors in the docblock so it's easier to know it is a class and/or method?

Thank you.

**Comment by jakubmisek** [comment]
@str sorry I forgot about the last comment as it was closed :) I'll create a new issue for method colors in PHPDoc!
