### ISSUE TITLE
Support PHP 8.2 `true` return type

### ISSUE THREAD

**Issue by ZebulanStanphill** [DEVSENSE/phptools-docs#311]
PHP 8.2 supports `true` as a stand-alone return type. https://www.php.net/releases/8.2/en.php#null_false_true_types

![image](https://user-images.githubusercontent.com/19592990/227812124-d34e86f9-ee5f-461b-a65f-9820b6ad8645.png)

**Comment by jakubmisek** [comment]
Thank you @ZebulanStanphill - we'll fix that!

**Comment by jakubmisek** [comment]
fixed in `1.32`! thank you
