### ISSUE TITLE
Support for Laravel Idea Metadata

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#312]
When the metadata files from Laravel Idea for PHPStorm (https://laravel-idea.com/) is generated in the vendor folder, PHP Tools show a warning:

_Instance method 'Illuminate\Database\Eloquent\Builder::where' should not be called statically PHP(PHP1413)_

![Function static warning](https://user-images.githubusercontent.com/441455/228365271-d77401c7-44ee-47bc-b7ab-bce32ac37695.png)

But, if I delete the files, PHP Tools stop showing me completions and intellisense for Model Classes in Laravel.

The extension have support for _ide_helper.php and _ide_helper_models.php from Laravel IDE Helper, and when we generate this files, everything works great.
Would be possible to support Laravel Idea as well?

**Comment by jakubmisek** [comment]
@trollfalgar Thank you for reporting the issue!

We're probably resolving a different `where()` method in this case ... and thus reporting the warning.

May I ask you to attach the corresponding metadata file? I'll take a look at that.

**Comment by trollfalgar** [comment]
The plugin generates files to help intellisense for many things: Jobs, Facades, Macros, Builders, Collections, Factories, Models, etc.

So I'm attaching a .zip with all the files as an example.
Maybe help you more.

[_laravel_idea.zip](https://github.com/DEVSENSE/phptools-docs/files/11094290/_laravel_idea.zip)

**Comment by jakubmisek** [comment]
@trollfalgar thank you!

**Comment by jakubmisek** [comment]
We have implemented a lot to respect the _ide_helper (despite the fact, that _ide_helper contains tons of incorrect information) ... 

Closing the issue for now, please let us know if there would be anything else we can improve with _ide_helper.

Thank you!
