### ISSUE TITLE
Support set the PHPUnit config files path or directory

### ISSUE THREAD

**Issue by zengbo** [DEVSENSE/phptools-docs#313]
In my project, there are many PHPUnit config files in a directory. I hope the PHP tools can search the specific directory, and discovery all tests in the config files.

**Comment by jakubmisek** [comment]
@zengbo thank you for reporting the issue.

The PHP extension should already process all the `phpunit.xml{.dist}` files and corresponding tests.

May I ask for more details?

**Comment by zengbo** [comment]
Our PHPUnit config file names like phpunit-{functions}.xml

**Comment by jakubmisek** [comment]
> Our PHPUnit config file names like phpunit-{functions}.xml

That would be the problem. I always thought it has to be `phpunit.xml...` but that will be easy to fix.

**Comment by zengbo** [comment]
my project directory struct likes this:

root
|- tests
|— phpunit-a.xml
|— phpunit-b.xml
|— …

**Comment by jakubmisek** [comment]
Thank you @zengbo 

The next update allows having custom PHPUnit XML config files: `**/phpunit*.xml`

They all will be listed in the _Testing_ panel.

**Comment by zengbo** [comment]
Thanks, the pre-version 1.32.12920 is ok

**Comment by jakubmisek** [comment]
thank you for trying the pre-release @zengbo !
