### ISSUE TITLE
When calling from $this within model class (using laravel's ide-helper)

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#317]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/2331052/229767365-10d149fc-a75f-45a0-be46-bc8999be1f4e.png">

This should recognise that property is already defined, thought now within this Model file (as docblock) but on another one (`.ide_helper_models.php`)

The Ctrl / Cmd + Click works and as saw on the screenshot above it also recognises types and everything from this column/attribute. 

**So the problem is within the diagnostics of this extension.**

**Extension version:** v1.32.12920
**Operating system:** Mac OS 13.3 (Ventura)
**VSCode:** 1.77.0

**Comment by d8vjork** [comment]
Also this doesn't happens outside the `$this` context (so within the same model class)

**Comment by jakubmisek** [comment]
Thank you @d8vjork !

**Comment by d8vjork** [comment]
Actually ignore this, found a solution: `php artisan ide-helper:models --reset --nowrite --write-mixin --no-interaction`

Adding that `--write-mixin` does the trick so it writes a `@mixin IdeHelperModelName` at the top of each model class
