### ISSUE TITLE
The laravel model property cannot be obtained when the debugger mouses over.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#32]
@jakubmisek 
![1](https://user-images.githubusercontent.com/4232281/61404948-34f95280-a90b-11e9-9857-3c9a9e58dbd9.png)
![2](https://user-images.githubusercontent.com/4232281/61404951-34f95280-a90b-11e9-962a-24e5bf96ea36.png)
![3](https://user-images.githubusercontent.com/4232281/61404953-3591e900-a90b-11e9-8770-d026bd7a724d.png)

**Comment by jakubmisek** [comment]
Just checking - `player_id` is obtained through the magic `__get()` method?

**Comment by tiansin** [comment]
Yes!

**Comment by Miloslav** [comment]
It's not directly caused by magic method as we support those during debug session.

I'm trying to figure out if it's not something laravel specific

**Comment by tiansin** [comment]
@jakubmisek @Miloslav This simple code can explain the problem.

![1](https://user-images.githubusercontent.com/4232281/61459560-979c2e00-a99f-11e9-95b2-f2f67ca4d622.png)

[test.zip](https://github.com/DEVSENSE/phptools-docs/files/3406607/test.zip)

**Comment by Miloslav** [comment]
Weird, this test case works on my station.

![image](https://user-images.githubusercontent.com/842147/61621103-8a6a9200-ac72-11e9-82a4-958b10ba675f.png)

What PHP framework and Xdebug version do you have?

**Comment by tiansin** [comment]
@Miloslav 

>Laravel Framework 5.6.39


> PHP Version 7.1.23
System	Darwin MacPro.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64
Build Date	Nov 27 2018 16:59:01



> xdebug
xdebug support	enabled
Version	2.5.5
IDE Key	VSDEBUG
Supported protocols	Revision
DBGp - Common DeBuGger Protocol	$Revision: 1.145 $
Directive	Local Value	Master Value
xdebug.auto_trace	Off	Off
xdebug.cli_color	0	0
xdebug.collect_assignments	Off	Off
xdebug.collect_includes	On	On
xdebug.collect_params	1	1
xdebug.collect_return	On	On
xdebug.collect_vars	On	On
xdebug.coverage_enable	On	On
xdebug.default_enable	On	On
xdebug.dump.COOKIE	no value	no value
xdebug.dump.ENV	no value	no value
xdebug.dump.FILES	no value	no value
xdebug.dump.GET	no value	no value
xdebug.dump.POST	no value	no value
xdebug.dump.REQUEST	no value	no value
xdebug.dump.SERVER	no value	no value
xdebug.dump.SESSION	no value	no value
xdebug.dump_globals	On	On
xdebug.dump_once	On	On
xdebug.dump_undefined	On	On
xdebug.extended_info	On	On
xdebug.file_link_format	no value	no value
xdebug.force_display_errors	Off	Off
xdebug.force_error_reporting	0	0
xdebug.halt_level	0	0
xdebug.idekey	VSDEBUG	VSDEBUG
xdebug.max_nesting_level	256	256
xdebug.max_stack_frames	-1	-1
xdebug.overload_var_dump	2	2
xdebug.profiler_aggregate	Off	Off
xdebug.profiler_append	Off	Off
xdebug.profiler_enable	Off	Off
xdebug.profiler_enable_trigger	Off	Off
xdebug.profiler_enable_trigger_value	no value	no value
xdebug.profiler_output_dir	/var/tmp/	/var/tmp/
xdebug.profiler_output_name	cachegrind.out.%p	cachegrind.out.%p
xdebug.remote_addr_header	no value	no value
xdebug.remote_autostart	On	On
xdebug.remote_connect_back	Off	Off
xdebug.remote_cookie_expire_time	3600	3600
xdebug.remote_enable	On	On
xdebug.remote_handler	dbgp	dbgp
xdebug.remote_host	localhost	localhost
xdebug.remote_log	no value	no value
xdebug.remote_mode	req	req
xdebug.remote_port	9000	9000
xdebug.scream	Off	Off
xdebug.show_error_trace	Off	Off
xdebug.show_exception_trace	Off	Off
xdebug.show_local_vars	On	On
xdebug.show_mem_delta	Off	Off
xdebug.trace_enable_trigger	Off	Off
xdebug.trace_enable_trigger_value	no value	no value
xdebug.trace_format	0	0
xdebug.trace_options	0	0
xdebug.trace_output_dir	/var/tmp/	/var/tmp/
xdebug.trace_output_name	trace.%c	trace.%c
xdebug.var_display_max_children	128	128
xdebug.var_display_max_data	512	512
xdebug.var_display_max_depth	3	3

**Comment by tiansin** [comment]
@Miloslav The problem of xdebug version compatibility, perhaps the version that comes with macos is too low, I compiled the source code of xdebug2.7.2 and the function is correct.

**Comment by Miloslav** [comment]
@tiansin great!

Yes, this is bug in Xdebug 2.5.5, there were lots of fixes since then. 

I'm glad the update has helped!
