### ISSUE TITLE
Respect class_alias in the phpdocs

### ISSUE THREAD

**Issue by marinaglancy** [DEVSENSE/phptools-docs#321]
Hello dear Devsense team. You have been so responsive to my request, I feel spoiled now!
Maybe it's a long shot, maybe it's something that would be easy to fix. It is not a deal breaker for us but something nice to have.

Moodle keeps cleaning up old code and move classes to autoloaded locations and defines class_alias() for the new names. It works most of time except when phpdocs refer to the old name (which is an alias). Here is an example:

```
<?php
class_alias('NewName', 'OldName');
class NewName {}

/**
 * @param OldName $param
 */
function x($param) {
}

x(new NewName());

```

The last line gives a warning:

**Argument '1' passed to x() is expected to be of type OldName, NewName givenPHP(PHP0406)**

![class_alias_warning](https://user-images.githubusercontent.com/836986/231744246-7bbfcf65-7d17-4b29-877d-21b57bc1f622.png)

**Comment by jakubmisek** [comment]
Hello Marina,

Thank you very much for the nice words!

We'll take a look at the issue soon, we should definitely handle `class_alias()` within our code diagnostics and phpdoc.

**Comment by jakubmisek** [comment]
@marinaglancy we have fixed this test case, thank you for the details and for reporting the issue in the first place.

The fix will be available in the next pre-release/release.

**Comment by marinaglancy** [comment]
Thank you very much!
