### ISSUE TITLE
[bug] duplicate code `declare(strict_types=1);`

### ISSUE THREAD

**Issue by zengbo** [DEVSENSE/phptools-docs#325]
**Environment**:
VSCode: 1.77.3
Setting:  
    "editor.formatOnPaste": true
    "editor.formatOnType": true,

**Issue**:
When I paste some code, `declare(strict_types=1);` is added to the line before the code.

**Comment by Miloslav** [comment]
Hello,

May I ask you to check if you don't have any other VSC extension that might affect PHP code?

Does it happen to you with some specific code in a certain situation?

**Comment by zengbo** [comment]
> Hello,
> 
> May I ask you to check if you don't have any other VSC extension that might affect PHP code?
> 
> Does it happen to you with some specific code in a certain situation?

Got it. I install another VSC extension: “php cs fixer”, it cause the bug.
