### ISSUE TITLE
Desable display inlay function return type when arrow function!

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#326]
Hello.
Is there an option to disable this, when using arrow functions?

![image](https://user-images.githubusercontent.com/441455/235001226-06094829-0601-44a3-8ae8-7db9d707c1ba.png)

Like this case:

![image](https://user-images.githubusercontent.com/441455/235001765-b775910a-9839-4630-aed6-cf5486fb7799.png)

**Comment by jakubmisek** [comment]
Thank you for the suggestion.

We'll add an option to disable inlay hints for arrow functions.

**Comment by jakubmisek** [comment]
The next pre-release introduces the following setting:

![image](https://user-images.githubusercontent.com/842150/235177082-3e8cb1b1-bf9c-42aa-b66a-716c0e9cc0e5.png)

Thank you again for the suggestion!

**Comment by trollfalgar** [comment]
Thank you, man you are fast!!!
I Appreciate the wonderful work.

**Comment by jakubmisek** [comment]
@trollfalgar Thank you! and thank you for the great feature suggestion
