### ISSUE TITLE
Suggestions for user snippets start work incorrectly

### ISSUE THREAD

**Issue by landerlive47** [DEVSENSE/phptools-docs#327]
After install this extension i cant normally use user snippets in suggestions popup.
While writing code in PHP files i see the suggestions popup but there are no user snippets.
They are shown only if i call suggestions popup by pressing "ctrl + space".

**Comment by jakubmisek** [comment]
I've fixed a bug when snippets stopped working after writing in HTML part of the file.

We're working on the other related issues...

**Comment by jakubmisek** [comment]
@landerlive47 please try the latest pre-release, thank you )

**Comment by jakubmisek** [comment]
The issue seems to be fixed, thank you for reporting it and if it happens again, please feel free to let me know. Thank you!
