### ISSUE TITLE
Warning saying that a sum of arrays is an int|float

### ISSUE THREAD

**Issue by marinaglancy** [DEVSENSE/phptools-docs#328]
Me again, thanks again for addressing our issues so quickly!

Here is another false positive warning message.  We have a bunch of functions that return array with two elements - string SQL fragment and an array of parameters for it. When joining these parameters arrays we get warnings.

Interesting is that if I remove the return type declaration, the extension is able to detect that the second element of the array is an array. However there is no way to specify this in the return typehint or phpdocs (at least I don't know how).

```
<?php
/**
 * Example 1 - with phpdocs
 * @return array
 */
function prepare_sql1() {
    return ['string', ['a' => 1]];
}
function prepare_sql2(): array {
    // Example 2 - with the defined return type
    return ['string', ['b' => 1]];
}
function prepare_sql3() {
    // Example 3 - without the return type
    return ['string', ['c' => 1]];
}
function do_something(array $x) {}
// Both prepare_sql1 and prepare_sql2 give an error:
[$sql1, $params1] = prepare_sql1();
[$sql2, $params2] = prepare_sql1();
do_something($params1 + $params2);
[$sql3, $params3] = prepare_sql2();
[$sql4, $params4] = prepare_sql2();
do_something($params3 + $params4);
// If there is no type for the return value, there is no error:
[$sql5, $params5] = prepare_sql3();
[$sql6, $params6] = prepare_sql3();
do_something($params5 + $params6);

```

![sum_of_arrays](https://user-images.githubusercontent.com/836986/235427132-2d5429c0-0c1a-4082-b1d2-f632cb7d9328.png)

**Comment by jakubmisek** [comment]
Thank you for the detailed test case, Marina!

We'll try to be less strict here; **a quick workaround** for Example 1 and Example 2 is to add the following `@return` type hint:

```php
/**
 * Example 1 - with phpdocs
 * @return array<string,array>
 */
```

so the editor knows, the returned array has `string` and `array` elements.

**Comment by marinaglancy** [comment]
Thanks Jakub, I'll keep it in mind for the new code but it's not always easy to change existing Moodle core functions. I guess we'll have to deal with these error messages for now

**Comment by jakubmisek** [comment]
I've fixed type analysis for this case - we should not treat the result of the operation `+` as `number` here.

Thank you for the test case Marina!
