### ISSUE TITLE
Construct explicit octal notation is supported since PHP 8.1

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#329]
I am getting a huge number of error messages `Construct explicit octal notation is supported since PHP 8.1` for  numeral notations with a leading zero, like 0777, 0644 etc.

**Comment by jakubmisek** [comment]
thank you for reporting that, it's a bug in the pre-release version - will be fixed within today

**Comment by jakubmisek** [comment]
Fixed in upcoming pre-release within today (`1.33.13070+`)

Thank you!
