### ISSUE TITLE
Lost types when passing variable by reference

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#33]
Screenshot say all:
$start is \DateTime
![grafik](https://user-images.githubusercontent.com/22061464/61456648-e37eb100-a966-11e9-81ca-0da985bb6d42.png)

$start is mixed???
![grafik](https://user-images.githubusercontent.com/22061464/61456668-eed1dc80-a966-11e9-8e77-3fede5035e56.png)

**Comment by jakubmisek** [comment]
thank you, looking into it

**Comment by jakubmisek** [comment]
I see the problem, `function assignbyref()` takes the 2nd argument by reference and it is typed as `mixed` so it might change `$start` to anything, the analysis is too strict in here .. 

We'll make this better

**Comment by jakubmisek** [comment]
This should be improved in the next update. Thank you @Mordef
