### ISSUE TITLE
Array Formatting

### ISSUE THREAD

**Issue by zarulizham** [DEVSENSE/phptools-docs#333]
When format php file, array will be formatted like this? Is it expected formatting?
<img width="196" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/10229855/f6822407-956b-4047-a0ac-e770c19798bc">

Perhaps can be formatted like this:

<img width="192" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/10229855/1d2c43e9-b885-4e86-b226-0aaae6c2d025">

**Comment by Miloslav** [comment]
Thank you for reporting this. You're right, the indentation should be just one level in this case. It will be fixed in the upcoming pre-release version.
