### ISSUE TITLE
Rename provider conflicts with other extensions

### ISSUE THREAD

**Issue by marinaglancy** [DEVSENSE/phptools-docs#334]
I'm working on my own extension that allows to refactor some strings used in PHP code that make sense for the project.  I noticed that PHP extension overrides the behavior of the rename provider not in a correct way.

I created a tiny demo extension to demonstrate it: https://github.com/marinaglancy/vscode-renamedemo/blob/master/src/extension.ts

As you can see in the screencast it behaves correctly when PHP extension is disabled and misbehaves when it is enabled. If I add some logging I can see that the "prepareRename()" method from my extension is not executed when PHP extension is enabled which makes me think that PHP extension also implements prepareRename() method but does not throw an error there (as it should because no renaming functionality is implemented in PHP extension in this case).

Screencast:
https://github.com/DEVSENSE/phptools-docs/assets/836986/1887e634-6295-45ba-926c-0c6ff8bcae93

**Comment by marinaglancy** [comment]
I forgot to mention, because of the vscode api there is no way for me to know in the provideRenameEdits() what was the range that was replaced because it was returned by some other extension in their prepareRename(). I created a bug report in vscode about it too.

**Comment by jakubmisek** [comment]
Thank you for the detailed description.

This seems similar to https://github.com/DEVSENSE/phptools-docs/issues/296 ; 

I'll update our rename provider to return `null` instead of an error message. Although, according to [specifications](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename) we should return an error response in case the location is not recognized by our extension .. 

`prepareRename` is not handled by us (yet), so I hope we don't break anything there.

**Comment by jakubmisek** [comment]
It seems it's "discussed" here: https://github.com/Microsoft/vscode/issues/48695

**Comment by marinaglancy** [comment]
yeah not so much for a discussion :)

I wonder if the extensions need to always implement the prepareRename and always throw an error if they do not handle the rename

**Comment by jakubmisek** [comment]
We don't throw an error but we return `null` in this case (afaik)

I guess the error would cause the rename to be aborted.

**Comment by marinaglancy** [comment]
I made a new screencast with only PHP extension, nothing else.
When I use rename in the JS files it only allows me to rename the elements it can rename. When I use rename in PHP file it allows me to rename anything and checks whether they CAN be renamed only after user typed new value.

You can avoid it by implementing the prepareRename() function and throw error from there. And it also will stop breaking other extensions like mine :)

https://github.com/DEVSENSE/phptools-docs/assets/836986/26b3200f-e3eb-413e-a915-39945a5dda1d

**Comment by jakubmisek** [comment]
@marinaglancy good point, we'll implement `prepareRename` API

**Comment by jakubmisek** [comment]
I've implemented `prepareRename`, and so far it seems it's working OK with your `vscode-renamedemo` extension.

Pre-release will be available within a day for you to try it.

Thank you!
