### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by zarulizham** [DEVSENSE/phptools-docs#335]
In Laravel framework, `app/Providers/RouteServiceProvider.php`

<img width="413" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/10229855/4890f1c1-1768-4fda-b692-d572d466eea5">

Formatting the document will have space after `for`. Eg: `::for (`.

It shall be no space `RateLimiter::for(`

**Comment by Miloslav** [comment]
Thank you for reporting this. It will be fixed in the upcoming pre-release.
