### ISSUE TITLE
UnitEnum and BackedEnum

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#337]
![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/5fd68dba-9efb-4ba4-b45e-81a4849f289f)

i dont know how to deal with this, because BackedEnum implement UnitEnum too

![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/2c55a8f8-ca95-4157-a4f2-c804f359ed28)

**Comment by jakubmisek** [comment]
`UnitEnum` does not have a property named `value`. It is implemented only on `BackedEnum`

`enum a : int` is `BackedEnum` and `UnitEnum`.
`enum b` is `UnitEnum` only.

**Comment by ProtocolLive** [comment]
A backedenum will enter in the if

**Comment by jakubmisek** [comment]
But `UnitEnum` does not have a property `value`, so the code will cause a warning in run time.

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/f7db33bd-ff07-4996-8637-bde2745b38b0)

A `BackedEnum` will enter the `if` as well, but the `if` states that the `$name` is expected to be `UnitEnum`. Hence the underlined code is correct.

**Comment by ProtocolLive** [comment]
I dont know why, but the enum acts like `BackedEnum` extends `UnitEnum`. Why thats enter the if...
The enum implements `BackedEnum` and`UnitEnum`, but acts like extends...

**Comment by jakubmisek** [comment]
`BackedEnum` extends `UnitEnum`, but not vice versa.

**Comment by ProtocolLive** [comment]
So, how to remove that false error?

**Comment by jakubmisek** [comment]
@ProtocolLive I'm trying to say - it's not a false error :) it's legit

`UnitEnum` does not have `value` property.

**Comment by ProtocolLive** [comment]
So, i have to remove the extension

**Comment by jakubmisek** [comment]
@ProtocolLive the error means, you have an error in your code. 

Object of instance of `UnitEnum` does not have property `value`. Your code will crash, that's why the extension warns you about it.

This is what you need to fix in your code:

```php
if ($name instanceof \BackedEnum)
```

**Comment by ProtocolLive** [comment]
But the example in first post?
https://user-images.githubusercontent.com/39626142/241592307-2c55a8f8-ca95-4157-a4f2-c804f359ed28.png

**Comment by jakubmisek** [comment]
you can see an analysis of another tool https://phpstan.org/r/917620e2-b8cd-4c0b-b8bc-cf273382a493

If something is `UnitEnum`, it doesn't mean it's `BackedEnum`. So there is a chance, the code will fail.

The example in the first post (https://user-images.githubusercontent.com/39626142/241592307-2c55a8f8-ca95-4157-a4f2-c804f359ed28.png) illustrates it. `b` is `UnitEnum` but not `BackedEnum`, hence it does not have `value` property.
