### ISSUE TITLE
return type true

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#338]
With PHP 8.2

```php
function foo():true{}
```
![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/d5ae7ddf-0007-4d36-9eb4-2f24f4c45cb2)

testing with slash
![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/84f76e29-eeb3-4284-8631-ec8d9028f963)

**Comment by jakubmisek** [comment]
Thank you @ProtocolLive, I'll fix that!

**Comment by jakubmisek** [comment]
Fixed in the upcoming pre-release/release.

Thank you!
