### ISSUE TITLE
array_uintersect show error

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#34]
![grafik](https://user-images.githubusercontent.com/22061464/61716255-06da9f00-ad5f-11e9-9701-719bd5bca879.png)

When i pass a functionname it's ok, but this is also valid
https://www.php.net/manual/en/function.array-uintersect.php

**Comment by jakubmisek** [comment]
Thanks, will be fixed. The editor was confused by the weird function signature where the vararg is in the middle

**Comment by jakubmisek** [comment]
the error checking will be fixed, also the signature helper will show an alternatives

**Comment by jakubmisek** [comment]
implemented in latest release `1.0.3748`, thank you :)
