### ISSUE TITLE
class methods named "define" shows inconsistent warning

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [DEVSENSE/phptools-docs#340]
Hello,

If a class has a method named "define" taking 3 arguments, it shows this warning, even if it's not related to the PHP define() built in function :

`Defining 'case-insensitive constants' is deprecated since PHP 7.3`

![CleanShot 2023-06-10 at 20 00 29](https://github.com/DEVSENSE/phptools-docs/assets/75493105/736d640b-e21d-4d8b-86ec-27a1014e91ce)
 
The extension should not show a warning in this situation.

**Comment by jakubmisek** [comment]
Thank you @Tanguy-Magnaudet for reporting that. Will be fixed!

**Comment by jakubmisek** [comment]
The pre-release `1.34.13249` fixes that, thank you!
