### ISSUE TITLE
please help me, I don't understand the point of this

### ISSUE THREAD

**Issue by SherinaNf** [DEVSENSE/phptools-docs#341]
Configuration "phpCodeSniffer.standard" Error: Failed to locate a PHPCS configuration file for "c:\xampp\htdocs\SCM\app\Config\Email.php".

**Comment by jakubmisek** [comment]
@SherinaNf thank you for reporting the issue.

However, this does not seem to be coming from our extension. We don't handle `"phpCodeSniffer"` settings, not `PHPCS` configuration files.
