### ISSUE TITLE
devsense.php.ls consumes too much RAM

### ISSUE THREAD

**Issue by zarulizham** [DEVSENSE/phptools-docs#343]
There are two processes with devsense.php.ls consume 10GB+ RAM.

I have quit VS Code, but the processes still there. I have to Force Quit from Activity Monitor. Normal Quit did not release the processes.

![image](https://github.com/DEVSENSE/phptools-docs/assets/10229855/98749daa-b409-49ec-ad7b-baa706ef9f8e)

Thank you.

**Comment by jakubmisek** [comment]
Thank you @zarulizham for reporting the issue.

This is definitely a bug. Is the CPU usage high as well?

(VS Code creates one process for each of your workspaces, so two processes are expected when you open two workspaces).

**Comment by jakubmisek** [comment]
@zarulizham May I ask what version do you have installed?

We have a pre-release, which fixes several memory issues, if you'd like to try (https://docs.devsense.com/en/vscode/installation#pre-release-installation).

**Comment by jakubmisek** [comment]
The latest release fixes the issue with the process not being terminated.

**Comment by jakubmisek** [comment]
Found the real memory leak, preparing udpate within today.

**Comment by chielteuben** [comment]
Tested various versions including pre-release, this issue still exists. It's even worse running multiple instances of VS Code.
I currently have 1 small project trying to eat up 8GB of memory for the php.ls process alone.
It has gotten to the point where a disk monitoring utility (company laptop) has started reporting (incorrect) SMART errors for my drive during VS Code usage with this extension enabled, which is quite hilarious.

If I could provide any information that would help you improve/fix this I'd be happy to help.

**Comment by jakubmisek** [comment]
@chielteuben thank you for letting us know! I appreciate your help.

This is definitely a bug. The expected RAM usage for larger projects is about 500MB now (and we're going to cut this to half soon).

How soon after opening VSCode does it get to 8GB?
Do you use `composer.json`, so we could take a look on the packages you use?

Thank you!

**Comment by chielteuben** [comment]
I can replicate this behaviour instantly after opening the project.
In this specific case I'm hovering a function within a test file:
`expect($result)->toBeTrue();`

This will properly display any related information instantly, devsense.php.ls being at ~ 350MB.
I then change `toBeTrue` to `toBeFalse` (which exists), and hover it again. The "loading..." notification is shown and the devsense.php.ls process spikes to 8GB.
The weird thing is, toBeFalse is already being used elsewhere in the same file and can be properly hovered prior to this without causing the same issue. For the record: this also happens with other functions being hovered after being changed.

I can share the composer.json this monday but I can tell you what's in it from memory because it's a brand new project, it's the base Laravel 10 default composer.json with only "pestphp/pest" added.
And even though I doubt it's relevant: the default namespace for the project was changed using `php artisan app:name NewNamespace` (in case you want to 1:1 replicate this scenario).

**Comment by jakubmisek** [comment]
@chielteuben awesome! I'll try to repro the issue within a day or two - if it happens to me as well, it should be easy to fix.

Thank you!

**Comment by jakubmisek** [comment]
@chielteuben thank you again, we've successfully reproduced the issue and fixed this one. Most probably, it's been causing RAM and CPU issues for all the users here.

We'll be preparing update within a few hours.

**Comment by jakubmisek** [comment]
Please try the latest `1.37.13534` and let me know. I appreciate your help with this - we've been trying to find the issue for months!

**Comment by chielteuben** [comment]
I just tested the latest version and the issue is solved!
I've also tested a larger project which uses the `php.workspace.includePath` setting to include 3 other large projects and the process sits at a (for me) respectable ~1600MB memory usage, where before VSCode was nearly unusable in that workspace when the extension was enabled.

**Comment by jakubmisek** [comment]
@chielteuben thank you very much for testing it so quickly.

I'm happy it works for you. We'll keep improving the RAM usage in the upcoming updates.

If there would be anything else weird, please let me know.

**Comment by neriyaco** [comment]
I'm using the extension on 2 different projects, one is totally fine, at 95MB but the other one sits on 3.8GB
`Linux Ubuntu 22.04`
`Extension v1.37.13534`

Screenshot
![image](https://github.com/DEVSENSE/phptools-docs/assets/42520786/1bad97d9-0867-477b-b7f6-81445fb3fcc3)

The bigger project is about 3-4 times bigger than the other one, but the RAM usage is insane, I'll will try to test if it is something specific.
Both use composer packages.

**Comment by LMachucaORT** [comment]
There is a way to ignore some folders to avoid indexing log folder for example?

**Comment by jakubmisek** [comment]
@LMachucaORT yes,
you can use settings:
- `files.exclude` - files won't be indexed
- [php.problems.exclude](https://docs.devsense.com/en/vscode/problems#configuration) to only ignore errors in a folder

**Comment by jakubmisek** [comment]
@neriyaco Thank you for trying our tools - May I ask if the RAM issue still happens? Most large projects we're testing sit at 1.5GB RAM.

**Comment by LMachucaORT** [comment]
> May I ask if the RAM issue still happens? Most large projects we're testing sit at 1.5GB RAM.

Yes, I solved the RAM problem, because the project got too big, but by excluding many folders that I will not be working with, the RAM consumption was cut in half.

**Comment by jakubmisek** [comment]
@LMachucaORT thank you for the update!

**Comment by zarulizham** [comment]
Hi, after exclude some files, I did not face any memory issues anymore.

**Comment by f5vmr** [comment]
I have recently updated vscode in my macbook 16.1.25. The devsense.php.ls still continues to run after shutdown of the application.

**Comment by jakubmisek** [comment]
@f5vmr thank you for reporting the issue. Does the (dead) process consume any CPU, and how much? Does it exit by itself after some period of time ?

**Comment by f5vmr** [comment]
I was exploring why the fan was persisting after a shutdown and removal of
all apps from the bar. When I checked, I found this devense item consuming
97% of the processor time.... Google showed me your link after a short
search. I use vscode studio in some PHP development I'm working on. It was
persistent so I discontinued it from the manager. No big issue really. I'll
watch for it next time.

**Comment by jakubmisek** [comment]
@f5vmr Thank you for the response, and sorry for the inconvenience. 

We'd like to fix this, is there any chance we could get the code and some steps to reproduce the issue?

**Comment by f5vmr** [comment]
If it is of any help, on my GitHub - https://github.com/f5vmr/SVXLink-Dash-V2 which is heavy on PHP, js and html, but I have recently updated VS Studio Code with PHP-MESS extension. Who knows what this can do?
But however I note that I have extension IntelliPHP also installed - perhaps I should uninstall?

I also have a number of other PHP extensions, where perhaps I need only those official extensions.

Regards

Chris

**Comment by jakubmisek** [comment]
@f5vmr thank you very much - that helps a lot. We'll be playing around and hopefully, we'll reproduce the issue.

The other extensions should not interfere with `devsense.php.ls` (unless they trigger something in VSCode).

Best,
Jakub

**Comment by jakubmisek** [comment]
@f5vmr We've tested the project, but no RAM issue yet. Next, we'll try some automated tests that will simulate typing and doing stuff.
If you have some steps that we should try, I'd appreciate that.

**Comment by szabodanika** [comment]
I just want to share here that I noticed that the devsense.php.ls process is using 100% CPU on my machine even when VSCode is not running. I have multiple php plugins from devsense so not sure which one the process belonged to. This has been causing crazy overheating on my M4 Mac recently. Hope you find out what's happening!

**Comment by jakubmisek** [comment]
@szabodanika thank you for sharing the problem with us - it should not happen and it's a bug. 

We couldn't reproduce the issue on our machines yet, so any steps to repro, a project causing it, or the machine configuration would be helpful.

**Comment by jakubmisek** [comment]
We were not able to repro this issue yet. If you have steps that we can try, please let us know. We'll be happy to fix it.
