### ISSUE TITLE
PHP › Format: Code Style not working after update to v1.34.13295

### ISSUE THREAD

**Issue by paperplanefactory** [DEVSENSE/phptools-docs#345]
Hello,
yesterday I updated extension for VSC (Mac) to v1.34.13295 - since then  PHP › Format: Code Style stopped working.
Please, let me know if you need more details and thanks for your support.

**Comment by jakubmisek** [comment]
Hello, and thank you for reporting the issue.

We have found an issue happening on Mac and working on a fix asap.

**Comment by jakubmisek** [comment]
The update has been released, please let me know if it works for you.

**Comment by paperplanefactory** [comment]
Works perfectly! Again, thanks for your support!

**Comment by jakubmisek** [comment]
thank you @paperplanefactory for your quick response! We're glad it works now.
