### ISSUE TITLE
Is possible to NOT use internal composer.phar in DEVSENSE.composer-php-vscode?

### ISSUE THREAD

**Issue by gremo** [DEVSENSE/phptools-docs#346]
I'm managing some legacy project with Composer v1. I've read that DEVSENSE.composer-php-vscode uses an internal composer.phar, but I'd like to use my own version, is possibile?

Thanks

**Comment by jakubmisek** [comment]
We'll add that option.

Currently, it looks for `composer` in the following order:

'/usr/bin/composer',
'/usr/local/bin/composer',
then the directory specified by `COMPOSER_HOME` environment variable, file `latest.phar`

**Comment by gremo** [comment]
My composer is always `/usr/local/bin/composer`, so can you confirm that the phar is never used?

**Comment by jakubmisek** [comment]
I can confirm, that the tool will use `/usr/local/bin/composer` preferably, if it's there. (I should probably add this to the documentation!)

I'll add more logging so we can be sure.

**Comment by jakubmisek** [comment]
The upcoming update uses your own composer, logs its path to the VSCode's developer console, and additionally, there is a new setting `"composer.bin"` where you can explicitly specify the path to the composer.

Thank you for the suggestions!

**Comment by gremo** [comment]
Thanks for the quick response! May I suggest another feature? Could the version be tuned like spacing and font size/color? As you can see they are very close to the actual composer requirement, it's a bit confusing. Minor feature ofc.

![Immagine 2023-06-16 164134](https://github.com/DEVSENSE/phptools-docs/assets/1532616/45ec51bd-84fa-4ecf-aa4c-4dce75780d17)

**Comment by jakubmisek** [comment]
Good idea, I'll take a look at it.

**Comment by jakubmisek** [comment]
@gremo I've added a space. Will be available in the next update.

Styling can be done through VSCode settings, as described at https://docs.devsense.com/en/vscode/editor/inlay-hints#customization (it's the official VSCode approach, the setting is not provided by our extension)

**Comment by gremo** [comment]
Thanks @jakubmisek great work! So I guess there is no way to turn off inlay only for this extension if using, for example, [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) to manage both npm/Composer but still able to use the great Composer menu commands?

**Comment by jakubmisek** [comment]
I see! I'll add an option to enable/disable the inlays for composer packages version.

**Comment by jakubmisek** [comment]
`"composer.inlayVersionEnabled"` setting added, available in the next update.

**Comment by gremo** [comment]
I've forced the latest version (maybe the store isn't updated yet): `DEVSENSE.composer-php-vscode@1.34.13313`. New setting `composer.inlayVersionEnabled` seems to work fine 😎 also inlay settings work too! Amazing job!

Last, just a minor suggestion, I think you should also add the ability to disable the schema settings for those who are using [JSON Schema Store Catalog](https://marketplace.visualstudio.com/items?itemName=remcohaszing.schemastore). it doesn't causes any trouble but seems a duplication.

**Comment by jakubmisek** [comment]
Thank you for trying it so fast. I'm glad it works for you now!

Sadly, the JSON schema validation is not configurable - we can't have a setting to disable it.
