### ISSUE TITLE
Cannot implicitly convert 'Doctrine\ORM\T|null' to xxxx

### ISSUE THREAD

**Issue by hsnfirdaus** [DEVSENSE/phptools-docs#347]
![image](https://github.com/DEVSENSE/phptools-docs/assets/38871578/2d5da8ad-5b51-4a97-86d6-f13bad9c44f7)

How can i get rid of this message in vscode? I think before extension update. It doesn't give any warning?

**Comment by jakubmisek** [comment]
Thank you for reporting this.

May I just ask you, where is `T` defined? I guess it would be in the doc comment above the `getReference()` definition.

**Comment by jakubmisek** [comment]
found it, I'll try to fix it as soon as possible

**Comment by hsnfirdaus** [comment]
Is this resolved? I'm still encounter this issue.

**Comment by hsnfirdaus** [comment]
@jakubmisek Is this resolved? I'm still encounter this issue...

**Comment by jakubmisek** [comment]
@hsnfirdaus please try clearing vendor cache:

vscode's command palette `> Clear /vendor/ cache ...`

**Comment by hsnfirdaus** [comment]
@jakubmisek already tried that..., the warning still showing...

**Comment by jakubmisek** [comment]
I can see this is still an issue - working on it.

**Comment by jakubmisek** [comment]
finally fixed the issue, the fix will be available in the upcoming release, thanks!
