### ISSUE TITLE
Can not jump definition.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#35]
@jakubmisek 
laravel file: app/Http/Kernel.php

![1](https://user-images.githubusercontent.com/4232281/61868195-79887d80-af0b-11e9-8401-c8f6be20c3e8.png)
![2](https://user-images.githubusercontent.com/4232281/61868197-79887d80-af0b-11e9-8f36-ce40f2067404.png)

**Comment by jakubmisek** [comment]
Thank you @tiansin , this happens only for the pseudo-`class`-constant. Will be fixed.

**Comment by jakubmisek** [comment]
fixed in the next update :)
