### ISSUE TITLE
chain suggestion on static methods

### ISSUE THREAD

**Issue by vkoori** [DEVSENSE/phptools-docs#351]
The chain suggestion feature is not operational for static methods, as seen in the following example:

```
/**
* @method static self foo()
* @method static self bar()
**/
class MyClass {
}
```
When attempting to use MyClass, no suggestions can be obtained for the chain of `MyClass::foo()->`.

**Comment by jakubmisek** [comment]
I've updated code completion, so it lists static `@method`s after object instance operator `->` as well.

Thank you for the pointing this out!
