### ISSUE TITLE
docBlock fqn

### ISSUE THREAD

**Issue by vkoori** [DEVSENSE/phptools-docs#352]
In the dockblock, FQN (fully qualified name) works for the return type of a method, but it does not work for input parameters.

For example:

```
/**
* @method static Type1 foo(Type2 $param)
**/
class MyClass {
}
```

In this example, the FQN works for Type1 as the return type, although it does not work for Type2 as the input parameter.

**Comment by jakubmisek** [comment]
thank you for pointing this out, we've implemented code completion for `@method`s parameter type hints as well.
