### ISSUE TITLE
Add option to limit number of parallel debug connections

### ISSUE THREAD

**Issue by iandunn** [DEVSENSE/phptools-docs#353]
When I'm debugging I often have multiple browser tabs open for the site, to test various aspects of it. Those pages often have "heartbeat" XHR requests that run automatically every ~30 seconds. Every time a new request comes in, the `Run and Debug` panel switches to it, and I have to stop the new request, then go back to my original one. That makes debugging very frustrating.

I think it'd be useful to have an option to limit the number of parallel requests, similar to [the `maxConnections` option](https://github.com/xdebug/vscode-php-debug/blob/66cd9369296a73d33f727af1d100c4f46ed24a69/README.md?plain=1#L81) in the Xdebug extension.

----

_Note: I've tried adding the endpoint filename to [the `exclude` param](https://github.com/DEVSENSE/phptools-docs/blob/d8cde349692f3b8058363727b968593d285d5000/docs/vscode/Debug/launch-json.md?plain=1#L112), but that doesn't do what I want. I want to completely ignore any requests to a specific URL/file, rather than processing the request but bypass the file when stepping through the code._

_As a workaround, I've tried enabling both extensions, but this one always seems to process the request, and I haven't found a way to make the Xdebug one "win" the conflict._

**Comment by jakubmisek** [comment]
Thank you for the suggestions. The `maxConnections` option might help.

Although (but we don't have the setting for it yet) Xdebug itself has a few settings to control connections more accurately.

**Would it help** if you could debug only requests with a specific GET parameter? We would take advantage of Xdebug's [trigger_value](https://xdebug.org/docs/all_settings#trigger_value) setting, so Xdebug would initiate connection only if there is a specified `?XDEBUG_TRIGGER=...` query parameter. Any other request would not even initiate the connection back to VSCode.

**Comment by jakubmisek** [comment]
@iandunn pre-release `1.35.13329` adds `"trigger"` launch setting which allows to debug only requests with `XDEBUG_TRIGGER` GET parameter, i.e.

```json
        {
            "name": "Debug built-in server",
            "type": "php",
            "request": "launch",
            "runtimeArgs": ["-S", "localhost:8000"],
            "trigger": "Start",
        },
```
so only `localhost?XDEBUG_TRIGGER=Start` will initiate debugging.

**Comment by iandunn** [comment]
🤔 That could help, but it could also be inconvenient to add it manually whenever I want to debug. I'll look into Xdebug's native settings, though, I hadn't thought of that 👍🏻

**Comment by iandunn** [comment]
I checked [the settings](https://xdebug.org/docs/all_settings) but didn't see anything related to limiting the # of simultaneous connections. Which one were you thinking of?

**Comment by Miloslav** [comment]
Hello,

Sorry it took a while, the next preview version will include the settings.

Thanks for the suggestions!

**Comment by iandunn** [comment]
Thanks!
