### ISSUE TITLE
Wrong recognition of `for` method

### ISSUE THREAD

**Issue by 0x00A1FA** [DEVSENSE/phptools-docs#354]
Hi,

Check out the screenshot below:

![image](https://github.com/DEVSENSE/phptools-docs/assets/110613761/2f022e3f-2703-402b-833e-caada3c6ac94)

The extension does not recognize the `for` there is actually a method.

**Comment by jakubmisek** [comment]
Thank you, I guess this is just the tool-tip got wrong; Code completion should work ok.

Will be fixes.
