### ISSUE TITLE
Add the ability to opt-out from Composer warnings to DEVSENSE.composer-php-vscode

### ISSUE THREAD

**Issue by gremo** [DEVSENSE/phptools-docs#356]
I work as a PHP developer mantaining more then 40 project, some of them legacy. All projects are dockerized and using the `DEVSENSE.composer-php-vscode` which I love ❤️ 

It would be nice to add the ability to suppress extensions warnings for abandoned packages. Sometimes updating these packages isn't easy or even possible, and having those messages under "Problems" all the time is confusing and distracting.

An option like `omposer.abandonedCheckEnabled ` would be much appreciated!👍 

![Immagine 2023-06-27 102956](https://github.com/DEVSENSE/phptools-docs/assets/1532616/aa551d14-2f05-4ebc-818c-0002c0bd404e)

**Comment by jakubmisek** [comment]
@gremo Thank you very much for your feedback and for the nice words!

An option is a good idea, will be added.

**Comment by jakubmisek** [comment]
The next upd
ate has `"composer.diagnosticsEnabled"` setting, thank you for the suggestion!
