### ISSUE TITLE
I've cracked the extension

### ISSUE THREAD

**Issue by 0x00A1FA** [DEVSENSE/phptools-docs#357]
Hi,

Is it OK if I use a cracked version of the extension? By the way, your obfuscation was disgusting. Took me almost an hour to crack lol.

Ty for your work!

**Comment by jakubmisek** [comment]
@0x00A1FA obviously, it is not OK.

You are violating the license agreement: https://www.devsense.com/en/purchase/licenses/community

**Comment by jakubmisek** [comment]
@0x00A1FA thank you for reporting the issue. Please let us know if the issue repeats.
