### ISSUE TITLE
'List' keyword tokenization syntax error

### ISSUE THREAD

**Issue by crockalet** [DEVSENSE/phptools-docs#359]
The keyword List in a namespace shows up as an error.

![Screenshot 2023-07-03 at 16 40 23](https://github.com/DEVSENSE/phptools-docs/assets/60240500/1443de81-82fb-4bbb-b8ec-de93d034344b)

![Screenshot 2023-07-03 at 16 43 55](https://github.com/DEVSENSE/phptools-docs/assets/60240500/b5ff7f14-21d9-4e30-9f39-b090fb313b9a)

**Comment by jakubmisek** [comment]
thank you for reporting the issue, will be fixed!

**Comment by jakubmisek** [comment]
Fixed in the upcoming pre-release (`>1.36.13418`), thanks!
