### ISSUE TITLE
The $this presence in HTML generates warning

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#360]
VS Code Environment
---------------------
VS Code version 1.80.0
Extension Version: v1.36.13417
PHP Version: 8.1.12
Codeigniter4  Version: 4.3.2
-------------------------
Issue description

When embed php code with HTML using the "$this" generates warnings. This would misleading as many such warnings could be generated in a project and confuses other real issues. See screencap below:

![Screenshot_3](https://github.com/DEVSENSE/phptools-docs/assets/63133893/6c54efff-93b2-40af-9d0c-eff6f0e19295)

**Comment by kanlukasz** [comment]
Abstracting from this warning, what you are doing is bad practice.
To the view, pass data using an array as the Symfony, Laravel etc. frameworks do.

Another way to bypass this warning is to use static methods and call them with instance (but it's also bad practice)

**Comment by murugappanrm** [comment]
@kanlukasz 

Bad practice or not I am not sure. The problem is Codeigniter 4 uses this syntax and method to inject layouts into a view. If i am not mistaken Laravel uses a similar syntax and method. The only difference is Laravel (perhaps symfony too) embed this in the Blade syntax which is a modified version Symfony's Twig

I think you need to fix this.

**Comment by murugappanrm** [comment]
Looks like there is no response to this annoying bug!!!!

**Comment by murugappanrm** [comment]
I have resolved the problem by inserting the following settings in setting.json:

 ```
 "php.problems.exclude": {
    "/": [406, 437, 6406],
    "vendor/": true
  },
```

**Comment by murugappanrm** [comment]
This issue is closed
