### ISSUE TITLE
Php Tools for VS Code causes HTML Formatting Error

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#363]
VS Code version 1.80.0
Extension Version: v1.36.13417
PHP Version: 8.1.12
---------------------------------

**This the HTML code in PHP File before the code is collapsed:**

![Screenshot_1](https://github.com/DEVSENSE/phptools-docs/assets/63133893/ef5ee2b6-0a42-4fe4-aaed-f06b15ecdb67)

**This is the code after the collapse with PHP Tools extension disabled:**

![Screenshot_2_no](https://github.com/DEVSENSE/phptools-docs/assets/63133893/c583c09a-d4a9-4ceb-b658-924e6cc5d4bd)

**This is the code after the collapse with PHP Tools extension enabled:**

![Screenshot_2_col](https://github.com/DEVSENSE/phptools-docs/assets/63133893/11969c54-bf97-4b18-96a9-84777c61dd83)

This problem is making difficult to locate the html code block when we need conserve space or copy/paste.

**Comment by murugappanrm** [comment]
Why is there no resolution to this?

**Comment by Miloslav** [comment]
Thank you for reporting this. It will be fixed

**Comment by Miloslav** [comment]
The fix will be released in the next pre-release.

Thanks again!

**Comment by Miloslav** [comment]
> @Miloslav the problem has been fixed thank you.

Thank you for reporting it!

**Comment by murugappanrm** [comment]
Confirmed and tested. Thank you so much.
