### ISSUE TITLE
Formatting does not apply the  settings

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#365]
The following are the version is I am using:

VS Code version 1.80.0
Extension Version: v1.36.13417
PHP Version: 8.1.12

------------------
Problem: 

I set the setting for the IF statement as per the screen cap below which disabled:

![Setting](https://github.com/DEVSENSE/phptools-docs/assets/63133893/83d96570-220a-4445-bfc8-4a3c153bf5ca)

When i save the script the formatting is applying the enabled option as below:

![Format](https://github.com/DEVSENSE/phptools-docs/assets/63133893/c3e7a927-bdf9-4f79-9c77-444154d8ad70)

**Comment by Miloslav** [comment]
Please check if `settings.json` in `.vscode` folder has correct settings.

"php.format.rules.openBraceOnNewLineForBlocks": true

should do:

```php
if (true)
{
}
```

**Comment by murugappanrm** [comment]
I notice that this happens only when i set Code Style to "PHP Tools". When i set to PSR-12 it works fine.
