### ISSUE TITLE
/** dockblock not generate

### ISSUE THREAD

**Issue by axmairat** [DEVSENSE/phptools-docs#366]
/** generated by vscode. How generate dockBlock by extension?
![image](https://github.com/DEVSENSE/phptools-docs/assets/47591259/d61f197d-d872-461b-a51b-87e87d369b85)

**Comment by jakubmisek** [comment]
Hello @axmairat 

Doc comment is generate dupon typing `/**` above function/class/property (https://docs.devsense.com/en/vscode/editor/phpdoc)

Additionally you can use a Code Action (`ctrl`+`.` / `cmd`+`.`) and choose `Add missing /** ...`

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/163bf82b-887a-4f60-8f67-76e869cd968b)
