### ISSUE TITLE
In the PHP 8.2 environment, the second parameter of the http_build_query function does not support null

### ISSUE THREAD

**Issue by F4NNIU** [DEVSENSE/phptools-docs#369]
Dear development team,

First of all, I'd like to say that your PHP Tools are truly amazing!

However, I noticed that the second parameter of the http_build_query function does not support null in PHP 8.2 environments. It would be great if you could address this issue as it's an important feature for me and other users.

Thank you very much for your patience and hard work. Looking forward to your response.

tooltips
<img width="690" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/3390878/3a919e14-aaf9-4771-990a-1c06ff8977b1">

**Comment by jakubmisek** [comment]
Thank you @F4NNIU,

You are right, `null` is not allowed. I think the tooltip denotates optional parameter in this way, but `null` looks misleading here.

**Comment by jakubmisek** [comment]
Fixed for some time already :)

<img width="606" alt="image" src="https://github.com/user-attachments/assets/93464ea1-9d3e-4319-836d-e8573ba8c107">
