### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by amosedmond1** [DEVSENSE/phptools-docs#37]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.0.3748`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\TE\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
closing because the protocol isn't attached
