### ISSUE TITLE
`{@inheritdoc}` documentation link is broken

### ISSUE THREAD

**Issue by AndreiOrmanji** [DEVSENSE/phptools-docs#373]
Description:
On hover there is a link to documentation https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.inheritdoc.pkg.html, but the link is broken.
![image](https://github.com/DEVSENSE/phptools-docs/assets/48985454/f93c4551-eb85-4cd5-9624-051731bd9df2)

![image](https://github.com/DEVSENSE/phptools-docs/assets/48985454/fb9e9281-9fd3-46d9-a855-29dd53003d28)

Instead of it I propose to replace it with https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html or to completely remove it.

**Comment by jakubmisek** [comment]
fixed in the next update1, thank you
