### ISSUE TITLE
Unexpected local variable rename in all scope

### ISSUE THREAD

**Issue by AndreiOrmanji** [DEVSENSE/phptools-docs#375]
Description:
There is an unexpected behavior of variable rename: if you place cursor on local variable and you start typing, all usages of this variable are renamed.

Preview:
![rename](https://github.com/DEVSENSE/phptools-docs/assets/48985454/684004bc-ec3d-495a-9317-fdddccdbb1c8)

**Comment by jakubmisek** [comment]
It is called "linked editing", and it is disabled by default.

Turn the following setting to `false`:

```json
"php.linkedEditing.variables": false,
```
