### ISSUE TITLE
Support for scalar_objects php extension

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#378]
I just started using this extension today, and I am absolutely floored at how well it works! I definitely expect to pay for premium when the free trial runs out. Anyway, the main thing it is lacking for me is, understanding code that utilizes the [scalar_objects](https://github.com/nikic/scalar_objects) php extension. This extension enables a syntax where it looks like you can call "methods" on values with built in types, such as string and int. So you can have code like `$myString->sub(0, 1);` Currently phptools always shows "Call to a member function sub() on a non-object of type stringPHP(PHP0404)" for these calls.

I realize it is a big ask to want support for a specific, non-standard php extension. This php extension is one of the keys to keeping php usable and nice for me. It works well even with php 8.2, and was developed by a well known and respected php developer that is very actively involved in the development of php. He didn't really intend it to be used in production code the way I do, but it seems to work quite well for me, and has been working for some time now.

**Comment by jakubmisek** [comment]
Preparing pre-release with the support for `scalar_objects` extension, IntelliSense, and code diagnostics for extension methods.

**Comment by still-dreaming-1** [comment]
Great! I just added those settings and switched to the pre-release version. It is no longer showing issues for these calls which is nice. If I hover over one of these extension method calls, it pops up with the signature information. If I edit the code and try to call one of these, it shows the correctly expected parameters, only the ones after the first parameter. It would be super helpful if I could use the Go To Definition feature on these, as I use this quite a lot.

**Comment by jakubmisek** [comment]
Great! Thank you for trying it so fast.

We'll try to fix the tooltip and _go to def_.

**Comment by still-dreaming-1** [comment]
Cool. Inlay hints is also not working yet.

**Comment by jakubmisek** [comment]
- [x] `scalar_objects` stubs
- [x] code diagnostics to respect defined methods on scalar types
- [x] code completion with extension methods
- [x] signature help for extension methods
- [ ] tool tip of extension method
- [ ] inlay hints of called extension methods
- [ ] go to def and refactoring

**Comment by jakubmisek** [comment]
thank you! I'll do some more testing and prepare a new pre-release.

**Comment by still-dreaming-1** [comment]
It all works perfectly now, thanks!

**Comment by jakubmisek** [comment]
@still-dreaming-1 thank you for testing it!
