### ISSUE TITLE
Feature: Autocomplete Class Names based on File Names

### ISSUE THREAD

**Issue by lucashtc** [DEVSENSE/phptools-docs#379]
When we create a new file, the code editor would analyze the file name and provide relevant autocomplete suggestions for the corresponding class name. This would ensure that the class name closely matches the purpose of the file.

By automating the process of generating class names, we can ensure consistency between file and class names, leading to better code organization and maintainability.

**Comment by jakubmisek** [comment]
Thank you for the suggestion - will be implemented.

**Comment by jakubmisek** [comment]
@lucashtc 

The latest pre-release (`1.38.13924`) provides inline suggestions with class names;

![vsc-complete-class-name](https://github.com/DEVSENSE/phptools-docs/assets/842150/7327868b-845e-48e1-adaf-b52818aace18)

Together with [IntelliPHP](https://marketplace.visualstudio.com/items?itemName=DEVSENSE.intelli-php-vscode), it also provides inline suggestions for the rest of the code (as shown in gif), if you'd be interested.

I appreciate any feedback on this!

If you'd have any more suggestions what else we can suggest using inline completions, I'll be happy to implement it.

Thank you

**Comment by lucashtc** [comment]
@jakubmisek Thanks.  Great to hear that you're this quick to create feature

**Comment by jakubmisek** [comment]
@lucashtc thank You for the suggestion!
