### ISSUE TITLE
Issue with enum

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#381]
![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/3139a1d4-dcb4-43ae-b46a-888afea38546)

PHP version are setted to 8.2
Extension: v1.37.13637

**Comment by jakubmisek** [comment]
thank you, may I ask where is "FilterFrom" defined? is it a part of some package?

**Comment by jakubmisek** [comment]
I believe this is a pre-release version? There might be an issue with enum/class members which we're fixing right now.

**Comment by ProtocolLive** [comment]
> thank you, may I ask where is "FilterFrom" defined? is it a part of some package?

In other file. Its my enum

**Comment by jakubmisek** [comment]
ok, thank you, I'll look into it.

**Comment by jakubmisek** [comment]
It was probably caused by an incomplete cache; we do recognize `enum`s and its `case`s as any other class in the workspace.

`v1.37.13637` was a pre-release version which had this bug. Please try again after updating.

Thank you very much.
