### ISSUE TITLE
Extension is throwing `Arg_ArgumentOutOfRangeException` when window reload / VSCode starting

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#382]
Extension keeps complaining on vendor classes everytime VSCode reloads or extension gets updated:

<img width="972" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/d1edea90-7636-41db-aa34-e2bab82c996e">

What's shown on the image, happens everytime I update the extension or VSCode or reload the project's window.

Think this might be the new classmap caching or some related issue with this.

Edit: This is what the output displays.

<img width="691" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/5dc04df3-c2bb-4d77-9c02-ee4f840aa68c">

**Extension version: v1.37.13637**

**Comment by jakubmisek** [comment]
Thank you! It seems (besides the exception) it does not "recognize" your `vendor` directory and does not cache the packages.

May I ask if you have `/vendor/` in your workspace and if there is a regular `composer.json` and `composer.lock` next to it?

The expected output would be something like:

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/94e2a57d-52d7-4134-8807-01ae56b80687)

**Comment by d8vjork** [comment]
@jakubmisek Yes, all together in the same (root) folder of the VSCode workspace

![image](https://github.com/DEVSENSE/phptools-docs/assets/2331052/35b8a6ca-ce2c-40f4-af67-1292167576e8)

**Comment by d8vjork** [comment]
@jakubmisek Yes, I'm using Mac OS

**Comment by jakubmisek** [comment]
@d8vjork May I ask to try the latest `1.37.13653`? If it's not working, there should be more details in OUTPUT / PHP Language Server.

Thank you!

**Comment by d8vjork** [comment]
@jakubmisek Yes there are more details! And got more errors too, here is the link:

https://gist.github.com/d8vjork/60734606fb3f9b48c8c385896739e1f4

**Comment by jakubmisek** [comment]
awesome, thanks! will be fixed today

**Comment by jakubmisek** [comment]
it should be fixed now

**Comment by d8vjork** [comment]
@jakubmisek Yes it is! Sorry for the late I was testing it further while working

The other thing I see changed is the go to class file it goes to the one "cached" (I think?): 

<img width="1147" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/3104cebd-c531-4f71-a41f-167fd8c96a83">

Is there a way to go to the original one under the vendor folder? Doing some sort of map with links back to the original files and the cached ones or something similar?

**Comment by jakubmisek** [comment]
@d8vjork thanks for testing it and for the feedback!

- right `go-to-def` goes to generated code for now. Jumping to the original code is in progress.
- facades should work as before, so this is most probably a bug. 

known issues:
- generics in vendor are broken
- go-to-def goes to generated code
- sometimes it caches an incomplete source code when running `composer install` or `update`

**Comment by jakubmisek** [comment]
The issue and the issues above have been fixed with the latest pre-release `v1.37.13728`.

Thanks!
