### ISSUE TITLE
Call to unknown method: PHP(PHP0418)

### ISSUE THREAD

**Issue by Loki3000** [DEVSENSE/phptools-docs#386]
Hi.
Seems I have false-positive message from extension:

![изображение](https://github.com/DEVSENSE/phptools-docs/assets/12333165/ef865f1d-b806-45cd-9dc6-82ec800bec4f)

Whole code example here https://github.com/Loki3000/devsence_php

**Comment by jakubmisek** [comment]
thank you for the test case, I'll try to fix it asap.

**Comment by jakubmisek** [comment]
It seems the property `$dependency` is typed as `AbstractDependency` which does not define `callMe()`.

I wonder what is the proper way of handling this since it is a potential error in runtime.

**Comment by Loki3000** [comment]
As you see ```$dependency``` is actually instance of ```MyDependency```. So it's could have any additional methods compared to the base class.

**Comment by jakubmisek** [comment]
It may be an instance of `MyDependency`, but the declaration says

```php
AbstractDependency $dependency,
```
https://github.com/Loki3000/devsence_php/blob/ed14707853365cd934a1b3c67fa3b7793c345d9e/AbstractClass.php#L8

The code editor may understand that in this particular case. Still, as it is declared, you may be assigning an instance of `AbstractDependency` to that properly, then calling `callMe()` would crash in run-time.

`AbstractDependency` should implement
```php
abstract function callMe();
```
or it should have a doc comment:
```php
/**
 * @method void callMe()
 */
```

**Comment by Loki3000** [comment]
You are probably right. However, my viewpoint still remains that inheritance implies that subclasses can extend and modify the parent class in arbitrary ways (with some restrictions).

Thanks.
