### ISSUE TITLE
VS Code Sticky Scroll didn't works

### ISSUE THREAD

**Issue by korandcom** [DEVSENSE/phptools-docs#387]
If set "Editor › Sticky Scroll: Enabled" in settings - this function didn't works. But if use another extension (Intelephense for example) - all works great. "Editor › Sticky Scroll: Default Model" is set to "outlineModel" by default.

**Comment by jakubmisek** [comment]
Thank you for letting us know.

Will be fixed in the upcoming pre-release!

**Comment by jakubmisek** [comment]
Thank you again @korandcom ,

The update `1.38.13779` implements the sticky scroll.

**Comment by korandcom** [comment]
All works great now. Thanks!

**Comment by jakubmisek** [comment]
thank you for the update!
