### ISSUE TITLE
Version 1.38.13759 is not working

### ISSUE THREAD

**Issue by lexman1958** [DEVSENSE/phptools-docs#388]
The new version is not resolving the errors after i do a composer install. This problem did not exist with version 1.37.13534. See screencap:

![Screenshot_10](https://github.com/DEVSENSE/phptools-docs/assets/127527088/f65acf1d-62a7-4796-973d-19bcbf384431)

**Comment by jakubmisek** [comment]
I can see `BaseConfig` is underlined.

May I ask to check OUTPUT, "PHP Language Server" ? There might be additional details. Also you may try pre-release version which has a few related issues fixed.

**Comment by azvyae** [comment]
Still the issue persists on the pre release version `v1.38.13767` here is the output:

```
PHP Tools server started.
    PID: 9354
    Processing files: *.php; *.phtml

[Info  - 3:01:17 PM] Processing packages in /home/azvyae/php-app/vendor/composer/installed.json ...
[Info  - 3:01:19 PM] Processing done in 00:00:01.5084083
```

**Comment by lexman1958** [comment]
Same result from me too.

**Comment by jakubmisek** [comment]
Thank you, may I ask you to try the update `1.38.13779` - we have fixed a few related issues there.

**Comment by cognitus** [comment]
we have a lots problem with new version `1.38.13779`...  on laravel don't recognize a lot function 

finally, we choice downgrade to `1.37.13534` =/

**Comment by lexman1958** [comment]
@jakubmisek  My suggestion: Destroy all versions after 1.37.13534 and start-over from there. This is avoid too many buggy in-between version especially when we want to revert to another version in vscode. Appreciate this.

**Comment by jakubmisek** [comment]
There is a bug when caching /vendor/ folder after `composer install` or `composer update`. It reads the files too early and doesn't wait for the composer to finish.

Sorry for the trouble, will be fixed.

**Comment by TheDevick** [comment]
Hey! This also occurs in my Symfony Project. I wrote an issue in the DevSense site:
https://community.devsense.com/d/1689-optimized-loading-and-memory-use-bug/11

**Comment by jakubmisek** [comment]
May I ask to try the latest pre-release (`1.38.13796`)? 

There is a new command `> Clear /vendor/ cache.` which updates the corrupted internal cache of composer packages.

**Comment by lexman1958** [comment]
@jakubmisek  still the same problem. After i do a composer install all the problem highlights are still not resolved unless i open each one of these. Only when i open each script, the problem items resolve for that script while rest remain.

![Screenshot_11](https://github.com/DEVSENSE/phptools-docs/assets/127527088/097fd610-cd97-4d72-8d28-7edd1f9c6d5f)

**Comment by jakubmisek** [comment]
@lexman1958 Thank you, Have you tried the command 'Clear /vendor/ cache` ?

I'm just releasing a pre-release that handles the composer updates.

**Comment by lexman1958** [comment]
@jakubmisek 

I tested with the pre-release version 1.38.13826. This what i did:

(1) On loading the app into vscode, the unresolved warnings showed up (this is normal)
(2) Under terminal, ran "clear /vendor/cache" as advised --> ok
(3) Run composer install --> all warnings got resolved
(4) Delete vendor folder
(5) Reloaded the app in vs code and as usual the unresolved warnings appears
(6) Run composer install without step 2 above ---> **every worked fine.**
(7) Repeated the steps (1) and  (3) for a few other apps ---> worked fine.

On top of working fine, another plus point i notices is the composer install completed much faster.

**Comment by jakubmisek** [comment]
@lexman1958 Thank you very much for testing the update so quickly, I appreciate the detailed steps!

I'll try to add those steps to our automated tests. Also from now on, the `clear /vendor/cache` command should not be necessary.

Good the update speedups `composer install`; we have started to do the /vendor/ analysis in batches, and it is good to see it actually improved the performance.

**Comment by jakubmisek** [comment]
`1.38.13826` is the latest release, it should have been available for a few hours already.

`clear vendor cache` may be necessary once, just to get rid of the pre-release caches.

**Comment by lexman1958** [comment]
@jakubmisek thank you for the update. I think we can close this issue. I will do the honor.

**Comment by lexman1958** [comment]
@cognitus @jakubmisek 

Its a bit unpredicatable. I loaded my laravel app  using the same extension but do not get these errors.  Unfortunately, i had a similar error with vanilla PHP app. See https://github.com/DEVSENSE/phptools-docs/issues/392 on the similar issue. 

My screencap on Laravel 10 app (no issues):

![Screenshot_16](https://github.com/DEVSENSE/phptools-docs/assets/127527088/f7061fc4-e0d2-46e2-b857-b226e245de98)

**Comment by jakubmisek** [comment]
@cognitus May I ask to

- open `OUTPUT` panel, tab `PHP Language Server`
- run "clear /vendor/ cache" command in VSCode's command palette
- in the output, you should see how it processes the composer packages
- after 30-60 seconds, it will cache the packages to disk

Is there any error in the OUTPUT window?

Thank you

**Comment by cognitus** [comment]
@jakubmisek 

first try:

```bash
[Info  - 5:46:42 PM] Deleting DEVSENSE/packages-cache ...
[Info  - 5:46:44 PM] Processing packages in /var/www/html/work/vendor/composer/installed.json ...
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/File/FindEndOfStatementTest.inc' errored.
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/File/GetMethodPropertiesTest.inc' errored.
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/File/FindExtendedClassNameTest.inc' errored.
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/File/GetMemberPropertiesTest.inc' errored.
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/File/FindImplementedInterfaceNamesTest.inc' errored.
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/File/IsReferenceTest.inc' errored.
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/tests/Core/Tokenizer/EnumCaseTest.inc' errored.
#
# (a lots errors parsing here)
#
[Error - 5:47:01 PM] Parsing '/var/www/html/work/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc' errored.
[Info  - 5:47:03 PM] Processing done in 00:00:18.2038141.
```


I removed  the package squizlabs/php_codesniffer, and I try again:

```bash
Info  - 5:52:13 PM] Deleting /home/tom/.local/share/DEVSENSE/packages-cache ...
[Info  - 5:52:13 PM] Deleting DEVSENSE/packages-cache ...
[Info  - 5:52:15 PM] Processing packages in /var/www/html/work/vendor/composer/installed.json ...
[Info  - 5:52:25 PM] Processing done in 00:00:10.3434780.
```

but without errors, but still gives the same problems

**Comment by jakubmisek** [comment]
@cognitus thank you,

is it still the same problem `unknown method Route::name()` ?

**Comment by jakubmisek** [comment]
@cognitus there is a new pre-release **1.38.13874** which fixes issues when having laravel-idea and ide-helper plugins.

**Comment by jakubmisek** [comment]
thank you for the quick confirmation!
