### ISSUE TITLE
PHP0418 when using Carbon

### ISSUE THREAD

**Issue by cconrad** [DEVSENSE/phptools-docs#389]
The following code unexpectedly reports the issue "Call to unknown method: Carbon\Traits\Creator::subMonths()" (PHP0418):

```php
use Carbon\Carbon;

class Test {
    public function test() {
        Carbon::now()->subMonths(1);
    }
}
```

**Comment by jakubmisek** [comment]
Thank you for reporting the issue, will be fixed!

The `static` return type got broken in the last release.

**Comment by jakubmisek** [comment]
The update `1.38.13779` fixes the issues with `Carbon` and other `static` methods in /vendor/ folder. Please try.

**Comment by cconrad** [comment]
It works! Thanks for the crazy fast fix!

**Comment by jakubmisek** [comment]
Thank You for checking it so fast! I'm glad it works.
