### ISSUE TITLE
HTML Highlight has errors in version 1.37

### ISSUE THREAD

**Issue by lexman1958** [DEVSENSE/phptools-docs#390]
Hi
There seems to be some bug in HTML tag highlighting. The tag <center> is not highlighted a valid syntax. But when i change it to <centre> (which is wrong), the highlight works.

![Screenshot_13](https://github.com/DEVSENSE/phptools-docs/assets/127527088/c8ec23bf-afe7-4237-9a83-f2df10639bac)

**Comment by jakubmisek** [comment]
Thank you for pointing this out.

This is, however, a vscode's feature. PHP extension does not integrate into .html files. (Unless you have changed the file associations)

I'd suggest reporting any misbehavior on https://github.com/microsoft/vscode/issues

**Comment by lexman1958** [comment]
@jakubmisek I have reported this issue in vscode github. Lets see the outcome.

**Comment by jakubmisek** [comment]
@lexman1958 thank you, I know they have a lot of opened issues. Hopefully, they would be able to help.

**Comment by lexman1958** [comment]
@jakubmisek the problem is that i was using an deprecated tag <center> which vs code ignores. My apologies for not checking this with Mozilla MDN. I will close this. Thank you.

**Comment by jakubmisek** [comment]
Thank you for the update, I hope it helps other users, dealing with the same issue.
