### ISSUE TITLE
Error: shows warning for an enum method that exists

### ISSUE THREAD

**Issue by lexman1958** [DEVSENSE/phptools-docs#392]
I am using PHP Tools Extension version 1.38.13826. The extension seems to highlight a warning for a enum method that exists in the enum class. The code works however. See the screencaps below:

![Screenshot_14](https://github.com/DEVSENSE/phptools-docs/assets/127527088/ea5877a8-3c43-4826-a7b7-8d1dfdace3fe)

![Screenshot_15](https://github.com/DEVSENSE/phptools-docs/assets/127527088/4c57dacc-59a4-401c-a15d-caef319ba8e2)

**Comment by jakubmisek** [comment]
This issue should be fixed in the latest 1.38 release.

**Comment by jakubmisek** [comment]
That should work, may I ask to mouse hover on "tryFrom(` ? whether it "known" it returns "InvoiceStatus"?

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/5265e18f-3783-479b-a97e-52e76882e85d)

**Comment by lexman1958** [comment]
@jakubmisek  its odd, I just reloaded the same app today and i dont get the problem.  I guess we can close this issue for now. Thank you for testing it out.

**Comment by jakubmisek** [comment]
Thank you for the update. If it happens again, I'll be happy to get it fixed.
