### ISSUE TITLE
Missing original Laravel methods when laravel-ide-helper file is generated

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#393]
I don't remember since when but this stopped working on some update of the extension:

<img width="1198" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/59bf8904-8022-4305-9468-00f80d3d13c6">

Any extended method from Laravel IDE Helper on the `_ide_helper.php` doesn't seem to have any method coming from the original class, in the case of the screen above should be `Illuminate\Support\Collection`

**PHPTools extension version:** 1.38.13826

**Comment by d8vjork** [comment]
Ok jumped back to v1.37.13534 of PHPTools and working:

<img width="1047" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/9808c1dc-039f-4d41-8710-a9c7dff60a12">

**Comment by jakubmisek** [comment]
Thank you for the feedback.

This is not a part of _ide_helper, just a regular trait function, but it's working in our tests (`1.38.13826`):

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/346e25b6-d5e6-429a-89e5-6b24776e595d)

I'll try more tests to repro the issue.

**Comment by d8vjork** [comment]
If this helps, we're having some custom "mixins" as Laravel likes to call them, and added them to this IDE Helper package so it does add these methods to the _ide_helper file:

This is our `config/ide-helper.php` just in case:

```php
   /*
    |--------------------------------------------------------------------------
    | Extra classes
    |--------------------------------------------------------------------------
    |
    | These implementations are not really extended, but called with magic functions
    |
    */

    'extra' => [
        'Eloquent' => [
            'Illuminate\Database\Eloquent\Builder',
            'Illuminate\Database\Query\Builder',
        ],
        'Session' => ['Illuminate\Session\Store'],
        'FileAdder' => ['App\FileAdder'],
        'Illuminate\Routing\Router' => ['App\Router'],
        'Illuminate\Routing\Route' => ['App\Router'],
        'Illuminate\Routing\PendingResourceRegistration' => ['App\Router'],
        'Illuminate\Database\Schema\Blueprint' => [
            'App\Blueprint',
        ],
        \Illuminate\Support\Collection::class => [
            \App\Collection::class,
            \OpenSoutheners\LaravelApiable\Collection::class,
        ],
        \Spatie\MediaLibrary\MediaCollections\FileAdder::class => [
            \App\FileAdder::class,
        ],
        \Spatie\MediaLibrary\MediaCollections\MediaCollection::class => [
            \App\MediaCollection::class,
        ],
        \Illuminate\Validation\Rule::class => [
            \App\Validation\SkoreRule::class,
        ],
        \Illuminate\Events\Dispatcher::class => [
            \App\Dispatcher::class,
        ],
        \Illuminate\Support\Str::class => [
            \App\Str::class,
        ],
        \Illuminate\Support\Arr::class => [
            \App\Arr::class,
        ],
        \Illuminate\Http\Request::class => [
            \App\Request::class,
        ],
    ],
```

**Comment by jakubmisek** [comment]
Thank you @d8vjork 

There is a new pre-release 1.38.13874 which works better with ide-helper and laravel-idea;

I don't think we'll process `config/ide-helper.php` file, but we are processing the ide-helper classes (generated by ide-helper) so that is sufficient I guess.

**Comment by d8vjork** [comment]
Hi @jakubmisek

Thanks so much! I think that will be more than enough, at least using the `_ide_helper.php` root project file **as an addon** to the root classes (`Illuminate\Support\Collection`, `Illuminate\Support\Str`, etc...)

**Comment by d8vjork** [comment]
Ok I can close this, as I see the issue is clearly fixed at least for me

**Comment by jakubmisek** [comment]
Thank you @d8vjork for the quick check.

Please feel free to let me know if there would be anything else. Laravel is important to us.
