### ISSUE TITLE
Refactoring only works partially

### ISSUE THREAD

**Issue by lexman1958** [DEVSENSE/phptools-docs#394]
When I refactor a symbol, it only refactors partially and not all the symbols in the script. See screencap below. If it only does partial then it may not refactor all the open files as documented. 

![Screenshot_17](https://github.com/DEVSENSE/phptools-docs/assets/127527088/97c18947-35e0-4843-89b3-189280816d0d)

**Comment by jakubmisek** [comment]
It looks like you're renaming `$start` which is the function's local variable. It is different than the other `$start` variables in your scriopts.

**Comment by lexman1958** [comment]
@jakubmisek 

Need to understand. Does it matter? Shouldn't it refactor all the variables anyway? Otherwise the refactoring feature may not be that useful. What i mean is, when i select to refactor a symbol it should refactor all. That is the whole purpose, am i right? From the documentation, i see what you mean but only sad that it is not complete.

**Comment by jakubmisek** [comment]
that's the point

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/36190bcb-3a4d-44ee-8771-b0b509a7c6f4)

those are two different symbols.

**Comment by d8vjork** [comment]
For this you can use the Search & replace feature of VSCode

<img width="446" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/a621d658-17f4-4479-8ae4-8298c74b5b51">

Refactor must be more cautious on the context of these things as normally we don't want to change some other variables names as a project gets bigger and bigger

**Comment by jakubmisek** [comment]
Thank you @d8vjork and @lexman1958 

After reviewing the issue, we have to close it, since it is indeed behaving as expected. Not renaming the other `$start` is intended.

Thank you for your time, and please feel free to keep reporting.

**Comment by lexman1958** [comment]
@jakubmisek Hi,

Just an update:

(1) PHP Tools no longer conflicts with Intelliphense extension. Only thing the formatting option in Intelliphense needs to disabled otherwise the formatting may conflict with PHP Tools. - Formats twice
(2) I am using PHP-Refactor extension "ctf0.vscode-php-refactor" which is more comprehensive then those provided by PHP Tools. Example, i could highlight a chunk of code and generate a method using the chunk. A refactor which we use often.
(3) For the refactor extension to work, it needs the Intellphense Extension.

**Comment by jakubmisek** [comment]
@lexman1958 thank you for the details, I appreciate it.

We're working on "extract method" refactoring but released it yet (https://github.com/DEVSENSE/phptools-docs/issues/213); I'll try to make the final version sonner.

**Comment by lexman1958** [comment]
@jakubmisek will wait for the release. Suggest try out the ""ctf0.vscode-php-refactor" extension. It has a number of other features that needs to be included so that we can drop this extension and also the PHP Intelliphense extension to optimize vs code performance. 

Thank you.
