### ISSUE TITLE
Not working with PHP scoper

### ISSUE THREAD

**Issue by mdalaminbey** [DEVSENSE/phptools-docs#396]
To avoid namespace conflict with other WordPress plugins. I am using humbug/php-scoper to add a prefix. 

The issue is PHP is not scanning the vendor build folder.

![image](https://github.com/DEVSENSE/phptools-docs/assets/75071900/ab638fe1-d49e-4e85-a43a-d94aa274272d)

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

Currently, the editor scans /vendor/ folder, and it ignores the `"vendor-dir"` configuration. **This will be fixed.**

As a quick workaround, you can revert to version `1.37` which scans the entire workspace.

**Comment by jakubmisek** [comment]
Update `1.38.13899` fixes the issue, thank you!

- we will correctly index /vendor-src/ and save it to cache for fast workspace load
- the /vendor/ directory will be indexed continuously, updating all the changes

> Note: when you change `"vendor-dir"` in composer.json, you may need to reload VSCode workspace.
