### ISSUE TITLE
v1.38.13879 / OpenCart / Undefined property error PHP0416

### ISSUE THREAD

**Issue by cagatay117** [DEVSENSE/phptools-docs#397]
I am using the pre-release version v1.38.13879 but in my OpenCart project files have hundreds of this "undefined property" errors in them.

![image](https://github.com/DEVSENSE/phptools-docs/assets/6120852/d2603dff-bf44-4d03-8b07-952c4361999b)

This is a built-in function in a built-in file and when I run, it works fine.
I don't want to suppress the error with extensions or config files or suppress codes please.
I switched back to release version v1.38.13826 and the problem went away. What can I do to solve this problem?

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

This happens only in the latest pre-release, will be fixed today.

**Comment by jakubmisek** [comment]
fixed, and preparing a new pre-release, thanks!

We've also improved some type checks in OpenCart, but there is a lot of unhandled cases - we'll be happy if you report anything not working properly. I.e. if something completion does not work after `->` operator, etc.
