### ISSUE TITLE
False-positive syntax errors in namespace/use statements: Unexpected token 'xxx' 

### ISSUE THREAD

**Issue by DaGhostman** [DEVSENSE/phptools-docs#399]
I am experiencing something similar to #266 but not exactly.

Basically I am working on a legacy codebase that has reserved keywords as part of the namespace, like: `Some\Module\Component\Clone\...` and the extension is reporting:
![image](https://github.com/DEVSENSE/phptools-docs/assets/2286949/d5534757-2195-4123-bb79-e9f430972168)

From what I can tell the parser is picking up the keywords inside of the `namespace`/`use` statements and that is annoying, since it breaks the code completion in files as well as wrongly flagging it as syntax error as `php -l` is absolutely happy with the situation.

Also if we hover the print (it shows the documentation about the `print` function but it is not a function)

<details>
<summary> Code Snippet </summary>

```php
<?php

namespace Some\Switch\Related\Thing;

use Some\Print\Related\Thing;

// ...
```

</details>

**Comment by jakubmisek** [comment]
Thank you for reporting that!

Will be fixed in the next update.

**Comment by jakubmisek** [comment]
Update `1.38.13899` fixes the issue, thank you!

**Comment by DaGhostman** [comment]
I've just checked and while if there is a `switch` there is no problem the issue still remains with other keywords, `Print`, `Clone` being 2 examples I have in the codebase, but I guess it will be the same for every keyword/function mentioned.

<details>
<summary>Updated code sample</summary>

```php
<?php

namespace Some\Print\Related\Thing;

use Some\Print\Related\Thing;

// ...
```

</details>

Also, if I hover the keyword, I still see the popup with
> **keyword** switch

which seems a little bit strange and could be confusing from time to time.

Would you prefer me to open a separate issue or you'd reopen this one.

Thanks!

**Comment by jakubmisek** [comment]
thank you for the update, other keywords will be fixed. I'll see if we can fix the tooltip for the next update as well.

**Comment by jakubmisek** [comment]
version `1.38.13909` (upcoming) fixes both the issues - tooltips and clone and print,

thank you!
