### ISSUE TITLE
using variable in arrow function got error.

### ISSUE THREAD

**Issue by zengboin** [DEVSENSE/phptools-docs#400]
The code:
```php
<?php

declare(strict_types=1);

$add  = 1;
$nums = [1, 2, 3, 4, 5];

array_map(fn (int $num) => $num + $add, $nums);
```
Got error:
`Use of unassigned variable '$add'`
<img width="1435" alt="2023-09-13-18 03 43" src="https://github.com/DEVSENSE/phptools-docs/assets/123235746/708447ca-2933-4db2-b765-ddff47aa1803">

**Comment by jakubmisek** [comment]
Thank you, this is an issue in the pre-release version. Will be fixed.

**Comment by jakubmisek** [comment]
Update `1.38.13899` fixes the issue, thank you!

We have also improved rename refactoring of variables inside the arrow function and semantic highlighting.
