### ISSUE TITLE
Panda Antivirus detects devsense.php.ls.exe as suspicious

### ISSUE THREAD

**Issue by jesalba31** [DEVSENSE/phptools-docs#401]
Antivirus Panda detects `devsense.php.ls.exe` as suspicious and prevents it from being executed, this has started happening to me today using the Pre-Release version, specifically after update **1.38.13885 (September 12, 2023) (Pre-Release)**.

![imagen](https://github.com/DEVSENSE/phptools-docs/assets/13825510/d326f369-8efd-4fe6-9373-0afc37c8f108)

When I upgrade to the stable version I don't have this problem and the extension works for me with all its features.

**Comment by Miloslav** [comment]
Thank you for reporting this. We're going to contact the vendor of the antivirus to fix this false positive. I will inform here about the progress.

**Comment by Miloslav** [comment]
Interesting virustotal didn't flag this file with Panda. Do you have latest version of Panda? 

https://www.virustotal.com/gui/file/3b494cc1d176d3da92f4a8245c2a1918003b35d3c09f809a3254da1a48081174?nocache=1

On the other hand different antivirus did, going to contact them now.

**Comment by jesalba31** [comment]
I have **Panda Adaptive Defense 360**
**Version**: 8.0.21.0005
**Agent version**: 1.20.0.0000
**Year**: 2023

**Comment by occirol** [comment]
Acronis Cyber Protect also detects the file .vscode/extensions/devsense.phptools-vscode-1.39.13943-linux-x64/out/server/devsense.php.ls as malware :

Alert category     Antimalware protection
File name             devsense.php.ls
File path               .vscode/extensions/devsense.phptools-vscode-1.39.13943-linux-x64/out/server
MD5                      31d5cd8e18877e2d9098066f7b6f6d62
SHA1                     911f6be097510276c6614261228d376c48a8dc6e
SHA256                c61824fd5124a75af8809f952fe84aa5448e05e51ea7ac8118b8d7def84a3884
Threat name       Trojan.Linux.Generic.320099
Action                  Moved to quarantine

Even so it does not seems the case on VirusTotal:

https://www.virustotal.com/gui/file/c61824fd5124a75af8809f952fe84aa5448e05e51ea7ac8118b8d7def84a3884/detection

**Comment by Miloslav** [comment]
Thank you, We've contacted Acronis and waiting for their reply

**Comment by Miloslav** [comment]
Acronis says they are no longer able to replicate the false positive. Could you please retest with the latest update of the antivirus?

Thanks!

**Comment by jakubmisek** [comment]
Closing the issue.

**Please let us know if there will be any other false-positives in the future.**

Thanks!

**Comment by firecrauter** [comment]
> Closing the issue.
> 
> **Please let us know if there will be any other false-positives in the future.**
> 
> Thanks!
Avast premium antivirus, after update 1.44.14997 (February 14, 2024)
![image](https://github.com/DEVSENSE/phptools-docs/assets/7044466/d05aa240-7e6f-4443-afd2-52b62405dda6)

**Comment by Miloslav** [comment]
Thank you, we've submitted the false positive report on Avast page. Hopefully they will be fast to resolve this.
