### ISSUE TITLE
Option to assign links to files path

### ISSUE THREAD

**Issue by kanlukasz** [DEVSENSE/phptools-docs#402]
I would like to ask if you have any plans to add a function that will create links in php files.
I mean something like this:
![php-file-link](https://github.com/DEVSENSE/phptools-docs/assets/30685349/a0207e5b-4a1d-4b23-b946-f2ac44354e5b)

There are several extensions with these features, but they don't always work the best:
- https://marketplace.visualstudio.com/items?itemName=pwarchol.vscode-php-file-link
- https://marketplace.visualstudio.com/items?itemName=jack89ita.open-file-from-path

It would be great to have such a native tool in your PHP Tools.
What do you think?

**Comment by jakubmisek** [comment]
Thank you for the suggestion!

Yes, we need to add file names code completion and links for file names as well.

Working on it.

**Comment by jakubmisek** [comment]
The feature is available in the latest pre-release (`1.38.13932`), thank you for the suggestion!

**Comment by kanlukasz** [comment]
Thank you so much for taking care of it so quickly.
I've done some tests:

1. Some links are inactive, eg.:
![111](https://github.com/DEVSENSE/phptools-docs/assets/30685349/bac92be4-6239-4839-9130-2e9ebfd26f6d)

2. Links lead to wrong files (it seems that file search works with wildcard?)
![2222](https://github.com/DEVSENSE/phptools-docs/assets/30685349/e85ac4f8-87f8-4aa7-98d3-f1be84713e14)

3. The link looks like a split `<name>` . `<extension>`. Or is it a matter of settings in VsCode?
![image](https://github.com/DEVSENSE/phptools-docs/assets/30685349/0d3e305c-dc8e-4a62-a995-b5400a3ea12d)

4. If I may make a suggestion, it would be much more readable for duplicate files if it worked this way:
![3333](https://github.com/DEVSENSE/phptools-docs/assets/30685349/2204f23b-775f-4b57-9a6b-67f516d2acbc)


> we need to add file names code completion

Does this also work anymore?
I tried typing the file name in `require_once` and there is no suggestion/completion

**Comment by jakubmisek** [comment]
@kanlukasz you're right, currently, we resolve the paths only after `__DIR__`, `__FILE__` and `dirname()`. But it's a good idea to understand more "dynamic" contexts, like this one in WordPress.

**Comment by jakubmisek** [comment]
@kanlukasz 
3. and 4. are provided by VSCode itself.

But we'll handle more cases in WordPress more precisely, so it will be resolved exactly.

**Comment by kanlukasz** [comment]
@jakubmisek

1. Ok thanks

2. Is there a plan to fix this?

3. Ok thanks

4. What does VSCode provide here? I just suggested a different way of implementation here :) I mean, the add-ons I mentioned at the beginning of the thread solve the problem of duplicates in this way

**Comment by jakubmisek** [comment]
First, VSCode asks extensions (like ours) if it knows exactly.

Then it simply looks up all the files matching the name in your workspace.

2/ We need to handle WPINC (and other constants) to handle the file path better. Working on it. Currently we understand file paths after `__DIR__`, `include`, `dirname(...)`
