### ISSUE TITLE
Disable highlighted TODO

### ISSUE THREAD

**Issue by KoljaL** [DEVSENSE/phptools-docs#403]
Disable highlighted TODO

I use VSCode: `1.82.1.`  
and PHP Tools: `1.38.13918`

To get a little bit more organized, I will try to use the ToDo-tree extension.

But there is a small (anoying) issue:

<img width="357" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/55852574/1717a29c-9fbf-4a23-976e-5bcc47cdb06f">

The yellow background is not from the TD-tree extension, I isnt even vissible in the dev-tools.
But it dissapears, if the PHP-tools are disabled.

I searched in the issues and found this old one: #107 

Is there in the meanwhile another solution, to hide this yellow background?

**Comment by jakubmisek** [comment]
Thank you for the question.

Please use the setting `"php.highlight-todo.enable"` to disable the highlighting of TODO comments.
