### ISSUE TITLE
Go to Definition F12 Redirecting to wrong location after MacOS Sonoma Upgrade

### ISSUE THREAD

**Issue by popeofhockey** [DEVSENSE/phptools-docs#407]
After upgrading to MacOS Sonoma

Prior to upgrade clicking on the path would launch a new tab with then file
case 15:
include ‘etc/modules/businesses/visitors/comp/visitor_detail.php’;
break;

After the upgrade the relative path sends you here
etc/modules/business/registered/etc/modules/businesses/visitors/comp/visitor_detail.php

Gives an error file not found.

Any ideas?

DevSense PHP v1.39.13943
VS ARM Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

**Comment by popeofhockey** [comment]
The Error is coming from  Devsense PHP Tools for Visual Studio Code v1.39.13943
The folder is a share on a server 
**Before**
//servname/share/ etc/modules/businesses/visitors/comp/visitor_detail.php

**After**
//servname/share/ etc/modules/business/registered/etc/modules/businesses/visitors/comp/visitor_detail.php


Error seem that go to definition/F12  is not going back to the root of the share and is trying to go to s sub directory of a the file you are currently working on.

**Comment by jakubmisek** [comment]
thank you for reporting this,
should be fixed in `1.39.14027` and newer
