### ISSUE TITLE
Heredoc/nowdoc with BLADE identifier breaks syntax highlighting when content contains SVG

### ISSUE THREAD

**Issue by godismyjudge95** [DEVSENSE/phptools-docs#410]
The following code (with nowdoc) is valid but breaks syntax highlighting:
```php
return Blade::render(<<<'BLADE'
	@foreach ($items as $item)
	@endforeach
BLADE, $data);
```

It also doesn't work with the normal heredoc: `<<<BLADE`

Screenshot of it broken:
![image](https://github.com/DEVSENSE/phptools-docs/assets/3847288/242464c8-7bb4-431e-b6e4-01c1833b41c5)

Screenshot of it working:
![image](https://github.com/DEVSENSE/phptools-docs/assets/3847288/ea76bb7f-be72-4910-8413-49c7ff985fb3)

**Comment by jakubmisek** [comment]
I think, the correct syntax is using double quotes

```php
return Blade::render(<<<"BLADE"
	@foreach ($items as $item)
	@endforeach
BLADE, $data);
```

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/ff01bb9b-7e16-4e4a-b494-b1e958926307)

See https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc, Example #11

**Comment by jakubmisek** [comment]
Isn't it broken because of an incorrect indentation? I'm just guessing ..

Please note, syntax colorization is built-in VS Code itself, maybe there's an issue for it already? https://github.com/microsoft/vscode/issues

**Comment by godismyjudge95** [comment]
> I think, the correct syntax is using double quotes
> 
> ```
> return Blade::render(<<<"BLADE"
> 	@foreach ($items as $item)
> 	@endforeach
> BLADE, $data);
> ```
> 
> ![image](https://user-images.githubusercontent.com/842150/272082981-ff01bb9b-7e16-4e4a-b494-b1e958926307.png)
> 
> See [php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc), Example #11
> 
> When using single-quotes, the whole string is just a text, so $variables are not highlighted differently than the other text.

Single or double quotes shouldn't matter, but I did end up finding the issue.
I think it's an issue with the Blade parser and SVG's:

![image](https://github.com/DEVSENSE/phptools-docs/assets/3847288/9e073bdf-4120-4308-b41d-8f08b45e1035)

Here's the code for that:
```php
$view = Blade::render(<<<'BLADE'
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25M16.5 7.5V18a2.25 2.25 0 002.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 002.25 2.25h13.5M6 7.5h3v3H6v-3z" />
    </svg>
BLADE, compact('data'));

// No syntax highlighting here?
Blade::render('');
return $view;
```

**Comment by jakubmisek** [comment]
Thank you for the test case.

I'm afraid it's out of the scope of our extension, and it's actually a part of vscode itself.

May I ask you to open an issue on https://github.com/microsoft/vscode/issues instead

**Comment by godismyjudge95** [comment]
> Thank you for the test case.
> 
> I'm afraid it's out of the scope of our extension, and it's actually a part of vscode itself.
> 
> May I ask you to open an issue on [microsoft/vscode/issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) instead

Oh I see now, if I disable the PHP plugin the problem is still there.  Sorry for the trouble!

**Comment by jakubmisek** [comment]
Thank you for checking it so quickly, let's hope VSCode team fixes it soon.
