### ISSUE TITLE
Cannot click on Class in new expression

### ISSUE THREAD

**Issue by shyim** [DEVSENSE/phptools-docs#413]
I cannot click somehow on the class in the `new` statement. 
<img width="339" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/6224096/565e6e6e-82a8-4340-adba-4c53dbe52bbd">

It works for any method call afterwards but not on the class there.

**Comment by jakubmisek** [comment]
Thank you @shyim , I'll take a look at it!

**Comment by jakubmisek** [comment]
I just tested it, and it is supposed to work fine;

Ctrl+Click on a class in `new` statement should open a peek window with both the `class` header and the corresponding `__construct`.

- Do you have a tooltip over the class name?

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/b8db4d12-e243-4a10-8c0e-dd3b7ab92638)

- Is the class imported?
  `use PHPUnit\Event\TestData\TestDataCollection;`

- Isn't there another extension that might break this functionality?

**Comment by shyim** [comment]
Hover this not showing up. 
<img width="696" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/6224096/42723c9a-14bf-466f-8c05-e35113c78264">

auto completion works for that class.
It's not that class from PHPUnit, it's this one :) https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Test/TestDataCollection.php


Deactivated all other extensions still not showing up 🙈 
<img width="452" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/6224096/b9b89795-1621-440d-8b69-eac4bb60b391">

**Comment by jakubmisek** [comment]
I see!

I guess it's in a composer package? It is marked with `@internal` tag, which might be the problem - we may be "hiding" it from the navigation.

I'll try that, I guess it's a good idea to allow `Ctrl+Click` even with `@internal` tag.

**Comment by jakubmisek** [comment]
Yep - it's because it has `@internal` tag, so we don't "mess" IntelliSense with it.

We can add an option whether to list internal symbols in IntelliSense, and allow Ctrl+Click to it anyways.

**Comment by jakubmisek** [comment]
I installed `shopware/core`, version 6.5.6.0`, and navigation works:

![ctrl-click-works](https://github.com/DEVSENSE/phptools-docs/assets/842150/23184614-d735-44e9-9dc1-7c5f319c1a0d)

Not sure, why it's not working for you. 

**Isn't there anything unusual in the OUTPUT window PHP Language Server tab? Any error?**

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/97f30084-0ad2-468e-aec1-0f6930cdfbe1)

**Comment by jakubmisek** [comment]
Probably fixed in some recent update. We can get back to it with more information.
