### ISSUE TITLE
in code-server this ext install fall

### ISSUE THREAD

**Issue by AliceSync** [DEVSENSE/phptools-docs#415]
I am a developer using codeserver, and when I tried to install this extension, I found that it couldn't be installed, whether using the extension file installation or the marketplace installation. I was unable to succeed.

code-server: https://github.com/coder/code-server
ide-tps:  The 'devsense.phptools-vscode' extension is not available for the web in code-server
mysystem: Rocky Linux release 9
code-server: code-server: v4.17.1 version: 1.82.2

Actually, I can use any other extension, and I haven't encountered errors with other extensions. It's just when I try this extension that I encounter this error. I really want to try this extension and I'm willing to pay for it. Would you consider providing support for code-server? My company uses a unified environment, so I can't use a local IDE for work. Thank you very much.

The extensions I'm currently using are: PHP Intelephense, golang, and PHP DocBlocker. I'm a paid user of PHP Intelephense, but it has stopped updates, and my experience is not good. I'm trying to find an alternative.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

I will try to add support for it, it's definitely our plan to do so.

Have you tried installing `linux-x64` version manually? The `web` is only intended fo github,dev.

**Comment by jakubmisek** [comment]
confirmed, please install `linux-x64` that can be downloaded on https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode 

I'll try to fix this behavior, code-server should install `linux-x64`, not `web` version.

**Comment by jakubmisek** [comment]
Thank you for the confirmation, and for reporting the issue!

I've opened an issue on https://github.com/coder/code-server/issues/6489 to help other users in the future.
