### ISSUE TITLE
bug class name and function name are the same, display error tps

### ISSUE THREAD

**Issue by AliceSync** [DEVSENSE/phptools-docs#416]
code:
```php
<?php

class test{
   function test($test){

   }
}

(new test)->test('1');
```
ide display:
```
[{
	"resource": "test.php",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "PHP0423",
	"severity": 4,
	"message": "Missing argument $test for __construct()",
	"source": "PHP",
	"startLineNumber": 9,
	"startColumn": 6,
	"endLineNumber": 9,
	"endColumn": 10
}]
```
version: v1.40.14053
os: rocky 9
php: 8.1

**Comment by jakubmisek** [comment]
Thank you.

I think it treats the function `test()` as a PHP4-style constructor.

Let me check if it's still a thing.

**Comment by jakubmisek** [comment]
Fixed in the upcoming update, thank you!

**Comment by jakubmisek** [comment]
It's a minor fix, so it will be released only together with more fixes.

I guess within a week.

**Comment by jakubmisek** [comment]
Thank you, please let me know if there will be anything else 🚀
