### ISSUE TITLE
"Implement abstracts" code action / quick fix inserts functions with wrong indentation style

### ISSUE THREAD

**Issue by taisph** [DEVSENSE/phptools-docs#417]
VScode indentation style is set to "Spaces: 4" but when using the code action quick fix "Implement abstracts", the wrong indentation style is used when inserting the code.

![screenshot highlighting the different indentation styles used](https://github.com/DEVSENSE/phptools-docs/assets/814148/23cc7fac-adfa-49ca-a8a1-8269a4b55047)

**Comment by jakubmisek** [comment]
Thank you for pointing this out!

**Comment by jakubmisek** [comment]
Fixed, will be available in the upcoming pre-release/release.

Thank you.
