### ISSUE TITLE
Better `@mixin` support

### ISSUE THREAD

**Issue by 0x00A1FA** [DEVSENSE/phptools-docs#418]
Hi,

Of course, I'm using Laravel. I'd like to kindly request better `@mixin` support for traits.

Consider the following trait:

```php
/**
 * @mixin \App\Models\InspectionTest
 */
trait HasPointMeasurements
{
    public function pointMeasurementResults(): Attribute
    {
        return Attribute::get(
            fn () => $this->point_measurements // I'd like to get autocomplete and intellisense on `point_measurements` (which is a column)
        );
    }
}
```

The class `InspectionTest` looks like this:

```php

/**
 * @mixin IdeHelperInspectionTest
 */
class InspectionTest
{
// Class contents
}
```

So `InspectionTest` does indeed have column type defs via Laravel IDE Helper (https://github.com/barryvdh/laravel-ide-helper).

Right now, I'm not getting any intellisense via the `@mixin`.

Is this something you're planning?

By the way, do you know https://github.com/bmewburn?

Thanks!

**Comment by jakubmisek** [comment]
The test case is incomplete. Please attach `.zip` with all the necessary files.
