### ISSUE TITLE
I cannot disable the "Rename Refactoring" feature.

### ISSUE THREAD

**Issue by AntoineDeRouck** [DEVSENSE/phptools-docs#419]
Hello,

I would to like to be able to disable the "Rename Refactoring" feature.
I already have an extension installed that do the job for me (and for free).
But when I activate your extension, it takes the priority on the other one that actually rename.
It means that instead of having the ability to rename my methods, classes, variables I have a popup telling me that I have to update to premium.
The only solution to this for the moment is to disable your extension.
If you provide the ability to disable your "Rename Refactoring" feature, I could be using both extensions flawlessly.

Thanks

**Comment by jakubmisek** [comment]
@AntoineDeRouck Thank you for the feedback.

I see, it should not behave like that.

I'll see what we can do.

**Comment by jakubmisek** [comment]
In the latest update (1.40) we have enabled rename refactoring.

**Comment by AntoineDeRouck** [comment]
Thank you @jakubmisek
