### ISSUE TITLE
Formatted code affects user experience

### ISSUE THREAD

**Issue by AliceSync** [DEVSENSE/phptools-docs#422]
Before formatting code：
```php
$test_1    = '1';      # ...aaa
$test_2    = '2';      # qqqqqqqqqqqqqq
$test_999  = '999aa';  # vvvvvvvvv
$test_99   = '999aaa'; # sssssss
$test_9999 = '99';     # 11111111
$test333   = '';       # 333333
```
After formatting the code：
```php
$test_1 = '1'; # ...aaa
$test_2 = '2'; # qqqqqqqqqqqqqq
$test_999 = '999aa'; # vvvvvvvvv
$test_99 = '999aaa'; # sssssss
$test_9999 = '99'; # 11111111
$test333 = ''; # 333333
```

In a large number of files with frequent manual alignments, formatting can lead to the failure of manual alignments, resulting in significant changes and unacceptable chaos.

**Comment by Miloslav** [comment]
Hello,

Thanks for submitting the issue. Now, the formatter just outputs the code as it's defined in the settings. But it actually makes sense, as you've mentioned to by default respect user-defined spacing in certain situations - I'm putting it on to-do list.

For the cases you've mentioned:

1.) 
```php
$test_1    = '1';      # ...aaa
$test_2    = '2';      # qqqqqqqqqqqqqq
$test_999  = '999aa';  # vvvvvvvvv
$test_99   = '999aaa'; # sssssss
$test_9999 = '99';     # 11111111
$test333   = '';       # 333333
```
Settings:
```json
"php.format.rules.arrayInitializersAlignKeyValuePairs" : "true"
```

But thanks for pointing out the comments

2.)
```php
if($a == 1) return true;
```
Settings:
```json
"php.format.rules.keepControlStatementsOnOneLine" : "true"
```

3.)
```php
match ('12345') {
    '111'         => '123',
    '2222'        => '123',
    '33333'       => '123',
    '44444441111' => '123',
};
```
We do not have this one yet. But it shouldn't be difficult to add - I'm adding it on to-do list and get back to you asap.

**Comment by Miloslav** [comment]
Hello,

Thanks again for pointing these issues out. We've addressed all of those in the upcoming pre-release. Once it's out (estimated during today), please test it out and let us know if everything works as it should.

1.) Comments after some code can be aligned in any way the user wants.
3.) We've added `php.format.rules.alignMatchArmBodies` option, which will align the bodies (results) within `match` expressions.

Thank you!

**Comment by Miloslav** [comment]
Thank you, then I'm going to close this one. Please comment on the issue that is still a problem. Thank you!
