### ISSUE TITLE
Bug: JavaScript code written in .php files cannot be folded correctly

### ISSUE THREAD

**Issue by AliceSync** [DEVSENSE/phptools-docs#423]
test code:
```html
<script>
    function a() {

    }
    function b() {

    }
    function c() {

    }
</script>
```

correct： in .html display:
```html
<script>...
</script>
```

In the past, I didn't encounter this issue with other extensions, and I think it's highly likely that the extension is overriding vscode's built-in HTML parsing. This issue needs to be fixed urgently, as it causes a lot of content inside script tags to not fold properly. In cases where there is a significant amount of JavaScript code, it can make development inconvenient.

**Comment by Miloslav** [comment]
Thank you for pointing this out. I'm afraid we've never supported this and we will have to do it in the next updates.

ref. https://community.devsense.com/d/1745-folding-in-within-the-script-is-disabled

**Comment by jakubmisek** [comment]
It seems there has been an update some time ago and nested languages have code folding now;

<img width="268" alt="image" src="https://github.com/user-attachments/assets/293af106-7951-4a42-8c5f-d1515ab7107a">
