### ISSUE TITLE
Laravel Blade false errors

### ISSUE THREAD

**Issue by 0x00A1FA** [DEVSENSE/phptools-docs#424]
Hi,

I'm seeing these errors in some of my Blade files:

Official Laravel Vite Blade directive:

![image](https://github.com/DEVSENSE/phptools-docs/assets/110613761/2f95e14e-ee51-4541-bded-7c252508ea86)

Echoing an indexed array of letters (`['A', 'B', …, 'Z'][number]`):

![image](https://github.com/DEVSENSE/phptools-docs/assets/110613761/7b60d527-954d-4ce0-b180-23614539cee6)

Can we figure these out?

Thanks!

**Comment by str** [comment]
I've just got other false error with v1.44.14922

![image](https://github.com/DEVSENSE/phptools-docs/assets/123817/5446ce9a-4179-4e36-af78-93416c235959)

**Comment by jakubmisek** [comment]
fixed in `1.44.14925`!

**Comment by jakubmisek** [comment]
please let us know if there would be anything else - we are trying to translate blade tags to actual functions to get precise parameters help;

**Comment by str** [comment]
Now, passing params to @extend, shows errors:
![image](https://github.com/DEVSENSE/phptools-docs/assets/123817/f07bf20f-4f99-43f2-b8df-b64d898119ac)

**Comment by jakubmisek** [comment]
Thanks! added to our tests and preparing pre-release with fixes.
