### ISSUE TITLE
Import class (add use) does not work in comments

### ISSUE THREAD

**Issue by Morgy93** [DEVSENSE/phptools-docs#428]
Hello,

the action to set a using works in the code:

![image](https://github.com/DEVSENSE/phptools-docs/assets/7961978/cf3cf345-10d0-490c-b0e9-017aa3c7a73d)

But does not in comments:

![image](https://github.com/DEVSENSE/phptools-docs/assets/7961978/649d3f1e-8011-4ba8-972b-47889de395a5)

Any help?

**Comment by jakubmisek** [comment]
@Morgy93 Thank you for reporting the issue.

I'll take a look on that.

**Comment by jakubmisek** [comment]
Implemented - will be available in the upcoming pre-release/release.

Thank you for the suggestion.
