### ISSUE TITLE
typehint wrong object in foreach

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#43]
![grafik](https://user-images.githubusercontent.com/22061464/63572437-2db90a80-c583-11e9-9a04-ce091a2e1784.png)

**Comment by jakubmisek** [comment]
I'm getting the correct results on this. What tooltip do you have on `$user`?
![image](https://user-images.githubusercontent.com/842150/63643194-81367000-c6cb-11e9-829e-586ec5038484.png)

**Comment by Mordef** [comment]
The tooltip on $user is fine:
![grafik](https://user-images.githubusercontent.com/22061464/63998420-58660e80-cb01-11e9-8a20-c37d1aacb936.png)

But every getter tells me is a non-object:
![grafik](https://user-images.githubusercontent.com/22061464/63998474-7895cd80-cb01-11e9-91bc-892fc9368edf.png)

**Comment by jakubmisek** [comment]
Seems the tooltip on `$user` is not correct - it shouldn't be `User[]` but `User`. Having `$user` typed as array causes the warning about non-object.

What is the tooltip on `$users` (with 's') ?

thank you

**Comment by Mordef** [comment]
![grafik](https://user-images.githubusercontent.com/22061464/64155939-1a842580-ce34-11e9-9d42-669f93a994fd.png)

**Comment by jakubmisek** [comment]
Thank you.

We cannot replicate the issue, maybe there is something else in the function causing the type analysis to behave incorrectly.

May I ask to send the entire function code? Only occurrences of `$user` and `$users` are important. Is it a part of a PHP framework (Laravel?)

**Comment by Mordef** [comment]
i can send you the files via mail.
It's not Laravel, it's a Smarty Project

**Comment by jakubmisek** [comment]
@Mordef yes please - info@devsense.com, we'll try to fix this within the next update

**Comment by Mordef** [comment]
While i was try to cleanup small version i found MY fault.
After the foreach comes this:
```php
/** @var \Model\User[] */  
$user = new \Model\User();
```
So they 
Have to delete tht typehint
So there is no bug!

Sorry and thank you

**Comment by jakubmisek** [comment]
Thank you for letting me know and for taking the time to find out! that makes sense. We're glad for any feedback, even if it's an issue somewhere else.

Please let us know if there would anything else.
