### ISSUE TITLE
VSCode rename refactoring on functions also renames matching string literals

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#435]
I discovered the painful way that using the rename refactoring feature on functions will also rename matching string literals. This is quite dangerous as strings can contain all kinds of things and there is no reason to assume that a matching string literal is intended to refer to code. Modern php provides enough ways to refer to the code without using strings literals (such as the [first class callable syntax](https://www.php.net/manual/en/functions.first_class_callable_syntax.php) and getting a fully qualified class name with `ClassName::class`) that I very rarely have code inside string literals anymore, not even function names, class names, or method names. I can see how others could find this behavior more useful as they may still have function or class names inside of strings and need them to be renamed together.

I think the way this should work is, if it finds matching strings, it should show a dialog of everything it will rename, like it does when you rename a class and it offers to rename the file, with the riskier boxes unchecked by default. It would also be nice if all the unchecked/risky renames were always at the very top of the list so we can easily review them and decide if we want to rename them or not. It would also be helpful to identify and offer to rename parts of code comments with matching text.

**Comment by jakubmisek** [comment]
Thank you for reporting that.

There must have been some change in VSCode, since we used to open a preview panel in case a string literal is about to change.

As a workaround for now, I'd recommend renaming using `Shift+Enter` to review changes:

![vsc-rename-preview](https://github.com/DEVSENSE/phptools-docs/assets/842150/cc9ea3e0-e1c9-4f05-bdf5-66347bf9f6e2)

Will be fixed - preview panel will be opened automatically in case there is a potentially dangerous refactoring.

**Comment by still-dreaming-1** [comment]
I tried using the workaround. It does work, but it leaves the potentially dangerous refactorings already checked, dispersed throughout all the other changes. It would be very helpful if the more dangerous ones were at the top of the list and unchecked by default. To go through them all one by one can be tough if there are a lot of changes.

**Comment by jakubmisek** [comment]
It seems like a bug in VSCode, because we're properly identifying dangerous replacements and telling VSCode to NOT replace it by default :-) ... I'm digging into it. It used to work ok.

**Comment by jakubmisek** [comment]
found a bug, preparing pre-release with the fix!

thank you for reporting that

**Comment by jakubmisek** [comment]
the latest pre-release fixes that!

thank you @still-dreaming-1

**Comment by still-dreaming-1** [comment]
Working well the pre-release. Thank you.

**Comment by jakubmisek** [comment]
Thank you for the confirmation.
