### ISSUE TITLE
[VSCode] [Test Explorer] Don't show test as failed when failOnRisky and failOnWarning are set to false

### ISSUE THREAD

**Issue by jlecordier** [DEVSENSE/phptools-docs#438]
Hi all,

I am writing the issue here as I am unable to write it on the DevSense support site.

In my `phpunit.xml` config file, both `failOnRisky` and `failOnWarning` are set to `false`, yet the test explorer is still showing the tests as failed when something as silly as `echo` is used in an otherwise fully working code (I am working on a legacy code).

Could you please handle those parameters or add an option in the extension ?

Thanks

**Comment by jlecordier** [comment]
Nevermind, my big ass brain missed the `beStrictAboutOutputDuringTests="true"` part in my `phpunit.xml` config file...

Turning this to `false` solved the issue!

**Comment by jakubmisek** [comment]
Thank you for the update @jlecordier. I didn't even dig into it yet.

I'm glad it got solved.
