### ISSUE TITLE
Packages cache for git repository (dev-[branch name] as version) did not updated when reference in composer.lock updated

### ISSUE THREAD

**Issue by hsnfirdaus** [DEVSENSE/phptools-docs#439]
For example i added git repository in my composer.json:
```json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/vendorname/reponame.git"
    }
],
```
Then i added branch name (`development`) as version:
```
"require": {
    "vendorname/reponame": "dev-development"
}
```
The composer.lock will save git reference:
```json
{
    "name": "vendorname/reponame",
    "version": "dev-development",
    "source": {
        "type": "git",
        "url": "https://github.com/vendorname/reponame.git",
        "reference": "9a64a9665d3cb02f5f55f6c460070821ec4011fd"
    },
   // Other package data
}
```
The devsense php vscode extension will write cache as:
```
~/.local/share/DEVSENSE/packages-cache/vendorname/reponame.dev-development.json.gz
```

Then, when the remote branch (`development`) updated, running `composer upgrade` will change the reference hash:
```json
"source": {
    "type": "git",
    "url": "https://github.com/vendorname/reponame.git",
    "reference": "044c9f52bb5756758f1fd4bf69c9959b78884f3c"
}
```

But, the cache will not updated right, because the version didn't change, even the git reference hash changed? So it will trigger warning for class/function that changed, the warning gone if i delete `~/.local/share/DEVSENSE/packages-cache/vendorname/reponame.dev-development.json.gz` because it will force create new package cache.

I think when caching git repository/vcs should also added the git reference hash, so when package.lock reference hash changed, the cache also updated. Or even it shouldn't cache at all when using "dev-xxx" version name?

**Comment by jakubmisek** [comment]
Thank you for pointing this out!

I'll try to fix this in the next update.

As a workaround, please run VSCode Command `Clear /vendor/ cache.`

**Comment by jakubmisek** [comment]
the latest pre-release fixes that, thank you!
