### ISSUE TITLE
WSL/Windows Lizenz

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#44]
First time i start with WSL, i need to reenter my key.
Now i need a Project on Windows, and now PHPTools wants again a Lizenz.
Its same VS-Code, only sometimes i use WSL

![grafik](https://user-images.githubusercontent.com/22061464/64114128-81e69a80-cd8c-11e9-8047-cfb508a80f15.png)

**Comment by jakubmisek** [comment]
Currently the activation is bound to the machine name + the user name (its hash code). Changing the underlaying OS may invalidate the activation.

We'll allow the activation on two (virtual) systems in a future update.

**Comment by jakubmisek** [comment]
Just released the update - `1.0.3936` which should allow you to activate your license under a different user names. So if the user name changes (you switch from Win to WSL), you can activate with your license key and if you switch back (from WSL to Win), your activation on WSL won't be lost and it should work the next time.

**Comment by Mordef** [comment]
Looks working, but now i got this:
![grafik](https://user-images.githubusercontent.com/22061464/64403840-58728b00-d07a-11e9-979b-d04481b21c70.png)
Live Share will not work
After deactivate PHP Tools the Live Share Extension is working fine.

On both systems, WSL and Win

**Comment by jakubmisek** [comment]
thank you, closing this issue and creating a new one for Live Share. Seems more likely like an issue in Live Share since we don't extend or modify anything related.
