### ISSUE TITLE
"php.executable" with dockerized container.

### ISSUE THREAD

**Issue by tyler36** [DEVSENSE/phptools-docs#440]
## Problem
I am having a problem running PHP Tools testing.

I have a Drupal website that is served via DDEV (docker containers), and connects to a dockerized database.
I have a custom alias called `dphp` that runs the PHP in the DDEV container.

```shell
command="ddev . php "$@""
$command
```

My tests passes when I run them
- inside the container via SSH (`phpunit --filter ActionDemoTest`)
- on my host PC via the alias (`dphp vendor/bin/phpunit --filter ActionDemoTest`)

I'm trying to follow the documentation on https://docs.devsense.com/en/vscode/php-version#choosing-php-version

```json
  "php.executables": {
    "php-dev": "~/bin/dphp",
    "7.3": "/usr/bin/php7.3"
    "8.2": "/usr/bin/php8.2",
```

When I set `"php.version": "myphp"`, I expect my tests to pass but I get
```shell
"php" -d display_errors=on /home/user13/code/vendor/bin/phpunit -c /home/user13/code/phpunit.xml --teamcity --colors=never --filter ^(ActionDemoUppercaseUsernameTest::.+(\s.*)?)$
```

When I set `"php.version": "7.3"`, I get
```shell
"/usr/bin/php7.3" -d display_errors=on /home/user13/code/vendor/bin/phpunit -c /home/user13/code/phpunit.xml --teamcity --colors=never --filter ^(ActionDemoUppercaseUsernameTest::.+(\s.*)?)$
```

VSCode: 1.84.2
PHP Tools: 1.41.14263
OS: WSL2 (Ubuntu) on Win11

**Comment by Morgy93** [comment]
Hello tyler36 😁 
I did not see your issue before I opened a duplicate to this. https://github.com/DEVSENSE/phptools-docs/issues/443

I tried both:
```
"php.executables": {
    "ddev": "ddev php"
},
"php.executablePath": "ddev php"
```
But like you already mentioned it stays at:
```
Running tests ...
"php" -d ....` 
```

Any help?

**Comment by tyler36** [comment]
Closing.

#443 is a duplicate but issue seems to be progressing there.
