### ISSUE TITLE
Support for Psalm type pure-callable in docblock

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#441]
I'm using VSCode. Psalm has a type called [`pure-callable`](https://psalm.dev/docs/annotating_code/type_syntax/callable_types/#pure-callables). It is the same as callable, but is guaranteed to be pure. When I have a function where the parameter type is `callable` in the php code, and also more specifically `pure-callable` in the docblock `@param`, I get "Use of unknown class: 'pure-callable'" from php tools. I don't need php tools to know/enforce anything about pure vs impure, it just needs to recognize the type as being basically the same as `callable`.

**Comment by jakubmisek** [comment]
Thank you for the suggestion.

Will be added.

**Comment by jakubmisek** [comment]
implemented in the next pre-release, thanks!

**Comment by still-dreaming-1** [comment]
It's working better. However, they are now considered to be a Closure. In php, callable and Closure are different types. It's not a Psalm thing, callable and Closure are both recognized php types and valid as php type hints. It's less of a problem this way than being an unrecognized type, but if I was to hover over a variable or something for the purpose of seeing the type, and it popped up with Closure when it is really a callable, it would be a bit misleading.

**Comment by jakubmisek** [comment]
Good point!

**Comment by jakubmisek** [comment]
Fixed in the next pre-release/release.

`callable` will be treated and shown in tooltips as `callable`. One known limitation. Internally, we don't remember the parameters and return type of `callable`. We do it only for `Closure`, so the following will lose some information:

- `callable(int, string): void` -> `callable` # we'll ignore the type information
- `Closure(int, string): void` -> `Closure(int, string): void`

**Comment by still-dreaming-1** [comment]
> One known limitation. Internally, we don't remember the parameters and return type of `callable`. We do it only for `Closure`

Interesting. I discovered that `callable` is also not a fully supported type in php either. You can't declare a property with `callable` as the type, only `Closure`.
