### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#442]
I have another question but lets solve this one first
Why i get 2 doc version of this method? (my method)
![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/eb1fde67-1e7d-45ac-8b0c-5a2fc0356881)
Why i disable your extension, none hint appears....

**Comment by jakubmisek** [comment]
This is caused by `_ide_helper.php` - it re-defines all the methods with slightly different signatures.

We can "fix" this by ignoring methods from _ide_helper if we know it better.
