### ISSUE TITLE
PHPUnit change run command

### ISSUE THREAD

**Issue by Morgy93** [DEVSENSE/phptools-docs#443]
Hello,

the PHPUnit Test View runs tests like:
```
Running tests ...
> "php" -d display_errors=on /path/to/project/bin/phpunit -c /path/to/project/phpunit.xml.dist --teamcity --colors=never --filter ^(Tests\\SomeTest::testSomething(\s.*)?)$
```

But since I use Docker and specifically https://github.com/ddev/ddev I need to exchange the `php` with `ddev php` or `ddev exec php`
I did not find a setting for this.

The next issue will be the location of phpunit. The `phpunit.phpunit` setting only changes the end of the path. But I want to replace it to use it globally.
Currently it is like `/path-to-project-that-is-always-added/path-to-phpunit-that-is-configurable`.
In my case to run phpunit I could just execute `ddev exec phpunit` (it runs global available phpunit in the container)

Any help?

**Comment by jakubmisek** [comment]
thank you for the suggestions, good point.

I'll make the necessary changes, and let you know once it's available in the pre-release build.

**Comment by jakubmisek** [comment]
The latest pre-release allows the following settings:

```json
"php.executable": "ddev exec php",
"phpunit.phpunit": "\"phpunit\""
```

but it will run tests using the command `ddev exec php "phpunit" -c ...` which is still not correct right?

**Comment by tyler36** [comment]
Tried testing PHP `v1.41.14309` but it says `"php.executable": "ddev exec php",` is an unknown configuration.

The following is an example of a running a specific test with DDEV:

```shell
ddev exec php ./vendor/bin/phpunit --filter ActionDemoUppercaseUsernameTest::testActionIsDiscoverable
```

DDEV executates commands from the project folder `/var/ww/html` so we would want to generate the following command:

```shell
ddev exec php -d display_errors=on /var/www/html/vendor/bin/phpunit -c /var/www/html/phpunit.xml --teamcity --colors=never --filter ^(ActionDemoUppercaseUsernameTest::testActionIsDiscoverable(\s.*)?)$
```

**Comment by jakubmisek** [comment]
Thank you for the testing and the feedback,

I'll prepare a few more fixes, test some configurations, and prepare a new pre-release.

**Comment by tyler36** [comment]
Just noticed a new pre-release version so I thought I would give it a try:

PHP `v1.41.14386`

I updated my settings file as such:

```json
  "phpunit.php": "ddev exec php",
  "phpunit.phpunit": "/var/www/html/vendor/bin/phpunit",
```

And tried to run a test but it failed.

```
Running tests ...
> ddev exec php /var/www/html/vendor/bin/phpunit -c "/path-to-project-on-the-host/phpunit.xml" --teamcity --colors=never --filter ^(ActionDemoUppercaseUsernameTest::testActionIsDiscoverable(\s.*)?)$
Process #10476 closed with exit code 2.
```

The PHPunit config file is invalid because it points to a file on the host which is not accessible from the container.

Ideally, PHPunit settings file should be configurable too. 
Although I've never had to specify the `-c` switch because I keep the config in the project root, I understand this may not be everyone's setup. So maybe have it optional? I'm not sure how PHPunit searchs for the file if not present.

Thank you for continuing to conside this and working towards a solution.

**Comment by jakubmisek** [comment]
I see, yep we're just trying some approaches here ... Maybe we should make the test command completely custom with variables.

I think the following would work:

**Proposal:**

```json
"phpunit.command": "ddev exec phpunit -c ${phpunitxml} ${phpunitargs}",
```

`phpunit.command` would have variables which you can use anywhere in the command, and fully customize it.

- `${cwd}`: workspace root path, local. The command will be executed in this directory.
- `${phpunitxml}`: path to the `phpunit.xml` relative to the workspace root.
- `${phpunitargs}`: constructed PHPUnit arguments. (we need --teamcity and --filter to function properly)
- `${phpargs}`: optional arguments to PHP which we use to ensure PHP runs and debugs correctly.

**Comment by tyler36** [comment]
Thank you @jakubmisek for the update. 
I understand its still a work-in-progress. 

> `phpunit.command` would have variables which you can use anywhere in the command, and fully customize it.

I think this approach offers the most flexiable ability and would resolve this issue.
I'm happy to test if you need.

**Comment by jakubmisek** [comment]
@tyler36 it's out as a pre-release, please feel free to try it

**Comment by Morgy93** [comment]
v1.41.14390

`"phpunit.command": "ddev exec phpunit ${phpunitargs}",`

The output shows `Process #19149 closed with exit code 2.` only, but running it manually:

```
zsh: no matches found: ^(WhateverTest::testWhatever(s.*)?)$
```

So, I think the "execution" part is fixed now, but there seems to be some issue using the filters in my case. 😅

It "works" if I remove the `${phpunitargs}` but it runs all the tests of course. I'll open another issue for the filter issue.

**Comment by Morgy93** [comment]
I just saw that the `-c ${phpunitxml}` is added using `${phpunitargs}` - is that correct?

It did not expect that since the example is like: `ddev exec phpunit -c ${phpunitxml} ${phpunitargs}` which outputs:

```
ddev exec phpunit -c /path-on-the-host/phpunit.xml.dist -c "/path-on-the-host/phpunit.xml.dist" .... and so on
```

**Comment by jakubmisek** [comment]
@Morgy93 thanks! you're right `-c ${phpunitxml}` should not be there, and (I guess) if you want to use a different phpunit.xml, you can put it as a last argument?

**Comment by tyler36** [comment]
As @Morgy93  said, the config file seems to be part of `${phpunitargs}` so it's confusing. 

I can't get the tests to run. 
```shell
ddev exec phpunit -c "/path-on-host/phpunit.xml" --teamcity --colors=never --filter "/^(Drupal\\Tests\\modern_demos\\Functional\\ModernDemosTest::.+(\s.*)?)$/" -c /var/www/html/phpunit.xml 
Process #4915 closed with exit code 127.
```
I tried various combinations but always got a `127` error.

```json
  "phpunit.command": "ddev exec phpunit ${phpunitargs}",
  "phpunit.command": "ddev exec phpunit -c /var/www/html/phpunit.xml ${phpunitargs}",
  "phpunit.command": "ddev exec phpunit ${phpunitargs} -c /var/www/html/phpunit.xml",
```

My main issue at the moment is test discovery.
After updating to `1.42.14396`, it only shows 1 test in the testing panel but the output panel shows:
```
Discovered PHPUnit configurations: file:///{workspace}/phpunit.xml
96 test(s) found.
```

I tried downgrading to `1.41.14390` and the testing panel again lists all my tests.
When I update, only a single test is displayed. If I click "Test refresh", it discovers 96 tests, but won't display them. 🤷

**Comment by jakubmisek** [comment]
@tyler36  I guess this happens only in ddev? :-)

**Comment by jakubmisek** [comment]
The custom command "phpunit" (executed using `ddev exec phpunit`) - what does it do?

**Comment by jakubmisek** [comment]
I have installed a few containers on ddev, but I don't have the `phpunit` ddev command; 

So far, it works for me with `ddev php ${phpargs} ./vendor/bin/phpunit ${phpunitargs}` (update `1.42.14401`)

**Comment by Morgy93** [comment]
> I have installed a few containers on ddev, but I don't have the `phpunit` ddev command;
> 
> So far, it works for me with `ddev php ${phpargs} ./vendor/bin/phpunit ${phpunitargs}` (update `1.42.14401` - [#455 (comment)](https://github.com/DEVSENSE/phptools-docs/issues/455#issuecomment-1842975643))

The execution works using `v1.42.14401` via `ddev php ${phpargs} ./vendor/bin/phpunit ${phpunitargs}`. 🙌 

Sadly, it says `No tests executed!` probably because of #455 - will continue there.

**Comment by tyler36** [comment]
Testing with latest version `v1.42.14428`

```json
  "phpunit.command": "ddev php ${phpargs} ./vendor/bin/phpunit ${phpunitargs}",
```

```
> ddev php -d display_errors=on ./vendor/bin/phpunit -c phpunit.xml --teamcity --colors=never --filter "(^(Drupal.Tests.modern_demos.Functional.ModernDemosTest::.+(\s.*)?)$)" 
```

If I run a similar command on my host I get: 

```shell
$ ddev php -d display_errors=on ./vendor/bin/phpunit -c phpunit.xml --teamcity --colors=never
PHP 8.1.23 (cli) (built: Oct  6 2023 10:11:51) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.23, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.23, Copyright (c), by Zend Technologies
```

> The custom command "phpunit" (executed using ddev exec phpunit) - what does it do?

I don't have a custom command in this project, but I do have `./vendor/bin` on my path in the container.

`v1.42.14428` is still only showing 1 test in the UI panel but the output pannel says it's found 105 tests.

**Comment by jakubmisek** [comment]
@tyler36 The UI has it's own way of resolving tests in your project;

May I ask for an example of a test class/method + the corresponding phpunit.xml? We might miss something.

**Comment by jakubmisek** [comment]
Closing the issue, as it has been implemented (see `"phpunit.command"` setting).

@tyler36 please create an issue for tests not being discovered. A sample of such test cases would be helpful. Thank you!
