### ISSUE TITLE
Implement abstracts action doesn't work

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#446]
<img width="1021" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/4f6cbc5e-22eb-416d-b4c7-22b2054219cc">

<img width="959" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/e7d43d45-4d2e-4be8-85a1-3b381938306d">

<img width="748" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/5d4b4bf1-e02a-4bb2-91e0-ea85d74d9fbb">

## Expected behaviour

When clicked on "Quick fix..." and "Implement abstracts" (first picture) should create the static function from interface (third picture).

Currently it does nothing (getting no logs on the Output - PHP Language Server tab)

**Comment by jakubmisek** [comment]
fixed in the upcoming update, thanks!
