### ISSUE TITLE
Renaming constructor property promotion parameter does not rename matching @param name

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#450]
When using constructor property promotion, the most natural place to add docblock information about both the parameter and the property is to do it as a normal constructor docblock and use the `@param` like you would if it were a normal parameter. I do this a lot, especially when I want to add Psalm annotations. It works well because Psalm does understand that these `@param` annotations refer both the parameter and the property.

I discovered that when using the rename refactor feature in VSCode for a parameter like this, it does not rename the parameter name in the docblock like it normally would if it were not a constructor property promotion parameter. It seemed like I was having a lot of intermittent problems when renaming parameters and properties, but now between these last 3 issues I filed here, I finally have figured out exactly what is happening in reproducible ways.

Here is some example code.

```
<?php

declare(strict_types=1);

namespace MyNamespace;

class MyClass
{
    /**
     * @param list<int> $numList
     */
    public function __construct(private array $numList) {
    }
}
```

**Comment by jakubmisek** [comment]
Good point, fixing `@param` above constructor properties.

Is there anything else we can improve for constructor properties?

**Comment by still-dreaming-1** [comment]
> Good point, fixing `@param` above constructor properties.
> 
> Is there anything else we can improve for constructor properties?

https://github.com/DEVSENSE/phptools-docs/issues/448

I thought I had posted one more issue, but now I'm not sure. I will edit this and add it here if I find it.

**Comment by cognitus** [comment]
@jakubmisek 
it should be acepted this too
```php
class MyClass 
{
    public function __construct(
        /** @var string */
        public $a,
    ) {}
}
```
source: https://stitcher.io/blog/constructor-promotion-in-php-8

**Comment by jakubmisek** [comment]
@cognitus may I ask for more details? the property `$a` should be renamed correctly:

![vsc-rename](https://github.com/DEVSENSE/phptools-docs/assets/842150/c832ad28-96ea-43da-b8b3-c46c8c2aca5d)

**Comment by cognitus** [comment]
@jakubmisek my bad, I had to clean vscode cache and now works

**Comment by jakubmisek** [comment]
@cognitus thanks for the update, is it something we can fix?

**Comment by cognitus** [comment]
I don't think so, the other plugins could was interfere, now is impossible reproduce
btw thanks, @jakubmisek
