### ISSUE TITLE
Add support for newrelic PHP extension

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#452]
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/20c37f22-d22c-47b3-a036-c43c2c615f10)

**Comment by php4fan** [comment]
Has this update not been released yet?

**Comment by jakubmisek** [comment]
The update with `newrelic` stubs has been already released.

You have to enable the stub using either:
- `php.stubs` setting
- or `Workspace Stubs` command:
  ![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/4ab25f6d-da98-4561-a474-e9141c37b5ae)
  ![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/eae5d8f1-d807-4053-a038-c6afc4e900b6)
- or specify `"ext-newrelic"` as a requirement in your `composer.json`

**Comment by php4fan** [comment]
> or specify "ext-newrelic" as a requirement in your composer.json

I did that, restarted, ran "composer update" (because without that it was still showing the errors).
After that, the errors briefly disappeared, for like a couple of minutes. I thought it was working.
But then the errors reappeared.
I restarted again, and the errors keep showing.

**Comment by php4fan** [comment]
Enabling the stub doesn't work either:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/a0f1cc0c-d0cd-4729-a707-9fea273e1f62)

**Comment by php4fan** [comment]
Oh I see, it used to be "call to unknown function", now it's **"missing arguments 2..5"**.

But those arguments are optional

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/32610b6c-d5b0-44c3-8e75-d89a68d62e46)

**Comment by jakubmisek** [comment]
Thanks for pointing this out.

It seems we just didn't have this information up-to-date - Optional arguments will be fixed.
