### ISSUE TITLE
PHPUnit filter not working

### ISSUE THREAD

**Issue by Morgy93** [DEVSENSE/phptools-docs#455]
Hello,

a follow-up from https://github.com/DEVSENSE/phptools-docs/issues/443#issuecomment-1840766260

`v1.41.14390`

Output: `--filter ^(Some\\ClassTest::testMethod(\s.*)?)$ `

It works using `--filter testMethod` but unsure what is the correct regex for the whole string would be.

The teamcity output is like: `\Tests\Some\ClassTest::testMethod`

**Comment by jakubmisek** [comment]
Thank you,

I might need more information. Locally the `--filter` seems to work as expected. (The regex was fine-tuned to handle data sets, and match the test method precisely ...)

With only `--filter testMethod`, we might run more tests that we want to :)

**Comment by Morgy93** [comment]
Yeah sure, that `--filter testMethod` was just a test to make sure that the issue is related to the regex and not some other setup. 

Feel free to ask for any information and I'd love to answer to get this fixed asap.

**Comment by jakubmisek** [comment]
Thank you @Morgy93, maybe it should be put into quotes or something ... I'll think about it

**Comment by jakubmisek** [comment]
Thanks. I think it would not work with datasets. PHPUnit appends something like `(dataset #1)` at the end of the test name. So we added `(\s.*)?` regex.

**Comment by jakubmisek** [comment]
@Morgy93 May I ask to try the following:

```
--filter "/^(Some\\ClassTest::testMethod(\s.*)?)$/"
```

**Comment by jakubmisek** [comment]
We just released `1.42` which fixes a few issues with `--filter` reported across various systems and PHPUnit versions.

It should fix this issues as well.

**Comment by Morgy93** [comment]
> We just released `1.42` which fixes a few issues with `--filter` reported across various systems and PHPUnit versions.
> 
> It should fix this issue as well.

Does not work, it throws:

```
bash: -c: line 1: syntax error near unexpected token `('
bash: -c: line 1: `set -eu && ( phpunit -c phpunit.xml.dist --teamcity --colors=never --filter /^(Some\ClassTest::.+(\s.*)?)$/)'
Failed to execute command phpunit -c phpunit.xml.dist --teamcity --colors=never --filter /^(Some\ClassTest::.+(\s.*)?)$/: exit status 2
```

**Comment by jakubmisek** [comment]
Thank you;

- The filter value should be enclosed in quotes: `--filter "/^(Some\\ClassTest::testMethod(\s.*)?)$/"`, I guess they get lost somewhere inside the `ddev` script?
- Quick question - Have you tried opening the remote container in VSCode directly? Everything then works as if it's local.

**Comment by jakubmisek** [comment]
I have `ddev` installed, with default Laravel and PHP 8.1. I made a minor change, so the resulting command will look like this for me:

settings.json:
```json
{
    "phpunit.command": "ddev php ${phpargs} ./vendor/bin/phpunit ${phpunitargs}"
}
```

Output:
```bash
ddev php -d display_errors=on ./vendor/bin/phpunit -c phpunit.xml --teamcity --colors=never --filter "/^(Tests\\Feature\\ExampleTest::test_the_application_returns_a_successful_response(\s.*)?)$/"

PHPUnit 10.5.2 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.26
Configuration: /var/www/html/phpunit.xml
Time: 00:00.318, Memory: 10.00 MB
OK (1 test, 1 assertion)
Process #13884 closed with exit code 0.
```

**Comment by jakubmisek** [comment]
So running all tests (without --filter) works I guess?

It may be some incompatibility with PHPUnit 9.x, let me try.

**Comment by Morgy93** [comment]
> So running all tests (without --filter) works I guess?
> 
> It may be some incompatibility with PHPUnit 9.x, let me try.

Yes, and the two from https://github.com/DEVSENSE/phptools-docs/issues/455#issuecomment-1840943337 work as well.

**Comment by jakubmisek** [comment]
I'm still having OK results with PHPUnit 9.x

```
Running tests ...
> ddev php -d display_errors=on ./vendor/bin/phpunit -c phpunit.xml --teamcity --colors=never --filter "/^(Tests\\Feature\\ExampleTest::test_the_application_returns_a_successful_response(\s.*)?)$/" 
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
Time: 00:00.345, Memory: 10.00 MB
OK (1 test, 1 assertion)
Process #26620 closed with exit code 0.
```

Not sure what to test next :/

**Comment by jakubmisek** [comment]
It will be probably a linux/osx thing - we'll test more scenarios there.

**Comment by Morgy93** [comment]
> It will be probably a linux/osx thing - we'll test more scenarios there.

Not sure how to be more helpful here. I could give you access to the project via VSCode Live Share and you could run some commands on your own until it works. 😅

**Comment by Morgy93** [comment]
It "seems" to be some issue with the \ before the class name.

Works: `--filter "/(SomeTest::testSomething(\s.*)?)$/"`
Does not work:
- `--filter "/(\SomeTest::testSomething(\s.*)?)$/"`
- `--filter "/(\\SomeTest::testSomething(\s.*)?)$/"`
- `--filter "/(/SomeTest::testSomething(\s.*)?)$/"`
- `--filter "/(//SomeTest::testSomething(\s.*)?)$/"`

Actual generated path: `--filter "/^(One\\Two\\Three\\SomeTest::testSomething(\s.*)?)$/"`

**Comment by jakubmisek** [comment]
maybe the backslash is decoded twice ... I guess `\\\\` would work there.

**Comment by Morgy93** [comment]
> maybe the backslash is decoded twice ... I guess `\\\\` would work there.

You're right, that does work as well as my previous answer. 😁 

`--filter "/^(One\\\\Two\\\\Thee\\\\SomeTest::testSomething(\s.*)?)$/"`

**Comment by Loki3000** [comment]
Hi there!
In version v1.42.14408 quotes disappeared. So testing still doesn't work:
`--filter (^(One.Two.Three.ClassTest::testMethod(\s.*)?)$)`

there must be
`--filter "(^(One.Two.Three.ClassTest::testMethod(\s.*)?)$)"`

**Comment by jakubmisek** [comment]
@Loki3000 quotes should not be the problem (the filter argument does not contain spaces).

Have you tested it with and without quotes? I'll put them back, just it wasn't necessary in our tests.

**Comment by jakubmisek** [comment]
@Loki3000 @Morgy93 

`1.42.14412` adds quotes and replaces backslashes, so it should get properly escaped on various Win/Mac/Linux shells

**Comment by Morgy93** [comment]
`v1.42.14412` works for me 🥳 Thanks ❤️‍🔥

**Comment by jakubmisek** [comment]
Awesome! Thank you @Morgy93
