### ISSUE TITLE
Double-click on variable should select entire variable including `$`

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#456]
Call this a feature request if you want.

Say you have a variable `$somevariable` in php code: 
```
<?php

$somevariable = "foo bar";
```
and you double-click in the middle of the variable name.

The **current behavior** of VSCode, and I guess the PHP extension is leaving it unchanged, is to select the **bare variable name without the `$`**.
This is pretty standard behavior for a **language-agnostic plain-text editor** and it makes sense outside of the specific context of a language that uses `$` for variable names.

However, for coding in PHP, it would be **way more handy** and useful to select the **entire variable including the `$`**. 

**PHPStorm does that**.

For ages (until more recently than I'd like to admit) I used all sorts of generic text editors, rather than full-blown IDEs, for coding in PHP, and I was used to this behavior. So, if I had any bias, it would be in favor of it.
However, when I started using PHPStorm, I _immediately_ found the select-whole-variable behavior way more intuitive, handy and useful, despite not being used to it. Which is a sign (although in the context of just one person's anecdotal experience) that it's **objectively better**.

I recently switched from PHPStorm to VSCode because PHPStorm is ridiculously slow and unusable with any greater-than-tiny code base. VSCode is way faster and more robust. But when it comes to design decisions, PHPStrom is superior in many aspects. It's like they had all the correct and good ideas, but not the coding skills. 

In fact, I would suggest you guys try using PHPStorm for 10 minutes and copy all its behavior. If you take PHPStorm as a prototype of how an IDE _should_ be, it's brilliant.

But I digress, this report is specifically for the double-click to select the full variable name including $.

**Comment by jakubmisek** [comment]
I think you may have your settings altered. By default, the entire variable name including the `$` prefix is selected.

![vsc-dblclick-var](https://github.com/DEVSENSE/phptools-docs/assets/842150/fda327b4-fa7b-4b46-a188-e024788bdd97)

VSCode has a setting for that (https://code.visualstudio.com/api/language-extensions/language-configuration-guide#word-pattern) and some extensions and some users modify it.

Check if you don't have another PHP extension that might break the default behavior, or you don't have the `"wordpattern"` settings changed.

**Comment by php4fan** [comment]
That's strange.

I only manually installed the "PHP" extension. By looking at the installed extensions, I only have these other three all by DEVSENSE:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/3b408106-1340-44d4-9cbe-afd788bd084e)

They either came preinstalled with VSCode or were installed as dependencies when I installed "PHP".

I definitely never touched the setting you mentioned.

Is it this one?:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/8e2a7fe9-ba4d-46f9-beea-3d51d5f1ce81)

**Comment by jakubmisek** [comment]
It seems it used to be different. 

The `$` in the setting `editor.wordSeparators` causes the wrong selection.

We'll force the correct value in the next update.

**Comment by paperplanefactory** [comment]
Thanks @jakubmisek ! 
If it can be helpful, it also happens when the string is 
`my-string`
and - is excluded from wordSeparators list.

**Comment by paperplanefactory** [comment]
I see, but in version 1.42.14396 double clicking on a string with - worked fine to select the whole string.

**Comment by jakubmisek** [comment]
> I see, but in version 1.42.14396 double clicking on a string with - worked fine to select the whole string.

that's weird, it shouldn't :-)

**Comment by serhumanos** [comment]
I have the `$` character in `editor.wordSeparators` as vscode default. But when I use the editor and double click in `$variableName` all characters are selected `$` included.

**Comment by jakubmisek** [comment]
@serhumanos it will change in the future update;

for now, the workaround is the following setting:

```json
"[php]": {
        "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
    }
```

**Comment by jakubmisek** [comment]
The latest pre-release `1.42.14717` respects the vscode settings.

By default, `$` is a word separator, so it's not selected on double-click.

In this way, it respects VSCode's defaults.

To select entire variable including `$` (cc @php4fan), please add the following settings:
```json
"[php]": {
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
}
```

**Comment by php4fan** [comment]
I stopped observing the issue for a while, and assumed the update with the fix had been released.

But now I'm observing it again. Or it is intermittent.

I have never touched any setting related to word separators.

**Comment by jakubmisek** [comment]
The extension complies with the VSCode defaults, which were changed a while ago.

```json
"editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
```

See https://github.com/DEVSENSE/phptools-docs/issues/456#issuecomment-1887344695 for details.

**Comment by php4fan** [comment]
I'm confused.

> We'll force the correct value in the next update.

> The latest pre-release 1.42.14717 respects the vscode settings.

So, you changed it and then changed it back?

Anyway, my current setting, which I never touched, is:

```
`~!@#$%^&*()-=+[{]}\|;:'",.<>/?
```
which includes the $.

Is this expected to be the current default in VSCode? I wouldn't expect to have to fiddle with settings to get such an obvious behavior as "clicking on a variable selects it". If this is the default, it is definitely not a good default for developing in PHP (yes I understand different users like different settings, but as a default, just nope); I don't know about in general.

**Comment by jakubmisek** [comment]
Yes, we have changed it back, because it was a mistake to force this VSCode setting. (if it's forced, then users can't change it back easily)

**Comment by php4fan** [comment]
After a recent update (I don't know whether of the extension or of VSCode itself), this started behaving like it should, i.e. double-click would select the entire variable including the $.

Then, after a few minutes of happiness, and without doing anything (not even restarting VSCode), it went back to the stupid behavior of selecting only the variable name without the $.

How a piece of software can exhibit such utterly random changes in behavior is beyond me.

**Comment by jakubmisek** [comment]
@php4fan the setting you are looking for is `"editor.wordSeparators"`

**Comment by php4fan** [comment]
> the setting you are looking for is "editor.wordSeparators"

I know but I never touched the setting ($ should be included by default for PHP), and the behavior suddenly changed for a few minutes or hours and then changed back. I don't know whether that was because of something in the extension or in VSCode itself though.

**Comment by jakubmisek** [comment]
@php4fan I understand. You can check if it isn't modified using Settings UI:

![Image](https://github.com/user-attachments/assets/294bc7ba-2652-49c8-b0b3-bc61aee65a8f)
