### ISSUE TITLE
Formatting now removes spaces, including control structures and concat, breaking PSR-12

### ISSUE THREAD

**Issue by echoix** [DEVSENSE/phptools-docs#457]
The newest update of the DEVSENSE.phptools-vscode extension forces a new formatting style, which is problematic. For example, it removes spaces between `if (` to `if(`, `foreach (` to `foreach(`, spaces between dots in concatenation etc. This is directly against PSR-12 (https://www.php-fig.org/psr/psr-12/#5-control-structures), which is the default style selected and the one I explicitly have in my settings.json. I also use PHP CodeSniffer to assure the style is correct, and is thus problematic. Is this behaviour the same in all of your other products?

I saw this behaviour a couple of weeks ago, and realized I was on the pre-release branch of the extension, so I promptly reverted to the release channel, hoping it was just a temporary glitch. But it seems it wasn't caught yet.

The only workaround around that bug seems to be a formatting feature that is paywalled, thus not really a solution.

```
Name: PHP
Id: DEVSENSE.phptools-vscode
Description: All-in-One PHP support - IntelliSense, Debug, Formatter, Code Lenses, Code Fixes, Linting, Refactoring, PHPUnit Tests, Web Server, and more.
Version: 1.42.14396
Publisher: DEVSENSE
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode
```

**Comment by jaceldran** [comment]
Same for me,  previous version v1.41.14263 works fine.

**Comment by Miloslav** [comment]
Hello,
Thank you very much for reporting this. May I ask you to update to the latest version and let us know if it works as expected now? The bug should be gone now.

**Comment by echoix** [comment]
I tried out 1.42.14401 (restarting VSCode in between) and it seems to work like 1.41.14263 from 3 weeks ago :)

**Comment by Miloslav** [comment]
Great! Thank you! Yeah, we broke it in between :-/ sorry about that
