### ISSUE TITLE
Version 1.42.14401 not work

### ISSUE THREAD

**Issue by lionbach** [DEVSENSE/phptools-docs#458]
I work on a project with PHP and SugarCRM 6.5. Version v1.42.14401 does not work for a coworker and me. When you activate the debug, the web page does not load. We went back to version v1.40.14103 and it works fine.

**Comment by jakubmisek** [comment]
@lionbach anything in VSCode's OUTPUT panel, or DEBUG panel? There is usually important log information that might help us determine the problem's cause.

**Comment by jluisfa** [comment]
I can't format the code because VSCode says I haven't installed the PHP extension.

<img width="330" alt="imagem1" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/a6826f90-4a51-4762-ac98-9c87ec2f9d54">

However, it is installed and registered in settings.json

<img width="523" alt="imagem2" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/5d728016-7e7a-4a30-8b6c-f84036b0a1ae">


With version v1.41.14263 formatting works!
Version 1.42.14434 does not fix the problem.

Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

**Comment by jakubmisek** [comment]
@jluisfa @lionbach 

Please post the log from the VSCode Output window. I'll go first:

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/ab6c81d6-eb1a-4446-a39d-e4eeb309e63a)

or when launching debug:
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/6dfdb7ec-2ed7-4ecc-9386-6336ac1865c9)

**Comment by jluisfa** [comment]
<img width="878" alt="Captura de ecrã 2023-12-26, às 16 20 20" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/7ebbf952-04f9-42e9-b1c9-4dc08bec16c5">
<img width="879" alt="Captura de ecrã 2023-12-26, às 16 16 36" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/a4e63cdb-66c9-4cee-ad6a-ff12e121c83e">
<img width="880" alt="Captura de ecrã 2023-12-26, às 16 13 51" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/d4132551-3a7e-4957-8cad-7e910b2466a2">

**Comment by jakubmisek** [comment]
@jluisfa Thank you, isn't there the `PHP Language Server` output?

**Comment by jluisfa** [comment]
In the version **v1.41.14263**

<img width="855" alt="Captura de ecrã 2023-12-26, às 18 55 22" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/0348a5c9-2e71-4ef6-b4fb-a539d4ba4be2">
<img width="727" alt="Captura de ecrã 2023-12-26, às 18 50 22" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/3f655f01-6a3c-4a26-aa01-e9c12671c441">


In the version **v1.42.14434**

<img width="868" alt="Captura de ecrã 2023-12-26, às 18 54 01" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/76e6706d-ecf1-4ad8-b0c1-6f4657db113b">

**Comment by jakubmisek** [comment]
@jluisfa it looks like the `v1.42` does not start.

May I ask for the log (especially errors) from `Help` -> `Toggle Developer Tools` -> `Console`?

Thank you

**Comment by jluisfa** [comment]
<img width="753" alt="Captura de ecrã 2023-12-26, às 19 30 20" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/ec71a84a-5730-4437-b218-087f2dbd996f">

**Comment by jakubmisek** [comment]
@jluisfa thank you,

Honestly, I don't know what's wrong.

There should be an error message somewhere. I'll add more console logging to narrow the problem, and prepare pre-release version for you to try.

**Comment by jluisfa** [comment]
Here's another print to help you find the error.

<img width="771" alt="Captura de ecrã 2023-12-26, às 20 55 06" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/ca718358-902e-4927-a4e8-9a14444723c6">

**Comment by jakubmisek** [comment]
> Here's another print to help you find the error.

Thank you, what does the error say?

**Comment by jakubmisek** [comment]
There is a pre-release `1.42.14593` (it will appear in a few minutes) with more logging (in Help -> Toggle Developer Tools -> Console)

Thank you for trying it.

**Comment by jluisfa** [comment]
I attach the Console Log for version v1.42.14434
[vscode-app-1703625395159.log](https://github.com/DEVSENSE/phptools-docs/files/13773723/vscode-app-1703625395159.log)

**Comment by jluisfa** [comment]
I attach the Console Log for version v1.42.14593
[vscode-app-1703625611109.log](https://github.com/DEVSENSE/phptools-docs/files/13773729/vscode-app-1703625611109.log)

**Comment by jluisfa** [comment]
<img width="1274" alt="Captura de ecrã 2023-12-26, às 21 27 13" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/caf2bd83-0257-4162-b1f8-ab603c5d2967">

**Comment by jakubmisek** [comment]
@jluisfa thank you,

I think I know what's wrong.

May I ask you to try opening a different workspace folder? (a local folder on your Mac, if it helps) There is probably a bug in `ftp://' workspaces (or any remote workspace possibly).

**Comment by jluisfa** [comment]
Only with a local file, no ftp.
version v1.42.14593

Results:
No problem. Formatting takes place normally.

I attach the Console Log for version v1.42.14593

[vscode-app-1703673143787.log](https://github.com/DEVSENSE/phptools-docs/files/13777813/vscode-app-1703673143787.log)

<img width="957" alt="Captura de ecrã 2023-12-27, às 10 34 17" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/cabc4a94-a5e4-410c-bccc-13e26ace3bac">

<img width="717" alt="Captura de ecrã 2023-12-27, às 10 36 21" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/6acaf29d-6eba-4814-a8f3-849da488bb99">

**Comment by jluisfa** [comment]
In version v1.42.14626 the extension works normally with remote workspace by FTP.
Thank you very much

Console Log for version v1.42.14626

[vscode-app-1703932582395.log](https://github.com/DEVSENSE/phptools-docs/files/13797787/vscode-app-1703932582395.log)

<img width="765" alt="Captura de ecrã 2023-12-30, às 10 35 54" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/3250fd58-b9eb-4c5c-be70-c00d9b5c8a9b">

<img width="959" alt="Captura de ecrã 2023-12-30, às 10 38 03" src="https://github.com/DEVSENSE/phptools-docs/assets/32515675/95d0b9be-3217-4fcb-a6bc-89fdafe4a8ca">

**Comment by jakubmisek** [comment]
@jluisfa Great! Thank you very much for the confirmation. This is exactly how it should look like.
