### ISSUE TITLE
Extension randomly stops working

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#459]
I was working on a PHP project in VSCode, and I don't know how long it was before I noticed, but the extension stopped... well... extending. Calls to nonexistent functions wouldn't be underlined, ctrl+click on a function call wouldn't do anything. When I hovered over a function name in a function call (I don't remember if holding Ctrl or not), instead of the usual tooltip with the function's signature, one that said "Loading..." would show up, and it would never load anything.

It was like the extension wasn't installed. Basic syntax highlight was still there.

Unlike in issue 451, there weren't any error messages in the Output tab.

Restarting VSCode fixed the issue.

**Comment by jakubmisek** [comment]
Thank you for reporting that. It would help to see a screenshot, output text, or a console log. The following usually helps to resolve the issue:
https://github.com/DEVSENSE/phptools-docs/issues/426#issuecomment-1848939914

Also, it would help to know if you are win/osx/linux?

**Comment by php4fan** [comment]
Just happened again.

There's **nothing in the Output tab** under "PHP Language server":
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/27ba95f7-c3e3-429a-a518-eb7adc4191d9)

The `[INFO....]` entries are from hours ago.

This:
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/276e6558-2127-4f8e-8542-25fd6e763e40)
is not very helpful without a timestamp. I assume it's the extension starting hours ago as expected, but for all I know it could be restarting every 5 minutes because of an error and clearing the output each time.

There's this under "Extensions host":
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/f130fd50-2ee7-4fdb-8c11-6f392ce2d8e6)
but I'm **almost sure** the timestamps of the errors are from **before the extension stopped working**.

Why isn't there an "All" options in that selector?? Having to go through all  the dozens of options to see if one of them contains errors is so stupid. I'll report that to VSCode.

Her'es something in "Window":
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/7180e996-df31-41cf-a2ff-ff56060dbcfd)

This might belong to VSCode itself?

**Comment by jakubmisek** [comment]
thank you @php4fan ! Those logs might be helpful - there is definitely an exception that may cause crashing the extension.

I'll try to do some fixes that should help, and I'll prepare pre-release.

**Comment by jakubmisek** [comment]
We have fixed a few related issues, please comment if it happens again.
