### ISSUE TITLE
Use type hints for DocBlocks

### ISSUE THREAD

**Issue by svenax** [DEVSENSE/phptools-docs#46]
macOS: 10.14.6
phptools: 1.0.3936

When generating DocBlock comments, phptools seems to disregard typehints in the code and only use it's own analysis. It should only use typehints when generating the DocBlock and flag type mismatches in the Problems console.

For example,
```php
    /**
     * Summary of test
     * @param string $a
     * @param float $b
     * @return float
     */
    public function test(string $a, float $b): string
    {
        return $b + $a;
    }
```
Expected
```php
    /**
     * Summary of test
     * @param string $a
     * @param float $b
     * @return string
     */
    public function test(string $a, float $b): string
    {
        return $b + $a;
    }
```

It also doesn't understand the *nullable* operator
```php
    /**
     * Summary of test
     * @param string $a
     * @param \?float $b
     * @return float
     */
    public function test(string $a, ?float $b = null): ?string
    {
        return $b + $a;
    }
```
Expected:
```php
    /**
     * Summary of test
     * @param string $a
     * @param float|null $b
     * @return string|null
     */
    public function test(string $a, ?float $b = null): ?string
    {
        return $b + $a;
    }
```

**Comment by jakubmisek** [comment]
thank you, will be fixed!

**Comment by jakubmisek** [comment]
fixed in the next update, the PHPDoc will be generated as expected:

![image](https://user-images.githubusercontent.com/842150/64417163-dfcef700-d098-11e9-9993-edec4f3ad1ae.png)

**Comment by jakubmisek** [comment]
just notifying - the update `1.0.3951` fixes this issue
