### ISSUE TITLE
Intellisense confused by null coalesce

### ISSUE THREAD

**Issue by tanzanite777** [DEVSENSE/phptools-docs#466]
Type: <b>Bug</b>

Intellisense gets confused by null coalesce and deduces the wrong type - frequently necessitating dotting around @var type corrections to keep intellisense on track. Possibly indicative of a bug or perhaps just not yet fully implemented. Not sure which.

Example code:
```
class Foo {

    function load(mixed $stuff) : ?Foo { return null; }

    function theGood(array $inp) : array {
        $res = [];
        foreach($inp as $stuff) {
            $tmp = $this->load($stuff);
            if($tmp === null) $tmp = new Foo(); // imitating null coalesce (like in 'theBad')
            $res[] = $tmp;
        }
        return $res; // intellisense correctly thinks type of 'res' is: Foo[]
    }

    function theBad(array $inp) : array {
        $res = [];
        foreach($inp as $stuff)
            $res[] = $this->load($stuff)
                ?? new Foo();
        return $res; // intellisense incorrectly thinks type of 'res' is: array<Foo|null>
    }

    function theUgly(array $inp) : array {
        $res = [];
        foreach($inp as $stuff)
            $res[] = $this->load($stuff)
                ?? throw new SomeException();
        return $res; // intellisense incorrectly thinks type of 'res' is: array<Foo|null>
    }

}
```

Extension version: 1.42.14626
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.61GB free)|
|Process Argv|--crash-reporter-id adf79977-8c83-4303-918e-a7dfc5f31bf1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by jakubmisek** [comment]
Fixed in the pre-release version `1.42.14717`.

Thank you!
