### ISSUE TITLE
Static methods hover cards disappearing

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#467]
![image](https://github.com/DEVSENSE/phptools-docs/assets/2331052/72eaa0ce-b812-4ceb-b968-9db1c33a7893)

![image](https://github.com/DEVSENSE/phptools-docs/assets/2331052/cb90c9ca-8123-4d56-9ffb-b14ab759ef36)

All static method calls doesn't have hover cards but I still receive them from non-static subsequents

**Extension version:** v1.43.14756
**OS:** MacOS 14.2.1 (Sonoma)

**Comment by d8vjork** [comment]
Ok this seems fixed in this last release 👍

**Comment by jakubmisek** [comment]
@d8vjork thanks for tracking this one!

I've added unit tests for that, it won't happen again.

**Comment by d8vjork** [comment]
@jakubmisek That's very cool, tests always prevents unwanted regressions to happen

**Comment by jakubmisek** [comment]
@d8vjork we try, we already have thousands of them :)
