### ISSUE TITLE
Syntax Highlighting Or WordHighlight Not working in vs code after enable PHP Devsense Extension

### ISSUE THREAD

**Issue by codez-test** [DEVSENSE/phptools-docs#468]
![Screenshot_1](https://github.com/DEVSENSE/phptools-docs/assets/91196194/6047044d-1dec-412c-9a9f-677111eb3114)

In line no 6, when I click the variable $test3, all double quotations are highlighted but not the variable $test3. Also after line no 6, there is no syntax highlighting working for any variable. 

This is a bug. Please resolve this issue.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue, I'm looking on it.

**Comment by jakubmisek** [comment]
This will be fixed in the next update, and upcoming pre-release.

Thank you!

**Comment by codez-test** [comment]
Thank you @jakubmisek. Can u please tell us when will we get the update?

**Comment by jakubmisek** [comment]
@codez-test The pre-release will be ready within a day or two.

**Comment by jakubmisek** [comment]
Pre-release `1.43.14786` with the fix is available! Thank you again for reporting the issue.

**Comment by codez-test** [comment]
@jakubmisek The issue has not been resolved yet. You can write the same code as I attached the image previously and try to click any variable after line 5,  you will see that the variable is not selected or highlighted, only the quotation '' on the array('', '') is selected. I have updated the extension but there is the same issue as the previous one. Please fix this issue.

**Comment by codez-test** [comment]
@jakubmisek Yes it's working on the pre-release version. Thank you so much for fix this issue.

**Comment by jakubmisek** [comment]
@codez-test thank you for the confirmation, and for keeping track of the issue.

We'll do the full update soon.

If you have any other feedback, we'd appreciate more issues like this one! :)
