### ISSUE TITLE
Incorrect code formatting for case keyword

### ISSUE THREAD

**Issue by vladyslav-mikhieiev** [DEVSENSE/phptools-docs#469]
For a function named "case" a space will be added before the parentheses although it is not present in other functions
![image](https://github.com/DEVSENSE/phptools-docs/assets/31040615/9a24f481-369b-4c1c-9f4e-44c6a715c6ef)

**Comment by Miloslav** [comment]
Hello,

Thank you for the bug report. This has been fixed and it will be available in the next pre-release.
