### ISSUE TITLE
LiveShare connect ENOENT

### ISSUE THREAD

**Issue by jakubmisek** [DEVSENSE/phptools-docs#47]
![grafik](https://user-images.githubusercontent.com/22061464/64403840-58728b00-d07a-11e9-979b-d04481b21c70.png)

Live Share will not work

After deactivate PHP Tools the Live Share Extension is working fine.

_Originally posted by @Mordef in https://github.com/DEVSENSE/phptools-docs/issues/44#issuecomment-528720304_

**Comment by jakubmisek** [comment]
There are some recent updates that might fix this for you (still we were not able to repro the issue).

Is it still happening?

**Comment by Mordef** [comment]
Looks good in normal mode.
WSL still broken, but thats not from PHP-Tools

**Comment by jakubmisek** [comment]
thank you for letting us know :)
