### ISSUE TITLE
Can't install 'devsense.intelli-php-vscode' extension because it is not compatible with the current version of Visual Studio Code (version 1.85.0).

### ISSUE THREAD

**Issue by ctml91** [DEVSENSE/phptools-docs#471]
Can't install 'devsense.intelli-php-vscode' extension because it is not compatible with the current version of Visual Studio Code (version 1.85.0).

https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode&ssr=false#review-details
![image](https://github.com/DEVSENSE/phptools-docs/assets/74685281/6c81dc3e-2bbc-4744-9cfa-020d3798b94a)

Bummer, this extension is a must have! Is this expected?

**Comment by jakubmisek** [comment]
@ctml91 thank you for reporting the issue.

Version 1.85 is supported; May I ask what's your OS and CPU?

**Comment by ctml91** [comment]
@jakubmisek 

Macbook M1 w/ OS 13.5.1 & using with Dev Containers v0.327.0. However I just rebooted my laptop and it began working on its own, so perhaps it is a bug/issue with VSCode and/or Dev Containers and nothing to do with the extension after all. In this case I will close the issue, btw thanks for the fantastic extension!

**Comment by jakubmisek** [comment]
@ctml91 oh interesting, thank you for the update - we'll try your setup, but the specs should work.

I'm glad you like our extension! Thanks!
