### ISSUE TITLE
Output should have timestamps

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#472]
This:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/162f765b-dc2b-474b-a2c9-31ddfccb5b47)

is utterly useless without timestamps.

When something is wrong and I look at this output, I have no clue whether that has been there since 40 hours ago when I last started the IDE, or if it has been printed a few seconds ago. I don't know whether this output gets cleared every time  the extension or the language server get restarted, or not, so the fact that I see only one occurrence doesn't reassure me enough that this was only printed once many hours ago, and not cleared and printed again a few seconds ago.

**Comment by jakubmisek** [comment]
This log is just a confirmation that the PHP extension has started, but we can add some timestamps to it.

More detailed information is in "PHP Language Server" output.

**Comment by php4fan** [comment]
> More detailed information is in "PHP Language Server" output.

And there, too, the "PHP Tools Server started" log lacks a timestamp (one can usually infer at least an approximate time by the timestamps of the logs preceding and following, but that's not ideal)

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/5c5c88cb-87ae-46bd-9df6-b65628014dd3)

**Comment by jakubmisek** [comment]
The language starts immediately after opening a folder/workspace in vscode, but as said
> we can add some timestamps to it.

**Comment by php4fan** [comment]
> as said, we can add some timestamps to it.

That would be great.

> The language starts immediately after opening a folder/workspace in vscode

Perhaps I should have emphasized more, that the timestamps would be useful when one is trying to figure out if and when the extension (or some component of it) has _**re**_**started**.

For example, I often hit #461 and/or #459. So before I completely restart the IDE, sometimes I try to see if killing the language server process helps. The process does restart (at least sometimes), but then the extension doesn't always start working again immediately, so I start looking clues to whether I should give it a few seconds, or just give up and restart the entire IDE.

**Comment by jakubmisek** [comment]
timestamps were added (some time ago) :) thanks for the suggestion!
