### ISSUE TITLE
Insufficient 'never' return type support and consequent invalid errors (PHP0405).

### ISSUE THREAD

**Issue by tanzanite777** [DEVSENSE/phptools-docs#474]
Type: <b>Bug</b>

Cannot find where i can specify source php version (8.1+ needed for 'never'), but since it currently somewhat understands 'never' i will assume it is supposed to work presently and is just a bit bugged.

Example:
```
class Foo {

    function bar($x) : bool { // Invalid error hint: "'bar': not all code paths return a value (PHP0405)"
        if($x) return true;
        else $this->snafu();
    }

    function snafu() : never { // Invalid function signature: "function Foo::snafu(): void"
        throw new Error();
    }
}
```

Extension version: 1.43.14858
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.99GB free)|
|Process Argv|--crash-reporter-id adf79977-8c83-4303-918e-a7dfc5f31bf1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by jakubmisek** [comment]
@tanzanite777 Thank you for reporting the issue.

To specify PHP version (aka PHP language level) used by the editor, please follow the steps at https://docs.devsense.com/en/vscode/php-version#choosing-php-version

I'll take a look at the wrong `never` handling, thank you for the test case.

**Comment by jakubmisek** [comment]
Improved in the latest pre-release

- fixed tooltip
- fixed inlay hints with return types
- fixes handling of exit; die; from functions
- resolves `never` return type hint correctly in overridable functions
- improves control flow analysis of code containing exit/die/throw/ and never returning function calls

**Comment by jakubmisek** [comment]
The latest release (`v1.44.14950`) treats `never` more precisely; please let me know if it's as expected now.

Thnaks
