### ISSUE TITLE
.blade.php Syntax error: unexpected token ','PHP(PHP2014)

### ISSUE THREAD

**Issue by AbyssMorganCTI** [DEVSENSE/phptools-docs#480]
Inside .blade.php i got Syntax error: unexpected token ','PHP(PHP2014) after last update v1.44.14925
```
@extends('content-partial', ['title' => 'Logi systemowe (Archiwum)'])
```
![image](https://github.com/DEVSENSE/phptools-docs/assets/72556823/85a20d81-366a-4277-838d-470943a6ae76)

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

This has been fixed in the latest pre-release 1.44.14927
