### ISSUE TITLE
Support for Override attributes

### ISSUE THREAD

**Issue by MrExplode** [DEVSENSE/phptools-docs#481]
Static analysis support for the [`#[\Override]`](https://wiki.php.net/rfc/marking_overriden_methods) attribute introduced in PHP [8.3](https://www.php.net/releases/8.3/en.php#override_attribute) would be great.

**Comment by jakubmisek** [comment]
@MrExplode The latest pre-release `1.44.14961` gets basic override diagnostics (there are a few cases with traits still not handled)

**Comment by jakubmisek** [comment]
Implemented in the latest update.

There is one more case, we don't handle:

- [ ] #[Override] on a function that hides function from a trait is not reported

**Comment by jakubmisek** [comment]
Thanks for the great suggestion! 

This feature has been implemebted; the function overrides are checked now.

Please report any missbehavior if you find one.
