### ISSUE TITLE
PHP Syntax Highlighting breaks on complex Regex

### ISSUE THREAD

**Issue by k33bs** [DEVSENSE/phptools-docs#484]
`$pattern = '/(?:{{|\%\%)\s*([\w\.]+)\s*(?:}}|\%\%)/';`

The regex causes no issues with the built in syntax highlighter.
Somehow the last ( causes the parser to interpret everything after the regex line as string.

With the PHP Tools extension v1.44.14927 (pre-release OR release) turned off the VS Code built in parser has no issues.

**Comment by jakubmisek** [comment]
Fixed in pre-release `1.44.14939`

**Comment by tobsn** [comment]
can confirm, works! awesome, thank you for the super quick fix! :)

**Comment by k33bs** [comment]
can confirm, it works! thank you for the super quick fix!

**Comment by jakubmisek** [comment]
@k33bs thank you for the confirmation! I'm glad it could be fixed quickly
