### ISSUE TITLE
Assigning "void" from a function property_exists()

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#485]
Since the latest update I am getting a warning that `Assigning "void" from a function property_exists() (PHP1408)`, e..g. in case of ...

`$PropertyExists = property_exists($object_or_class, $property);`

Function `property_exists()`, however, returns `bool`, not `void` (s. https://www.php.net/manual/de/function.property-exists.php).

**Comment by jakubmisek** [comment]
Thank you for reporting the issue, will be fixed asap. Just preparing the update.

**Comment by jakubmisek** [comment]
fixed in `1.44.14950`!

**Comment by menturion** [comment]
Just updated. It is fixed. 
Thanks!

**Comment by php4fan** [comment]
I am getting bogus "Assigning void from function" with user-defined functions:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/316fd143-e3b9-4d66-a19b-910a547df788)

This is the function definition:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/3cb503b2-0ecf-4ac4-aac7-6ad530b77999)

Is this the same issue?

Supposedly I have v1.44.14961

**Comment by jakubmisek** [comment]
Thank you for pointing this out.

I've noticed we don't update errors unless the file gets changed - working on it.

**Comment by php4fan** [comment]
> I've noticed we don't update errors unless the file gets changed 

I'm not sure this has anything to do with updating. I have already changed the file but the error won't go away.

**Comment by jackskaret-aimclear** [comment]
I'm building a WordPress plugin and receiving a lot of this error, specifically when trying to use ACF functions. I installed the acf stubs:

![Image](https://github.com/user-attachments/assets/2c9dd571-228b-41fd-8da6-0078de6d05b0)

I even added to the include path:

![Image](https://github.com/user-attachments/assets/86193cbd-ff7d-4fff-99e5-2e27c2ddbbbc)

 but still receiving this:

![Image](https://github.com/user-attachments/assets/48bfa321-5d46-449a-a213-2f75fff1e25c)



When I "Go to definition" or "Peek definition" I see the correct definition, so where is it pulling the incorrect one from?
