### ISSUE TITLE
Incorrect docs on function implode() in PHP 7.4+

### ISSUE THREAD

**Issue by JokaJukka** [DEVSENSE/phptools-docs#488]
Hey there,
I've noticed that `implode()` function has incorrect documentation; quoting [PHP documentation](https://www.php.net/manual/en/function.implode.php):

`implode(string $separator, array $array): string`

Alternative signature (not supported with named arguments):
`implode(array $array): string`

Legacy signature **(deprecated as of PHP 7.4.0, removed as of PHP 8.0.0):**
`implode(array $array, string $separator): string`

The extension is offering all three possible syntaxes no matter what PHP version I set. Would it be possible to fix this?
Thanks!

**Comment by jakubmisek** [comment]
Thank you for pointing this out!

**Comment by jakubmisek** [comment]
Fixed in the latest update (1.44+)

![vsc-implode](https://github.com/DEVSENSE/phptools-docs/assets/842150/f2a19c97-0463-4365-847a-c3048d52a187)

thank you!

**Comment by ulin-evgeny** [comment]
@jakubmisek If you press ctrl+p, the extension shows all available method signatures. However, if you press ctrl+click, the extension ONLY shows the legacy signature.
