### ISSUE TITLE
Nonsensical autocomplete suggestion for "." always gets in my way when concatenating strings across multiple lines

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#489]
When editing a PHP file, **every single time** I try to write something like:

```
$someString = "Lorem ipsum dolor sit amet" .
    "consectetur adipiscing elit. Integer fermentum";
```
the moment I write the concatenating dot, this autocomplete suggestion shows up (or some variation of it):
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/4a668911-b509-4792-95aa-55ea0e224e13)
which makes no sense whatsoever in this context.
And because typically, after I write the dot, I'll hit Enter to go to the next line, I end up unwillingly "accepting" the proposed autocomplete suggestion, and I end up with some crap like this:

```
$someString = "Lorem ipsum dolor sit amet" <div class=""></div>
```
which makes zero sense.

This is SO f***ing irritating.

**Comment by jakubmisek** [comment]
We don't do that.

This behavior is a part of VSCode; it can be disabled with:
```json
    "emmet.excludeLanguages": [
        "markdown", "php"
    ]
```

**Comment by php4fan** [comment]
I shouldn't have to manually exclude every single type of suggestions from every single place where they have zero chance of being useful (and are actually harmful). Defaults should be reasonable.

I'm honestly not sure whether the responsibility for excluding this from PHP by default is VSCode's or yours.

**Comment by jakubmisek** [comment]
No you shouldn't, and we can't change user's settings, not everybody may like that.

Sadly, this behavior is not provided by our extension so I can't fix it.

If you feel this is a bug, please let them know at https://github.com/microsoft/vscode
