### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by wasay048** [DEVSENSE/phptools-docs#49]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.0.3951`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\wasay\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
please attach `DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt` the next time so we can resolve this.
