### ISSUE TITLE
Function call autocomplete doesn't include parentheses

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#492]
Say you have:

```
class Something {
    public function doSomething() {}
}
function compute_something() {
    return 3;
}
$something = new Something();

```

Now at the bottom you start typing:
```
$something->doSo
```
The autocomplete suggestion for `doSomething` shows up, so you hit Tab to accept the suggestion.

Or alternatively, you start typing:
```
$x = compu
```
The autocomplete suggestion for `compute_something` shows up, so you hit Tab to accept it.

**EXPECTED**

In both cases, I would expect the autocomplete to write the entire function call **including the parentheses**, like this:
```
$something->doSomething()
```
or this:
```
$x = compute_something()
```
with **the text cursor between the parentheses**. Most other IDEs do that.

In such context, I'm pretty sure the opening parenthesis is literally the only thing that can legally follow. If not, anything else is a very rare edge case, and anyone would be happy having to delete the parentheses in that < 0.0001% of cases.

**OBSERVED**

When I hit Tab, the autocomplete autocompletes the function name but not the parentheses. I have to type the opening parenthesis every single time, as if there was anything else that could reasonably follow.

**Comment by jakubmisek** [comment]
Thank you for the suggestion.

We have a setting for that:

```json
"php.completion.parameters": "parentheses" // adds `()` and places cursor inside
```

or

```json
"php.completion.parameters": "parameters" // to complete the whole call signature as a snipet
```

**Comment by php4fan** [comment]
Why is 'none' the default?

**Comment by jakubmisek** [comment]
It is a workaround for a recent bug in VSCode in combination with inline code suggestions ... I'll review it if it's still happening.

The problem was, that when there was an inline code completion (the grayed text) after auto-completing parentheses `()`, the editor went crazy and removed the right parenthesis sometimes in a weird way.

**Comment by jakubmisek** [comment]
Preparing pre-release that fixes parentheses completion in combination with AI suggestions (IntelliPHP, Copilot, Tabine, anything, ...)

**Comment by php4fan** [comment]
For some reason, parenthesis completion in function calls (which I have enabled after you pointed it out to me, and it usually works)  randomly fails to work in some cases:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/af11840d-8b4e-466c-959c-b9e2270a3473)

I have been unable  to reproduce with a minimal trivial example (it's not like it always fails when inside another pair of parentheses), but in the context of the code above it happens systematically.

I typed this:
```
return $this->logWhatsappClick(
```
which auto-closed the parenthesis correctly, so I got this:
```
return $this->logWhatsappClick()
```
with the cursor inside the parentheses. So far so good.
So I added the following (incomplete) inside the parentheses (showing the entire line):
```
return $this->logWhatsappClick($botFactory->getFirst()->_getProd)
```
Now my cursor is just before the closing parenthesis, and I'm offered to autocomplete `_getProductPrefix` which is a **method**. I hit Enter and I get:
```
return $this->logWhatsappClick($botFactory->getFirst()->_getProductPrefix)
```
without the parentheses for the method call. The expected result was:
```
return $this->logWhatsappClick($botFactory->getFirst()->_getProductPrefix())
```

**Comment by jakubmisek** [comment]
It seems like the editor just does not know, that `_getProductPrefix` is a function, because it probably does not resolve type of `$this->logWhatsappClick($botFactory->getFirst()`. If you mouse hover on `getFirst`, does it show a tooltip?

**Comment by php4fan** [comment]
You are right!
How come it knew that `_getProductPrefix` even existsted though? 

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/3286ed19-d780-4f70-9a4e-cc95bfc8a08c)

**Comment by jakubmisek** [comment]
This is just a word that occurs in the file somewhere else, so it gets "desperate" and suggests that at least.

We could be smarter in that case;

Is there any way, we could infer the type of `getFirst()` correctly?

**Comment by php4fan** [comment]
Oh I see. I should have known that from the "abc" symbol. As I saw the suggestion and it was correct, and there weren't a bunch of nonsensical suggestions, I assumed it had detected it.

But no, I'm afraid that would be too much to expect in this case, my bad.

**Comment by jakubmisek** [comment]
Ok, If you'll find some kind of pattern that we could implement to infer the type correctly, it would be great.

Have you seen the PHPDoc annotations using generics and tags like `@template T` and `class-string<T>`? It allows typing the methods pretty accurately.
