### ISSUE TITLE
"No quick fixes available" for "Class doesn't implement abstract methods"

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#493]
This is a class that is declared as implementing an interface but doesn't implement its methods:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/91f4803e-a11b-41f1-86c8-03fa96df281b)

What do you mean no quick fixes available?? There is a very obvious quick fix which is: create stubs for the missing methods. Other IDEs such as PhpStorm offer that.

**Comment by jakubmisek** [comment]
Not sure why you don't see the quick fix, it's supposed to be there:

![vsc-quickfix](https://github.com/DEVSENSE/phptools-docs/assets/842150/532d3ded-2d26-42f9-87eb-7cbed1a017a7)

I'll try more test cases.

**Comment by jakubmisek** [comment]
Side-note, quick fixes/code actions are available in **premium**

**Comment by php4fan** [comment]
> Side-note, quick fixes/code actions are available in premium

Oh I see 🤦🤦

Is that a VSCode thing or a DEVSENSE thing?

The "no quick fixes available" message should either not show up at all for non-premium users (it's completely useless if it's always the case), or have a clear indication that they are not available because it's a paid feature. The way it's shown now strongly suggests that no quick fixes are available in this particular case, i.e. for the problem being shown.

**Comment by jakubmisek** [comment]
That's a very good point, 

It's both - DEVSENSE's extension does not provide code fixes without a license, and VSCode shows "no quick fixes available".

We'll try to figure out, how to make this clear and not confusing.

**Comment by php4fan** [comment]
I'm not sure if everyone would agree, but IMHO even showing a "Quick fix" button that, when clicked (or when clicking on the particular quick fix to apply), said "Sorry you need to pay for this" or whatever, would be _less_ annoying (obviously only when there really is at least one quick fix). Because at least one wouldn't waste time trying to figure out why there's no quick fix when the fix seems obvious... or reporting a bug about it.

**Comment by jakubmisek** [comment]
I agree, we need to find a non-disruptive way of letting people know.

So as you said, we can list the code actions/code fixes, and add a little note (i.e. /premium/) next to it. When clicked, it would open some licensing info.

I'd also add a setting to hide premium code actions if the user is not interested and they don't want to be bothered.
