### ISSUE TITLE
Add support for "Inline Parameters for VSCode" extension plugin

### ISSUE THREAD

**Issue by AHS12** [DEVSENSE/phptools-docs#494]
Inline Parameters for VSCode help us see in line params in PHP and other language. However its not working when using DEVSENSE PHP support extension.

however it is working fine if we use PHP Intelephense
<img width="711" alt="Screenshot 2024-02-16 at 10 24 46 PM" src="https://github.com/DEVSENSE/phptools-docs/assets/25058208/d34df793-2f1e-4588-b625-b21dc703be35">

**Comment by jakubmisek** [comment]
We have this feature builtin, enable "php.inlay.***" setting.

**Comment by jakubmisek** [comment]
I see - we don't display the inlay hint if the name of the parameter is the same as the name of the variable.

I'll fix it for fields, i.e. `$data->date`.

**Comment by AHS12** [comment]
Thanks

**Comment by jakubmisek** [comment]
Thanks for pointing this out - we'll prepare pre-release with fix soon.

**Comment by jakubmisek** [comment]
fixed in the latest update, thanks!
