### ISSUE TITLE
Laravel Blade Syntax problems with Blade Directives

### ISSUE THREAD

**Issue by wfern** [DEVSENSE/phptools-docs#496]
Syntax broke when use blade directives inside html attributes, example:

Line 12: 
```blade 
data-event="@json('test')"
```
![image](https://github.com/DEVSENSE/phptools-docs/assets/4096003/93037ad4-3dc7-4069-a3fd-9e231774590a)

**Comment by jakubmisek** [comment]
Thank you for pointing this out. Fixed in the next update.
