### ISSUE TITLE
VSC Warnings/Errors, ignore problems in external libraries

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#5]
Analyse Warnings/Errors when file open, not on Start project.

To test: Install TYPO3 and open the Folder.
You'll get >4k Warnings/Errors
Not needed to fix external Librarys and can save memory

@jakubmisek > Attaching checklist:
- [x] exclude folder from problems window
- [x] specify what problems to be excluded or all
- [ ] update problems panel when the setting is changed
- [ ] match the glob only against path within the workspace
- [ ] the setting documentation

**Comment by jakubmisek** [comment]
Memory is a different issue.

How to recognize an external library? Anything in a 'vendor' folder?

**Comment by Mordef** [comment]
Vendor is an option but  not a good way. Some old library dont have vendor folder.
Think best way is a setting like
phptools.externLib = [
  'vendor'  : true,
  'typo3' : true,
  'smarty' : true
]

**Comment by Mordef** [comment]
I made short test with the new setting "php.problems.exclude" and looks good.
Testetd with pathnames and some glob-patterns.

**Comment by jakubmisek** [comment]
@Mordef thanks, we're glad it works. There are still a few details we'd like to implement tho.

**Comment by Mordef** [comment]
How do you found that error?
![grafik](https://user-images.githubusercontent.com/22061464/48000257-3da35300-e105-11e8-8a3b-83caa4024b1d.png)

**Comment by jakubmisek** [comment]
Oh, will be fixed : )

**Comment by jakubmisek** [comment]
the issue fixed (next update) and setting `php.problems.exclude` is now working and refreshes Problems window even if changed (next update).

note - ignoring some problems might not refresh the problems window and affected file has to be reopened. This will be updated in a future version.

closing, thanks for the feedback!
