### ISSUE TITLE
WSL: Warnigs on settings

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#50]
Got Warnings on non editable settings files:
![grafik](https://user-images.githubusercontent.com/22061464/66981060-fb271c00-f0b2-11e9-8d52-6af9c37eab33.png)

Please disable this files

**Comment by jakubmisek** [comment]
Do you know what warnings are there? PHP Tools don't inspect `.json` files.

**Comment by Mordef** [comment]
they comes only when php tools active.

**Comment by jakubmisek** [comment]
and do you what warnings it is?

**Comment by Mordef** [comment]
![grafik](https://user-images.githubusercontent.com/22061464/67179126-a0086880-f3d5-11e9-908b-72089ab52206.png)

NOT php-tools!
Have deactivated now and after open settings same warnings comes.
Sorry, pls close, wil search for the extension that will show that warnings.

**Comment by jakubmisek** [comment]
ok, thank you for the info :)
