### ISSUE TITLE
Colors become weird sometimes

### ISSUE THREAD

**Issue by marcelosantos89** [DEVSENSE/phptools-docs#501]
Hello,
With the php extension for vscode sometimes the text becomes like in the picture below.

![image](https://github.com/DEVSENSE/phptools-docs/assets/5165063/de7f27a3-9ed4-4b02-a313-c3e5286275f3)

If I disable the PHP Extension it works fine.

**Comment by jakubmisek** [comment]
thank you for reporting that, this is wild :) will be fixed
