### ISSUE TITLE
Randomizer::getBytesFromString marked as unknown (PHP0418)

### ISSUE THREAD

**Issue by GroM** [DEVSENSE/phptools-docs#502]
`<?php
$r = new Random\Randomizer();
echo $r->getBytesFromString('abc', 6); 
`
For some reason it VS Code marks this as unknown method PHP0418, even when it's running properly. 

![image](https://github.com/DEVSENSE/phptools-docs/assets/302731/ef314aed-2d43-4651-98d9-f17fa47b8534)

As you can see the version is set to PHP 8.3 (where this method was added), and php executable is set to PHP 8.3.3.

**Comment by jakubmisek** [comment]
Thank you for reporting that. We'll update the builtin manual with the latest functions.

**Comment by jakubmisek** [comment]
Fixed in the upcoming pre-release.
