### ISSUE TITLE
Parsing issue / DocBlock

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#508]
The parser seems to have issues with parsing DocBlocks containing declarations like this ...

```
     * @param array{
     *   ACL?: null|BucketCannedACL::*,
     *   Bucket: string,
     *   CreateBucketConfiguration?: null|CreateBucketConfiguration|array,
     *   GrantFullControl?: null|string,
     *   GrantRead?: null|string,
     *   GrantReadACP?: null|string,
     *   GrantWrite?: null|string,
     *   GrantWriteACP?: null|string,
     *   ObjectLockEnabledForBucket?: null|bool,
     *   ObjectOwnership?: null|ObjectOwnership::*,
     *   '@region'?: string|null,
     * }|CreateBucketRequest $input
```
see also https://github.com/async-aws/s3/blob/e6260647d5abe476e65c419acc4c3e392864f754/src/S3Client.php#L607.

With respect to the above example, this results in the issue message `Argument '1' passed to createBucket() is expected to be of type void, array given (PHP0406)`  when calling `createBucket` although arg#1 expects array and not void (s. code).

**Comment by jakubmisek** [comment]
Thank you for reporting the issue!

**Comment by jakubmisek** [comment]
The latest version should parse this already:
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/66d21c37-c03f-43d4-b91b-9f41481ad7bf)

May I ask you to clear the vendor cache? Using the command palette, `Clear /vendor/ cache ...`:
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/03ba0049-7b67-4cc9-8c82-f5edc999156e)

**Comment by menturion** [comment]
Thanks for your reply.
I cleared the cache. But still getting this issue.

![2024-03-07_074431](https://github.com/DEVSENSE/phptools-docs/assets/41576848/661adb54-89f4-493d-bbad-291c7b8a7106)

**Comment by jakubmisek** [comment]
Thank you for the reply.

I was able to replicate the issue - working on it.

**Comment by jakubmisek** [comment]
The latest pre-release `1.45.15130` fixes that, thank you!

**Comment by menturion** [comment]
Just tested. Can confirm that it is fixed.
Thanks!

**Comment by jakubmisek** [comment]
Thank you very much for the confirmation.
