### ISSUE TITLE
Disable Warning

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#51]
Please disable Warning fo php-dockblocker (neilbrayfield.php-docblocker) 
![grafik](https://user-images.githubusercontent.com/22061464/66981239-6f61bf80-f0b3-11e9-8c7f-2dcbf7c16f95.png)

It's not possible for me to set "editor.formatOnType": true"

**Comment by jakubmisek** [comment]
We are going to stop warning about conflicting extensions in general; at least on every workspace load.

- Would it help to not base the feature on `editor.formatOnType` setting?
- What is the reason you cannot enable the setting? Is there anything we can do?

Thanks

**Comment by Mordef** [comment]
editor.formatOnType ist for all, not only php. So if deactivated it will help and also thats the reason.

**Comment by jakubmisek** [comment]
thank you!

the upcoming update lets you to disable the warnings about extensions, and in a future update we'll make the phpdoc not depending on `editor.formatOnType`

**Comment by Mordef** [comment]
I'm on 1.0.4145 now
Warning-message still appear

**Comment by Mordef** [comment]
Thank you, works
