### ISSUE TITLE
No error given for incompatible override

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#512]
This is a method definition in a child class, which overrides a method in the parent class shown below:
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/ee01df2a-884e-429a-97cd-8804c30eefc9)

The return type declaration is missing from the override, and therefore this will cause a compile-time error when executing the code in PHP.

And yet, there's no indication whatsoever in the IDE than anything is wrong.

**Comment by d8vjork** [comment]
@jakubmisek this might be fixed with #234?

**Comment by jakubmisek** [comment]
@d8vjork yes! thank you for keeping track of it

**Comment by jakubmisek** [comment]
This issue is fixed with #234. 

We're preparing a new pre-release with some additional improvements.

Thanks!
