### ISSUE TITLE
Autocompleted override of method definition does not include return type (and therefore is incompatible)

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#514]
I start here:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/2ebe7866-175e-44bd-907e-672fe944b848)

and I want to override a method called `render()` that exists in the parent class.

So I start typing the method definition and I get this suggestion:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/ee1c7e79-2f19-4258-a65d-e5686f0bcf64)

Awesome! That's exactly the method declaration I want to override.
Note that it includes a return type. But probably I won't pay too much attention to that. Why should I? That's the method declaration I want and you're offering me to autocomplete it, so you'll take care of it, right?

So I accept the suggestion, and I get this:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/b69166ba-8c08-4623-8fda-1cec1c6299e6)

Note that **the return type is missing**.
Obviously I won't notice that, I'll assume you autocompleted the method definition correctly, I'll open the `{` and go on....

...writing an incompatible override that will throw a compile error.

Additionally, because of bug #512, I don't even get any warning about that.

Perhaps the two issues are related?

**Comment by jakubmisek** [comment]
Thanks! preparing pre-release with the fix.

**Comment by jakubmisek** [comment]
Implemented in pre-release, thanks!

**Comment by jakubmisek** [comment]
Released
