### ISSUE TITLE
[Error] Declaration of MySessionHandler ::open(string $myPath, string $myName): bool must be compatible with SessionHandler::open($path, $name)

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#515]
Version: 1.45.15130

In case of ...
```
class MySessionHandler extends SessionHandler {
    /**
     * @param string $myPath
     * @param string $myName
     * @return bool
     * @see https://www.php.net/manual/de/sessionhandler.open.php
     */
    public function open(string $myPath, string $myName): bool
    {
        // ...
    }
}
```

... I am getting the below error message:

`Declaration of MySessionHandler::open(string $myPath, string $myName): bool must be compatible with SessionHandler::open($path, $name).`

If I remove the `string` type hints within the method declaration, like `open($myPath, $myName`), no error message is shown.

This seems to be a general issue because I am getting this kind of issue also for other extended class methods.

**Comment by d8vjork** [comment]
They need to follow same typing, so you should remove the string types as your extended class does not enforce types.

Related #234

**Comment by menturion** [comment]
Please see https://www.php.net/manual/de/sessionhandler.open.php
public SessionHandler::open(string $path, string $name): bool

**Comment by d8vjork** [comment]
Ok so I think is the "stubs" the extension saves from PHP internal stuff

<img width="1046" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/2331052/51f409b7-25ea-49f1-a870-03297e069b68">

They need to refresh all these with their types so this can be solved (but you could also ignore that issue within .editorconfig as [they documented on their PHPTools website](https://docs.devsense.com/en/vscode/problems#rule-format), buy yes... not the ideal)

**Comment by menturion** [comment]
Right, I also thought/think that the internal representations might cause these issues.

**Comment by jakubmisek** [comment]
Thank you for reporting that - you are right, internally we treat the types only as a phpdoc type hint - causing the override check error.

**Comment by menturion** [comment]
The error messages are gone ... but with them apparently also this kind of static analysis, because I do not get an error message when I e.g. create a test scenario in which the constructor of a child class does not match that of the parent class or the type hints of a child method violates the ones of the parent class.

**Comment by jakubmisek** [comment]
@menturion constructor (`__construct`) does not have to match

**Comment by menturion** [comment]
> onstructor of a child class does not match that of the parent class.

Thanks. 
I thought this due to the error messages I got due to this issue.

**Comment by jakubmisek** [comment]
@d8vjork yes, that was a bug; `__construct` is not treated as an override.
