### ISSUE TITLE
Formatting glitches with `unset()`

### ISSUE THREAD

**Issue by SharakPL** [DEVSENSE/phptools-docs#518]
I use your extension as a formatter like this:
```json
  "[php]": {
    "editor.tabSize": 4,
    "editor.formatOnSave": true,
    "files.insertFinalNewline": true,
    "editor.codeActionsOnSave": {
      "source.fixAll": "explicit"
    },
    "editor.defaultFormatter": "DEVSENSE.phptools-vscode"
  },
```
But it looks like it can't handle `unset()` properly.
It won't format this (other functions are formatted properly at this state):
![obraz](https://github.com/DEVSENSE/phptools-docs/assets/5007456/8dc998ff-40a5-42aa-a904-eb5352d8611b)

Expected is this:
![obraz](https://github.com/DEVSENSE/phptools-docs/assets/5007456/2c206f70-a8c4-49d8-954a-b01295bae4ce)

But when I format it myself and save, it reformats the code to this:
![obraz](https://github.com/DEVSENSE/phptools-docs/assets/5007456/38997c3d-be8c-4263-847b-c7bce316fd74)

Does the extension implement all the [psr-12](https://www.php-fig.org/psr/psr-12/) standards properly?
Can it handle project standards eg. **.php-cs-fixer.dist.php** in project root?

Would be much better if it showed specific rules that are not met by the code and will trigger formatting on save. Just like stylelint or eslint do it in VSCode's Problems tab, eg.:

![obraz](https://github.com/DEVSENSE/phptools-docs/assets/5007456/ec341127-df47-40a1-ae25-8054fdacdd75)

**Comment by Miloslav** [comment]
Thank you for reporting this, it will be fixed.

Regarding the code style inspections, currently, we do not do that, but I'm taking a note to explore this in the future.

Thank you!

**Comment by Miloslav** [comment]
The fix will be present in the next pre-release. Thank you!

Regarding the PSR-12 question, it is fully supported; the issue you encountered was indeed a bug.

Please note that we do not read .php-cs-fixer.dist.php files, though. (yet)

**Comment by SharakPL** [comment]
Thanks 👍
