### ISSUE TITLE
Bogus error for incompatible constructor override

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#519]
Consider this code:
```
<?php

class TestParent {
    public function __construct(string $name) {
        echo "Parent constructor: $name";
    }
}

class TestChild extends TestParent {
    public function __construct(array $something) {
        parent::__construct("Default name");
        print_r($something);
    }
}

$test = new TestChild([1, 2, 3]);
```

Notice the constructor in the child class has a signature incompatible with the parent's constructor. This is fine in PHP, though. The code above will compile and run without any error or warning on any version of PHP >= 7.0.0.

However, the IDE will mark this as an error:
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/ed32103c-201d-4007-bd4e-21dae1e688fb)
```
Declaration of TestChild::__construct(array $something) must be compatible with TestParent::__construct(string $name)PHP(PHP2439)
```

**This would be a real error for any regular method, but not for constructors**. And I don't think it's considered bad practice either, as it is basically unavoidable when doing dependency injection.

**This might be a regression**: I noticed this when opening some files that I wrote several weeks ago, and I'd be very surprised if the error was already highlighted and I didn't notice the first time. But I may very well be wrong about that.

**Comment by jakubmisek** [comment]
Thank you for reporting that. I think we have fixed that in the latest pre-release.

The stable release will be prepared soon.

**Comment by jakubmisek** [comment]
Fixed in the latest update. Thanks!
