### ISSUE TITLE
Add support for hiding premium warnings/problems

### ISSUE THREAD

**Issue by AHS12** [DEVSENSE/phptools-docs#521]
![image](https://github.com/DEVSENSE/phptools-docs/assets/25058208/a1e34534-fa09-48b4-8ed0-0700d5d67bf6)
Even after activating this checkbox still getting this warnings.

![image](https://github.com/DEVSENSE/phptools-docs/assets/25058208/c27b7660-918b-4b30-9262-cf0ad7abec05)
![image](https://github.com/DEVSENSE/phptools-docs/assets/25058208/93020193-0f6b-468a-b0ec-c1f452061a5d)

Is there any way to now getting these warnings?

**Comment by jakubmisek** [comment]
Code diagnostics are not a premium feature. It's free.

To disable free code diagnostics, please see https://docs.devsense.com/en/vscode/problems#phpproblemsscope or just press F1, search for php problems - and choose `none`
