### ISSUE TITLE
Space erroneously added between `empty` function and opening parenthesis when formatting in PSR-12

### ISSUE THREAD

**Issue by taisph** [DEVSENSE/phptools-docs#523]
According to [PSR-12: 4.7 Method and Function Calls][1] "there MUST NOT be a space between the method or function name and the opening parenthesis", yet it seems to happen with the `empty()` function when reformatting a PHP file under PSR-12. May be a regression because I am fairly sure this hasn't always been like this.

devsense.phptools-vscode v1.45.15145.

[1]: https://www.php-fig.org/psr/psr-12/#47-method-and-function-calls

**Comment by Miloslav** [comment]
Hi,

Thank you for reporting this. Yes, this happened in the latest release. We've already fixed this for the upcoming pre-release (https://github.com/DEVSENSE/phptools-docs/issues/522) .

Thanks again!
