### ISSUE TITLE
[BUG] spaceBeforeParenthesesInCalls always true for isset

### ISSUE THREAD

**Issue by DevMude** [DEVSENSE/phptools-docs#525]
With `spaceBeforeParenthesesInCalls` set to `true`:
```php
isset ($foo);
// Some other core php function:
abs (1);
```

With `spaceBeforeParenthesesInCalls` set to `false`:
```php
isset ($foo);
// Some other core php function:
abs(1);
```

In the latter example, `isset` still has a space before the parenthesis.

**Comment by Miloslav** [comment]
Thanks for reporting. This is fixed in the pre-release version, soon to be released.

https://github.com/DEVSENSE/phptools-docs/issues/523
