### ISSUE TITLE
Formatter inserts a space after "language construct" keywords

### ISSUE THREAD

**Issue by cangokdayi** [DEVSENSE/phptools-docs#526]
This is not related to the setting "Insert space after function calls" so it only happens with language construct keywords like `empty()` or `isset()`

So basically:
```php
$arr = [];

if (empty($arr) || ! isset($x)) {
    throw new LogicException();
}
```

Becomes:
```php
$arr = [];

if (empty ($arr) || ! isset ($x)) {
    throw new LogicException();
}
```

Can you please look into this issue?

**Comment by Miloslav** [comment]
Hi,

Thanks for reporting this. We've fixed it in the pre-release, soon-to-be-release version. Please check it out.

Related: https://github.com/DEVSENSE/phptools-docs/issues/525

**Comment by cangokdayi** [comment]
Sweet, thanks a lot man.

**Comment by Miloslav** [comment]
No problem, thanks for reporting it ;-)
