### ISSUE TITLE
Hover appears `$$this`

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#527]
```php
<?php

class A {
    /**
     * @param callable($this):void $callable
     * @return void
     */
    public function map($callable) {

    }
}
```

`function A::map((callable(A $$this):void) $callable): void`, hover has `$$this` that shouldn't have.

![image](https://github.com/DEVSENSE/phptools-docs/assets/42226341/67849e42-ed6b-40e5-8321-841c90a0764a)

**Comment by jakubmisek** [comment]
Thanks! fixed.

Will be released in the next update.
