### ISSUE TITLE
Same name property and method issue

### ISSUE THREAD

**Issue by lhmuk** [DEVSENSE/phptools-docs#529]
![01](https://github.com/DEVSENSE/phptools-docs/assets/83061548/f1d9954a-5a80-4678-ac84-60a515e42e2c)
![02](https://github.com/DEVSENSE/phptools-docs/assets/83061548/5ee7b9db-55dc-4af7-b50f-0f9f808a9c51)
![03](https://github.com/DEVSENSE/phptools-docs/assets/83061548/a98fc14d-4ed8-473c-aac6-13e06838647a)

In an extended class, when using a parent property which has the same method, the Php-Extension does not recognize the property.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

It seems we ignored properties from trait uses! Will be fixed asap.
