### ISSUE TITLE
Incorrect triggering of PHP0421 warning: The variable '$...' is assigned, but its value is never used

### ISSUE THREAD

**Issue by coderapers** [DEVSENSE/phptools-docs#533]
Hi.

Why when I use assignment to array by just created variable Devsense reports me PHP0421 warning? Variable will be used in next code line.

![image](https://github.com/DEVSENSE/phptools-docs/assets/138874300/5b748467-9e60-43a2-b6eb-13c010e232cb)

**Comment by jakubmisek** [comment]
Thank you for reporting that, it looks like a bug.

**Comment by jakubmisek** [comment]
Code to reproduce:

```php
$form[0] = $container = [];
$container[1] = 123;
```
