### ISSUE TITLE
Assigning "void" from a function array_pop()

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#537]
v1.45.15249 (pre-release)

### EDITED ###

The following test scenario results in `Assigning "void" from a function array_pop()` due to the assignment within the loop is not resolved, i.e. `$ap` is considered to be `[]`. 

It turns out that the warning is mainly caused by a `if (false) {...}` condition placed before the code although this if-statement does not affect the further code (s. below). If switching the condition to `if (true) {...}`, the warning disappears. 

However, the warning will also disappear if you move the statement `$ap[] = 'any data';` outside the loop.

I have not tested all sensitivities. 

```
        if (false) {
            // If this "false" condition is placed here it will not work. Change to "true" and the warning disappears.
        }

        $ap = [];

        $apples = range(1, 10);
        foreach ($apples as $apple) {
            $ap[] = 'any data';
        }
        
        $temp = array_pop($ap);
```

**Comment by jakubmisek** [comment]
Thank you @menturion !

**Comment by jakubmisek** [comment]
We're improving analysis in this pre-release so dead code won't affect type inferring of a valid code; This revealed two pretty old bugs - fixed and adding more tests for it.

Thanks!

**Comment by jakubmisek** [comment]
Fixed in the upcoming pre-release

**Comment by menturion** [comment]
v1.45.15254 (pre-release)
Just want to confirm that it is fixed. Thanks!
