### ISSUE TITLE
Bogus "variable is not used" warning out of the blue after pasting unrelated code before variable assignment

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#541]
I know this will be extremely difficult to reproduce, but it's certainly a bug and needs to be reported nevertheless.

I don't know how to reproduce but here's what happened.

I was editing a file containing this piece of code, and everything was highlighted correctly, but all of the sudden, the variable `$garbageptn` that you can see at the top of the screenshot, became highlighted with the color that corresponds to unused variables, and sure enough upon rollover, the warning appeared:
![image](https://github.com/microsoft/vscode/assets/13969584/a6d41bd3-8928-4090-ab3e-b0f70284486c)

This happened the moment I pasted one line of code just before the part visible in the screenshot. The line of code I pasted was:
```
$garbage = '[\x{fe00}-\x{fe0f}\x{00a0}\s]*';
```
(the variable `$garbage` was already assigned before that, so the presence of that line changed nothing in terms of any warning, related or not to this one)
and then I modified it removing the `\s` (an irrelevant change), and the bogus warning remained.
At no point during this were there ever any syntax errors in the code anywhere in the file.

I stared at the code in disbelief for several minutes, looking for whatever I could be missing. How could I have made that variable become unused? That was completely impossible, so I searched for the next half-sensible thing, which was what syntax error could I possibly have introduced, or could have been there all along, but there was none either.

Finally I added and removed a space at some random position in the code (unfortunately I don't remember where, but somewhere within the screenshot I'm pretty sure), and immediately the bogus warning disappeared.

Things like this make us waste time, and cause us to be completely **unable to trust ANYTHING** that the IDE tells us about the code. When everything looks good, I have to fear that the IDE is missing some issue. When the IDE yells at me about an issue, I have to consider the possibility that the issue doesn't exist.

**Comment by jakubmisek** [comment]
Thank you for the detailed issue. I understand.

There is a "by-design" delay when updating diagnostics, but we should review if it works as expected.

Also, I have noticed, that sometimes VSCode does not update the diagnostics (and the grey highlighting) - we may look for a synchronization issue somewhere - looking at it.

**Comment by jakubmisek** [comment]
The latest pre-release `1.45.15391` improves updates of diagnostics, please let me know if it helps.
