### ISSUE TITLE
False error on blade

### ISSUE THREAD

**Issue by zarulizham** [DEVSENSE/phptools-docs#544]
Version: Pre-release
Editor: VS Code (Mac OS)

Only happen on pre-release, release version no issues.

Syntax error: unexpected token '='PHP(PHP2014):
<img width="577" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/10229855/73dfb0b4-a8ea-4828-9f48-159151dd4752">

Syntax error: unexpected token '{'PHP(PHP2014): (Livewire)
<img width="844" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/10229855/1d689372-c007-4527-8893-3b58a1dea53a">

<img width="674" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/10229855/a0ce5261-56e0-4698-ba2a-b228aee30578">

**Comment by jakubmisek** [comment]
Thank you for reporting the bug.

May I ask for this `.blade.php` file (or at least a part of it)?

**Comment by zarulizham** [comment]
> Thank you for reporting the bug.
> 
> May I ask for this `.blade.php` file (or at least a part of it)?

Yes, this is .blade.php file.

**Comment by jakubmisek** [comment]
And may I ask what's inside that file?

**Comment by jakubmisek** [comment]
fixed in the latest pre-release `1.45.15382`, thanks!
