### ISSUE TITLE
Feedback/Errors 1.45.15380 (May 03, 2024) (Pre-Release) 

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#547]
Nice release, but I have some problems.

### BLADE FORMATTER

When formatting a .blade.php file, I see the following erros:

On Windows:

![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/13532a15-5c88-4369-8202-de73dcaa3535)

On Windows (with WSL) and Linux

![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/ccf3e2c9-7919-4d52-9563-c646f69034ca)

In this case, the syntax error is about Livewire actions call:

![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/ca0c0239-9d43-40d1-a3c9-cbaf334f609d)
![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/fbee3917-9c73-4639-9daa-a56753b5d6b8)
![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/98780eed-d3f3-43f2-a97c-37fd27b204b6)

Another problem (actually the same problem), PHP dosn't recognize a specific token `{` or `:`
![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/1663696c-a239-488e-acf5-e8111d0aed7c)

Beacause of the false errors, the files can not be formatted.

### THE MAIN PROBLEM

Because PHP needs the language of the file be `PHP`, other extensions doens't works.
They need .blade.php files be identify as `BLADE`. And if we do that, PHP stops to working properly.

The extensions I refer to is: GoTo Blade Components, or Livewire Language Support, GoTo Livewire Component, Livewire Switcher, or Laravel Component Switcher, and others.

Working with Laravel/Blade is very nice these extensions to speed up the work flow.

### SUGGESTIONS

- Blade Components support
- Livewire support
- AlpineJS support (comes with Livewire now)

**Comment by trollfalgar** [comment]
@jakubmisek, I'm sending two simple files as exemple.
One is just a icon component with a svg code.
The other is a Livewire component with a simple table.

[ExemplesErrosPHP.zip](https://github.com/DEVSENSE/phptools-docs/files/15201199/ExemplesErrosPHP.zip)

**Comment by jakubmisek** [comment]
We'll try to prepare new pre-release asap.

**Comment by trollfalgar** [comment]
> We'll try to prepare new pre-release asap.

Thank you!

**Comment by jakubmisek** [comment]
Syntax error fixed in the latest pre-release `1.45.15382`, thanks!

If you'll get the warning **Couldn't format the code due to unexpected change on line ...**, please let me know. That's something else.
