### ISSUE TITLE
SUGGESTION: Auto Rename Tag

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#549]
Maybe this is in your TODO list already (if it is, you can close this), but, in adition to HTML Auto Closing tags implemented in the preview version.

Would be very nice Auto Rename Tag too.

![usage](https://github.com/DEVSENSE/phptools-docs/assets/441455/3d92f15a-001e-465a-b7ad-448555f9eea7)

**Comment by Miloslav** [comment]
This is supported, but it needs to be turned on:

```json
"[php]": {
    "editor.linkedEditing": true,
}
```

**Comment by trollfalgar** [comment]
> This is supported, but it needs to be turned on:
> 
> ```json
> "[php]": {
>     "editor.linkedEditing": true,
> }
> ```

Didn't know, perfect.
Thanks!
