### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#55]
[DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt](https://github.com/DEVSENSE/phptools-docs/files/4045340/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`- Extension Name: `phptools-vscode`- Extension Version: `1.0.4277`- OS Version: `Windows_NT x64 10.0.18362`- VSCode version: `1.41.1`:warning: Make sure to **attach** this file from your *home*-directory::warning:`C:\Users\xxx\DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Renji-FR** [comment]
I confirm the extension cause high CPU load too:

```
PID       USER     PR   NI    VIRT          RES        SHR S      %CPU  %MEM     TIME+   COMMAND
83234   xxxxx     20   0      4130968   660952  36432 S    100.0   32.5          97:53.32   Devsense.PHP.La

/home/xxxxx/.vscode-server/extensions/devsense.phptools-vscode-1.2.5931/out/server/Devsense.PHP.Langua
```

**Comment by jakubmisek** [comment]
@Renji-FR please try the latest update `1.2.5973` which improves issues on linux/macOs systems.

**Comment by Renji-FR** [comment]
Ok thank you, I have updated Visual Studio Code and the Devsense extension, I will test it during the next days:
`/home/xxxxx/.vscode-server/extensions/devsense.phptools-vscode-1.2.5973/out/server/Devsense.PHP.LanguageServer`

**Comment by jakubmisek** [comment]
thank you, please let us know.

Although there is an expected CPU load once a folder is opened. This can be disabled by disabling `"php.problems.workspaceAnalysis"` setting (https://docs.devsense.com/en/vscode/problems#phpproblemsworkspaceanalysis)

**Comment by jakubmisek** [comment]
I'm closing the issue for now; the excessive use of CPU after the workspace has been closed is fixed now.
