### ISSUE TITLE
generic issue

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#550]
```php
<?php


/**
 * @template Tkey
 * @template TValue
 */
class Collection
{
    /**
     * @template TMap
     * @param callable(TValue, Tkey): TMap $callable
     * @return static<TKey, TMap>
     */
    public function map($callable)
    {

    }
}

/**
 * @template TKey
 * @template TValue
 * 
 * @param iterable<TKey, TValue>|array<TValue> $iter
 * @return Collection<TKey, TValue>
 */
function collection($iter)
{

}

$c = collection([1, 2, 3]);
$c1 = $c->map(function ($value, $key): string {
    // $value should be int
    return 'string';
}); // $c1 should be Collection<TKey, string> instead  Collection<TKey, int>
```

**Comment by jakubmisek** [comment]
Thank you!

We have ignored the generic arguments for `static` in its case. The `$value` type may be a bit more difficult, working on it.

- [x] bind TMap in `static<TKey, TMap>`
- [ ] resolve lambda's parameter `$value` from the calling method generic parameter description

**Comment by ging-dev** [comment]
A small bug related to hover differences in `vendor`:
![image](https://github.com/DEVSENSE/phptools-docs/assets/42226341/4f77cba9-1814-4495-8879-7dd31b182ffd)

**Comment by jakubmisek** [comment]
Implemented inferring for lambda parameters + inlay type hint:

```php
$c->map(function (/*int*/ $value, $key): string {
    // $value is int
});
```

![vsc-lambda-params-inlays](https://github.com/DEVSENSE/phptools-docs/assets/842150/1b1e3a4e-8f3a-4ca5-88a1-fae050813a5e)

It will be in the next update.

**Comment by jakubmisek** [comment]
Closing the issue.

The incorrect (double) hover will be fixed separately.
