### ISSUE TITLE
Formatter: @js() inside Javascript Code

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#551]
The formatter is adding spaces to objects with properties when using the blade directive `@js()` to pass PHP expressions inside a JS code.

![Sem título](https://github.com/DEVSENSE/phptools-docs/assets/441455/171201fc-6fbd-43a4-9525-fc922590341b)

**Comment by jakubmisek** [comment]
thanks! the editor did not recognize `@js` directive so its content was formatted as it would be HTML ... 

fixed and preparing pre-release

**Comment by jakubmisek** [comment]
There is a first version of the fix in pre-release `1.46.15400`.
