### ISSUE TITLE
The result of 'explode' is not recognized as an array

### ISSUE THREAD

**Issue by lhmuk** [DEVSENSE/phptools-docs#552]
![20240508_01](https://github.com/DEVSENSE/phptools-docs/assets/83061548/a2d0f28b-b171-4333-9394-1a0c19158ac4)

VSCode 1.89.0
PHP Extension 1.46.15395

When the || operator is used inside the 'try-catch' block within the 'throw_if' function, 'explode' does not recognize the result as an array.

**Comment by jakubmisek** [comment]
Fixed and preparing pre-release.

**Comment by jakubmisek** [comment]
pre-release `1.46.15400` fixes the issue

Stable release is expected within a few days.
