### ISSUE TITLE
Couldn't start language server for 'win32-x64' on 'win32-x64'. 

### ISSUE THREAD

**Issue by jhs1873** [DEVSENSE/phptools-docs#553]
![image](https://github.com/DEVSENSE/phptools-docs/assets/11732611/0b6f1799-25c1-4bd4-8a98-b36b28ce4545)

.vscode\extensions\devsense.phptools-vscode-1.46.15395-win32-x64\out\server\devsense.php.ls failed.

vscode: 1.85.2
php Extension: v1.46.15395

**Comment by jhs1873** [comment]
v1.46.15414 is normal

**Comment by jakubmisek** [comment]
> v1.46.15414 is normal

Please, what is in OUTPUT?

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/b11d2c9c-1458-4333-86ad-b4f82a1aa589)
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/8a7cf9b0-2f6d-4105-8721-896234a14e53)

Any error will be there.

**Comment by jhs1873** [comment]
@jakubmisek [Error - 09:29:57] Starting client failed
Launching server using command c:\Users\Administrator\.vscode\extensions\devsense.phptools-vscode-1.46.15414-win32-x64\out\server\devsense.php.ls failed.

**Comment by jakubmisek** [comment]
@jhs1873 please copy the log from Help -> Toggle Developer Tools -> Console

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/0742ce01-cd9e-48b1-a39e-b0c8506e5da5)

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/7b78b67d-eb98-43ed-a15f-cea42772ec11)

**Comment by jhs1873** [comment]
@jakubmisek  
![image](https://github.com/DEVSENSE/phptools-docs/assets/11732611/5d2015ef-e3e8-4a43-bf23-55b551013919)

**Comment by jhs1873** [comment]
v1.46.15498 is normal

**Comment by jakubmisek** [comment]
Thank you for the log.

It is possible, that your antivirus software may block our extension. Can you check that?

**Comment by jhs1873** [comment]
v1.47.15512 is normal.   Antivirus software has not been turned off, no problems can be detected

**Comment by jakubmisek** [comment]
@jhs1873 that's because every version is different. Antivirus software may block one version, and ignore another.
