### ISSUE TITLE
Unnecessary space inside PHP Attributes

### ISSUE THREAD

**Issue by trollfalgar** [DEVSENSE/phptools-docs#555]
Inside Attributes, the extension add a space at the start **when using named arguments**.
I didn't find a specific configuration to enable/disable this in `PHP>Formatting (Spacing)`. And the others are disabled.

![image](https://github.com/DEVSENSE/phptools-docs/assets/441455/4ceaf677-0660-4237-8b7e-526a751dd143)

**Comment by Miloslav** [comment]
Thanks Tiago! This is a bug, will be fixed.

**Comment by Miloslav** [comment]
Fixed - will be in the next pre-release.
