### ISSUE TITLE
Does not auto-suggest or complete Magic Methods

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#561]
Hi,

I notice the extension does not provide auto suggestion/completion for Magic Methods such as __get, __set etc.

Please advise.

**Comment by jakubmisek** [comment]
Hello,

May I ask for a sample code, example, or screenshot?

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/b469d81f-0764-4a42-9a59-f8d86c714220)

**Comment by murugappanrm** [comment]
Hi @jakubmisek 

Thank you for responding so quick. I had (now resolved) this problem and later i discovered it was caused by an extension for Alpinejs. I found this out by accident when i was resolving a syntax highlighting problem with React.  I have removed that extension and now it seems to work fine. 

Please accept my apologies for the inconvenience.

**Comment by jakubmisek** [comment]
Thank you for the clarification.

No worries, I'm glad it got resolved.
