### ISSUE TITLE
Improved stubs for reflection

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#566]
Some functions like ‎`ReflectionClass.getMethods()` return an `array`, which can return the type of the element in the array: https://github.com/JetBrains/phpstorm-stubs/blob/2f406927040058c3beb6fcba0f92f926dc382d22/Reflection/ReflectionClass.php#L217
Perhaps take advantage of `phpstorm-stubs` to improve.

**Comment by jakubmisek** [comment]
Thanks. We're using the original PHP manual in all available languages with tons of adjustments, this one was missing. phpstorm stubs are English only with some missing annotations.
