### ISSUE TITLE
Sticky Scroll Issue

### ISSUE THREAD

**Issue by remedix** [DEVSENSE/phptools-docs#567]
In both stable and prelease version (v1.47.15538 (pre-release)) sticky scroll stops working when class has nested functions. This should obey vscode's native `editor.stickyScroll.maxLineCount`

**Comment by jakubmisek** [comment]
Fixed and preparing pre-release.

Also, we'll be showing names of functions and classes without the namespace part which simplifies the outline view.

**Comment by jakubmisek** [comment]
Fixed in `1.47.15578`, thank you!
