### ISSUE TITLE
Code Action: Getters and Setters generating incorrect function names

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#570]
Hi,

I am using versions v1.47.15512 (the latest). When i use the code action and generate the getters and setters for the class constructor variables, the name of the getter and setter function is incorrect. See screencap below:

![Screenshot_1](https://github.com/DEVSENSE/phptools-docs/assets/63133893/aa213f01-3c70-4673-8e7a-90a0df065b18)

**Comment by jakubmisek** [comment]
fixed in the upcoming update, thanks!

**Comment by murugappanrm** [comment]
Hi @jakubmisek thank you for the update. Will test it out today.
