### ISSUE TITLE
Warning 0413 on a Laravel blade code on Route class which is a valid class.

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#574]
I am using extension version 1/47.15512. The extension produced a 0413 warning on a Laravel blade code on Route class which is a valid class. See screencap:

![Screenshot_1](https://github.com/DEVSENSE/phptools-docs/assets/63133893/e67e1ebe-6a61-4074-88cf-e409b89551d9)

**Comment by murugappanrm** [comment]
Hi

I am sorry. Its a false alarm. This happen for sure but when i reloaded the vs code it was no longer there. 

I am closing this.

**Comment by jakubmisek** [comment]
Thank you for pointing this out.

It should not happen at all - let me check.

**Comment by jakubmisek** [comment]
Found the bug, it happens during initial composer packages indexing.

Will be fixed!

**Comment by murugappanrm** [comment]
@jakubmisek 

Ah, so it was a bug. Ok thank you for the update. Some of my extension have been misbehaving and i am still trying to debug.
