### ISSUE TITLE
Static variables lose their type when assigned

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#579]
![image](https://github.com/DEVSENSE/phptools-docs/assets/42226341/6cb3456d-37e1-43c3-9cf7-96acef72a6c7)

Should be `string|null`

**Comment by jakubmisek** [comment]
Thanks, actually the `if` itself breaks it :/

```php
function test() {
    static $a = null;
    if (null === $a) {
    }
    /** @trace $a */
}
```

We'll add a test case for it and fix it.

**Comment by jakubmisek** [comment]
Will be fixed in the next update, thanks!
