### ISSUE TITLE
Can't use in bigger Projects

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#58]
My Project contains 44047 Files.
There are 5280 PHP Files.

It works very slow, most time the hints allways show "Wird geladen..." 
Autocomplete so also not working.

Small Projects work fine.

**Comment by jakubmisek** [comment]
Have you tried setting `"php.problems.workspaceAnalysis" : false,` ?

doc at https://docs.devsense.com/en/vscode/configuration#configuration-options

**Comment by Mordef** [comment]
first impression looks good. ill work a day with this and tell you if something is missing/failed

**Comment by Mordef** [comment]
It works fine with that setting
