### ISSUE TITLE
Lack of error diagnosis on the interface

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#581]
```php
interface A {
    /**
     * @param string $class
     * @return void
     */
    public function test($class);
}

/**
 * @var A $a
 */

$a->test(1); // <-- missing error
```

**Comment by jakubmisek** [comment]
This depends on whether you have
```php
declare(strict_types=1);
```

Most of the legacy code without `strict_types` is basically built on implicit number->string conversion.

**Comment by jakubmisek** [comment]
I'll take it as solved :) 

Would it make sense to have a global `"strict_types"` setting?

**Comment by ging-dev** [comment]
> Would it make sense to have a global `"strict_types"` setting?

That's not really necessary, I'm fine with `declare(strict_types=1);` :D

**Comment by jakubmisek** [comment]
alright, thanks @ging-dev ! :)
