### ISSUE TITLE
Not suggesting array keyword and it's info on hover [MINOR BUG]

### ISSUE THREAD

**Issue by Maaz0313** [DEVSENSE/phptools-docs#583]
PHP extension is not suggesting array keyword, and also not it's info on hovering it.

**Comment by jakubmisek** [comment]
Thank you for noticing.

It seems we're showing `array` but with parenthesis in the completion list:
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/1d3592cf-b8e4-4b8e-ab77-1c3ef0ec4c09)

And no mouse hover as you said.

Is it the case, or there's something else?

**Comment by jakubmisek** [comment]
Fixed in the recent update, thanks!
