### ISSUE TITLE
Add 1 newline between methods and strip unnecessary newlines 

### ISSUE THREAD

**Issue by Teraskull** [DEVSENSE/phptools-docs#584]
Add one newline between functions/methods:
```php
function a() {
    echo "";
}

function b() {
    echo "";
}
```

**Comment by Miloslav** [comment]
Thank you for the suggestion. We will add format settings to achieve that soon.

**Comment by Miloslav** [comment]
Hello,

This can be configured in the latest release:

```json
"php.format.rules.blankLinesBeforeMethod": 1,
"php.format.rules.blankLinesAfterMethod": 1,
"php.format.rules.blankLinesBeforeFunction": 1,
"php.format.rules.blankLinesAfterFunction": 1,
```

We've also added more blank lines related settings https://docs.devsense.com/en/vscode/editor/customize-formatting#blanklines

Thanks again for the suggestion!

**Comment by Teraskull** [comment]
Thanks a lot!

Small nit, some descriptions are confusing or contradict the heading:

![image](https://github.com/user-attachments/assets/beaa795f-1b93-4442-9bd4-b99ee622bdc1)

Noticed it with a few others too before, not sure if those were fixed already.

**Comment by Miloslav** [comment]
Thank you for noticing! We'll fix that and check the others.
