### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by thanhtran468** [DEVSENSE/phptools-docs#586]
Class inheriting from `ArrayObject/ArrayAccess` should not have this warning:

```php
class A extends ArrayObject {}
$a = new A();
$a->name = 'Thanh';
$a->name; // Undefined property

// Works as expected
$a = new ArrayObject();
$a->name = 'Thanh';
$a->name;
```

**Comment by thanhtran468** [comment]
A few other cases: Class inherits from `stdClass`, `#[\AllowDynamicProperties]`, ...

**Comment by jakubmisek** [comment]
thank you, fixed and preparing updated pre-release
