### ISSUE TITLE
Support unsealed array shape syntax

### ISSUE THREAD

**Issue by thanhtran468** [DEVSENSE/phptools-docs#587]
More information in: https://github.com/vimeo/psalm/issues/8804#issuecomment-1936625455

**Comment by jakubmisek** [comment]
Thank you. We support the array doc comment syntax:

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/90660b53-09a1-4f7e-8c38-4729f076f733)

Is there anything specific that does not work in VS Code?

**Comment by jakubmisek** [comment]
implemented, preparing pre-release

**Comment by thanhtran468** [comment]
> implemented, preparing pre-release

Thanks!

![image](https://github.com/DEVSENSE/phptools-docs/assets/174078328/2c5032d5-60fb-4586-9b05-613fd0bfd20e)

i think this case should be `array<float|int|string>`?
