### ISSUE TITLE
Licence key sent message should say "sent" instead of "send"

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#59]
![image](https://user-images.githubusercontent.com/3308769/86170330-e2f90f00-bb12-11ea-9b62-b6312de021a0.png)
Should be "licence key has been sent to foo@bar.baz" instead of "send to" in English.

**Comment by addshore** [comment]
Even better would be "A 30-day licence key has been sent to foo@bar.baz"

**Comment by jakubmisek** [comment]
thanks! updated
