### ISSUE TITLE
Cache??

### ISSUE THREAD

**Issue by ProtocolLive** [DEVSENSE/phptools-docs#590]
Allways when i create new method, the extension say the method dont exits when i use them.
Maybe a command to reindex helps

**Comment by jakubmisek** [comment]
Isn't there a syntax error in the file with the method definition (red underline)?

**Comment by ProtocolLive** [comment]
No red line
Just Call to unknown method: ..... PHP(PHP0418)

**Comment by jakubmisek** [comment]
Is the file, containing your method definition, syntactically OK and listed in your VSCode's workspace?

Isn't there a "loading" in VSCode's status bar?

**Comment by ProtocolLive** [comment]
Nothing
I have other intelisense extension. He recognize the method

**Comment by jakubmisek** [comment]
Thank you.

Could you provide a screenshot or more information? There is no "cache" or a need for "reindexing".

Do you have the latest update?
Isn't there an error in VSCode log? (Help -> Toggle Developer Tools -> Console)
Error in VSCode§s Output? (View -> Output -> "PHP Language Server" tab)

**Comment by ProtocolLive** [comment]
![image](https://github.com/DEVSENSE/phptools-docs/assets/39626142/e970afe7-464c-444b-865e-918fb6fa4e58)

Everything updated!
Devtools log: [Extension Host] Received response message without id. No further error information provided. (at console.<anonymous> (a:\Programas\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:47717))
No errors in PHP Language Server

**Comment by jakubmisek** [comment]
I see; just a quick check - if you edit the file with that warning, the warning disappears?

**Comment by ProtocolLive** [comment]
When i edit, disappears.  When i close, comes back

**Comment by jakubmisek** [comment]
hmm couldn't there be two traits with the same name?

**Comment by ProtocolLive** [comment]
two traits with the same name?? no

**Comment by jakubmisek** [comment]
> When i edit, disappears. When i close, comes back

The file with the trait or with the warning?

**Comment by ProtocolLive** [comment]
when i close the trait, the warning comes back

**Comment by jakubmisek** [comment]
> when i close the trait, the warning comes back

This usually happens when the file (with the trait) is not saved properly on disk - OR - when we couldn't detect its encoding.

**Comment by ProtocolLive** [comment]
strange... i have pushed the file to github...

**Comment by jakubmisek** [comment]
May I ask what's the file encoding? It would be in lower right corner:

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/5941d62a-bfe5-45d5-94cd-30a9ec560eb6)

**Comment by ProtocolLive** [comment]
UTF8 in all

**Comment by jakubmisek** [comment]
thanks,

Isn't the file in a /vendor/ folder, or excluded from VSCode's explorer?

**Comment by ProtocolLive** [comment]
the trait is in vendor folder, but not excluded

**Comment by jakubmisek** [comment]
I see, yes, we ignore changes in vendor folder unless specified as a development package in `composer.json`

**Comment by jakubmisek** [comment]
So this file is a part of some regular versioned composer package?

**Comment by ProtocolLive** [comment]
> So this file is a part of some regular versioned composer package?

Yes. Its my own packge. Just creating new resource

**Comment by jakubmisek** [comment]
I'll have to look at how to make this work without any additional configuration.

Currently, we support/expect the local packages as described for example at https://stackoverflow.com/a/38698049/601646 (otherwise `composer install/update` may delete your local changes).

You can "force" the changes in vendor by running VSCode Command "Clear /vendor/ cache".

**Comment by jakubmisek** [comment]
@ProtocolLive I would still consider it as a bug. We should respect user's changes automatically.

I'll try to come up with a solution/fix.

Thank you for pointing this out!
