### ISSUE TITLE
Why can't I install the latest version?

### ISSUE THREAD

**Issue by ellermister** [DEVSENSE/phptools-docs#593]
Why can't I install the latest version?

amd64
in docker 
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    Container: Yes
    Shell: 5.1.4 - /bin/bash

![image](https://github.com/DEVSENSE/phptools-docs/assets/23046078/2e2f969d-09ac-4bb9-bbe8-779d0c209dfb)

**Comment by jakubmisek** [comment]
Thank you;

related to https://github.com/DEVSENSE/phptools-docs/issues/592

It should be working now.
