### ISSUE TITLE
Cannot fold a function if it closes PHP tags inside

### ISSUE THREAD

**Issue by str** [DEVSENSE/phptools-docs#594]
I have a function that generates HTML code. For me, it is easy to close PHP tags and generte the HTML tags between the closing and reopening PHP tags. If I do so, I cannot fold the function

![image](https://github.com/DEVSENSE/phptools-docs/assets/123817/5f731faf-da0b-4459-b896-c6acec4f028e)

**Comment by jakubmisek** [comment]
Thank you. The fix will be available in the next update!
