### ISSUE TITLE
generic

### ISSUE THREAD

**Issue by thanhtran468** [DEVSENSE/phptools-docs#595]
![image](https://github.com/DEVSENSE/phptools-docs/assets/174078328/06a3d2c7-68c6-4376-b633-c1371cc5cd67)

**Comment by jakubmisek** [comment]
@thanhtran468 Thanks for the test case.

This is a question; `__construct` is the only function not "overridden" properly - it can have different parameters than its parent, and all the parameters may have a different "meaning". That's why we don't automatically inherit their types from parent.

**Comment by thanhtran468** [comment]
> @thanhtran468 Thanks for the test case.
> 
> This is a question; `__construct` is the only function not "overridden" properly - it can have different parameters than its parent, and all the parameters may have a different "meaning". That's why we don't automatically inherit their types from parent.

Oh I see. It seems that with `psalm`, `mixed` is the correct behavior, but with `phpstan` they will inherit by parameter name. Since there is no consistency between these 2 tools I think `mixed` is the expected behavior.

**Comment by jakubmisek** [comment]
Matching by parameter name might make sense! Sometimes it may have a side-effect however; once there is explicitly specified `@inheritDoc`, user is probably well aware what he's doing right?

**Comment by thanhtran468** [comment]
> Matching by parameter name might make sense! Sometimes it may have a side-effect however; once there is explicitly specified `@inheritDoc`, user is probably well aware what he's doing right?

Exactly :D
