### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by MudassirAmeen** [DEVSENSE/phptools-docs#596]
Type: <b>Bug</b>

This Extention makes this error 
Extension host terminated unexpectedly 3 times within the last 5 minutes.
and now my i am unable to run my code. so i uninstalled this extention once and install this again but same thing happens. please review the problem and fix it.

Extension version: 1.49.15728
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.88GB free)|
|Process Argv|C:\\xampp\\htdocs\\stockfiy --crash-reporter-id d8dab6be-b7f7-4afe-a5d5-848c9ed102db|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31094926
pythonrstrctxt:31093869

```

</details>

**Comment by jakubmisek** [comment]
Thank you for letting us know. May I ask for the log at View -> Output -> PHP Language Server? There will be detailed information so we can fix it promptly.

![image](https://github.com/user-attachments/assets/54823540-0b29-497f-b0df-6898a1692b30)

**Comment by MudassirAmeen** [comment]
sorry but i have uninstall the extention so i don't have any outputs now.

**Comment by jakubmisek** [comment]
We can't fix an issue without any information.
