### ISSUE TITLE
Classifies uppercase and lowercase letters when autocompleted

### ISSUE THREAD

**Issue by thanhtran468** [DEVSENSE/phptools-docs#598]
Problem: I want to call a calculation method in the `Arr` class (laravel), however LSP seems to prioritize function auto-completion more, perhaps it should prioritize auto-completion in upper or lower case letters that the user enters?

![image](https://github.com/user-attachments/assets/3408d9b7-1938-4788-96fe-1be075df651a)

**Comment by jakubmisek** [comment]
I think we prioritize symbols, that are imported/visible in the current context. But I agree casing and aliases should be taken into account.

**Comment by jakubmisek** [comment]
Improved in the latest pre-release version.
