### ISSUE TITLE
Conflict with vscode-wordpress-hooks

### ISSUE THREAD

**Issue by soderlind** [DEVSENSE/phptools-docs#60]
<img width="534" alt="composer json — read-offline 2020-07-15 23-17-49" src="https://user-images.githubusercontent.com/1649452/87604116-8e4fb980-c6f8-11ea-9255-348d3ffdeb21.png">

macos: 10.15.5 (19F101)
vs code: 1.47.1
php tools: 1.0.4908
[vscode-wordpress-hooks](https://github.com/johnbillion/vscode-wordpress-hooks): 0.2.1

**Comment by johnbillion** [comment]
I'm the author of the aforementioned extension, and as far as I can tell there is no functional overlap between these two extensions.

**Comment by jakubmisek** [comment]
Thank you @soderlind and @johnbillion, seems there is no actual conflict, as you said. The message will be removed within the next update!

**Comment by jakubmisek** [comment]
fixed in latestb update
