### ISSUE TITLE
Property Hooks support (PHP 8.4)

### ISSUE THREAD

**Issue by rodrigoslayertech** [DEVSENSE/phptools-docs#600]
Hello, since `Property Hooks` has been approved and already implemented in the `alpha2` version of `PHP 8.4`, I create this Issue to track support for this newly syntax.

Reference: [https://wiki.php.net/rfc/property-hooks](https://wiki.php.net/rfc/property-hooks)

**Comment by jakubmisek** [comment]
Good news. Prerelase version already supports property hooks!

**Comment by rodrigoslayertech** [comment]
> Good news. Prerelase version already supports property hooks!

Wow! Very fast! I will test it and buy the license key if it works! Thanks!

**Comment by jakubmisek** [comment]
Feel free to give us feedback on property hooks. There's still a lot of editor features we can add to them, or improve :)

**Comment by rodrigoslayertech** [comment]
> Feel free to give us feedback on property hooks. There's still a lot of editor features we can add to them, or improve :)

![image](https://github.com/user-attachments/assets/d680327a-553a-4ec2-9bd2-501a651cc626)
Does not recognize the $this on hook get

![image](https://github.com/user-attachments/assets/0467f48a-79de-4c21-8d32-0c1e08ab6de1)

**Comment by jakubmisek** [comment]
Good one! Will be fixed tomorrow :)

**Comment by jakubmisek** [comment]
The pre-release `1.49.15785` resolves the `$this` issue, and adds rename refactoring.

We still need to add code completion in case of the short hooks (`get => ...`), and a few more features. Please let us know if anything unexpected happens or if something nice-to-have is missing.
