### ISSUE TITLE
The variable type does not change when reassigning a value

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#601]
![image](https://github.com/user-attachments/assets/753fb088-8fb7-4e18-8f10-6cfb1b5422e3)

**Comment by jakubmisek** [comment]
I think we just prefer the type annotation over code flow analysis; But since this is re-assigned in a different statement, we may respect it

**Comment by jakubmisek** [comment]
related to 
- https://github.com/DEVSENSE/phptools-docs/issues/653
- https://github.com/DEVSENSE/phptools-docs/issues/660
- https://community.devsense.com/d/2118-wrong-variable-type-after-being-reasigned

**Comment by jakubmisek** [comment]
Fixed and prepared for the next update, thank you!
