### ISSUE TITLE
No error for referencing non-existent class's static variable

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#604]
In this code:
![image](https://github.com/user-attachments/assets/fa491dab-8cfe-481b-840e-24b083fc7076)
the class `\vBP_Engine` does not exist. I meant to write `\vBP_Engine` but I forgot the back slash.

However, the IDE didn't catch it and showed to error or warning.

Some more tests:
![image](https://github.com/user-attachments/assets/1a13f866-2a40-477b-bfcc-6d1346bb69b6)

It seems to happen systematically when referencing static variables in a class.

**Comment by jakubmisek** [comment]
That's weird, we should underline any unknown class name,

We only don't underline when indexing is in progress, or when the class was already underlined in the function previously.

**Comment by jakubmisek** [comment]
We also don't underline unknown classes when indexing is has not finished yet.

**Comment by php4fan** [comment]
Does this not reproduce for you?

```
<?php

echo NonExistentClass::$foo;
```

**Comment by jakubmisek** [comment]
@php4fan I see, it does! thank you

**Comment by jakubmisek** [comment]
Fixed
