### ISSUE TITLE
Have "references" show instantiations of classes (using new keyword) when looking at __construct

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#61]
**Narrative:**
As a developer using phptools
I want to be able to find all references of a __construct method (including use of the new keyword to create objects)
So that I can easily find where a class is used.

This is a feature that is for example provided by PHPStorm and I use it in my daily workflows.

![image](https://user-images.githubusercontent.com/3308769/89432583-3590a100-d739-11ea-9a0c-d0c8fc69798c.png)

Actual references detected:

![image](https://user-images.githubusercontent.com/3308769/89433134-daab7980-d739-11ea-9fe7-6521ed803d2f.png)

**Comment by jakubmisek** [comment]
that's a must to have feature for me as well - it works in other languages like C#, and we should do the same.

**Comment by jakubmisek** [comment]
Oh I see - we already do it in full Visual Studio ... but we skipped this feature for the lightweight VS Code :) ... will be added within the next update!

**Comment by addshore** [comment]
Amazing! I look forward to it!

**Comment by jakubmisek** [comment]
implemented in `1.0.5051`+
