### ISSUE TITLE
Do not show useless hovers

### ISSUE THREAD

**Issue by jrmajor** [DEVSENSE/phptools-docs#611]
Currently when you hover over `public`, `return`, `function`, `if` etc. you see a hint like in the screenshot below:

![CleanShot 2024-07-29 at 13 20 44@2x](https://github.com/user-attachments/assets/adc4022e-e8d4-4599-97a3-fc082413bd68)

This does not happen in JS files.

**Comment by jakubmisek** [comment]
I agree; they were previously used for educational purposes together with detailed descriptions (which you can see for other keywords)

for example;
![image](https://github.com/user-attachments/assets/6db31f06-16c8-4520-bf9f-d87d4df71324)

**Comment by jakubmisek** [comment]
fixed in the next update, thanks!

**Comment by jrmajor** [comment]
Thanks!

**Comment by jakubmisek** [comment]
@jrmajor I'm glad it helps!
