### ISSUE TITLE
Simplify syntax highlighting for PHPDoc

### ISSUE THREAD

**Issue by jrmajor** [DEVSENSE/phptools-docs#612]
This is how a complex docblock is currently highlighted:
![CleanShot 2024-07-29 at 15 59 05@2x](https://github.com/user-attachments/assets/4e002d7c-f98c-47be-98b8-d80ba43183c3)

For comparison, this is how a JSDoc is highlighted:
![CleanShot 2024-07-29 at 15 59 55@2x](https://github.com/user-attachments/assets/db950e9b-a0b8-40c9-a1a1-890c2d8d8c38)

I would like the same highlighting rules to apply to PHPDoc: one color for tag (eg. `@param`), second color for type and third color for param name / generic type definition.

**Comment by jakubmisek** [comment]
This is a bug in vscode's builtin php support.

With PHP Tools extension this should look different already - not sure why you don't see it :/

I'll send a screenshot in a few hours how's it suppose to look like.

**Comment by jakubmisek** [comment]
May I ask you to try a different theme? Maybe we use a nonstandars semantic token color.

**Comment by jrmajor** [comment]
The color theme on the screenshot is GitHub Light. I checked with Dark Modern and it looks like the same tokens are highlighted, just with different colors.

**Comment by jrmajor** [comment]
After randomly reopening the file, force retokenizing, making some changes to the file and then reverting them, the syntax highlighting changed:
![CleanShot 2024-07-29 at 20 38 45@2x](https://github.com/user-attachments/assets/ec5b674c-d068-4417-b8fe-d44180487734)

Argument names now have distinct color, but type highlighting is still chaotic. My request to make all types in docblocks have one color would still be relevant.

BTW, I think that it's the parentheses in the last two params that cause following tags to be blue instead of red.

<details>
<summary>(here is the code from the example)</summary>

```php
<?php

/**
 * Some comment
 * @template T of string|int
 * @param array{foo: T, bar: int} $arrayShape
 * @param object{'foo': int, "bar"?: string} $objectShape
 * @param Foo<int, string, bool> $genericClass
 * @param array<string, int> $genericArray
 * @param Foo::STATUS_* $constantEnum Some comment
 * @param int[] $simpleArray Some comment
 * @param non-negative-int $nonNegativeInt
 * @param int<min, 5> $genericInt
 * @param callable(int &$foo, string ...$bar): void $callable
 * @param (Foo&Bar)|null $intersection
 * @return void some comment
 */
function foo(
    array $arrayShape,
    object $objectShape,
    Foo $genericClass,
    array $genericArray,
    int $constantEnum,
    int $simpleArray,
    int $nonNegativeInt,
    int $genericInt,
    $intersection,
    callable $callable,
): void {
}
```
</details>

**Comment by jrmajor** [comment]
Thank you for the explanation. Unfortunately, this really doesn't work for me – I find docblocks very distracting with the current highlighting. Using one color for the entire type in docblock is what is done by built-in JS support with JSDoc, so it feels like it's not unreasonable to expect third party plugins to follow the precedence, although I understand that some people may find more granular highlighting useful. Maybe you could consider adding a setting for that, something like `php.granularDocblockHighlighting`, so that it could be disabled?

**Comment by jrmajor** [comment]
> Here we "fixed" the inconsistency of built-in colors (VSCode does not understand the syntax of PHPDoc well, and breaks the colors).

Sorry, I assumed that VS Code does not highlight PHPDoc at all.

> Sadly we can't "remove" colors from PHPDoc.

Oh, that's bad news. I'll try raising an issue in VS Code repo then. Thank you for your help!

**Comment by jakubmisek** [comment]
That is what we hoped for as well; there are several issues in VSCode's built-in PHP grammar, and I'm pretty sure they won't/can't fix it.

- their grammar tries to colorize keywords in PHPDoc, but
- the (extended) syntax used by PhpStan, Psalm, and others grew and got too complex
- vscode probably can't keep up and won't support the extended syntax

We can however provide a different color, for example, we can dim type names or make them with a single color. If that would help?

**Comment by jrmajor** [comment]
> We can however provide a different color, for example, we can dim type names or make them with a single color. If that would help?

That's exactly what my request was about! I would like the entire type definition to have a single color, just like for JSDoc.

To avoid confusion, here's a mockup of how perfect highlighting for me would look (this is not a screenshot from VS Code, I've just colored this fragment manually in TextEdit):
![CleanShot 2024-07-30 at 10 15 21@2x](https://github.com/user-attachments/assets/e08bdf15-60e8-4c68-a870-7c06fba71abe)

**Comment by jakubmisek** [comment]
I see! There were too many various issues, we'll get there.

I'll add a setting for phpdoc "uniform" types color, something like `"php.docblock.colors": default|simple` ?

**Comment by jrmajor** [comment]
Sounds good to me, I'll leave the naming up to you :)

**Comment by jakubmisek** [comment]
Implemented, setting `"php.docblock.colorMode"`.

Will be available in the next update/pre-release.

Thanks for the suggestion!

**Comment by jrmajor** [comment]
Is it available in `1.49.15818` pre-release? I see it mentioned in the changelog, but VS Code tells me there is no such setting.

**Comment by jakubmisek** [comment]
Sorry for the confusion, the latest one doesn't have it yet.

The next one will :)

**Comment by jakubmisek** [comment]
pre-release `1.49.15843` is out:

![image](https://github.com/user-attachments/assets/56c81a07-f31c-416f-b204-c79e549a2e0d)

**Comment by jrmajor** [comment]
I love it, that's perfect for me. Thanks @jakubmisek!

**Comment by jakubmisek** [comment]
I'm glad it works for you; it was a good suggestion!
