### ISSUE TITLE
No autocomplete suggestions for variables inside "string" right after "\n"

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#613]
Autocomplete suggestions don't work in this scenario:

![image](https://github.com/user-attachments/assets/b678fa4f-f453-4035-8623-fee50f86887d)

It works if I remove the "\n":

![image](https://github.com/user-attachments/assets/581977b0-6fba-4389-a08f-3f60b32c1cac)

**Comment by jakubmisek** [comment]
Thank you for reporting that.

It's caused by any letter character placed before `$`, i.e. `"n$wh"`, and it's a "misbehavior" in VSCode.

I'll try to work around it.
