### ISSUE TITLE
Laravel Storage:disk() return type issue

### ISSUE THREAD

**Issue by lhmuk** [DEVSENSE/phptools-docs#618]
VSCode 1.92.0
PHP Extension: v1.49.15843 (pre-release)
Laravel 10.48.8

![image](https://github.com/user-attachments/assets/ea28d691-7917-4fd9-9684-6d8b0ca95551)

```php
<?php

use Illuminate\Filesystem\FilesystemAdapter;

class TestClass
{
    public function getDisk(): FilesystemAdapter
    {
        return \Storage::disk('my');
    }
}
```

The code works correctly, but Extension considers it an error.

**Comment by jakubmisek** [comment]
Thank you for the sample.

Sadly the annotation in Laravel is wrong; so we incorrectly report an error.

We'll try to workaround this.

**Comment by jakubmisek** [comment]
The correct return type is:

```php
public function getDisk(): Filesystem
```

The code may work by coincidence, but it may eventually throw an error. The warning seems to be correct.

**Comment by lhmuk** [comment]
```php
<?php

class Illuminate\Filesystem\FilesystemAdapter implements Illuminate\Contracts\Filesystem\Cloud
{}

class Illuminate\Contracts\Filesystem\Cloud extends Illuminate\Contracts\Filesystem
{}
```

Ultimately, isn't it correct to say that Illuminate\Filesystem\FilesystemAdapter implements Illuminate\Contracts\Filesystem?

![image](https://github.com/user-attachments/assets/594c1a62-1b4f-4a8c-809d-63d43ca4b3a0)

If you specify Illuminate\Contracts\Filesystem\Filesystem as the type, any method calls outside of its implementation will be flagged as errors.

**Comment by jakubmisek** [comment]
`\Storage::disk()` does not return `FilesystemAdapter` but `Filesystem`.

It does return an instance of `FilesystemAdapter` in most cases but as it is annotated, it may also return something else. Then your program will crash.

I understand you want to "force" the code completion to give you a more specific type; you would probably need to do a type check:

```php
    public function getDisk(): FilesystemAdapter
    {
        $obj = \Storage::disk('my');
        if ($obj instanceof FilesystemAdapter) return $obj;
        throw new UnexpectedValueException();
    }
```
