### ISSUE TITLE
"Goto Implementation" support

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#62]
Quite often in my daily workflows, I find the need to look at all implementations of an interface or classes that extend some other class. Or look at method implementations or overrides.

PHPStorm / IntelliJ provides this next to the `class Foo` definition or method definition in the sidebar (and in some other places)
I'd love to see this in phptools, or if it exists know where it is and have it more prominently exposed.

Using "references" for this case isn't super useful as the cases that I want to look at are jumbled among all the other references.

Example in PHPStorm / IntelliJ...

Exposure of subclasses:
![image](https://user-images.githubusercontent.com/3308769/89433784-a6848880-d73a-11ea-9285-857042e14cc0.png)
Example list of subclasses:
![image](https://user-images.githubusercontent.com/3308769/89433835-b4d2a480-d73a-11ea-8da4-3410d59e2e80.png)
This method is overriding something:
![image](https://user-images.githubusercontent.com/3308769/89433982-e64b7000-d73a-11ea-87fa-cd92d11d0622.png)

**Comment by jakubmisek** [comment]
that's a good idea - in VS Code there might two UI options:

1. a quick action next to the class header similar to phpstorm
2. code lens which is above the class header

**Comment by addshore** [comment]
> 1. a quick action next to the class header similar to phpstorm
> 2. code lens which is above the class header

Not sure quite what the code lens looks like?
Would that also work for method overrides & parents etc? or would that be best for the quick action?

**Comment by jakubmisek** [comment]
Seems VS and VSCode both have standardized "find all implementations" command which we will provide as well.

![image](https://user-images.githubusercontent.com/842150/89529510-279c5800-d7ed-11ea-88fe-adafa473f574.png)

**Comment by jakubmisek** [comment]
implemented since `1.0.5017`
(to be released)

**Comment by addshore** [comment]
Nice, I can verify that it seems to work for me!

Example Find all implementations:

![image](https://user-images.githubusercontent.com/3308769/89787050-c211d980-db14-11ea-9ddd-07bd9deb3129.png)
