### ISSUE TITLE
Generic phpdoc template incorrect

### ISSUE THREAD

**Issue by vitkutny** [DEVSENSE/phptools-docs#620]
Source code from Doctrine ORM:

```
namespace Doctrine\ORM;

interface EntityManagerInterface extends ObjectManager
{
    /**
     * {@inheritDoc}
     *
     * @psalm-param class-string<T> $className
     *
     * @psalm-return EntityRepository<T>
     *
     * @template T of object
     */
    public function getRepository($className);
```

Method call:

```
$this->entityManager->getRepository(MyEntity::class)->findBy($criteria);
```

Actual results:

```
Call to unknown method: MyEntity::findBy() – PHP(PHP0418)
```

Expected result: no errors – expecting getRepository return value to by of type `EntityRepository<MyEntity>` instead of `MyEntity` itself

**Comment by jakubmisek** [comment]
Thank you. I'm trying doctrine/orm v2.18:

![image](https://github.com/user-attachments/assets/2ac689f9-68a9-4e64-99b6-c42b48cf117e)

and it works as expected;

Can you check where the editor guesses the wrong type exactly? Or create a complete small test case. Do you have the correct function signature in tooltip?

![image](https://github.com/user-attachments/assets/baf50459-ce35-4b7f-8d09-4be94d397842)

**Comment by vitkutny** [comment]
Maybe it works differently in VS code <=> VS – if your screenshots are from VS ? I am using VS code extension. Tried upgrading doctrine/orm and reinstalling php extension which didnt help.

<img width="804" alt="Screenshot 2024-08-17 at 10 12 32" src="https://github.com/user-attachments/assets/b3334263-da07-47bf-b6fd-6bf0449a30ba">
<img width="939" alt="Screenshot 2024-08-17 at 10 08 04" src="https://github.com/user-attachments/assets/216c2465-6807-4cda-a6f6-ca12a85621c3">

**Comment by jakubmisek** [comment]
Isn't there an "ide_helper" with some incorrectly generated stubs?

**Comment by vitkutny** [comment]
Found the source of this issue! We are using `nettrine/orm` which integrates Doctrine into Nette framework https://github.com/contributte/doctrine-orm

There is phpstorm metadata file `.phpstorm.meta.php` – everytihing works correctly when deleted https://github.com/contributte/doctrine-orm/blob/master/.phpstorm.meta.php

It was added for phpstorm to be able to detect dynamic return type, but looking at the file its wrong that the definition of `find` and `getRepository` is the same. Dont know if this is working correctly in phpstorm, or getRepository meta should be deleted / edited

**Comment by jakubmisek** [comment]
Awesome! I thought it would be something like this.

It seems the `.phpstorm.meta.php` file is simply incorrect, and it does not work in PhpStorm either (PhpStorm is just much quieter about errors, so people may not notice). I suggest reporting the issue to them as well.
