### ISSUE TITLE
Syntax error when using binary string

### ISSUE THREAD

**Issue by vitkutny** [DEVSENSE/phptools-docs#621]
Code:
```
private const CSV_BOM = b"\xEF\xBB\xBF";
```

Actual result:
```
Syntax error: unexpected token 'b"\xEF\xBB\xBF' – PHP(PHP2014)
```

Expected result: no error

**Comment by jakubmisek** [comment]
Thank you for reporting that.

As a workaround, we support single-quoted binary strings. We'll fix the double-quoted asap.

**Comment by jakubmisek** [comment]
fixed in the upcoming update (pre-release)
