### ISSUE TITLE
Null coalescing operator does not behave same as isset in if condition

### ISSUE THREAD

**Issue by vitkutny** [DEVSENSE/phptools-docs#628]
Code:
```php
namespace Test {

	#[\AllowDynamicProperties]
	final class DefaultTemplate
	{
	}

	$template = new DefaultTemplate();
	$template->foo = 123;

	echo $template->bar ?? ''; # Undefined property: DefaultTemplate::$bar PHP0416

	if (isset($template->bar)) {
		echo $template->bar ?? ''; # OK – does not throw error
	}
}
```

There should be no error when property existence is checked using `??` operator

**Comment by jakubmisek** [comment]
`isset()` has a "quiet" semantic, so it does not throw any warnings or errors. It is used basically to check if the property is undefined so it does not make sense to report in-editor warning for the check.

**Comment by vitkutny** [comment]
> It is used basically to check if the property is undefined so it does not make sense to report in-editor warning for the check.

The problem is opposite – problem is that `??` operator throws error. When `echo $template->bar ?? ''` is basicalliy shortand for `isset($template->bar) ? $template->bar : null`. So it should have same behaviour as "full-size" if condition – do not throw error, because it checks for property existence.

**Comment by jakubmisek** [comment]
You're right, I didn't realize that `??` makes the L-Value "quiet" as well, i.e. it's a shorthand for `isset(L) ? L : R`. 

I suppose we should make `??` quiet as well.

**Comment by jakubmisek** [comment]
fixed in the next update, thanks!
