### ISSUE TITLE
Provide some OUTPUT feedback when initial load of workspace is complete

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#63]
As far as I can tell when I load vscode for my project a bunch of indexing is done by phptools (to be expected).
However as far as I can tell in the IDE there is no indication of the progress of this operation or if it is still running.
My only indication is looking at the output of `htop` and waiting for the CPU usage for drop down.

Some more feedback to the user would be great.
IMO this could be as simple as a line in the OUTPUT saying "Successfully processed X files" or something like that

**Comment by jakubmisek** [comment]
great idea, we're planning following:
- [ ] loading status in status bar
- [ ] current php version indicator/selector

I understand the loading takes some time which we have tried to improve (in my case MediaWiki loads in 4 seconds), but on some machines and some configurations, this time is significantly higher.

**Comment by addshore** [comment]
> I understand the loading takes some time which we have tried to improve (in my case MediaWiki loads in 4 seconds), but on some machines and some configurations, this time is significantly higher.

The speed for me is fine, and as far as I can tell much faster than PHPStorm has been for me in the past.
I have MediaWiki + quite a few skins, extensions and composer packages etc, but it's still fast enough :)

> * [ ]  loading status in status bar

Sounds great!

**Comment by jakubmisek** [comment]
The load status indicator was added to the next update. Also when the whole workspace is running analysis, there is status as well.

For reference; MediaWiki is prepared in less than 5 seconds on a regular dual-core laptop with SSD. If your time will be significantly higher, we will look into some optimizations.
