### ISSUE TITLE
Wrongly suggests replacing ternary operator with null coalescing • PHP7103

### ISSUE THREAD

**Issue by boradatti** [DEVSENSE/phptools-docs#633]
This looks wrong, since ternaries aren't equivalent to null coalescing most of the time. 

![image](https://github.com/user-attachments/assets/88b77504-e585-46a3-8128-84eaa1ef8860)

It might be better to instead recommend replacing with the `?:` Elvis operator.

```php
echo (0 ? 0 : 'nope') . PHP_EOL; // nope
echo (0 ?? 'nope') . PHP_EOL; // 0
echo (0 ?: 'nope') . PHP_EOL; // nope
```

**Comment by jakubmisek** [comment]
That's a good point.

You're right that `?:` is best suited.

**Comment by jakubmisek** [comment]
fixed in the next update/pre-release, thanks!
