### ISSUE TITLE
Calling `is_numeric` on string converts variable type to float/int

### ISSUE THREAD

**Issue by vitkutny** [DEVSENSE/phptools-docs#634]
Calling `is_numeric` on string converts variable type to float/int. It should remain string – specificaly can be changed to `numeric-string` similar to phpstan behaviour https://phpstan.org/writing-php-code/phpdoc-types#other-advanced-string-types

Code with error:

```php

$string = '0123';

if (is_numeric($string)) {
	echo trim($string, '0'); # Argument '1' passed to trim() is expected to be of type string, float|int given – PHP0406
}

```

Expected result: no error

**Comment by jakubmisek** [comment]
thanks, this inferring will be removed for now.
