### ISSUE TITLE
Typed class constants seems not supported? 

### ISSUE THREAD

**Issue by yinheli** [DEVSENSE/phptools-docs#639]
![image](https://github.com/user-attachments/assets/71eabb3d-734e-4182-b687-dd348656024b)

rfc: https://wiki.php.net/rfc/typed_class_constants

**Comment by ging-dev** [comment]
> ![image](https://private-user-images.githubusercontent.com/235094/360747658-71eabb3d-734e-4182-b687-dd348656024b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODc5MDgsIm5iZiI6MTcyNDM4NzYwOCwicGF0aCI6Ii8yMzUwOTQvMzYwNzQ3NjU4LTcxZWFiYjNkLTczNGUtNDE4Mi1iNjg3LWRkMzQ4NjU2MDI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNDMzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmUwZjc4YjYxNzJjNTMwODYwZDFiMmNiYjRmODgwNTVlMGUzODg3ZDBmZmZiM2IwMjQ4ZmFjZDU2NGEzZjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HVJR6N_GbpyQiuUpAoOXNQvM06Z6MXYjNWJh2XOoJr4)
> 
> rfc: https://wiki.php.net/rfc/typed_class_constants

Make sure you set php version to 8.3:

![image](https://github.com/user-attachments/assets/0c5c1ec7-05df-4f99-be55-1e80591f6a6d)

**Comment by ging-dev** [comment]
@jakubmisek there is a hover error with const

![image](https://github.com/user-attachments/assets/c298de66-217b-4a95-b350-adf180be6d8b)

**Comment by jakubmisek** [comment]
> @jakubmisek there is a hover error with const

hover for typed const fixed, thanks @ging-dev !

**Comment by jakubmisek** [comment]
closing; switching language level to 8.3 fixes the issue
