### ISSUE TITLE
Deprecated method problems don't go away if I remove the @deprecated tag

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#64]
If I have a @deprecated phpdoc annotation above a method that causes a PHP6406 problem to be listed in another file
When I remove that @deprecated phpdoc annotation
I would expect that the PHP6406 problem in the other file would go away / not be listed
Instead the PHP6406 problem continues to be listed

If I remove and re add the method call the PHP6406 problem will no longer appear.

**Comment by addshore** [comment]
It looks like intelephense for example already does this, so looks like it is already possible within vscode, but phptools doesn't implement it yet

![image](https://user-images.githubusercontent.com/3308769/89543755-3852cb00-d7f9-11ea-8dff-712495010bae.png)

**Comment by jakubmisek** [comment]
Oh you are right, we suppose to do that. Will be fixed!

**Comment by jakubmisek** [comment]
fixed since 1.0.5031 (to be released)
