### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kauai03** [DEVSENSE/phptools-docs#641]
- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.50.15906`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.92.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Marku/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment]
Please:

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️file:///c%3A/Users/Marku/AppData/Local/Temp/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt
