### ISSUE TITLE
Error warnings sometimes appear in `vendor`

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#643]
They sometimes appear for no apparent reason, I have to open the file with the error warning and close the file and the error will be hidden, however they will appear again a while later:
![image](https://github.com/user-attachments/assets/06a2ad1a-8a79-4a1e-b42c-dea36af7187c)

**Comment by ging-dev** [comment]
Call to unknown function: 'get_terms' with package `php-stubs/wordpress-stubs`, it seems `get_terms` is not cached even though it is defined

**Comment by jakubmisek** [comment]
This may be caused by an invalid composer.json? or the package is missing in your composer.json?

Please try to run the command "clear /vendor/ cache" if it helps.

**Comment by jakubmisek** [comment]
The function may be hidden because of its `@internal` phpdoc tag, I'll take a look at it because we should not treat it like this.

**Comment by ging-dev** [comment]
> The function may be hidden because of its `@internal` phpdoc tag, I'll take a look at it because we should not treat it like this.

Perhaps hiding the `@internal` method is not a good idea, some package use it incorrectly, instead a gray warning should be given to users to be careful when using them.

**Comment by jakubmisek** [comment]
fixed, thanks :)

**Comment by jakubmisek** [comment]
after the update, `clear vendor cache` may be needed

**Comment by jakubmisek** [comment]
FYI: we have included the stub for Wordpress (command pallete -> PHP: stubs -> Wordpress)

ofcourse this @internal function is not there yet either, but it will
