### ISSUE TITLE
Import class at quick-fix sometimes doesn't work

### ISSUE THREAD

**Issue by ivan88217** [DEVSENSE/phptools-docs#644]
It's a really nice feature to import class when I forget to use them.
But I found some class will work at quick-fix but some class will not, since update to v1.49

some class works:
![image](https://github.com/user-attachments/assets/cb81765a-5357-4943-a1ff-741f1f6b59a6)

some class doesn't works (v1.49 and above):
![image](https://github.com/user-attachments/assets/c79e40d3-d311-4ac0-95d9-a51a6193bef6)

same code at old version works (v1.48 and earlier):
![image](https://github.com/user-attachments/assets/94711450-b330-488f-9858-51a55249df03)

**Comment by ivan88217** [comment]
I found that the same class in the comments can be imported, but the other one in the code cannot.

![image](https://github.com/user-attachments/assets/75c7e336-ead5-4f14-b8e4-136ec86b2922)
![image](https://github.com/user-attachments/assets/bd398082-4793-4e79-ba9a-15854663faef)

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

Let me check.

**Comment by jakubmisek** [comment]
Are you using "Quick Fix..." command:
<img width="275" alt="image" src="https://github.com/user-attachments/assets/56074140-79f1-43d9-8bfc-8c28c15214f1">

Or the "Light Bulb"
<img width="275" alt="image" src="https://github.com/user-attachments/assets/7ebe8a47-4e97-4c7f-8c9b-4b9f76dc46a2">

?

**Comment by ivan88217** [comment]
Quick Fix command

**Comment by jakubmisek** [comment]
I see, thanks!

**Comment by jakubmisek** [comment]
fixed, will be working again in the next update. Thanks!
