### ISSUE TITLE
Sophos Antivirus is Marking Your Extension as Ransomware

### ISSUE THREAD

**Issue by intellisoftwaremx** [DEVSENSE/phptools-docs#646]
I install this extension on my Visual Code in my Mac and my Sophos Antivirus is alerting me that this program is Ransomware Malware. See the screenshot.

Do i need to remove it from my VCode?

<img width="603" alt="Screenshot 2024-09-08 at 9 40 23 PM" src="https://github.com/user-attachments/assets/232ad515-296c-470a-9930-be4998490061">

**Comment by Miloslav** [comment]
Hello,

That is a false positive finding. 

No other antivirus flagged this particular binary https://www.virustotal.com/gui/file/5c178c4db860127a7fbbf547fcbc4da97bf8585dc5351c0ed96ffb3b0b4d10c3/detection

Could you please contact Sophos support team, so they can fix this false positive?

Thank you!
