### ISSUE TITLE
Inconsistent Cursor Behavior with Auto-Closing Quotes in Attributes

### ISSUE THREAD

**Issue by codez-test** [DEVSENSE/phptools-docs#649]
# Inconsistent Cursor Behavior with Auto-Closing Quotes in Attributes

## Current Behavior
When typing an HTML/PHP attribute (e.g., `id=`), the plugin auto-completes it to `id=""` and places the cursor between the quotation marks. If the user then manually types a double quote (which is a common habit for some developers), the cursor jumps to the outside of the closing quote, resulting in `id=""|` (where | represents the cursor position).

## Expected Behavior
After auto-completion of `id=""` with the cursor between the quotes, if the user manually types a double quote, the cursor should remain between the quotation marks. The expected sequence would be:

1. User types: `id=`
2. Plugin auto-completes to: `id="|"` (where | is the cursor)
3. User types a double quote
4. Cursor should remain: `id="|"` 

Instead of the current behavior where it becomes: `id=""|`

## Why This Matters
This current behavior disrupts the workflow of developers who are accustomed to manually typing closing quotes, even when auto-completion is active. It requires an extra step (moving the cursor back) to continue editing the attribute value, which can be frustrating and reduce productivity, especially when working with numerous attributes.

## Additional Context
- This behavior is consistent across different file types (HTML, PHP, etc.) where attributes are used.
- The issue persists regardless of the `editor.autoClosingQuotes` setting.

## Environment
- VS Code Version: 1.93.0
- PHP Extension Version: PHP Devsense -  v1.51.15986
- OS: [Windows 11]

**Comment by jakubmisek** [comment]
Thank you for your suggestion. This behavior is from VSCode itself (you can try it in a pure `.html` file), and it is by purpose.

When the cursor is inside the snippet `id="|"`, writing quote `"` is treated as a closing quote.

There are several HTML settings related:
- `html.autoCreateQuotes`
- `html.autoClosingTags`

I can only suggest creating an issue/feature request at https://github.com/microsoft/vscode/issues 

Please correct me if I misunderstood.

**Comment by codez-test** [comment]
Ok. Thank you for getting back to me so quickly. I am posting this issue to Vs code
