### ISSUE TITLE
Incorrect method signature for `PDOStatment::execute()`

### ISSUE THREAD

**Issue by Pamblam** [DEVSENSE/phptools-docs#650]
![Screenshot 2024-09-13 at 9 00 55 AM](https://github.com/user-attachments/assets/311e49d2-cb6f-4306-a276-2c39300643d7)

It's showing that the signature for PHP's [`PDOStatment::execute()`](https://www.php.net/manual/en/pdostatement.execute.php) takes a parameter of type "type" so whenever I put the correct type, an array, I get the squiggly lines.

I have searched around and was surprised to not see anyone else with the same issue, so perhaps something with my settings? If so, could you tell me how to fix it?

**Comment by jakubmisek** [comment]
thank you for reporting the issue! will be fixed.

**Comment by jakubmisek** [comment]
please make sure, you have the latest version (1.51). This was a few years old bug, already fixed.

<img width="742" alt="image" src="https://github.com/user-attachments/assets/40639381-14f8-418a-a03b-0be012a0f0a2">
