### ISSUE TITLE
Quick Fix for "use fully_qualified_class_name" does not add a new line before first `use`

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#655]
When using the quick fix to add a missing use or to turn a fully qualified name into a shortened one with a use, if this results in the very first `use` being added in that file, it does not add a newline before the use. This often results in  a namespace towards the top of the file followed by a use with no newlines in between. This is true even though I have the following setting `"php.format.rules.blankLinesBeforeUseStatements": 1`

**Comment by jakubmisek** [comment]
Thanks for noticing that! Adding the newline and fixing a few related issues.

**Comment by jakubmisek** [comment]
The update `1.51.16045` adds the newline. 

For future, we will also format the added `use` according your formatting settings.

**Comment by still-dreaming-1** [comment]
The fix isn't working for me. I end with something like this towards the top of my file, with the missing newline:

```
namespace The\Namespace;
use The\Added\Use\Class;

// rest of the code
```

It doesn't seem to be the result of any other extensions I have installed, but I haven't tried disabling them all as there are so many of them.

**Comment by jakubmisek** [comment]
Thanks for trying the update. I'll add a few more tests and fix this.

**Comment by jakubmisek** [comment]
Fixed and preparing updated pre-release

**Comment by still-dreaming-1** [comment]
Works well in v1.51.16197, thanks.

**Comment by jakubmisek** [comment]
Thank you for the confirmation.

In the future update, we'll also respect the `blanklines` setting.
