### ISSUE TITLE
The functions in the namespace do not appear in the autocomplete list

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#656]
It seems that the functions placed in the namespace will not be listed in the suggestion list.

**Comment by jakubmisek** [comment]
@ging-dev May I ask for an example? This should work:

![fncompletion](https://github.com/user-attachments/assets/a7417fae-16f2-41dc-b75b-ae4901d52ab5)

**Comment by ging-dev** [comment]
> @ging-dev May I ask for an example? This should work:
> 
> ![fncompletion](https://private-user-images.githubusercontent.com/842150/368144245-a7417fae-16f2-41dc-b75b-ae4901d52ab5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzI3NzMsIm5iZiI6MTcyNjU3MjQ3MywicGF0aCI6Ii84NDIxNTAvMzY4MTQ0MjQ1LWE3NDE3ZmFlLTE2ZjItNDFkYy1iNzViLWFlNDkwMWQ1MmFiNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTY0MjcyOWQwZTU4ZGQzYjM1MDBiZWVjYzFlM2Q4MTY4MzE1NWJmMmM1Y2MxNmVkNzM3MDEzOGQ5NzAxNWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tPYbBQRTJPpzIgis1psn_KVdOnG69HWTh9nD-2KzXhw) [ ![fncompletion](https://private-user-images.githubusercontent.com/842150/368144245-a7417fae-16f2-41dc-b75b-ae4901d52ab5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzI3NzMsIm5iZiI6MTcyNjU3MjQ3MywicGF0aCI6Ii84NDIxNTAvMzY4MTQ0MjQ1LWE3NDE3ZmFlLTE2ZjItNDFkYy1iNzViLWFlNDkwMWQ1MmFiNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTY0MjcyOWQwZTU4ZGQzYjM1MDBiZWVjYzFlM2Q4MTY4MzE1NWJmMmM1Y2MxNmVkNzM3MDEzOGQ5NzAxNWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tPYbBQRTJPpzIgis1psn_KVdOnG69HWTh9nD-2KzXhw) ](https://private-user-images.githubusercontent.com/842150/368144245-a7417fae-16f2-41dc-b75b-ae4901d52ab5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzI3NzMsIm5iZiI6MTcyNjU3MjQ3MywicGF0aCI6Ii84NDIxNTAvMzY4MTQ0MjQ1LWE3NDE3ZmFlLTE2ZjItNDFkYy1iNzViLWFlNDkwMWQ1MmFiNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTY0MjcyOWQwZTU4ZGQzYjM1MDBiZWVjYzFlM2Q4MTY4MzE1NWJmMmM1Y2MxNmVkNzM3MDEzOGQ5NzAxNWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tPYbBQRTJPpzIgis1psn_KVdOnG69HWTh9nD-2KzXhw) [ ](https://private-user-images.githubusercontent.com/842150/368144245-a7417fae-16f2-41dc-b75b-ae4901d52ab5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzI3NzMsIm5iZiI6MTcyNjU3MjQ3MywicGF0aCI6Ii84NDIxNTAvMzY4MTQ0MjQ1LWE3NDE3ZmFlLTE2ZjItNDFkYy1iNzViLWFlNDkwMWQ1MmFiNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTY0MjcyOWQwZTU4ZGQzYjM1MDBiZWVjYzFlM2Q4MTY4MzE1NWJmMmM1Y2MxNmVkNzM3MDEzOGQ5NzAxNWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tPYbBQRTJPpzIgis1psn_KVdOnG69HWTh9nD-2KzXhw)

You can test with this package, maybe it not work with package in `vendor`
https://github.com/hyperf/collection/blob/master/src/Functions.php

**Comment by ging-dev** [comment]
> @ging-dev May I ask for an example? This should work:

I found the cause, if the file with a namespace it will reproduce the bug:

```php
<?php

namespace Other;
```

**Comment by jakubmisek** [comment]
thanks! fixed
