### ISSUE TITLE
Highlight deprecated methods in a different way to other problems

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#66]
One feature that our team misses is strikethrough for use of deprecated methods and classes, rather than just highlighting them as another generic problem.
Not sure if this is really an issue for phptools of for vscode in general, happy to move this issue to vscode if needed or be told it is already possible.

**Comment by jakubmisek** [comment]
They are currently reported with a different severity - informational - underlined with a different color. So it is not a warning nor error. Not sure if it helps.

**Comment by addshore** [comment]
Indeed it sounds like perhaps this would need to be another level implemented in vscode to allow some sort of highlighting in a different way? (such as a strikethrough)?

**Comment by jakubmisek** [comment]
vscode allows for
- red underline (error)
- yellow underline (warning)
- blue underline (informational problem)
- dimmed text (used for unused variables)

we can choose any of these, but strikethrough does not make much sense for me personally.

**Comment by addshore** [comment]
I think strikethrough is fairly common in IDES for deprecated things AFAIK

Netbeans example: https://netbeans.org/images_www/articles/73/java/editor-codereference/coloring.png
Eclipse: https://www.eclipse.org/pdt/images/2.2m7/more-syntax-coloring.png
Jetbrains / Intelij: https://blog.jetbrains.com/wp-content/uploads/2018/11/mps-UIUX_New-Actions-to-find-deprecated-code_3.png

It looks like the inteliphense vscode plugin also does this so I imagine it should be possible for phptools too

![image](https://user-images.githubusercontent.com/3308769/89647977-5e8a7080-d8b6-11ea-8bc6-457948de033f.png)

**Comment by jakubmisek** [comment]
you're right, ok let's see if we can do the same with VSCode!

**Comment by jakubmisek** [comment]
thanks, implemented and will be avail. in next update

![image](https://user-images.githubusercontent.com/842150/89651368-1e31ef00-d8c4-11ea-93a1-9f99025bbfbb.png)

**Comment by jakubmisek** [comment]
should it be also underlined? for now we don't underline it and treat the deprecated function call with "hint" severity

**Comment by addshore** [comment]
Looking good to me!

![image](https://user-images.githubusercontent.com/3308769/89787358-39e00400-db15-11ea-9ce2-f068b240a550.png)
