### ISSUE TITLE
Wrong variable type after being reasigned

### ISSUE THREAD

**Issue by str** [DEVSENSE/phptools-docs#660]
I'm hinting the class to a $variable, because I'm setting the class on runtime. After that, the $variable changes it's type, hinted by a method, but the new type is not reflected, and the old type is still used, which is wrong

1) setting the $field as AbstractField
![image](https://github.com/user-attachments/assets/150fbda7-7fc1-4cbb-955e-cc2ce1c91cda)

2) confirming $field is an AbstractField
![image](https://github.com/user-attachments/assets/4099ec9d-d5c1-4807-b38f-d4c70b498d9d)

3) overwriting $field with $field->html() which returns a string, so $field should be a string now
![image](https://github.com/user-attachments/assets/abbab983-3a24-4d36-888c-8a88339c8bf9)

4) but vscode still thinks $field is an AbstratField, not a string
![image](https://github.com/user-attachments/assets/d11a90c7-374a-4e1b-a8a1-7e3a6e5352ea)

**Comment by jakubmisek** [comment]
Thank you,

The issue has been fixed, will be prepared for the next update.
