### ISSUE TITLE
False positive error when accessing a class property defined as @property or @property-read

### ISSUE THREAD

**Issue by marinaglancy** [DEVSENSE/phptools-docs#662]
Hello!

The following valid code gives an error "Member has protected visibility and is not accessible from the current context."

```
<?php

/**
 * @property-read int $id
 */
class MyClass {
    protected int $id;

    public function __get($name) {
        return $this->$name;
    }
}

$a = new MyClass();
echo $a->id;
```

![php_error_protected](https://github.com/user-attachments/assets/02ef905d-929b-45e3-a392-28080d933905)

**Comment by jakubmisek** [comment]
Thank you for the test case @marinaglancy,

We'll implement better treating of `property-read` and `property-write`.

**Comment by jakubmisek** [comment]
Thank you @marinaglancy ,

We have fixed this issue by first respecting the `@property` from PHPDoc.

The fix will be available in the next update.
