### ISSUE TITLE
Cannot understand 64-bit PHP requirements

### ISSUE THREAD

**Issue by Vectorial1024** [DEVSENSE/phptools-docs#665]
As per Composer docs:

https://getcomposer.org/doc/01-basic-usage.md#platform-packages

> To require a 64bit version of php, you can require the `php-64bit` package.

------

However, if I have `"php-64bit": ">=8.3"` in `composer.json`, then the tools warn me about this syntax, which should be allowed in PHP 8.3:

```php
class TestClass
{
    // Construct typed constants is supported since PHP 8.3PHP(PHP6401)
    public const int TEST_CONST = 5;
}
```

This problem does not occur if I have `"php": ">=8.3"` in `composer.json`.

**Comment by jakubmisek** [comment]
Thank you for reporting that.

We automatically detect your PHP version based on `composer.json`, and we didn't recognize this syntax - will be fixed.

As a workaround, you can manually select your PHP version using settings (https://docs.devsense.com/en/vscode/php-version#choosing-php-version)
