### ISSUE TITLE
File -> Create new Class

### ISSUE THREAD

**Issue by shyim** [DEVSENSE/phptools-docs#669]
Hey,

I am trying always to switch from PhpStorm, but what I really miss is that I can click New Class type my class name and it creates a new file and already fills the boilerplate:

```
<?php

declare(strict_...);

namespace <auto-detected>;

class MyClass {

}
```

I would make my life SO much easier, if that would be possible 🤔

**Comment by shyim** [comment]
whoopsie, https://github.com/DEVSENSE/phptools-docs/issues/191

**Comment by jakubmisek** [comment]
Thank you for the feature request, and for finding the duplicate :)
