### ISSUE TITLE
Code key word coloring errors

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#672]
I am using version: 1.51.16078. The code keywords coloring appears to be off after a particular line of code. See 2 examples below:

![Screenshot_1](https://github.com/user-attachments/assets/8261178e-dd12-4f23-b3dd-ad65b133fc89)

![Screenshot_2](https://github.com/user-attachments/assets/05dbb87f-62c2-43fb-83fe-44b42dc4d590)

**Comment by jakubmisek** [comment]
Thank you for the details.

This looks weird, but we don't change the colors of variables in the PHP code (only in PHPDoc comments).

Can it be another extension?

**Comment by murugappanrm** [comment]
I will recheck and advise

**Comment by murugappanrm** [comment]
I used this extension "jrieken.bisectdemo" to debug the extensions. I found that the Alpinejs extension "sperovita.alpinejs-syntax-highlight" was the culprit. I disabled the extension things are fine now. Please close this issue.

**Comment by jakubmisek** [comment]
Thank you @murugappanrm for digging into it and finding the cause of the problem. I appreciate it.
