### ISSUE TITLE
False positive with `self` in cache

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#673]
`Argument '1' passed to stream() is expected to be of type Symfony\Component\HttpClient\Response\self[]|Traversable, Symfony\Contracts\HttpClient\ResponseInterface givenPHP(PHP0406)`

Maybe cache in `vendor` not resolve `self` correctly, (maybe include `static`)

**Comment by jakubmisek** [comment]
Thanks! Right, `self[]` gets corrupted in cache. Do you know what file has this definition? (https://github.com/symfony/http-client/tree/7.2/Response)

**Comment by ging-dev** [comment]
> Thanks! Right, `self[]` gets corrupted in cache. Do you know what file has this definition? (https://github.com/symfony/http-client/tree/7.2/Response)

This line, i guess: https://github.com/symfony/http-client/blob/7f387663bf3d3418d41950a663bf1375960c830c/Response/TransportResponseTrait.php#L138

**Comment by jakubmisek** [comment]
Fixed, we'll prepare pre-release soon!
