### ISSUE TITLE
Format switch

### ISSUE THREAD

**Issue by str** [DEVSENSE/phptools-docs#674]
From my experience there are 2 major (very different) coding standards: PSR-12 and WordPress. One can have it's own preferences, or pick some rules from one or the other, but in general, most projects are either PSR-12 or WordPress.

If I have to switch between developing a Laravel project and then switch to a WordPress plugin, I will need to go one by one through all format rules between one or the other. Specially after purchasing the pro license, there are a lot of flags.

Could there be a way to switch between PSR-12 / WordPress standards? I could manually customize rules after applying the switch, but as an initial setup that would be great.

Thank you.

**Comment by Miloslav** [comment]
Hello,

Yes, you can use code-style settings for that. 

[Code styles in VS Code](https://docs.devsense.com/en/vscode/editor/code-styles) They serve as a base and you can customize on top of them.

In Visual Studio we have Code styles as well, but they work slightly differently. They change the global settings. I think it would be useful to be able to customize per project basis as well.
![image](https://github.com/user-attachments/assets/19773861-ed78-47f3-94d7-06402c6d00da)

**Comment by str** [comment]
Thank you.
