### ISSUE TITLE
PHPDocs array shape

### ISSUE THREAD

**Issue by gilney-canaltelecom** [DEVSENSE/phptools-docs#679]
Hi, i would like to know if this is normal or if i'm doing something wrong...

![image](https://github.com/user-attachments/assets/f5758a32-228c-4d5d-8d01-5b43e8fc1c58)

In this case, shouldn't the array shape described appear on hover in some way instead of `array<bool|string>`?

The autocomplete inside the class works, but from outside there is no way to know what should be passed to $params (besides opening the class, of course)...

VS Code info:
```
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

Extension version: v1.51.16099

**Comment by jakubmisek** [comment]
Hello, and thank you for the issue.

We simplify the types (for historical reasons), but we can fix this in the next update.

**Comment by jakubmisek** [comment]
Structured array types will be shown in tooltips in the next update.

Thanks!

**Comment by ging-dev** [comment]
> Structured array types will be shown in tooltips in the next update.
> 
> Thanks!

Maybe incorrect in this case:

```php
/**
 * @param array{string, int} $data
 * @return void
 */
function test($data) {
}
// it give me function test(array{int: int, string: string} $data): void, must be function test(array{string, int} $data): void
```

**Comment by jakubmisek** [comment]
thanks @ging-dev , implemented!

<img width="513" alt="image" src="https://github.com/user-attachments/assets/2ff768fa-93d5-4f1c-8ec3-f08d28f2f47a">
