### ISSUE TITLE
Seems to conflict with SonarSource.sonarlint-vscode plugin, but they provide different functionality

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#68]
I saw that this recently happened with another plugin, so though I would also create an issue for `SonarSource.sonarlint-vscode` so we can investigate.

e.g. Sonar Lint reports array_slice([1,2,3], 0,2);, php tools does not

**Comment by jakubmisek** [comment]
the extension is allowed since the next update, thanks

we'll take a look onto !
```php
array_slice([1,2,3], 0,2);
```

**Comment by jakubmisek** [comment]
@addshore what's wrong with `array_slice([1,2,3], 0, 2);` ?

**Comment by addshore** [comment]
So the sniff that is returned by sonar lint is as follows (when the return is not used, sorry I should have specified that).

![image](https://user-images.githubusercontent.com/3308769/89787749-ec17cb80-db15-11ea-991d-e9729cbf5e04.png)

So Sonar Lint and phptools should probably be able to work side by side rather than complain that they conflict.
Looking at 1.0.5029 it seems this might be already fixed then (I don't see it pop up)? :)

**Comment by jakubmisek** [comment]
Right, now it does not report the conflict. Anyways our goal is to report all those issues, more precisely and with less CPU usage. So in the future, having both might be redundant.
