### ISSUE TITLE
Use Quick Fix "Remove Unused Uses and Sort" in codeActionsOnSave

### ISSUE THREAD

**Issue by Morgy93** [DEVSENSE/phptools-docs#683]
Hello,

there is a Quick Fix "Remove Unused Uses and Sort":

![image](https://github.com/user-attachments/assets/c07ddc1e-c487-48f7-9af9-029d67959867)

I want to be able to use that in the actions on save:

```
"editor.codeActionsOnSave": {
      "source.fixAll": "explicit",
      "source.fixAll.eslint": "explicit",
      "source.organizeImports": "explicit" <---- does not do what the quick fix does
  },
```

Is it possible to add some some `phptools.removeUnusedUsesAndSort` or bind it to the system `source.organizeImports`?

**Comment by jakubmisek** [comment]
Thank you for pointing this out.

We've changed the default behavior in "editor.codeActionsOnSave" so it behaves the same as other languages in VSCode.

To "Remove Unused and Sort' on save, use the following

```json
  "source.sortAndRemoveImports": "explicit"
```


I'll update the documentation as well.
