### ISSUE TITLE
PHP0413 Error (Unknown Class) for symlinked packages

### ISSUE THREAD

**Issue by julesgilson** [DEVSENSE/phptools-docs#684]
Intellisense is always showing **"unknown class" PHP0413** for composer **packages installed from local repo**. Unsure if this is because composer creates a symlink in `./vendor/publisher/` to the package or for another reason.

> Note: This is on Windows - symlinks on *nix systems may not have the same issue - if it is a link issue.

Re-importing the class fixes the issue until VSC is restarted - where the problem returns. Quite tedious as the package is used in many other classes...

This scenario is common when developing composer packages - i.e before they can be installed from Packagist

---

Package installed with Composer from a repo defined in `composer.json`:

```
"repositories": [
        {
            "type": "path",
            "url": "../relativepathto/package"
        }
    ],
```

As this is a `path` type repo, by default composer creates a symlink in `./vendor/publisher/` to the package's source

Is therefore included in `./vendor/composer/installed.json`:

```
{
            "name": "publisher/package",
            "version": "dev-master",
            "version_normalized": "dev-master",
            "dist": {
                "type": "path",
                "url": "../relativepathto/package",
                "reference": "a7acca5e62f96425339de18a781fee5a83e7b84a"
            },
           ... ...
            "type": "library",
            "extra": {
                "laravel": {
                    "providers": [
                        "publisher\\package\\provider"
                    ]
                }
            },
            "installation-source": "dist",
            "autoload": {
                "psr-4": {
                    "publisher\\package\\": "src/"
                }
            },
            ... ...
            "transport-options": {
                "relative": true
            },
            "install-path": "../publisher/package"
        },
```

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

We specifically handle symlinked packages on Windows - let me check what we're doing wrong here.

**Comment by jakubmisek** [comment]
It seems we incorrectly ignore any directories (after resolving the symlink) that are outside the workspace root. Will be fixed!

**Comment by julesgilson** [comment]
I am sure I saw an email with a further response from you.... not showing here! In it you mentioned you found the source of the issue and that it would be fixed. Any update when?

**Comment by jakubmisek** [comment]
> I am sure I saw an email with a further response from you....

sorry, it was a mistake. I thought I found the culprit :)

**Comment by julesgilson** [comment]
so, um... any ideas for a work around? It is driving me crazy having to reimport every class every time I open a file 😕

**Comment by jakubmisek** [comment]
is the symlink target outside of the workspace folder?

**Comment by julesgilson** [comment]
> is the symlink target outside of the workspace folder?

yep. Its a Laravel package in dev - installed in a few test projects with composer - so creates a symlink to source in the vendor folder of each project.

I could move the package source to a project's vendor folder - but that only solves the problem for one project.

I guess my question is... is this just something that can't be fixed? If so I will have to get creative. (maybe syncing copies of the source to each projects vendor folder.) I would prefer the correct solution if that is possible.

Thanks.

**Comment by jakubmisek** [comment]
The latest release (1.53) fixes the indexing of packages symlinked outside the vendor folder.

Please let us know if it works now.

Maybe it will be necessary to run VSCode Command from Command Palette: "clear /vendor/ cache".

Thanks!

**Comment by julesgilson** [comment]
That doesn't seem to have worked.

I updated to V1.53.16338 - restarted VSC - cleared vendor cache and it still doesn't see the package that is symlinked in composer.

I tried removing the `use` statement from one file, restarting VSC and re-adding it - which works until VSC is restarted. This is the same behaviour as before, can click to import class and get a toast "The class is already imported" but it does then clear all the errors and I get class info on hover - until VSC is restarted.

I note that after clearing the vendor cache the extension output lists the packages it has cached again. The package in question is not in that list....
```
[Info  - 9:08:09 AM] PHP Language Server Started (PID: 17144)
[Info  - 9:08:11 AM] Loaded 141 package(s) from cache in 00:00:01.1616301.
[Info  - 9:08:11 AM] Deleting C:\Users\xxx\AppData\Local\DEVSENSE\packages-cache ...
[Info  - 9:08:13 AM] Processing packages in c:\Users\xxx\vendor\composer\installed.json ...
[Info  - 9:08:13 AM] Processing packages in c:\Users\xxx\vendor\composer\installed.json ...
[Info  - 9:08:13 AM] Processing done in 00:00:00.0000477.
[Info  - 9:08:19 AM] Processing done in 00:00:05.7303397.
[Info  - 9:09:20 AM] Storing package asm89/stack-cors@v2.0.3 cache ...
[Info  - 9:09:20 AM] Storing package aws/aws-crt-php@v1.0.2 cache ...
etc...
```
Here is the package's entry in `\vendor\composer\installed.json` (as created by composer)
```json
{
    "name": "xxx/yyy",
    "version": "dev-master",
    "version_normalized": "dev-master",
    "dist": {
        "type": "path",
        "url": "../yyy/_package",
        "reference": "a7acca5e62f96425339de18a781fee5a83e7b84a"
    },
    "require": {
        "firebase/php-jwt": "^5.5",
        "guzzlehttp/guzzle": "^7.4"
    },
    "require-dev": {
        "laravel/framework": "^8.65",
        "php": "^7.3|^8.0"
    },
    "type": "library",
    "extra": {
        "laravel": {
            "providers": [
                "xxx\\yyy\\ServiceProvider"
            ]
        }
    },
    "installation-source": "dist",
    "autoload": {
        "psr-4": {
            "xxx\\yyy\\": "src/"
        }
    },
    "license": [
        "MIT"
    ],
    "authors": [{
            "name": "xxx",
            "email": "zzz"
        }
    ],
    "description": "A package",
    "transport-options": {
        "relative": true
    },
    "install-path": "../xxx/yyy"
}
```

Thanks.

**Comment by jakubmisek** [comment]
Thank you for checking and for the details.

Based on this:
```json
 "install-path": "../xxx/yyy"
```

The package's actual path is `c:\Users\xxx\vendor\yyy'` ?

**Comment by jakubmisek** [comment]
Thank you very much for the details! and for the sample solution.

**Comment by julesgilson** [comment]
> Thank you very much for the details! and for the sample worspace.

It annoys me that much to have to keep re-importing the classes - anything to help you fix it! 😄

**Comment by jakubmisek** [comment]
> It annoys me that much to have to keep re-importing the classes - anything to help you fix it! 😄

I totally understand :) we'll definitely fix this asap.

The quick workaround is to open/add the folder with "package_a" to your VSCode workspace. If it's not there, we are ignoring it (which is not correct)

**Comment by julesgilson** [comment]
🤸‍♂️ - yep 1.53.16357 fixes it! Thanks.

**Comment by jakubmisek** [comment]
thank you for the confirmation!
