### ISSUE TITLE
Inlay hint does not check php version settings

### ISSUE THREAD

**Issue by ntm-dev** [DEVSENSE/phptools-docs#686]
Hey there.

The named argument feature was introduced in php version 8.0.0

My current php setted to 5.6:
![image](https://github.com/user-attachments/assets/3e86fbc8-d1b5-45b6-bf71-2b69bf14107f)

However, the insert hint is still displayed and I can double-click for named argument:
![image](https://github.com/user-attachments/assets/31b821f0-d35d-4aec-a1a8-25171124180d)

That doesn't make sense for php version <8.0

**Comment by jakubmisek** [comment]
Thank you for the issue;

The inlay hint is a helper information that tells developers the name of the bound parameter. It does not respect the PHP version by purpose.

However; we can disable insert-on-double-click for PHP < 8.0
