### ISSUE TITLE
Return type of ArrayAccess::offsetGet is incorrect

### ISSUE THREAD

**Issue by ntm-dev** [DEVSENSE/phptools-docs#689]
My current php setted to 7.4:
![image](https://github.com/user-attachments/assets/ab0ca63c-ff62-412d-be74-78a2ecc9a52f)

Error `Declaration of ArrayIterator::offsetGet($key) must be compatible with ArrayAccess::offsetGet(mixed $offset): mixed` has been displayed:

![image](https://github.com/user-attachments/assets/34652fb6-f2b7-4041-9b0e-f2686049d8eb)

But the mixed type available as of PHP 8.0.0

see [PHP: Type declarations](https://www.php.net/manual/en/language.types.declarations.php)

**Comment by jakubmisek** [comment]
Thank you! Upcomning update fixes the falsy warning in PHP <= 8.1.
