### ISSUE TITLE
PHP0413 & PHP0406 iterable issues

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#69]
In the below code example iterable seems to be fine in the actual type for $a (not shown in the example), but phptools seems to complain about it in the phpdoc.

`PHP0413`, Use of unknown class: 'iterable'

```
/**
 * @param iterable $a
 */
function someMethod( a ) {
	var_dump( $a );
}
```

When trying to pass this method an array phptools also complains, and I imagine it has the same root cause.

```
someMethod( [] );
```

`PHP0406 Argument '1' passed to someMethod() is expected to be of type iterable, array given`

**Comment by jakubmisek** [comment]
you are right, `iterable` is a reserved keyword and should be recognized in PHPDoc

**Comment by jakubmisek** [comment]
fixed in the next update, thank you
