### ISSUE TITLE
Feature Request: Add a code action to create a use import for a function call

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#693]
This would be very similar to the code action "use ClassName". For example, it could be offered for code like this: `\gzencode($data, 9);`
The action would add `use function gzencode;` below the use imports for classes. The line where the function call is made would be changed to not have a "\\" character. This is a convention I have noticed in several modern php projects where they prefer to have a use import instead of a fully qualified name for function calls, including for calling built-in php functions.

**Comment by jakubmisek** [comment]
good idea, thanks!

**Comment by jakubmisek** [comment]
implemented, thanks! Will be in the next update.
