### ISSUE TITLE
Type pruning issue

### ISSUE THREAD

**Issue by tanzanite777** [DEVSENSE/phptools-docs#694]
Type: <b>Bug</b>

Code snippet for explanation
```php
function bug(?int $why = null) : void {
    if($why !== 42) {
        /** @trace $why */
        if($why !== null) throw new Error("bug: $why"); // incorrect: "Cannot implicitly convert 'void' to 'string' PHP(PHP0410)"
    }

    // perhaps related concerns:
    // if the code above would be fixed - i wonder if the code below would break (due to the long standing signature bugs)
    $buf = ob_get_clean(); // ob_get_clean signature is wrong - true is not an option!
    if($buf !== '') echo "buf: $buf"; // mostly-correct ('bool' must be 'false'): "Cannot implicitly convert 'bool' to 'string' PHP(PHP0410)"
    if($buf !== false && $buf !== '') echo "buf: $buf"; // correct: no issues found
}
```

Extension version: 1.51.16099
VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.99GB free)|
|Process Argv|--crash-reporter-id adf79977-8c83-4303-918e-a7dfc5f31bf1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
showbadge:31153266
5fd0e150:31155592

```

</details>

**Comment by ging-dev** [comment]
May same problems with my case:

```php
<?php

class A {
    /** @var array<string> */
    public array $methods;
}

$a = null;
if ($r) {
    if ($r instanceof A) {
        $a = $r;
    }
}

$b = $a->methods; // $b can't resolve type to string[], even through $a is A|null
```

**Comment by jakubmisek** [comment]
thanks @tanzanite777  - fixed and prepared for the next udpate.

**Comment by jakubmisek** [comment]
@ging-dev `$b` should be resolved to `string[]`:

<img width="610" alt="image" src="https://github.com/user-attachments/assets/ea028433-9336-4ca0-8a4c-6b942f984155">

Maybe just the tooltip is incorrect?

**Comment by ging-dev** [comment]
> @ging-dev `$b` should be resolved to `string[]`:
> 
> <img alt="image" width="610" src="https://private-user-images.githubusercontent.com/842150/376784647-ea028433-9336-4ca0-8a4c-6b942f984155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDYwMDcsIm5iZiI6MTcyOTA0NTcwNywicGF0aCI6Ii84NDIxNTAvMzc2Nzg0NjQ3LWVhMDI4NDMzLTkzMzYtNGNhMC04YTRjLTZiOTQyZjk4NDE1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwMjI4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQ2ZWYzYjM1NmZlYjFmYzQwMjI3OTgyMzIzNTlhNzYxNzc5ZjcwOGJkMWMyZGU4N2U5ZDllYjgyNGZlN2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5TEc9i-DNlkUtNCPzPls_ofHuGWBsQlP_gOUJid6Mzs">
> Maybe just the tooltip is incorrect?


`@trace` is correct but tooltip and autocomplete not working:

![image](https://github.com/user-attachments/assets/751f9f25-6a8d-4641-9f8c-6a27d60beb55)

**Comment by jakubmisek** [comment]
@ging-dev I see, thanks. Will be fixed!

**Comment by jakubmisek** [comment]
@ging-dev I've created a new issue for this.

The original issue has been fixed.
