### ISSUE TITLE
phpdoc local variable

### ISSUE THREAD

**Issue by zak-wojtek77** [DEVSENSE/phptools-docs#697]
If is written such phpdoc:

```php
/* @var $register \Register */
$register = $arr['register'];
```
or
```php
/** @var $register \Register */
$register = $arr['register'];
```
there is no hint for the class "\Register".

The first is used in NetBeans the second is used in PHPStorm.

**Comment by ging-dev** [comment]
> If is written such phpdoc:
> 
> ```
> /* @var $register \Register */
> $register = $arr['register'];
> ```
> 
> or
> 
> ```
> /** @var $register \Register */
> $register = $arr['register'];
> ```
> 
> there is no hint for the class "\Register".
> 
> The first is used in NetBeans the second is used in PHPStorm.

This is valid spec for local variable in phpstan/psalm/phpstorm:
```php
/** @var \Register */
$register = $arr['register'];
```
or
```php
/** @var \Register $register */
$register = $arr['register'];
```

**Comment by jakubmisek** [comment]
Thank you for the discussion.

I confirm. If it is written the other way `/** @var $name TYPE Description */`, then the _TYPE_ is often confused with _Description_.
