### ISSUE TITLE
hint for ??

### ISSUE THREAD

**Issue by snithfferx** [DEVSENSE/phptools-docs#700]
Hi.
I got an issue when I declare something like "$result = isset($array['key']) ? $array['key'] : null" the extension wants "$result = $array['key'] ?? null" this is not well see by PHP, because, "$result = $array['key'] ?? null" it returns boolean, not a value.

The symbol "??" returns boolean, when you are trying to see if a key is set or not on an array.

It is not a problem, but annoying when you are trying to format well the code.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

`??` does not return `false`, it is a null-coalescing operator shortly described at https://stackoverflow.com/a/53610732/601646

It should be alright. Do you have a more complete example where it's not working as expected?

**Comment by snithfferx** [comment]
sorry about the confusion.
try this: an array with associative keys, then try ?? in a not set index and you cannot do what the long way give you. 
I mean this:
$array = ['locals' =>[], 'vars' =>[]] ;
$user = $array['useroptions'] ?? null; 

is not the same as:
$user = isset($array['useroptions']) ? $array['useroptions'] : null; 

Is just for esthetics, so it cannot be solve is OK. Just a little annoying jejeje🙃

**Comment by jakubmisek** [comment]
oh, but I think it is the same. Those two lines will have the same behavior:

```php
$user = $array['useroptions'] ?? null;
$user = isset($array['useroptions']) ? $array['useroptions'] : null;
```

The first one is preferred, because it's a smaller code so less likely to make a mistake.

**Comment by jakubmisek** [comment]
I did a simple test to compare "??" and "isset(a) ? a : ...":

<img width="512" alt="image" src="https://github.com/user-attachments/assets/3e652f13-ab2f-41d9-b5b7-1e4dfe2b5441" />

Both results are equal, hence the code action is correct.

You can disable the code action for simplifying to `??` using the setting described at https://docs.devsense.com/vscode/Code%20Actions/hide-code-action/

Thank you for the comments, and please feel free to post any other issue you find. We'll be happy to take a look at it :)
