### ISSUE TITLE
lose type when extends class

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#702]
![image](https://github.com/user-attachments/assets/08dee4fb-8b87-4204-adad-296d081f50a8)

May related: https://github.com/DEVSENSE/phptools-docs/issues/577

**Comment by jakubmisek** [comment]
thanks for the test case! implemented

**Comment by ging-dev** [comment]
> thanks for the test case! implemented

Hi @jakubmisek, i'm missing this test case:

![image](https://github.com/user-attachments/assets/3b0a3046-5175-40d9-b999-c80cffd34e73)

**Comment by jakubmisek** [comment]
thanks, https://github.com/DEVSENSE/phptools-docs/issues/702#issuecomment-2429808489 fixed in the next update
