### ISSUE TITLE
Union array shape being simplify

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#703]
![image](https://github.com/user-attachments/assets/249123a5-d08b-41ad-9dbc-744f0155ae32)

**Comment by jakubmisek** [comment]
Thank you for the suggestion.

The upcoming update will merge the structured array properties, and types of those properties, into a single element:

<img width="496" alt="image" src="https://github.com/user-attachments/assets/d59d4d05-3f4c-4c3f-bdc2-ea4797f78537" />

The order of properties will be undefined tho.
