### ISSUE TITLE
No warning for incompatible override

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#704]
This code:
```
<?php

class ParentClass {
    function test($foo = "", $bar = "") {
        
    }
}

class ChildClass extends ParentClass {
    function test($foo, $bar = "") {
        
    }
}
```

will trigger a fatal error in PHP 8 and a warning in PHP 7:
```
Warning: Declaration of ChildClass::test($foo, $bar = '') should be compatible with ParentClass::test($foo = '', $bar = '')
```

Therefore, I'd expect it to be highlighted as warning or error in the IDE, but there's nothing.

I can't remember if I explicitly configured my project somewhere to target PHP 7 (which is what I'm actually targeting) rather than 8, and therefore whether to expect a warning or an error, but either way, I'm getting neither.

**Comment by jakubmisek** [comment]
Thank you. Yes, we don't check the parameter's initial value yet. It will be implemented.

**Comment by jakubmisek** [comment]
We've added some checks for parameters initial value.

There is still more we can do, please feel free to report anything that should be also reported. (after we release the udpate :))
