### ISSUE TITLE
Keybindings are Broken

### ISSUE THREAD

**Issue by JonesScherver** [DEVSENSE/phptools-docs#706]
After the update to the newest version of the project, the keybindings Ctrl + F2 and Ctrl + F don't work anymore.
This is a real pity because I do like this extension. I have downgraded the version and everything worked fine again.
So please fix this.
I'm working on Windows 11.
And my IDE is VS Code.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

This may be hard to solve as we don't override or handle keybindings.

`Ctrl+F` as for the regular "Find" command?

**Comment by JonesScherver** [comment]
Ah, okay, I didn't know that. 
Then maybe I didn't rule out the right source of the problem, but I am still pretty sure.
Yes, Ctrl+F is the regular "Find" command.

**Comment by jakubmisek** [comment]
May I ask you to check the VSCode main menu -> Settings -> Keyboard Shortcuts.

<img width="441" alt="image" src="https://github.com/user-attachments/assets/793acb20-9a56-4f7a-a530-0dbfeb7dd8c3">



Search for "Find" and there will be more details on **Source** who is handling the shortcut and how:

<img width="1162" alt="image" src="https://github.com/user-attachments/assets/b8d7c818-e5a0-4221-bd74-55a0f3522a33">

**Comment by JonesScherver** [comment]
My screenshots look just like your picture. However, I think you can close this issue because when I tried to take screenshots of the broken search "popup," it worked fine. So, downgrading and then upgrading again has solved the issue.

**Comment by jakubmisek** [comment]
@JonesScherver thank you for the update, and I'm sorry I couldn't provide more help with this. I'm glad it works now.
