### ISSUE TITLE
No quickfix for "The use directive is unnecessary." PHP(PHP7001)

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#71]
In the screenshot the following use statement is not used.

```
use Wikimedia\Rdbms\LoadBalancer;
```

![image](https://user-images.githubusercontent.com/3308769/89790501-ec19ca80-db19-11ea-89ac-ac35dc842ef8.png)

I would have expected a qucikfix to be available to remove it.

**Comment by jakubmisek** [comment]
thanks for the idea! will be implemented in the next update (1.0.5044+)
