### ISSUE TITLE
Cannot use object of type 'FFI\CData' as array

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#710]
Actually it can:
```php
/** @var \FFI\CData $a */
$a;
$a[$i] = ...
```

**Comment by jakubmisek** [comment]
Thank you. [`FFI\CData`](https://www.php.net/manual/en/class.ffi-cdata.php) has a lot of dynamicity. We have to implement them all.

**Comment by jakubmisek** [comment]
FFI\CData won't be reported when used as an array.

The rest of `CData` special uses are still not handled and we will adjust the diagnostics in future.
