### ISSUE TITLE
posix_getsid() is not recognized by PHP parser

### ISSUE THREAD

**Issue by neuralldev** [DEVSENSE/phptools-docs#711]
the posix_getsid() function exist for a long time and is not recognised by intelliphp with either php 7.X or 8.X code. 
it should be added as it is a basic php function call to interact with tasks. 

the exact error message is: 

> (Warning sign) Call to unknown function: 'posix_getsid' (PHP0417)

used in my section of code: 

`  if (file_exists($pid_file)) {
          if (@posix_getsid(trim(file_get_contents($pid_file)))) 
            $return['state'] = 'ok';
          else 
            shell_exec(system::getCmdSudo() . 'rm -rf ' . $pid_file . ' 2>&1 > /dev/null');
        }
   `

**Comment by jakubmisek** [comment]
Please add a "posix" stub, using "Workjspace Stubs" command from Command Palette:

<img width="594" alt="image" src="https://github.com/user-attachments/assets/9e0521d2-c1eb-4f80-9b9c-055ec6621020">

<img width="604" alt="image" src="https://github.com/user-attachments/assets/9b8c2283-cbbe-4e1c-b348-5bf2114f776d">

It is dsabled by default on non-Windows machines.
