### ISSUE TITLE
Return Type warning when type is correct

### ISSUE THREAD

**Issue by murugappanrm** [DEVSENSE/phptools-docs#712]
My extension version : 1.52.16226

In the Laravel code shown below, the return type is defined as View and the return value is  view but it generates a warning. I am not sure why?

![Screenshot_3](https://github.com/user-attachments/assets/c1b98ffa-aff8-401f-af35-acff16ea6815)

**Comment by jakubmisek** [comment]
Thank you for the issue.

I think the `View` is a facade to "view" service, and we don't handle this case well.

**Comment by murugappanrm** [comment]
So how do i get rid of this type of error? Dont define the return type?

**Comment by jakubmisek** [comment]
For now, yes, you can not define the return type.

But it is a bug on our side.

**Comment by jakubmisek** [comment]
When I actually run the code, I'm getting this exception:

```
Return value must be of type View, Illuminate\View\View returned
```

I guess, you need to add `use Illuminate\View\View;` to make it work. I'm not getting the warning then:

![image](https://github.com/user-attachments/assets/057f4b39-a778-4887-8c0c-6ff7e7a00056)

**Comment by murugappanrm** [comment]
Yep, it works. The code action was also helpful. Otherwise it would be extremely difficult with Laravel being monolithic and messy. I am fan of Codeigniter which small, simple and fast (documentation needs a lot of improvement).

Thank you for your assistance. Leave it to you to determine if this issue should be closed.

**Comment by jakubmisek** [comment]
Thank you for the confirmation.

Since the warning is actually correct, we'll keep it as it is.
