### ISSUE TITLE
How to turn off parameter prompts

### ISSUE THREAD

**Issue by itliujia** [DEVSENSE/phptools-docs#713]
I am not very accustomed to such parameter prompts. Can I set them in configuration?

![微信截图_20241029151238](https://github.com/user-attachments/assets/059c537d-8771-48bc-84c5-b2bdc1fd2cff)

**Comment by jakubmisek** [comment]
Thank you for the question.

The feature is called "inlay hints", you can enable/disable various kinds of inlay hints in VSCode settings (command `Open Settings (UI)`):

<img width="310" alt="image" src="https://github.com/user-attachments/assets/850e37b4-37be-4f19-ae47-af06f1a2e07c">

<img width="620" alt="image" src="https://github.com/user-attachments/assets/58c5a0f3-32e6-4bbc-8b4e-7f743f943607">

Or you can disable them all using the setting `"editor.inlayHints.enabled"`.

**Comment by itliujia** [comment]
Thank U
