### ISSUE TITLE
Formatting in saved files does not work anymore

### ISSUE THREAD

**Issue by Morgy93** [DEVSENSE/phptools-docs#714]
Hello,

for me, the formatter does not work anymore as soon as a file is saved.

If I open a new tab with CMD + N and type:

```
<?php

    $test = 'test';
```

The formatter changes it to:

```
<?php

$test = 'test';
```

Which is fine. But if I save the file to the disc via CMD + S like Test.php and do the same thing, the formatter does nothing.

Any idea?

```
Version: 1.95.0-insider
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:14:20.189Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.0.0

PHP Tools for Visual Studio Code: v1.52.16266
```

**Comment by jakubmisek** [comment]
Thank you for reporting that. We broke format-on-type in the latest update; releasing fix now.

**Comment by Morgy93** [comment]
I cannot confirm that the `v1.52.16271` fixes it. 

@jakubmisek Still broken for me, any idea?

**Comment by jakubmisek** [comment]
@Morgy93 I can confirm, `v1.52.16271` is working for me now.

**Comment by jakubmisek** [comment]
@Morgy93 there is one more related bug, it seems that may be causing the issue in your case. Working on it.

**Comment by Morgy93** [comment]
`v1.52.16273` fixes it, thank you 🫶
