### ISSUE TITLE
Invalid "use of unknown class" (PHP0413) errors

### ISSUE THREAD

**Issue by tanzanite777** [DEVSENSE/phptools-docs#722]
Type: <b>Bug</b>

Issue has been present for quite a while, but i mostly just ignored it - might be something with my settup, but i got nowhere while investigating. Managed to create a minimal reproduction - that at least always exhibits the problem on my system. Here goes ...

Make a new folder and add two files - index.php and composer.json.

```
<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

require 'foo/bar/autoload.php';

$chk = new PHPMailer(true); // Use of unknown class: 'PHPMailer\PHPMailer\PHPMailer' PHP(PHP0413)
$chk->SMTPDebug = SMTP::DEBUG_LOWLEVEL; // Use of unknown class: 'PHPMailer\PHPMailer\SMTP' PHP(PHP0413)
$chk->isSMTP();
```

```
{
    "config": {
        "vendor-dir": "foo/bar/"
    },
    "require": {
        "phpmailer/phpmailer": "^6.9.2"
    }
}
```

Then do the usual "composer update" and then create a new workspace for this folder.

Open index.php - and it cannot find any of the PHPMailer classes. Opening the relevant PHPMailer class will cause it to find the class and remove the problems and closing it restores the bogus problems.

VSCode settings of note (user):
"php.problems.scope": "all"
"php.problems.exclude": { "/foo/bar/" : true } -- just checking, yep, works
nothing in "files.exclude"

Noticed nothing interesting in output (PHP Language Server / etc)

... i am out of ideas.

Extension version: 1.53.16338
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.52GB free)|
|Process Argv|--crash-reporter-id adf79977-8c83-4303-918e-a7dfc5f31bf1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by jakubmisek** [comment]
It's fixed with the latest v1.53.16357 (pre-release), the same issue as https://github.com/DEVSENSE/phptools-docs/issues/684
