### ISSUE TITLE
Running tests without debugging tries to connect to XDebug

### ISSUE THREAD

**Issue by 1stthomas** [DEVSENSE/phptools-docs#723]
When I run the tests without debugging I get following error in Output/Tests:
`[Error] Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 127.0.0.1:9003 (through xdebug.client_host/xdebug.client_port).`

When I debug the tests the above error doesn't get logged and it works as expected. The problem is, when running over 100 Tests I have to wait more than 10s longer after the tests are finished until all these error are logged.

I could reproduce the problem with this simple test repo: https://github.com/1stthomas/phptool-sample-project

Versions:
- PHP: 8.3.3
- PHPTools: 1.82.20175

**Comment by Miloslav** [comment]
Hello Thomas,

Thank you for the issue and sample test repo. Please let me check that and get back to you.

**Comment by Miloslav** [comment]
Hello Thomas,

Could you please try to create xdebug log when running the tests and send it to me?

Add to php.ini:
```
xdebug.log="C:\Windows\Temp\xdebug.log"
```

I think you have this in your php.ini:
```
xdebug.start_with_request=yes
```

which should be fine, because when just running the script and not listening for xdebug connection, Xdebug wait just 200ms. the log would look like:

```
[101088] Log opened at 2024-11-27 14:46:57.074212
[101088] [Step Debug] INFO: Connecting to configured address/port: 127.0.0.1:9003.
[101088] [Step Debug] ERR: Time-out connecting to debugging client, waited: 200 ms. Tried: 127.0.0.1:9003 (through xdebug.client_host/xdebug.client_port) :-(
[101088] Log closed at 2024-11-27 14:46:57.478000
```

**Comment by 1stthomas** [comment]
Here the logs of a single, simple test run:  
```sh
[21252] Log opened at 2024-11-27 15:14:06.536488
[21252] [Step Debug] INFO: Connecting to configured address/port: 127.0.0.1:9003.
[21252] [Step Debug] ERR: Time-out connecting to debugging client, waited: 200 ms. Tried: 127.0.0.1:9003 (through xdebug.client_host/xdebug.client_port).
[21252] [Step Debug] INFO: Connecting to configured address/port: 127.0.0.1:9003.
[21252] [Step Debug] ERR: Time-out connecting to debugging client, waited: 200 ms. Tried: 127.0.0.1:9003 (through xdebug.client_host/xdebug.client_port).
[21252] Log closed at 2024-11-27 15:14:08.151220
```
I started a single test which doesn't have a data provider defined. But, as opposed to your log example, I get 2 connection attempts.  

This is the command for this test (I removed some parts, which are replaced by "<" some text in between and ">"):  
```sh
>> "C:\<some_path>\php-8.3.3\php.exe" -ddisplay_errors=1 "-cC:\<some_path>\php-8.3.3" -dxdebug.mode=debug -dxdebug.client_host=127.0.0.1 -dxdebug.client_port=9003 -dxdebug.start_with_request=yes -dxdebug.idekey=PHP-XDEBUG "-dinclude_path=<some_include_paths>" "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\<a_hash>\phpunit-11.1.3.phar" -c "C:\<project_path>\phpunit.xml.tmp" --teamcity --colors=never --testsuite PhpTools_TestSuite --filter '(^<namespace>\\TrafficLightColorValuesTest::testGetAllColorStrings(\s|$))'
```
I don't have any XDebug config in my `php.ini` besides the newly added log config.
As you can see, PHPTools defines `-dxdebug.mode=debug` . Related description of this config:
> Enables [Step Debugging](https://xdebug.org/docs/step_debug). This can be used to step through your code while it is running, and analyse values of variables.  

Src: https://xdebug.org/docs/all_settings#mode  
Also `-dxdebug.start_with_request=yes` is coming from PHPTools. When I look at that I think we need different commands for step debugging and for the simple test runs.

**Comment by 1stthomas** [comment]
Hello Miloslav,
Sounds good, thank you very much!

**Comment by Miloslav** [comment]
Hi Thomas,

Could you please try the latest pre-release? https://www.devsense.com/en/download and let me know if that solves this issue for you?

Thank you

**Comment by 1stthomas** [comment]
Hello Miloslav,  
I can confirm: the new pre-release version from 2024-12-03 fixes the problem of this issue.  
Following a sample output of a single test method:  
![image](https://github.com/user-attachments/assets/026996ad-9c69-4ef3-bd00-459b669b7bd8)
 Thank you very much!
