### ISSUE TITLE
losing warnings when accessing private properties

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#724]
It seems that the cache system for /vendor/ has recently been optimized and does not store the private properties and methods of the class, but that means there will be a loss of warnings when users try to access private properties and may affect feature https://github.com/DEVSENSE/phptools-docs/issues/701 in the future.

**Comment by jakubmisek** [comment]
good point!

**Comment by jakubmisek** [comment]
private members are respected now, may need to run command: clear /vendor/ cache
