### ISSUE TITLE
How to disable code actions?

### ISSUE THREAD

**Issue by gremo** [DEVSENSE/phptools-docs#727]
![image](https://github.com/user-attachments/assets/13db953d-107e-4468-9f22-95eef3993add)

First time using this VSCode extension, thank you for the great work!

I don't use code actions. Is it possible to disable the lightbulb icon that appears when I click on something?

**Comment by jakubmisek** [comment]
Thank you @gremo! Sure, please see the settings at https://docs.devsense.com/en/vscode/code%20actions/hide-code-action#hide-all-code-actions 

Although I hope you will find code actions, diagnostics, code fixes, and refactorings useful :)

**Comment by jakubmisek** [comment]
That's alright @gremo , I hope it works well for you

**Comment by gremo** [comment]
Sure, it works! 👍 I hope this beautiful extension will be available in the future as a one-time lifetime payment—it would be amazing!
