### ISSUE TITLE
Asymmetric visibility support for (PHP 8.4)

### ISSUE THREAD

**Issue by gremo** [DEVSENSE/phptools-docs#728]
[Asymmetric visibility](https://wiki.php.net/rfc/asymmetric-visibility-v2) seems not supported so far (good on work btw, works like without issues)?

```php
class Person {
    public private(set) ?int $age = null;
}
```

![image](https://github.com/user-attachments/assets/df2aaac9-416b-41ec-ab67-7ebecce289c0)

> Syntax error: unexpected token ')'

**Comment by jakubmisek** [comment]
Thank you for reporting the issue!

You are right, this is not implemented (we did not expect _this_ to be included in PHP 8.4!).

**Comment by gremo** [comment]
Thanks. Are you planning to implement that (maybe there is an ETA?)?

**Comment by jakubmisek** [comment]
Yes, this will be implemented. We'll try to make it within a week or two.

**Comment by jakubmisek** [comment]
The feature has been implemented, and we'll publish pre-release within a few hours
