### ISSUE TITLE
Phrasing of notice is different from the PHP one and misleading

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#732]
This code in PHP:
```
function whatever() {
    return 3;
}

$x = &whatever();
```

generate a notice in PHP 7 and 8 that says:
> Notice: Only variables **should be assigned** by reference

https://3v4l.org/TCoKn

However, in the IDE, it's phrased like this:
> Only variables **can be _passed_** by reference

![image](https://github.com/user-attachments/assets/fd7ab66c-aff9-46d9-8114-26b60b5573f5)

This might seem pedantic, but it can actually be confusing.
I had a real-life use case that was more like this:

```
<?php

class TestClass {
    static $foo = 23;
}

class OtherClass {
    static function doSomethingByReference(&$x) {
        $y = $x;
        return $y;
    }
}


$bar = &OtherClass::doSomethingByReference(\TestClass::$foo);
```
and it took me a while to figuring out because, since it said "*passed* by reference", I thought the problem was here:
![image](https://github.com/user-attachments/assets/0e4cd3a1-c1c2-424d-a5eb-59e979cefcab)

**Comment by jakubmisek** [comment]
I see, thank you for the test case.

We try to underline the exact expression causing the warning, but here we may be more specific.

The phrasing will be updated, as I remember we reported it back when PHP 5.4 was a thing.

**Comment by jakubmisek** [comment]
thanks @php4fan , we added a separate diagnostic code for "Only variables should be assigned by reference" (PHP0445)
