### ISSUE TITLE
Let executablePath to be configured on a workspace level

### ISSUE THREAD

**Issue by gyulavoros** [DEVSENSE/phptools-docs#733]
We are using Laravel Sail for local development, which means that PHP is running in a Docker container. I want to configure the VS Code extension in a way that "forwards" PHP executable invocations into the container.

I'm trying to configure it like:
`"php.executablePath": "${workspaceFolder}/bin/php"`

`bin/php` is a bash script that sets the correct `$PWD` and invokes `sail php`.

The problem is that `php.executablePath` seems to have an "application scope", so it's not possible to configure it on a workspace level.

Things are working great if I hardcode the absolute path to the project instead of using `${workspaceFolder}`.

Would it be possible to make `php.executablePath` configurable on the workspace level?

**Comment by jakubmisek** [comment]
Thank you for pointing this out!

The setting has been updated. The update  will be included in the upcoming pre-release and release.

- `"php.executablePath"` setting can be changed in workspace scope settings.
- `"php.executablePath"` and `"php.executables"` can contain variables, i.e. `"${workspaceFolder}/bin/php"`.
