### ISSUE TITLE
Laravel code style formats differently than Pint

### ISSUE THREAD

**Issue by gyulavoros** [DEVSENSE/phptools-docs#734]
We have a project setup with Pint configured as a git hook, so it reformats changed files automatically. We also have the DEVSENSE extension configured in VS Code to format PHP files automatically on save. We use the `"php.format.codeStyle": "Laravel"` setting. The extension applies different formatting rules, that Pint enforces, which means it's a continuous whack-a-mole between Pint and the extension, as they overwrite each other's changes.

One example would be Laravel migrations, where the extension produce:
```
return new class extends Migration {
```
however, Pint would format
```
return new class extends Migration
{
```

**Comment by Miloslav** [comment]
This will be addressed in the upcoming pre-release.

Thanks!

**Comment by gyulavoros** [comment]
Looking forward to taking a look! Thank you for the superfast response. 🙏

**Comment by Miloslav** [comment]
No problem. If you run into any other inconsistency please let us know.

**Comment by gyulavoros** [comment]
@Miloslav I think there's one more, Laravel defaults to not having spaces around colons in return type signatures, as per defined in [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/return_type_declaration.rst).

The DEVSENSE extension, however, puts one space before the colon, e.g.:

```
public function up() : void
```

**Comment by Miloslav** [comment]
@gyulavoros Thanks! You're right, it will be fixed as well.

**Comment by gyulavoros** [comment]
@Miloslav There's one more, it's related to string concatenation, the default style doesn't use spaces, where the extension adds spaces around the dot, e.g.

**Laravel default**
```
require __DIR__.'/admin.php';
```

**Extension**
```
require __DIR__ . '/admin.php';
```

**Comment by Miloslav** [comment]
Thanks, will be fixed as well. Please let us know if you run into anything else

**Comment by Miloslav** [comment]
Fixed in the latest.

Closing the issue for now, but please reopen if you run into anything else.

Thanks!
