### ISSUE TITLE
socket_set_option does not recognize IPPROTO_IP and MCAST_JOIN_GROUP

### ISSUE THREAD

**Issue by neuralldev** [DEVSENSE/phptools-docs#735]
I cannot get rid of these warning with PHP 8.x constants for socket_set_option like for example for mDNS listening:

<img width="936" alt="image" src="https://github.com/user-attachments/assets/00b251e6-a4c4-4d21-978d-c30a7876b6b9">

the error messages are:

<img width="936" alt="image" src="https://github.com/user-attachments/assets/b4cd7144-4fa0-488d-adf7-d4be993e444e">

in php Stubs options, socket is correctly checked

<img width="588" alt="image" src="https://github.com/user-attachments/assets/6a93965d-46af-488b-bb7a-07665dede7c1">

**Comment by jakubmisek** [comment]
The constants were already added in the latest Pre-Release version.

The full release will be published soon.
