### ISSUE TITLE
"Rename symbol" on global variable in one file renames variables of the same name in completely unrelated files WITHOUT WARNING

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#736]
I renamed a global variable in one php file with "Rename Symbol", and as a result,global variables of the same name in other completely **unrelated scripts** throughout my **entire project** got renamed. Never in a million years would I have imagined that was a possibility. Not without asking me for confirmation.

Unfortunately I didn't realize until a few hours later. This has basically destroyed my codebase. Of course I have all under version control and I can roll back, but I have already done a lot of work after that before I realized, so now I have to review all the changes manually to distinguish the legitimate changes from the bogus ones. 

To reproduce:

1. create 2 files:

```
// file1.php
<?php

$foo = 123;

echo $foo;
```
```
//file2.php
<?php
foreach ($things as $foo) {
  echo $foo;
}
?>
```
2. In `file1.php `, right-click on variable `$foo`, select "Rename Symbol" and change the name to `$bar`

Expected: should only replace occurrences of that actual variable, and only within the current file, OR (given that in this case it's a global variable, which may or may not be the same variable as other global variables of the same name in other files) ask the user whether they want to perform the same renaming in all files in the current project.

Observed: with no warning, also renames the variable `$foo` in file 2.

I performed an extension bisect, and the option "rename symbol" is not available until the devsense extension gets enabled, so I assume it's a function provided by the extension.

**Comment by jakubmisek** [comment]
Thank you for pointing this out, and sorry for the trouble!

It used to popup the confirmation window, but something in VSCode has changed - we'll look at it asap.

**Comment by jakubmisek** [comment]
renaming a global variable in another file will always show preview window first
