### ISSUE TITLE
How to prevent the installation of related VSCode extensions?

### ISSUE THREAD

**Issue by gremo** [DEVSENSE/phptools-docs#738]
Hi, first thank you for the best VSCode PHP extension ever made! I'm just interested in the basic PHP features, is there any way to avoid the installation of PHP Profiler and IntelliPHP extensions?

My container right now has just the` DEVSENSE.phptools-vscode` extension, but the other gets installed automatically.

**Comment by jakubmisek** [comment]
thank you @gremo !

We intentionally moved those features into separate extensions so you can uninstall them (https://code.visualstudio.com/docs/editor/extension-marketplace#_uninstall-an-extension). Once you uninstall them, VSCode won't install them again during the next update.

**Comment by gremo** [comment]
Thanks @jakubmisek for the quick answer! Sure I can, but being the the extensions of `devcontainer.json`, they would pop up again as I rebuild, am I right?

**Comment by jakubmisek** [comment]
@gremo good point! I didn't realize it's a bit more complicated in containers.

I have found the solution in a year-old release note: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_85.md#opt-out-of-extensions

**Comment by gremo** [comment]
Never heard of that! That'is the solution 👍

**Comment by gremo** [comment]
It's not working btw, I guess this is a relly old option that doesn't work anymore 😄 

```
"-devsense.intelli-php-vscode"
"-devsense.profiler-php-vscode"
```

Given that those are the correct extension IDs.

**Comment by jakubmisek** [comment]
Hmm yes, those IDs are correct. I'll try to find a different solution if it exists ...

**Comment by jakubmisek** [comment]
is it at least possible to disable those extensions using VSCOde configuration?
