### ISSUE TITLE
`Go To Definition` with Asymmetric Property Visibility

### ISSUE THREAD

**Issue by alexraputa** [DEVSENSE/phptools-docs#741]
<img width="532" alt="Знімок екрана 2024-12-12 о 11 37 58" src="https://github.com/user-attachments/assets/0dc0a464-f72c-4937-84b9-354c03cbbdb3" />
<img width="660" alt="Знімок екрана 2024-12-12 о 11 38 32" src="https://github.com/user-attachments/assets/a1f225a9-6494-4d1a-94c1-835a7f449ae0" />
<img width="942" alt="Знімок екрана 2024-12-12 о 11 39 27" src="https://github.com/user-attachments/assets/84fd4c5a-ef41-47d0-9769-2fdaf2446ba1" />

VS Code Extension Version - `1.54.16480`

```sh
$ php -v
PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
```

**Comment by jakubmisek** [comment]
thank you for pointing this out!

completion/gotodef/hover after `(set)` keywords have been implemented, ready for the next update
