### ISSUE TITLE
Not suggest autocompletion correctly

### ISSUE THREAD

**Issue by khan-aafiya** [DEVSENSE/phptools-docs#742]
https://github.com/user-attachments/assets/39a673b1-d809-49d9-a03c-70851db56144

Is not suggest syntax why?

**Comment by jakubmisek** [comment]
Can you please post

- the code sample
- version of PHP extension

In the current version, the completion works as expected:

![completion-sample](https://github.com/user-attachments/assets/4bd0dd87-5e5b-409f-908a-8f411780c5b2)
