### ISSUE TITLE
No hover popup and no completion in parenthesized assignment

### ISSUE THREAD

**Issue by gremo** [DEVSENSE/phptools-docs#743]
I've found this bug and, I have to say, it's the only bug I've found so far, even if it's pretty annoying.

As you can see there is no hover popup and no completion using parenthesized assignment. I generaly dislike this kind of syntax but in some case this make sense (when you need to use `$qb->expr()->eq('field', ':param')`):

```php
($qb = $conn->createQueryBuilder())
    ->select('*')
    ->where($qb->expr()->eq('field', ':param'))
 ;
```

![phptools](https://github.com/user-attachments/assets/19b201e4-fcf2-40d5-be7e-ee65b628ef0d)

Extension version is 1.54.16480.

**Comment by jakubmisek** [comment]
Thank you for pointing this out! Will be fixed

**Comment by gremo** [comment]
You're welcome, @jakubmisek. Always happy to help to this great extension 😎

**Comment by jakubmisek** [comment]
Fix will be available in the very next update! Thanks again for reporting it.

![hover-paren-ass](https://github.com/user-attachments/assets/ec2dd028-ecc4-410d-906c-b81d26232e48)
