### ISSUE TITLE
Quickfix for PHP6504 in PHPDoc only suggests using class inline not adding use

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#75]
When quick fixing the following problem:

![image](https://user-images.githubusercontent.com/3308769/90022928-0800a600-dcab-11ea-953f-769622344de5.png)

The only option is to use the class inline

![image](https://user-images.githubusercontent.com/3308769/90023001-13ec6800-dcab-11ea-852e-809f4d9ccba6.png)

Which results in:

![image](https://user-images.githubusercontent.com/3308769/90023023-1c44a300-dcab-11ea-91ae-016b779b3b43.png)

I would expect an option to be available to add it as a use statement instead / as well

![image](https://user-images.githubusercontent.com/3308769/90023083-34b4bd80-dcab-11ea-8ba6-0d7808601701.png)

**Comment by jakubmisek** [comment]
good point, will be fixed!

**Comment by jakubmisek** [comment]
fixed since 1.0.5065
