### ISSUE TITLE
Find all implementations / usages does not work sometimes (after checking out a commit)

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#76]
I am performing code review on a patch: https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/616471/8

This patch introduces a new interface and a few implementations of the interface.
The new interface `ImageLinker` in `namespace Wikibase\Lib\Formatters;`
and 2 implementations `CommonsImageLinker` and `LocalImageLinker` also in the same namespace.

All of these files classes and interfaces were added in the same commit which I have checked out for code review.

When clicking find all implementations I only see one of the classes, until going and manually opening the other file, then everything seemed to work.
Was something missed from the indexing when I checked out the commit to review?

There was not output or errors in the PHP or lang server logs during this time

**Comment by addshore** [comment]
The same thing also seemed to happen with "find all usages" after I wrote this ticket.

For example, find all usages of the class output:
![image](https://user-images.githubusercontent.com/3308769/90025017-77779500-dcad-11ea-9a79-8b15965f7485.png)

plain text search of the class revealing many more usages:

![image](https://user-images.githubusercontent.com/3308769/90025057-83635700-dcad-11ea-8be3-bf3e762f1fd4.png)

**Comment by jakubmisek** [comment]
it's probably indexing problem after performing the commit (or revert, or cherry-pick, or changing HEAD in general?)

Do you see any kind of error in OUTPUT panel, `PHP Language Server` group?

**Comment by addshore** [comment]
> Do you see any kind of error in OUTPUT panel, `PHP Language Server` group?

Nope

> it's probably indexing problem after performing the commit (or revert, or cherry-pick, or changing HEAD in general?)

Yup, sounds like it.

Happy to keep an eye out and report if I see it again and see any different output.
(more output in general would be nice to figure things like this out), is there a phptools verbose mode? :D

**Comment by jakubmisek** [comment]
fixed in the next update (`1.0.5227`+)
