### ISSUE TITLE
PHP0406 problem reported after a instanceof check for the type

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#77]
ItemId implements EntityId.
At the start of the method there is an early return if `$id` is not an `ItemId`, thus after this point `$id` must be an `ItemId`
I would not expect to see this problem reported in this situation.

`Argument '1' passed to getPageNameForItem() is expected to be of type Wikibase\DataModel\Entity\ItemId, Wikibase\DataModel\Entity\EntityId given`

![image](https://user-images.githubusercontent.com/3308769/90064197-52e9e000-dce2-11ea-833c-7a8df2df9a12.png)

**Comment by jakubmisek** [comment]
thanks, fixed since next update (1.0.5059)
