### ISSUE TITLE
Cannot explore certain PHAR files in VS Solution Explorer

### ISSUE THREAD

**Issue by roberthusak** [DEVSENSE/phptools-docs#78]
Given the test PHP project in [`PharUseCase.zip`](https://github.com/DEVSENSE/phptools-docs/files/5067632/PharUseCase.zip), Visual Studio doesn't enable to explore the contents of `phpunit.phar`. That's not true for all the PHAR archives, as the included `sample.phar` (its generation is in [`SamplePharMake.zip`](https://github.com/DEVSENSE/phptools-docs/files/5067635/SamplePharMake.zip)) works fine. See this screenshot:

![PharUseCase](https://user-images.githubusercontent.com/22641707/90104941-5f535480-dd45-11ea-8589-738dc48a6e2c.png)

PHP Tools version: 1.40.11953
Visual Studio version: Enterprise 2019, 16.6.5

**Comment by jakubmisek** [comment]
this should be workarounded in latest release at https://www.devsense.com/en/download

however the problem is in https://github.com/DEVSENSE/Devsense.PHP.Phar , `bool IsFile` property
