### ISSUE TITLE
No quick fixes listed on hover, but they appear when pressing the quickfix shortcut

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#79]
Might have something to do with 2 problems being listed on the line?
Could this be a vscode bug rather than a phptools one?

![2020-08-13_15-56-24](https://user-images.githubusercontent.com/3308769/90150450-96455c80-dd7d-11ea-81c5-427223dc5a97.gif)

**Comment by jakubmisek** [comment]
Seems like a VSCode issue; phptools provide the quickfix but it is not shown by VSCode in case there are more than one problem with a different location.

**Comment by addshore** [comment]
Filled upstream

**Comment by jakubmisek** [comment]
awesome, thanks

**Comment by addshore** [comment]
@jakubmisek see https://github.com/microsoft/vscode/issues/104574#issuecomment-675070812

> Does the php extension mark its code actions with [`CodeActionKind.QuickFix`](https://github.com/microsoft/vscode/blob/6445a9633d428e0879d172d4f392c542ba887768/src/vs/vscode.d.ts#L2009)?

**Comment by jakubmisek** [comment]
Yes we do that, quick fix works fine if there is just one problem at the same location.

**Comment by jakubmisek** [comment]
@addshore thank you, it was a kind of issue in our code. Fixed since `1.0.5088`
