### ISSUE TITLE
VSC: Any plan to show phpcs linting errors?

### ISSUE THREAD

**Issue by swashata** [DEVSENSE/phptools-docs#8]
First of all I really like your extension. As a WordPress developer, it has significantly eased up my life.

There are two things I would like to suggest though

## 1:  `phpcs` linting

The current extension that we have through marketplace, doesn't work good for really large files, on top of that, if I set it to use composer phpcs and if it doesn't find any for a project, it keeps on showing errors everytime I type or open a file. I am sure devsense can do better here.

## 2: Formatting with `phpcbf`

I am not sure how the current formatting works. I have even seen some errors poping up (which I am not able to reproduce) sometimes. But as WordPress developer, I would really like to ability to format current file on save (configurable), just like `eslint.fixOnSave`.

Once again, thank you for your consideration.

**Comment by jakubmisek** [comment]
Thanks for the suggestions! For now we do our own "linting" (code validation) and formatting. Still in progress but it performs faster. We'll make it working with wordpress development better in future updates.

Any 3rd party extensions for VSC are still possible to use but we cannot provide a support for them.

**Comment by swashata** [comment]
I totally understand, actually I wasn't asking for third-party support here. I was just suggesting having your own implementation for `phpcs` linting and fixing tool. And thank you for your consideration.

**Comment by jakubmisek** [comment]
Thanks, yes we are implementing our linting already. If there is any analysis we can improve or add, please make an issue for that : )

**Comment by swashata** [comment]
I will then open up an issue for WordPress specific use case.
