### ISSUE TITLE
quickfix list should be deduplicated

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#80]
These quick fixes have the same outcome and should be deduplicated.
Rather than seeing 4 I would expect to see 2.
I imagine the duplication is coming from the fact my project dir has 2 of these classes in the same namespace currently.

![image](https://user-images.githubusercontent.com/3308769/90150619-c55bce00-dd7d-11ea-9312-b55a3e91090f.png)

**Comment by jakubmisek** [comment]
good point, will be fixed

**Comment by jakubmisek** [comment]
fixed since 1.0.5057, thanks!
