### ISSUE TITLE
namespaces suggestions should be namespaces and not classes

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#81]
When writing the namespace of a class vscode suggested using a class name.
This is undesired and is never right in this situation.
Instead known namespaces should be suggested.

![image](https://user-images.githubusercontent.com/3308769/90158997-a5310c80-dd87-11ea-8be6-2510e5efee7c.png)

The namespaces I would have expected to be suggested that already exists was `namespace Wikibase\Repo\Tests\FederatedProperties;`

**Comment by jakubmisek** [comment]
Actually phptools by purpose never suggest anything when writing a new namespace (or a new variable or a new class name), this is porvided by VSCode itself.

We can only add our own suggestions which would be added to the list provided by VSCode

**Comment by addshore** [comment]
> We can only add our own suggestions which would be added to the list provided by VSCode

If the namespaces can be added to that list that would be great (not sure how that works internally).
I would love for it to suggest `FederatedProperties` at that stage, to be added to the rest of the namespace that is already there.

**Comment by jakubmisek** [comment]
thanks, implemented!
