### ISSUE TITLE
Use statements added by quickfixes always add to the bottom of the list not alphabetically

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#82]
The projects that I work on would expect the use statements to be alphabetical (as is indicated by the failing sniff in the image on line 5).
It would be great if phptools could do this by default.

![image](https://user-images.githubusercontent.com/3308769/90159574-8121fb00-dd88-11ea-8703-3de3eb223da1.png)

**Comment by jakubmisek** [comment]
Makes sense.

Quick question - is there any kind of standardized configuration file (like .editorconfig) that would define the order of 'use' in the code?

**Comment by addshore** [comment]
> Quick question - is there any kind of standardized configuration file (like .editorconfig) that would define the order of 'use' in the code?

Not that I am aware of :/
For our code this requirements is specificed in a phpcs sniff https://github.com/wikimedia/mediawiki-tools-codesniffer/blob/master/MediaWiki/Sniffs/Classes/UnsortedUseStatementsSniff.php

**Comment by jakubmisek** [comment]
implemented already!

closing )
