### ISSUE TITLE
No quickfix suggested when class appears to extend itself, but other classes exist

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#83]
In this example I am creating a new class that will have the same name as another class that lives in a different namespace

![image](https://user-images.githubusercontent.com/3308769/90165041-0230c080-dd90-11ea-87ac-b91306b8152b.png)

I would expect phptools to:
 1) Realize that extending ones self is not okay
 2) Suggest a quick fix which would be adding a `use` statement for the class that exists in another namespace, specifically `Wikibase\Lib\Formatters\LabelsProviderEntityIdHtmlLinkFormatter`

In a case where there is no other class with this name if should probably be reported as a problem?

**Comment by jakubmisek** [comment]
thanks, implemented
