### ISSUE TITLE
PHP2414 could be more helpful, specifying where the abstract method requirement is defined.

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#84]
In the screenshot I have a PHP2414 problem, which apparently means this class should have a count method.
I don't know where in the class chain this requirement is stated, having the class name specified in the problem message would make fixing such problems easier.

![image](https://user-images.githubusercontent.com/3308769/91062105-3627a380-e624-11ea-8ea8-ed0000924803.png)

**Comment by jakubmisek** [comment]
That's a good suggestion. We may change the error message to 

```
Class {...} does not implement abstract methods:
function Countable::count()
```

**Comment by addshore** [comment]
So my issue was less not knowing about the `Countable` interface having the count method, but rather the class that implements `Countable` thus creating the requirement to have a `count` method.

But now I write that perhaps it is an impossible message to create...

Anyway, I'm pretty sure this problem is actually caused by an issue in phptools, as this class does not implement the `Countable` interface anywhere as far as I can tell.
But I don't know how to provide you with any more helpful information....

**Comment by jakubmisek** [comment]
I see. Countable was just an example. We'd provide the class/interface/trait that makes the method abstract. Maybe phptools are wrong about it after all.

**Comment by addshore** [comment]
Okay I found where the implementation of `Countable` happens, but also where it is implemented, and thus shouldn't be reported as a problem.

The chain of classes goes:
 - `class HtmlPageLinkRendererEndHookHandlerTest extends MediaWikiIntegrationTestCase {`
 - `abstract class MediaWikiIntegrationTestCase extends PHPUnit\Framework\TestCase {`
 - `abstract class TestCase extends Assert implements SelfDescribing, Test`
 - `interface Test extends Countable`
 - `interface Countable`

However the `TestCase` abstract class does implement the `count()` method

![image](https://user-images.githubusercontent.com/3308769/91152649-26a56a80-e6b7-11ea-8b48-cdda98c74996.png)

**Comment by jakubmisek** [comment]
Aren't there some trait uses as well?

**Comment by addshore** [comment]
Hmm, I don't see how traits would come into this particular issue at all?
The `TestCase` class satisfies the requirement of the `count` method for the `Countable` interface.
Anything that extends `TestCase` should not have this reported as a problem.

Interestingly `MediaWikiIntegrationTestCase` doesn't have the problem reported.

**Comment by jakubmisek** [comment]
traits might get us confused :)

**Comment by addshore** [comment]
> traits might get us confused :)

So there are a few traits

![image](https://user-images.githubusercontent.com/3308769/91154818-e1366c80-e6b9-11ea-9cc0-ae16de147fe6.png)

**Comment by jakubmisek** [comment]
we've found and fixed issues, and improved the warning message as well ) closing
