### ISSUE TITLE
Better order for use class quickfixes

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#86]
When listing the quickfixes for using a class I personally would prefer it if the shortest namespaces names came earlier in the list.
An exception might be for classes that are in the same namespace (or partial namespace) as the class that is having the quickfix applied in it.

![image](https://user-images.githubusercontent.com/3308769/91156692-57d46980-e6bc-11ea-885b-89d0e6b89dd4.png)

**Comment by jakubmisek** [comment]
But once the class is in the same namespace, there is no quickfix for it. Do you have an example of such an exception?

**Comment by addshore** [comment]
> But once the class is in the same namespace, there is no quickfix for it. Do you have an example of such an exception?

I guess if the class is in namespace `\A\B\C\Classname`
and we are looking at where to import `ImportableClass` from
a goodish order could look like:

- `\A\B\ImportableClass`
- `\A\ImportableClass`
- `\ImportableClass`
- `\SomeOtherNamespace\ImportableClass`
- `\SomeOtherNamespace\BlaBlaBla\ImportableClass`

Surfacing the possibly most relevant classes to you first.

I have no idea what the behaviour of other IDEs is in this regard

**Comment by jakubmisek** [comment]
As for now, we have added `Sort uses` code fix. 

In the future update, the uses will be added in the correct order already.

**Comment by jakubmisek** [comment]
we're preparing pre-release that sorts newly added 'use's

thank you @addshore !
