### ISSUE TITLE
quickfix adding use statement can add it in the wrong place

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#87]
![image](https://user-images.githubusercontent.com/3308769/91157643-80109800-e6bd-11ea-9e9e-9c721d6fc2a7.png)

As far as I can tell this happens when interacting with a problem that the IDE still shows but not in the correct place. (the file has not yet been re indexed for problems since the last change).

![2020-08-25_10-26-32](https://user-images.githubusercontent.com/3308769/91157682-90287780-e6bd-11ea-8a0c-7531d974fbac.gif)

**Comment by jakubmisek** [comment]
Thanks. Seems some problems get updated after a while causing this. Will look into it.

**Comment by jakubmisek** [comment]
we have fixed that; please create a new issue if it happens again )
