### ISSUE TITLE
No quickfix for adding a use of a fully qualified class name

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#88]
I dont think this should always be listed as a "problem" perhaps that is something that needs to be decided per project.
However I'd love to still be able to perform an quickfix / action on code like this:

![image](https://user-images.githubusercontent.com/3308769/91185714-122c9680-e6e6-11ea-84e3-f5f1ef03e073.png)

Rather than manually adding: `use MediaWikiIntegrationTestCase;` and removing the `\`

**Comment by jakubmisek** [comment]
This is not listed as a problem by phptools (it's coming from `phpcs`)

**Comment by jakubmisek** [comment]
yes, we can add a quickfix (without reporting a problem) to ass `use ****` in this case

**Comment by jakubmisek** [comment]
implemented in the upcoming update, thanks!
