### ISSUE TITLE
I would like to see which methods in a class override / implement methods in parents

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#89]
In the example screenshot, the first 3 methods are implementations of methods in interfaces, and the bottom one (just added) is not yet.
Trying to figure this out is extremely hard with phptools as this is not visually represented.
The only approaches I can currently think of would be to either: 1) "Go to definition" for every method, until I find one that doesn't have a parent definition. 2) Click through each interface that is implemented and record all of the methods provided?

![image](https://user-images.githubusercontent.com/3308769/91271960-e9061780-e772-11ea-94d9-416e4f91c4e3.png)

As briefly discussed in https://github.com/DEVSENSE/phptools-docs/issues/62 having some annotations in the margin would dramatically help here, similar to the behaviour of PHPStorm / IntelliJ.

![image](https://user-images.githubusercontent.com/3308769/91272088-18b51f80-e773-11ea-8ecc-8b398fb168c2.png)

**Comment by addshore** [comment]
I find myself constantly missing this feature from other IDEs (The sidebar link to parents, or implementations and subclasses).

It's good that the list is availible
![image](https://user-images.githubusercontent.com/3308769/117893076-a315c300-b2b1-11eb-8219-e020f6577f40.png)


But I still wish it were only a single click in the sidebar away, rather than 2 clicks (menu open, click on the correct menu entry)

**Comment by jakubmisek** [comment]
I think we won't be able to add an icon into the text area margin although we could add a code-lens above the declaration.

- The question is, is it reasonable to annotate every declaration (constant, function, class) with code-lens?

Also, I'd add, we do support "Find All Implementations" menu command for classes, interfaces, traits, and functions.

**Comment by jakubmisek** [comment]
@addshore we have finally finished the code lens (beta) implementation; it will support peeking into overrides, base implementation, and references:

![image](https://user-images.githubusercontent.com/842150/149681589-663a80b5-c853-491c-8a7e-29e50374d9a3.png)
![image](https://user-images.githubusercontent.com/842150/149681597-fdaf4610-827c-404d-96c7-e0712287a9d7.png)
![image](https://user-images.githubusercontent.com/842150/149681608-39967a7d-c1d2-4d3f-99f0-ce4170e7afeb.png)

**Comment by addshore** [comment]
Super exciting!

**Comment by jakubmisek** [comment]
Thanks, and thanks for all the ideas! Will be released soon.

**Comment by jakubmisek** [comment]
released in v1.5

thanks!
