### ISSUE TITLE
Add visibility from implemented interfaces when using quickfix for stubs

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#90]
I have an interface that looks like this specifying a public method

![image](https://user-images.githubusercontent.com/3308769/91273830-b6a9e980-e775-11ea-8266-9225615b359b.png)

When using this interface in a class and then using the quickfix to add methods that need to be implemented according to the interface the visibility of the method is lost.

![image](https://user-images.githubusercontent.com/3308769/91273924-dd682000-e775-11ea-8789-908995719df1.png)

This method should be created with the visibility set

**Comment by jakubmisek** [comment]
thanks! done
