### ISSUE TITLE
quickfix for using class when in global scope doesnt appear

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#91]
![image](https://user-images.githubusercontent.com/3308769/91274799-253b7700-e777-11ea-9599-66fffbaf6d6d.png)

I would expect a quick fix to be able to do the following:

```
use MediaWiki\MediaWikiServices;

if ( !function_exists( 'mws' ) ) {
	function mws() {
		return MediaWikiServices::getInstance();
	}
}
```

**Comment by jakubmisek** [comment]
Right, we don't provide quick fixes when the name is fully qualified or contains the namespace parts. But we can look for the class in the same way as phpcs - ignoring the specified namespace and just look for the class name.

**Comment by jakubmisek** [comment]
will be added within the next update (1.0.5155+), thanks!

**Comment by addshore** [comment]
![image](https://user-images.githubusercontent.com/3308769/103563098-177bc800-4eb4-11eb-8a20-cd52a0982d31.png)
It looks like this is happening again?

**Comment by jakubmisek** [comment]
I think we never provided code actions if the class name is correct and fully qualified.

**Comment by addshore** [comment]
I believe what was done in this issue was adding the quick fix for creating a use statement from a fully qualified correct name, and I'm fairly sure I was using it and it stopped working, but I would be wrong!

**Comment by addshore** [comment]
TO add some visuals to the issue I encounter.

In Jetbrains IDEs, adding use statements for these 2 classes can be completed in 4-6 key presses in a few seconds.
In phptools the process if a bit longer.. Either I go the automated route?
 - Remove the fully specified class name with namespace
 - Wait for phptools to figure out what class to suggest (as it is no guessing and needing to look it up in the index, vs already being told)
 - Apply the quickfix that shows up after a bit of time processing the file

https://user-images.githubusercontent.com/3308769/103631772-56089580-4f3b-11eb-9120-8c34375ad2b7.mp4

I could also go the manual route of copy the class name to a use statement, and remove by hand the namespace in front of the class.
but IMO this is a task the IDE should help me do..

**Comment by jakubmisek** [comment]
I see; it makes sense to provide quick action for fully qualified names; also it seems something is slowing down the editor, a lot. May I ask for a list of your extensions?

**Comment by addshore** [comment]
> May I ask for a list of your extensions?

Is there an easy way to output the full list?

**Comment by addshore** [comment]
I just tried the reproducing in the video again and it happened much faster.
It might just be because i was video recording? or a one off. Normally it is faster. :)
I spotted a new process monitor in VSCode I'll be sure to look at next time things are slow.

**Comment by jakubmisek** [comment]
The following command should output the list of extensions (ref https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions)

```
code --list-extensions
```

**Comment by addshore** [comment]
:(

```
adam@adsh+wsl:~/dev/git/gerrit/mediawiki/core/extensions/OnOrProt (main)$ $ code --list-extensions
Ignoring option list-extensions: not supported for code.
```

```
code 1.52.1

Usage: code [options][paths...]

To read from stdin, append '-' (e.g. 'ps aux | grep code | code -')

Options
  -d --diff <file> <file>           Compare two files with each other.
  -a --add <folder>                 Add folder(s) to the last active window.
  -g --goto <file:line[:character]> Open a file at the path on the specified line and character position.
  -n --new-window                   Force to open a new window.
  -r --reuse-window                 Force to open a file or folder in an already opened window.
  -w --wait                         Wait for the files to be closed before returning.
  --locale <locale>                 The locale to use (e.g. en-US or zh-TW).
  -h --help                         Print usage.

Extensions Management
  --enable-proposed-api <extension-id> Enables proposed API features for extensions. Can receive one or more extension IDs to enable individually.

Troubleshooting
  -v --version                       Print version.
  --verbose                          Print verbose output (implies --wait).
  --log <level>                      Log level to use. Default is 'info'. Allowed values are 'critical', 'error', 'warn', 'info', 'debug', 'trace', 'off'.
  -s --status                        Print process usage and diagnostics information.
  --prof-startup                     Run CPU profiler during startup
  --disable-extensions               Disable all installed extensions.
  --disable-extension <extension-id> Disable an extension.
  --sync <on> <off>                  Turn sync on or off
  --inspect-extensions <port>        Allow debugging and profiling of extensions. Check the developer tools for the connection URI.
  --inspect-brk-extensions <port>    Allow debugging and profiling of extensions with the extension host being paused after start. Check the developer tools for the connection URI.
  --disable-gpu                      Disable GPU hardware acceleration.
  --max-memory                       Max memory size for a window (in Mbytes).
```
