### ISSUE TITLE
Select leading $ when double clicking a word

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#92]
When I have a code snippet such as:
`$languageFallback = new TermLanguageFallbackChain( [`
I may double click on the `$languageFallback` with the intention of copying the whole string including the `$`.
Current vscode behaviour with phptools is to not copy the `$` which ends up being quite annoying, needing the `$` to be added back.
Is this the sort of thing vscode allows plugins to alter?
IT would be a great feature IMO.

**Comment by jakubmisek** [comment]
This is controlled by VSCode setting `editor.wordSeparators` where you have to delete `$` character.

This can be configured for a single language [php] as mentioned in the comment https://github.com/microsoft/vscode/issues/33701#issuecomment-616911062

It seems, for now, this feature is not extensible. But we might be able to set the user setting upon first use.

**Comment by addshore** [comment]
Working perfectly!

And I have updated our new MediaWiki docs page with this detail https://www.mediawiki.org/w/index.php?title=Visual_Studio_Code&diff=4059040&oldid=4058983

**Comment by addshore** [comment]
I guess this could be reopened if you want to get this as an automatic phptools thing! :)

**Comment by jakubmisek** [comment]
Thanks, we'll check if this can be automatic because, at least, we'd like to be consistent with full Visual Studio behavior.
