### ISSUE TITLE
Make "Go To Definition" work on @dataProvider comments

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#93]
@dataProvivder comments will refer to a method name.
It would be great to be able to use the "Go To Definition" feature to go to the place that the method is defined.

In the example picture `validCallProvider` is defined in the class I'm looking at, but `validContextProvider` is defined in a parent class.
I'd like to be able to quickly get to the definition!

![image](https://user-images.githubusercontent.com/3308769/91408338-a0fef780-e83b-11ea-837e-26e271e36f63.png)

**Comment by jakubmisek** [comment]
implemented including code completion and other code sense features; since `1.0.5118`
