### ISSUE TITLE
unused constructor arguments are not highlighted as a problem

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#94]
![image](https://user-images.githubusercontent.com/3308769/91578830-a3984480-e942-11ea-97a1-45eb8d619ebd.png)

I would expect for this to be highlighted as a problem.
Maybe even with a quick fix for it to be removed (along with removing it from callers of the constructor)
This should probably also apply to general methods (not sure if it does currently)

**Comment by jakubmisek** [comment]
thanks @addshore , added to the next update. We will report unused parameters for `__construct` and private functions.
