### ISSUE TITLE
Renaming a function caused an error (code 102)

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#95]
I was trying to rename a function and got this error.
Renaming functions is one of the cases that should be fine?
Version: devsense.phptools-vscode-1.0.5153

![image](https://user-images.githubusercontent.com/3308769/91826653-c9b92f80-ec35-11ea-98c3-9402147812dd.png)

**Comment by jakubmisek** [comment]
I think the message is a bit misleading. It works for global functions, not class functions (methods).

We are afraid we won't find all the occurrences, which might leave your code broken.

**Comment by addshore** [comment]
> I think the message is a bit misleading. It works for global functions, not class functions (methods).
> 
> We are afraid we won't find all the occurrences, which might leave your code broken.

Aaah, that is a shame :(
What makes you worry? :P

**Comment by jakubmisek** [comment]
discussing the same issue on https://community.devsense.com/d/266-rename-class-method-fail

**Comment by jakubmisek** [comment]
Ok, I agree. We'll enable it within a future update, keeping you informed in here.

**Comment by jakubmisek** [comment]
VSCode allows to preview before rename now (https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_42.md#rename-preview) so we can safely let users rename anything

**Comment by jakubmisek** [comment]
The next version will allow rename refactoring of anything. If anything should be checked by you, it will open a preview panel.

**Comment by jakubmisek** [comment]
Implemented in `1.2.5887`, whenever there is an unsafe rename, a preview of all changes is opened where you can review before confirm.
