### ISSUE TITLE
Undefined variable problem

### ISSUE THREAD

**Issue by AShujiao** [DEVSENSE/phptools-docs#96]
![image](https://user-images.githubusercontent.com/14969576/94533444-b370b480-0271-11eb-96ac-9b232181bc83.png)
![image](https://user-images.githubusercontent.com/14969576/94533469-bbc8ef80-0271-11eb-931f-89cfe0e93cd9.png)
Compare with PHP intelephense
Left: PHP tools for vs Code
Right: PHP intelephense
When the developer is careless, it can not be detected if the variable is not marked with '$'

**Comment by jakubmisek** [comment]
Thanks for the issue, what would you expect as an error message for `cc`? Because `cc` might be a global constant as well.

**Comment by AShujiao** [comment]
Same tip as $cc

**Comment by jakubmisek** [comment]
thanks, will be added in the upcoming update since `1.1.5483`
