### ISSUE TITLE
PHP7001 reported when class name is used in a doc comment

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#97]
This doesn't happen in other IDEs, so perhaps should not happen i phptools.

The class is used in a comment, and although not used in code the use statement is needed context for this case.

![image](https://user-images.githubusercontent.com/3308769/94925372-04bdb580-04b7-11eb-91b1-4a596794bbb0.png)

**Comment by jakubmisek** [comment]
thanks, fixed in the next update. Together with suggesting the typo in `@depreacted`.
