### ISSUE TITLE
Support PHP annotations

### ISSUE THREAD

**Issue by andreheeke** [DEVSENSE/phptools-docs#98]
Due to the popularity of the PHP frameworks Symfony and Doctrine, it would be great if PHP annotations were supported.

As an example:
```PHP
// src/Entity/Product.php
namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    // ... getter and setter methods
}
```

**Comment by jakubmisek** [comment]
Thank you for the suggestion, we'll definitely do that!

May I ask for a link to the documentation of annotations?

**Comment by andreheeke** [comment]
Sure! You can find details at [Doctrine annotations](https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/index.html) or get inspired by the [PhpStorm plugin](https://plugins.jetbrains.com/plugin/7320-php-annotations).

**Comment by jakubmisek** [comment]
The next update (`1.1.5493` and newer) will add the first support for annotations - completion and navigation to annotation types. Not parameter completion yet.

**Comment by andreheeke** [comment]
Awesome. I will test this feature.
Do you plan to support the parameters in the future? Especially with regard to the native attributes in PHP 8 this is exciting.

**Comment by jakubmisek** [comment]
@andreheeke yes, parameters and the new PHP 8 attributes will be supported, together with the named parameters. Not sure if it'll be the next update tho
